define((function(){return(function(r){var n={};function e(t){if(n[t])return n[t].exports;var i=n[t]={i:t,l:!1,exports:{}};return r[t].call(i.exports,i,i.exports,e),i.l=!0,i.exports}return e.m=r,e.c=n,e.d=function(r,n,t){e.o(r,n)||Object.defineProperty(r,n,{enumerable:!0,get:t})},e.r=function(r){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(r,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(r,"__esModule",{value:!0})},e.t=function(r,n){if(1&n&&(r=e(r)),8&n)return r;if(4&n&&"object"==typeof r&&r&&r.__esModule)return r;var t=Object.create(null);if(e.r(t),Object.defineProperty(t,"default",{enumerable:!0,value:r}),2&n&&"string"!=typeof r)for(var i in r)e.d(t,i,function(n){return r[n]}.bind(null,i));return t},e.n=function(r){var n=r&&r.__esModule?function(){return r.default}:function(){return r};return e.d(n,"a",n),n},e.o=function(r,n){return Object.prototype.hasOwnProperty.call(r,n)},e.p="",e(e.s=0)})({"./flash_detect.js":
/*!*************************!*\
  !*** ./flash_detect.js ***!
  \*************************/
/*! no static exports found */function(r,n){var e=new(function(){var r=this;r.installed=!1,r.raw="",r.major=-1,r.minor=-1,r.revision=-1,r.revisionStr="";var n=[{name:"ShockwaveFlash.ShockwaveFlash.7",version:function(r){return e(r)}},{name:"ShockwaveFlash.ShockwaveFlash.6",version:function(r){var n="6,0,21";try{r.AllowScriptAccess="always",n=e(r)}catch(r){}return n}},{name:"ShockwaveFlash.ShockwaveFlash",version:function(r){return e(r)}}],e=function(r){var n=-1;try{n=r.GetVariable("$version")}catch(r){}return n},t=function(r){var n=-1;try{n=new ActiveXObject(r)}catch(r){n={activeXError:!0}}return n},o=function(r){var n=r.split(",");return{raw:r,major:parseInt(n[0].split(" ")[1],10),minor:parseInt(n[1],10),revision:parseInt(n[2],10),revisionStr:n[2]}},a=function(n){return parseInt(n.replace(/[a-zA-Z]/g,""),10)||r.revision};r.majorAtLeast=function(n){return r.major>=n},r.minorAtLeast=function(n){return r.minor>=n},r.revisionAtLeast=function(n){return r.revision>=n},r.versionAtLeast=function(n){var e=[r.major,r.minor,r.revision],t=Math.min(e.length,arguments.length);for(i=0;i<t;i++){if(e[i]>=arguments[i]){if(i+1<t&&e[i]==arguments[i])continue;return!0}return!1}},r.FlashDetect=(function(){if(navigator.plugins&&navigator.plugins.length>0){var e="application/x-shockwave-flash",i=navigator.mimeTypes;if(i&&i[e]&&i[e].enabledPlugin&&i[e].enabledPlugin.description){var s=i[e].enabledPlugin.description,u=(f=(v=s).split(/ +/),p=f[2].split(/\./),m=f[3],{raw:v,major:parseInt(p[0],10),minor:parseInt(p[1],10),revisionStr:m,revision:a(m)});r.raw=u.raw,r.major=u.major,r.minor=u.minor,r.revisionStr=u.revisionStr,r.revision=u.revision,r.installed=!0}}else if(-1==navigator.appVersion.indexOf("Mac")&&window.execScript){s=-1;for(var c=0;c<n.length&&-1==s;c++){var l=t(n[c].name);if(!l.activeXError&&(r.installed=!0,-1!=(s=n[c].version(l)))){u=o(s);r.raw=u.raw,r.major=u.major,r.minor=u.minor,r.revision=u.revision,r.revisionStr=u.revisionStr}}}var v,f,p,m})()});e.JS_RELEASE="1.0.4",r.exports=e},0:
/*!*******************************!*\
  !*** multi ./flash_detect.js ***!
  \*******************************/
/*! no static exports found */function(r,n,e){r.exports=e(/*! ./flash_detect.js */"./flash_detect.js")}})}));
//# sourceMappingURL=flash_detect.webpack.min.js-vflewTsAr.map