define(["focus-trap","react"],(function(e,t){return(function(e){var t={};function r(o){if(t[o])return t[o].exports;var n=t[o]={i:o,l:!1,exports:{}};return e[o].call(n.exports,n,n.exports,r),n.l=!0,n.exports}return r.m=e,r.c=t,r.d=function(e,t,o){r.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:o})},r.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},r.t=function(e,t){if(1&t&&(e=r(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var o=Object.create(null);if(r.r(o),Object.defineProperty(o,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var n in e)r.d(o,n,function(t){return e[t]}.bind(null,n));return o},r.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return r.d(t,"a",t),t},r.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},r.p="",r(r.s=0)})({"./node_modules/focus-trap-react/dist/focus-trap-react.js":
/*!****************************************************************!*\
  !*** ./node_modules/focus-trap-react/dist/focus-trap-react.js ***!
  \****************************************************************/
/*! no static exports found */function(e,t,r){"use strict";var o=(function(){function e(e,t){for(var r=0;r<t.length;r++){var o=t[r];o.enumerable=o.enumerable||!1,o.configurable=!0,"value"in o&&(o.writable=!0),Object.defineProperty(e,o.key,o)}}return function(t,r,o){return r&&e(t.prototype,r),o&&e(t,o),t}})();function n(e,t){if(!(e instanceof t))throw new TypeError("Cannot call a class as a function")}function u(e,t){if(!e)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return!t||"object"!=typeof t&&"function"!=typeof t?e:t}var s=r(/*! react */"react"),i=r(/*! focus-trap */"focus-trap"),a=["active","paused","tag","focusTrapOptions","_createFocusTrap"],c=(function(e){function t(){var e,r,o;n(this,t);for(var s=arguments.length,i=Array(s),a=0;a<s;a++)i[a]=arguments[a];return r=o=u(this,(e=t.__proto__||Object.getPrototypeOf(t)).call.apply(e,[this].concat(i))),o.setNode=function(e){o.node=e},u(o,r)}return(function(e,t){if("function"!=typeof t&&null!==t)throw new TypeError("Super expression must either be null or a function, not "+typeof t);e.prototype=Object.create(t&&t.prototype,{constructor:{value:e,enumerable:!1,writable:!0,configurable:!0}}),t&&(Object.setPrototypeOf?Object.setPrototypeOf(e,t):e.__proto__=t)})(t,e),o(t,[{key:"componentWillMount",value:function(){"undefined"!=typeof document&&(this.previouslyFocusedElement=document.activeElement)}},{key:"componentDidMount",value:function(){var e=this.props.focusTrapOptions,t={returnFocusOnDeactivate:!1};for(var r in e)e.hasOwnProperty(r)&&"returnFocusOnDeactivate"!==r&&(t[r]=e[r]);this.focusTrap=this.props._createFocusTrap(this.node,t),this.props.active&&this.focusTrap.activate(),this.props.paused&&this.focusTrap.pause()}},{key:"componentDidUpdate",value:function(e){e.active&&!this.props.active?this.focusTrap.deactivate():!e.active&&this.props.active&&this.focusTrap.activate(),e.paused&&!this.props.paused?this.focusTrap.unpause():!e.paused&&this.props.paused&&this.focusTrap.pause()}},{key:"componentWillUnmount",value:function(){this.focusTrap.deactivate(),!1!==this.props.focusTrapOptions.returnFocusOnDeactivate&&this.previouslyFocusedElement&&this.previouslyFocusedElement.focus&&this.previouslyFocusedElement.focus()}},{key:"render",value:function(){var e={ref:this.setNode};for(var t in this.props)this.props.hasOwnProperty(t)&&-1===a.indexOf(t)&&(e[t]=this.props[t]);return s.createElement(this.props.tag,e,this.props.children)}}]),t})(s.Component);c.defaultProps={active:!0,tag:"div",paused:!1,focusTrapOptions:{},_createFocusTrap:i},e.exports=c},0:
/*!**********************************************************************!*\
  !*** multi ./node_modules/focus-trap-react/dist/focus-trap-react.js ***!
  \**********************************************************************/
/*! no static exports found */function(e,t,r){e.exports=r(/*! ./node_modules/focus-trap-react/dist/focus-trap-react.js */"./node_modules/focus-trap-react/dist/focus-trap-react.js")},"focus-trap":
/*!*****************************!*\
  !*** external "focus-trap" ***!
  \*****************************/
/*! no static exports found */function(t,r){t.exports=e},react:
/*!************************!*\
  !*** external "react" ***!
  \************************/
/*! no static exports found */function(e,r){e.exports=t}})}));
//# sourceMappingURL=focus-trap-react.webpack.min.js-vflekfg3y.map