#!/bin/bash
#
HP85=/share/embedded/GPIB/mike/hp85disk
ESP=/opt/Espressif/projects/esp8266_ili9341

DIRS="fatfs fatfs.hal fatfs.sup lib posix printf"

diffit()
{
        echo "$1"
        diff -b "$1" "$2"
        echo =======================================================
}


for i in $DIRS
do
        echo $i
        diff -rb $HP85/$i $ESP/$i
        echo =======================================================
done

diffit $HP85/hardware/hal.c $ESP/esp8266/hal.c
diffit $HP85/hardware/hal.h $ESP/esp8266/hal.h
diffit $HP85/hardware/bits.h $ESP/esp8266/bits.h
#diffit $HP85/hardware/rtc.c $ESP/esp8266/rtc.c
diffit $HP85/hardware/hal.h $ESP/esp8266/hal.h
echo =======================================================

