gpib/amigo.h File Reference
AMIGO disk emulator for HP85 disk emulator project for AVR8.
#include `user_config.h`
*
#include `defines.h`
*
Macros
#define UNL 0x3F
#define UNT 0x5F
#define LLO 0x11
#define DCL 0x14
#define PPU 0x15
#define SPE 0x18
#define SPD 0x19
#define GTL 0x01
#define SDC 0x04
#define PPC 0x05
#define GET 0x08
#define TCT 0x09
Functions
void amigo_init (void)
Initialize Amigo state machine, Disk Position, Error status.
int amigo_request_logical_address (void)
Set current address in amigo_logical_address[].
int amigo_request_status (void)
Set drive status in amigo_status[].
int amigo_send_logical_address (void)
Send current address in amigo_logical_address[].
int amigo_send_status (void)
Send drive status in amigo_status[].
int amigo_increment (char *msg)
Increment sector if it will not overflow.
int amigo_seek (DiskType *p)
Seek to the position held in the disk structure.
int amigo_verify (uint16_t sectors)
Verify Disk Sectors at current position.
int amigo_format (uint8_t override, uint8_t interleave, uint8_t db)
Format Disk.
int amigo_buffered_read (void)
Do a buffered read of the current sector.
int amigo_buffered_write (void)
Do a buffered write of the current sector.
int amigo_cmd_dsj (void)
Send DSJ.
int amigo_cmd_wakeup (void)
Wakeup (undocumented), just enable PPR response.
int amigo_cmd_clear (void)
Response to selected device clear or all clear.
int amigo_todo_op (uint8_t secondary, uint8_t opcode, int len)
Report any Unimplimented commands with Op Codes.
int amigo_todo (uint8_t secondary)
Report any Unimplimented commands.
int Amigo_Command (int secondary)
Amigo Command and OP Code Processing functions.
int Amigo_Execute (int secondary)
Amigo Execute command processing.
int AMIGO_COMMANDS (uint8_t ch)
AMIGO Command state processing.
Variables
VolumeLabelType vl
LIF data structures used by stand alone formatting utility.
DirEntryType de
LIF DIrectory Entry.
uint8_t amigo_state
AMIGO emulator state machine index.
int Amigo_Errors
Detailed Description
AMIGO disk emulator for HP85 disk emulator project for AVR8.
Edit History - [1.0] [Mike Gore] Initial revision of file.
Copyright 2014 Mike Gore, Inc. All rights reserved.
Based on work by Anders Gustafsson.
Copyright 2014 Anders Gustafsson All rights reserved..
Definition in file amigo.h.
Macro Definition Documentation
#define DCL 0x14
Definition at line 26 of file amigo.h.
Referenced by GPIB().
#define GET 0x08
Definition at line 33 of file amigo.h.
#define GTL 0x01
Definition at line 30 of file amigo.h.
#define LLO 0x11
Definition at line 25 of file amigo.h.
#define PPC 0x05
Definition at line 32 of file amigo.h.
#define PPU 0x15
Definition at line 27 of file amigo.h.
#define SDC 0x04
Definition at line 31 of file amigo.h.
Referenced by GPIB().
#define SPD 0x19
Definition at line 29 of file amigo.h.
Referenced by GPIB().
#define SPE 0x18
Definition at line 28 of file amigo.h.
Referenced by GPIB(), and SPI0_Init().
#define TCT 0x09
Definition at line 34 of file amigo.h.
#define UNL 0x3F
Definition at line 23 of file amigo.h.
Referenced by GPIB_COMMANDS(), and GPIB_LISTEN().
#define UNT 0x5F
Definition at line 24 of file amigo.h.
Referenced by AMIGO_COMMANDS(), Amigo_Execute(), amigo_todo(), amigo_todo_op(), GPIB_COMMANDS(), GPIB_LISTEN(), gpib_read_byte(), GPIB_TALK(), and gpib_task().
Function Documentation
int amigo_buffered_read (void)
Do a buffered read of the current sector.
Reference: A33.
Returns
0 ok
GPIB Errors status,Sets dsj and Amigo_errors
Todo
Todo Do we fail on overflow ? currently djs is set - do we want to report that now ?
Definition at line 550 of file amigo.c.
Referenced by Amigo_Execute().
int amigo_buffered_write (void)
Do a buffered write of the current sector.
Reference: A43.
Returns
0 ok
GPIB Errors status,Sets dsj and Amigo_errors
Definition at line 616 of file amigo.c.
Referenced by Amigo_Execute().
int amigo_cmd_clear (void)
Response to selected device clear or all clear.
Reference: A23.
Select sector 0.
Returns
0
Todo
Todo FIXME
Clear the DSJ byte that might be 2 after powerup
Definition at line 763 of file amigo.c.
Referenced by GPIB().
int amigo_cmd_dsj (void)
Send DSJ.
Reference: A11.
Returns
0 ok
GPIB send Errors status
Sets dsj and Amigo_errors
Definition at line 683 of file amigo.c.
Referenced by AMIGO_COMMANDS().
int amigo_cmd_wakeup (void)
Wakeup (undocumented), just enable PPR response.
Todo
Todo
not finished
Sets dsj and Amigo_errors
Returns
GPIB Errors status - or 0 OK
Todo
Todo FIXME
Definition at line 725 of file amigo.c.
int Amigo_Command (int secondary)
Amigo Command and OP Code Processing functions.
We disbale PPR as soon as a valide command is decoded.
ONLY process Secondary Commands in listen mode with op codes and optional data
Ignore Talking.
Ignore Seconday Addresses.
Ignore Execute state `0x60` here.
Must have OP Codes, or Data, and EOI.
Read all of the Data/Opcodes/Parameters at once - while ATN is false.
Last byte read should be EOI or an error.
Unknown OP Code processing rules.
Skip the remaining codes, Wait for Report Phase.
We enable PPR on exit.
Parameters
in secondary command
Returns
0 on sucess
or GPIB error flags on fail
See Also
gpib.h ERROR_MASK defines for a full list)
Reference: A14
Reference: A25
Note: the function will `unread` any commands and return All Data MUST have EOI
Reference: A40
Todo
Todo FIXME
Todo
Todo FIXME
Reference: A27
Seek 1 byte cylinder
Reference: A27
Seek 2 byte cylinder
Reference: A15
Todo
Todo is this the unit $ ?
Reference: A35
Todo
Todo unit ???
Reference: A48 .. A50
Reference: A23
Definition at line 856 of file amigo.c.
Referenced by AMIGO_COMMANDS().
int AMIGO_COMMANDS (uint8_t ch)
AMIGO Command state processing.
Perform Command, Execute or Reporting Phase functions.
Amigo_Command().
Amigo_Execute().
amigo_cmd_dsj().
Parameters
in ch command.
Returns
0 on sucess
or GPIB error flags on fail
See Also
gpib.h ERROR_MASK defines for a full list.
Definition at line 1278 of file amigo.c.
Referenced by GPIB_COMMANDS().
int Amigo_Execute (int secondary)
Amigo Execute command processing.
Parameters
in secondary command
Returns
0 on sucess
or GPIB error flags on fail
See Also
gpib.h ERROR_MASK defines for a full list)
Definition at line 1166 of file amigo.c.
Referenced by AMIGO_COMMANDS().
int amigo_format (uint8_t override, uint8_t interleave, uint8_t db)
Format Disk.
Refernce: A50.
Parameters
in override not used
in interleave not used
in db byte to fill sector buffer with)
Returns
0 ok
1 on Error,Sets dsj and Amigo_errors
Definition at line 494 of file amigo.c.
Referenced by Amigo_Command().
int amigo_increment (char * msg)
Increment sector if it will not overflow.
Parameters
in msg user message on overflow.
Returns
0 ok.
1 error.
Definition at line 383 of file amigo.c.
Referenced by amigo_buffered_read(), amigo_buffered_write(), amigo_format(), and amigo_verify().
void amigo_init (void)
Initialize Amigo state machine, Disk Position, Error status.
Returns
void
Todo
Todo verify that we always want PPR disabled EnablePPR(AMIGO_PPR);
Definition at line 157 of file amigo.c.
Referenced by gpib_init_devices().
int amigo_request_logical_address (void)
Set current address in amigo_logical_address[].
Reference: A15-A19
State: Command
Returns
0
Definition at line 185 of file amigo.c.
Referenced by Amigo_Command().
int amigo_request_status (void)
Set drive status in amigo_status[].
Reference: A15-A19.
State: Command.
Returns
0
Todo
Todo dsj
Definition at line 202 of file amigo.c.
Referenced by Amigo_Command().
int amigo_seek (DiskType * p)
Seek to the position held in the disk structure.
Reference: A27.
We should not commit bad head/sector/cylinder values until tested!..
Parameters
in p DiskType (Current Disk Position) pointer.
Returns
0 ok
1 error
Definition at line 409 of file amigo.c.
Referenced by Amigo_Command().
int amigo_send_logical_address (void)
Send current address in amigo_logical_address[].
Reference: A15-A19.
State: Execute
Returns
0 on sucess
status GPIB error flags on fail
See Also
gpib.h ERROR_MASK defines for a full list.
Definition at line 253 of file amigo.c.
Referenced by Amigo_Execute().
int amigo_send_status (void)
Send drive status in amigo_status[].
Reference: A15-A19.
State: Execute>
Returns
0
status GPIB error flags on fail
See Also
gpib.h ERROR_MASK defines for a full list.
Definition at line 290 of file amigo.c.
Referenced by Amigo_Execute().
int amigo_todo (uint8_t secondary)
Report any Unimplimented commands.
Parameters
in secondary GPIB seconday command
Returns
0
Definition at line 816 of file amigo.c.
Referenced by Amigo_Execute().
int amigo_todo_op (uint8_t secondary, uint8_t opcode, int len)
Report any Unimplimented commands with Op Codes.
Parameters
in secondary GPIB secondary command
in opcode GPIB data byte OP Code
in len Length of GOIB data returned
Returns
0
Definition at line 791 of file amigo.c.
Referenced by Amigo_Command().
int amigo_verify (uint16_t sectors)
Verify Disk Sectors at current position.
Refernce: A36
Returns
0 ok
1 Error, Sets dsj and Amigo_errors
Definition at line 437 of file amigo.c.
Referenced by Amigo_Command().
Variable Documentation
int Amigo_Errors
uint8_t amigo_state
AMIGO emulator state machine index.
Definition at line 101 of file amigo.c.
Referenced by Amigo_Command(), Amigo_Execute(), amigo_init(), amigo_todo(), and amigo_todo_op().
DirEntryType de
LIF DIrectory Entry.
Reference: hpdisk (c) 2014 Anders Gustafsson anders.gustafsson@pedago.fi
LIF filesystem http://www.hp9845.net/9845/projects/hpdir/#lif_filesystem
LIF data is BIG endian
Definition at line 89 of file amigo.c.
Referenced by gpib_format_disk().
VolumeLabelType vl
LIF data structures used by stand alone formatting utility.
///  Reference: Amigo Command Set Reference used in this document
///  Short Form         Title
///  SS80       "Subset 80 from Fixed and flexible disc drives" 5958-4129
///  HP9123         9123 disc drive manual addendum 5957-6584
///  A          Appendix A "HP 9895A Disc Memory Commends Set"
///             See Receive Status A16
///  L    Buffered Read             0x05    2       A33     Y
///  L    Request Physical Address  0x14    2       A21     Y 0x68
///             See Send Address A20
/// 
///  0x6B Command Op Codes          OP      bytes
///  L    Buffered Read Verify      0x05    2       A37     Y
///  L    ID Triggered Read         0x06    2       A41     Y
/// 
///  0x6C Command Op Codes          OP      bytes
///  L    Unbuffered Read Verify    0x05    2       A38     Y
///  L    Request Physical Address  0x14    2       A21     Y 0x68
///  L    Format Request            0x18    2       A50     N
///  L    Door Lock                 0x19    2       A30     N
///  L    Door Unlock               0x1A    2       A31     N
/// 
///  0x6F Command Op Codes          OP      bytes
///  L    Download Controller       ---     1..256  A26     N
/// 
///  0x70 Command Op Codes          OP      bytes
///  L    HP-300 Clear              ---     1       A23     N
///  T    DSJ                       ---     1       A11     N
/// 
///  0x77 Command Op Codes          OP      bytes
///  T/L  HP-IB CRC                 ---     ---     A30     N
/// 
///  0x7E Command Op Codes          OP      bytes
///  L    Write Loopback Record     ---     1..256  A25     N
///  T    Read Loopback Record      ---     1..256  A14     N
/// 
///  0x7F Command Op Codes          OP      bytes
///  T    Read Self Test Results    ---     2       A13     N
///  L    Initiat Self Test         ---     2       A24     N
/// 
LIF Volume label structure
Reference: hpdisk (c) 2014 Anders Gustafsson anders.gustafsson@pedago.fi
LIF filesystem http://www.hp9845.net/9845/projects/hpdir/#lif_filesystem
LIF data is BIG endian
Definition at line 74 of file amigo.c.
Referenced by gpib_format_disk().