gpib/amigo.c File Reference
AMIGO disk emulator for HP85 disk emulator project for AVR8.
#include `user_config.h`
*
#include `defines.h`
*
#include `gpib.h`
*
#include `gpib_hal.h`
*
#include `gpib_task.h`
*
#include `amigo.h`
*
Enumerations
enum AMIGO_states {
*
AMIGO_IDLE = 0,
AMIGO_REQUEST_STATUS,
AMIGO_REQUEST_STATUS_UNBUFFERED,
AMIGO_REQUEST_STATUS_BUFFERED,
*
AMIGO_REQUEST_LOGICAL_ADDRESS,
AMIGO_COLD_LOAD_READ,
AMIGO_READ_UNBUFFERED,
AMIGO_READ_BUFFERED,
*
AMIGO_WRITE_UNBUFFERED,
AMIGO_WRITE_BUFFERED,
AMIGO_INITIALIZE
 }
Functions
void amigo_init ()
Initialize Amigo state machine, Disk Position, Error status.
int amigo_request_logical_address ()
Set current address in AMIGOState.logical_address[].
int amigo_request_status ()
Set drive status in AMIGOState.status[].
int amigo_send_logical_address ()
Send current address in AMIGOState.logical_address[].
int amigo_send_status ()
Send drive status in AMIGOState.status[].
static DWORD amigo_chs_to_logical (AMIGOStateType *p, char *msg)
Convert Drive CHS position to offset.
static int amigo_overflow_check (AMIGOStateType *p, char *msg)
Check for CHS position overflow.
int amigo_increment (char *msg)
Increment sector if it will not overflow.
int amigo_seek (AMIGOStateType *p)
Seek to the position held in the disk structure.
int amigo_verify (uint16_t sectors)
Verify Disk Sectors at current position.
int amigo_format (uint8_t override, uint8_t interleave, uint8_t db)
Format Disk.
int amigo_buffered_read ()
Do a buffered read of the current sector.
int amigo_buffered_write ()
Do a buffered write of the current sector.
int amigo_cmd_dsj ()
Send DSJ.
int amigo_cmd_wakeup ()
Wakeup (undocumented), just enable PPR response.
int amigo_cmd_clear ()
Response to selected device clear or all clear.
int amigo_todo_op (uint8_t secondary, uint8_t opcode, int len)
Report any Unimplimented commands with Op Codes.
int amigo_todo (uint8_t secondary)
Report any Unimplimented commands.
int Amigo_Command (int secondary)
Amigo Command and OP Code Processing functions.
int Amigo_Execute (int secondary)
Amigo Execute command processing.
int AMIGO_COMMANDS (uint8_t ch)
AMIGO Command state processing.
Variables
uint8_t talking
gpib talk address
uint8_t listening
gpib listen address
Detailed Description
AMIGO disk emulator for HP85 disk emulator project for AVR8.
Edit History - [1.0] [Mike Gore] Initial revision of file.
Copyright 2014 Mike Gore, Inc. All rights reserved.
Based on work by Anders Gustafsson.
Copyright 2014 Anders Gustafsson All rights reserved..
Enumeration Type Documentation
enum AMIGO_states
Enumerator
AMIGO_IDLE
AMIGO_REQUEST_STATUS
AMIGO_REQUEST_STATUS_UNBUFFERED
AMIGO_REQUEST_STATUS_BUFFERED
AMIGO_REQUEST_LOGICAL_ADDRESS
AMIGO_COLD_LOAD_READ
AMIGO_READ_UNBUFFERED
AMIGO_READ_BUFFERED
AMIGO_WRITE_UNBUFFERED
AMIGO_WRITE_BUFFERED
AMIGO_INITIALIZE
Definition at line 153 of file amigo.c.
Function Documentation
int amigo_buffered_read (void)
Do a buffered read of the current sector.
Reference: A33.
Returns
0 ok
GPIB Errors status,Sets dsj and Amigo_errors
Todo
Todo Do we fail on overflow ? currently djs is set - do we want to report that now ?
Definition at line 563 of file amigo.c.
Referenced by Amigo_Execute().
int amigo_buffered_write (void)
Do a buffered write of the current sector.
Reference: A43.
Returns
0 ok
GPIB Errors status,Sets dsj and Amigo_errors
Definition at line 629 of file amigo.c.
Referenced by Amigo_Execute().
static DWORD amigo_chs_to_logical (AMIGOStateType * p, char * msg) [static]
Convert Drive CHS position to offset.
Reference: A15-A19.
Parameters
in p Disk Layout
in msg user message on error
Returns
0
Definition at line 341 of file amigo.c.
Referenced by amigo_buffered_read(), amigo_buffered_write(), amigo_format(), and amigo_verify().
int amigo_cmd_clear (void)
Response to selected device clear or all clear.
Reference: A23.
Select sector 0.
Returns
0
Todo
Todo FIXME
Clear the DSJ byte that might be 2 after powerup
Definition at line 776 of file amigo.c.
Referenced by GPIB().
int amigo_cmd_dsj (void)
Send DSJ.
Reference: A11.
Returns
0 ok
GPIB send Errors status
Sets dsj and Amigo_errors
Definition at line 696 of file amigo.c.
Referenced by AMIGO_COMMANDS().
int amigo_cmd_wakeup (void)
Wakeup (undocumented), just enable PPR response.
Todo
Todo
not finished
Sets dsj and Amigo_errors
Returns
GPIB Errors status - or 0 OK
Todo
Todo FIXME
Definition at line 738 of file amigo.c.
int Amigo_Command (int secondary)
Amigo Command and OP Code Processing functions.
We disbale PPR as soon as a valide command is decoded.
ONLY process Secondary Commands in listen mode with op codes and optional data
Ignore Talking.
Ignore Seconday Addresses.
Ignore Execute state `0x60` here.
Must have OP Codes, or Data, and EOI.
Read all of the Data/Opcodes/Parameters at once - while ATN is false.
Last byte read should be EOI or an error.
Unknown OP Code processing rules.
Skip the remaining codes, Wait for Report Phase.
We enable PPR on exit.
Parameters
in secondary command
Returns
0 on sucess
or GPIB error flags on fail
See also
gpib.h ERROR_MASK defines for a full list)
Reference: A14
Reference: A25
Note: the function will `unread` any commands and return All Data MUST have EOI
Reference: A40
Todo
Todo FIXME
Todo
Todo FIXME
Reference: A27
Seek 1 byte cylinder
Reference: A27
Seek 2 byte cylinder
Reference: A15
Todo
Todo is this the unit $ ?
Reference: A35
Todo
Todo unit ???
Reference: A48 .. A50
Reference: A23
Definition at line 869 of file amigo.c.
Referenced by AMIGO_COMMANDS().
int AMIGO_COMMANDS (uint8_t ch)
AMIGO Command state processing.
Perform Command, Execute or Reporting Phase functions.
Amigo_Command().
Amigo_Execute().
amigo_cmd_dsj().
Parameters
in ch command.
Returns
0 on sucess
or GPIB error flags on fail
See also
gpib.h ERROR_MASK defines for a full list.
Definition at line 1291 of file amigo.c.
Referenced by GPIB_COMMANDS().
int Amigo_Execute (int secondary)
Amigo Execute command processing.
Parameters
in secondary command
Returns
0 on sucess
or GPIB error flags on fail
See also
gpib.h ERROR_MASK defines for a full list)
Definition at line 1179 of file amigo.c.
Referenced by AMIGO_COMMANDS().
int amigo_format (uint8_t override, uint8_t interleave, uint8_t db)
Format Disk.
Refernce: A50.
Parameters
in override not used
in interleave not used
in db byte to fill sector buffer with)
Returns
0 ok
1 on Error,Sets dsj and Amigo_errors
Definition at line 507 of file amigo.c.
Referenced by Amigo_Command().
int amigo_increment (char * msg)
Increment sector if it will not overflow.
Parameters
in msg user message on overflow.
Returns
0 ok.
1 error.
Definition at line 396 of file amigo.c.
Referenced by amigo_buffered_read(), amigo_buffered_write(), amigo_format(), and amigo_verify().
void amigo_init (void)
Initialize Amigo state machine, Disk Position, Error status.
Returns
void
Todo
Todo verify that we always want PPR disabled
Definition at line 171 of file amigo.c.
Referenced by gpib_init_devices().
static int amigo_overflow_check (AMIGOStateType * p, char * msg) [static]
Check for CHS position overflow.
Reference: A15-A19
Returns
0
1 overflow
Definition at line 364 of file amigo.c.
Referenced by amigo_increment(), and amigo_seek().
int amigo_request_logical_address (void)
Set current address in AMIGOState.logical_address[].
Reference: A15-A19
State: Command
Returns
0
Definition at line 198 of file amigo.c.
Referenced by Amigo_Command().
int amigo_request_status (void)
Set drive status in AMIGOState.status[].
Reference: A15-A19.
State: Command.
Returns
0
Todo
Todo dsj
Definition at line 215 of file amigo.c.
Referenced by Amigo_Command().
int amigo_seek (AMIGOStateType * p)
Seek to the position held in the disk structure.
Reference: A27.
We should not commit bad head/sector/cylinder values until tested!..
Parameters
in p AMIGOStateType (Current Disk Position) pointer.
Returns
0 ok
1 error
Definition at line 422 of file amigo.c.
Referenced by Amigo_Command().
int amigo_send_logical_address (void)
Send current address in AMIGOState.logical_address[].
Reference: A15-A19.
State: Execute
Returns
0 on sucess
status GPIB error flags on fail
See also
gpib.h ERROR_MASK defines for a full list.
Definition at line 266 of file amigo.c.
Referenced by Amigo_Execute().
int amigo_send_status (void)
Send drive status in AMIGOState.status[].
Reference: A15-A19.
State: Execute>
Returns
0
status GPIB error flags on fail
See also
gpib.h ERROR_MASK defines for a full list.
Definition at line 303 of file amigo.c.
Referenced by Amigo_Execute().
int amigo_todo (uint8_t secondary)
Report any Unimplimented commands.
Parameters
in secondary GPIB seconday command
Returns
0
Definition at line 829 of file amigo.c.
Referenced by Amigo_Execute().
int amigo_todo_op (uint8_t secondary, uint8_t opcode, int len)
Report any Unimplimented commands with Op Codes.
Parameters
in secondary GPIB secondary command
in opcode GPIB data byte OP Code
in len Length of GOIB data returned
Returns
0
Definition at line 804 of file amigo.c.
Referenced by Amigo_Command().
int amigo_verify (uint16_t sectors)
Verify Disk Sectors at current position.
Refernce: A36
Returns
0 ok
1 Error, Sets dsj and Amigo_errors
Definition at line 450 of file amigo.c.
Referenced by Amigo_Command().
Variable Documentation
uint8_t listening
gpib listen address
Definition at line 92 of file gpib.c.
Referenced by Amigo_Command(), AMIGO_COMMANDS(), Amigo_Execute(), amigo_todo(), amigo_todo_op(), GPIB(), GPIB_COMMANDS(), GPIB_LISTEN(), GPIB_SECONDARY_ADDRESS(), GPIB_TALK(), gpib_task(), and PRINTER_COMMANDS().
uint8_t talking
gpib talk address
/// SS80 References: ("SS80" is the short form used in the project)
///  "Subset 80 from Fixed and flexible disc drives"
///   Printed November, 1985
///   HP Part# 5958-4129
///
/// CS80 References: ("CS80" is the short form used in the project)
///   "CS/80 Instruction Set Programming Manual"
///   Printed: APR 1983
///   HP Part# 5955-3442
///
/// Amigo References: ("Amigo" is the short form used in the project)
///   "Appendix A of 9895A Flexible Disc Memory Service Manual"
///   HP Part# 09895-90030
/// 
///  Reference: Amigo Command Set Reference used in this document
///  Short Form         Title
///  SS80       "Subset 80 from Fixed and flexible disc drives" 5958-4129
///  HP9123         9123 disc drive manual addendum 5957-6584
///  A          Appendix A "HP 9895A Disc Memory Commends Set"
///             See Receive Status A16
///  L    Buffered Read             0x05    2       A33     Y
///  L    Request Physical Address  0x14    2       A21     Y 0x68
///             See Send Address A20
/// 
///  0x6B Command Op Codes          OP      bytes
///  L    Buffered Read Verify      0x05    2       A37     Y
///  L    ID Triggered Read         0x06    2       A41     Y
/// 
///  0x6C Command Op Codes          OP      bytes
///  L    Unbuffered Read Verify    0x05    2       A38     Y
///  L    Request Physical Address  0x14    2       A21     Y 0x68
///  L    Format Request            0x18    2       A50     N
///  L    Door Lock                 0x19    2       A30     N
///  L    Door Unlock               0x1A    2       A31     N
/// 
///  0x6F Command Op Codes          OP      bytes
///  L    Download Controller       ---     1..256  A26     N
/// 
///  0x70 Command Op Codes          OP      bytes
///  L    HP-300 Clear              ---     1       A23     N
///  T    DSJ                       ---     1       A11     N
/// 
///  0x77 Command Op Codes          OP      bytes
///  T/L  HP-IB CRC                 ---     ---     A30     N
/// 
///  0x7E Command Op Codes          OP      bytes
///  L    Write Loopback Record     ---     1..256  A25     N
///  T    Read Loopback Record      ---     1..256  A14     N
/// 
///  0x7F Command Op Codes          OP      bytes
///  T    Read Self Test Results    ---     2       A13     N
///  L    Initiat Self Test         ---     2       A24     N
/// 
/// Secondary_Commands and OP Code processing
///
/// 0x60 Command Op Codes           OP      bytes
/// L    Receive Data               ---     ---
///         Execute of most receive data requests
///         All Disk Write
/// T    Send Data                  ---     ---
///         Execute of most send data requests
///         All Disk Read
///
/// 0x68 Command Op Codes           OP      bytes   Ref     Execute Phase
/// L    Cold Load Read             0x00    2       A40     Y
/// L    Seek                       0x02    6       A27     N
/// L    Request Status buffered        0x03    2       A15     Y 0x68
/// L    Unbuffered Read            0x05    2       A35     Y
/// L    Verify                     0x07    4       A36     N
/// L    Unbuffered Write Request   0x08    2       A45     Y
/// L    Initialize                 0x0B    2       A46     Y
/// L    Initialize DBIT                0x2B    2       A46     Y
/// L    Request Logical Address    0x14    2       A20     Y 0x68
/// L   End                         0x15    2       A29     N
/// T    Send Status or Address         ----    4       A20     N
///         Execute of all Address and Status Requests 
///         (Y 0x68)
///
/// 0x69 Command Op Codes           OP      bytes
/// L    Buffered Write Request     0x08    2       A43     Y
///
/// 0x6A Command Op Codes           OP      bytes
/// L    Request Status Unbuffered   0x03    2      A15     Y 0x68
///         See Receive Status A16
/// L    Buffered Read              0x05    2       A33     Y
/// L    Request Physical Address   0x14    2       A21     Y 0x68
///         See Send Address A20
///
/// 0x6B Command Op Codes           OP      bytes
/// L    Buffered Read Verify       0x05    2       A37     Y
/// L    ID Triggered Read          0x06    2       A41     Y
///
/// 0x6C Command Op Codes           OP      bytes
/// L    Unbuffered Read Verify     0x05    2       A38     Y
/// L    Request Physical Address   0x14    2       A21     Y 0x68
/// L    Format Request                 0x18    2       A50     N
/// L    Door Lock                  0x19    2       A30     N
/// L    Door Unlock                0x1A    2       A31     N
///
/// 0x6F Command Op Codes           OP      bytes
/// L    Download Controller        ---     1..256  A26     N
///
/// 0x70 Command Op Codes           OP      bytes
/// L    HP-300 Clear               ---     1       A23     N
/// T    DSJ                        ---     1       A11     N
///
/// 0x77 Command Op Codes           OP      bytes
/// T/L  HP-IB CRC                  ---     ---     A30     N
///
/// 0x7E Command Op Codes           OP      bytes
/// L    Write Loopback Record      ---     1..256  A25     N
/// T    Read Loopback Record       ---     1..256  A14     N
///
/// 0x7F Command Op Codes           OP      bytes
/// T    Read Self Test Results         ---     2       A13     N
/// L    Initiat Self Test          ---     2       A24     N
/// 
Definition at line 87 of file gpib.c.
Referenced by Amigo_Command(), AMIGO_COMMANDS(), Amigo_Execute(), amigo_todo(), amigo_todo_op(), GPIB(), GPIB_COMMANDS(), GPIB_LISTEN(), GPIB_SECONDARY_ADDRESS(), GPIB_TALK(), and PRINTER_COMMANDS().