posix/buffer.c File Reference
#include `user_config.h`
#include `fatfs.h`
#include `posix.h`
#include `buffer.h`
Functions
buffer_t * buffer_read_open (char *name, uint8_t *buf, int size)
FatFS does not have a f_fgetc() function Using f_read() of just 1 byte is VERY VERY SLOW.
void buffer_read_close (buffer_t *p)
buffered read close FatFS does not have a f_fgetc() and using f_read() of just 1 byte is VERY SLOW
void buffer_ungetc (buffer_t *p, int c)
buffered ungetc
int buffer_getc (buffer_t *p)
buffered getc
uint8_t * buffer_gets (uint8_t *str, int size, buffer_t *p)
buffered getc
Function Documentation
buffer_getc()
int buffer_getc (buffer_t * p)
buffered getc
Parameters
 in p buffer structure ppointer
Returns
character or EOF
Definition at line 98 of file buffer.c.
Referenced by buffer_gets().
buffer_gets()
uint8_t* buffer_gets (uint8_t * str, int size, buffer_t * p)
buffered getc
Parameters
 out str string
   [int] size: maximum string size
 in p buffer structure ppointer
Returns
string or NULL on EOF
Definition at line 132 of file buffer.c.
buffer_read_close()
void buffer_read_close (buffer_t * p)
buffered read close FatFS does not have a f_fgetc() and using f_read() of just 1 byte is VERY SLOW
Parameters
 in p buffer structure ppointer
Returns
void
Definition at line 72 of file buffer.c.
Referenced by buffer_read_open().
buffer_read_open()
buffer_t* buffer_read_open (char * name, uint8_t * buf, int size)
FatFS does not have a f_fgetc() function Using f_read() of just 1 byte is VERY VERY SLOW.
buffered read open
Parameters
 in name file name
 in buf buffer to use when reading
 in size buffer size
Returns
buffer_t pointer, or NULL on error
Read and process into image file
Definition at line 41 of file buffer.c.
buffer_ungetc()
void buffer_ungetc (buffer_t * p, int c)
buffered ungetc
Parameters
 in p buffer structure ppointer
 in c character to unget
Returns
void
Definition at line 88 of file buffer.c.
Referenced by buffer_gets().