posix/buffer.h File Reference
character read buffering wrappers for FatFS WHY? Character at a time operation is in FatFS are VERY slow
Data Structures
struct buffer_t
Functions
buffer_t * buffer_read_open (char *name, uint8_t *buf, int size)
FatFS does not have a f_fgetc() function Using f_read() of just 1 byte is VERY VERY SLOW.
void buffer_read_close (buffer_t *p)
buffered read close FatFS does not have a f_fgetc() and using f_read() of just 1 byte is VERY SLOW
void buffer_ungetc (buffer_t *p, int c)
buffered ungetc
int buffer_getc (buffer_t *p)
buffered getc
uint8_t * buffer_gets (uint8_t *str, int size, buffer_t *p)
buffered getc
Detailed Description
character read buffering wrappers for FatFS WHY? Character at a time operation is in FatFS are VERY slow
character read buffering wrappers for FatFS Character at a time operation is FatFS are VERY slow
Copyright 2014-2020 Mike Gore, All rights reserved. GPL License
See also
http://github.com/magore/hp85disk
http://github.com/magore/hp85disk/COPYRIGHT.md for specific Copyright details
You are free to use this code under the terms of GPL
please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Function Documentation
buffer_getc()
int buffer_getc (buffer_t * p)
buffered getc
Parameters
in p buffer structure ppointer
Returns
character or EOF
Definition at line 98 of file buffer.c.
Referenced by buffer_gets().
buffer_gets()
uint8_t* buffer_gets (uint8_t * str, int size, buffer_t * p)
buffered getc
Parameters
out str string
Definition at line 132 of file buffer.c.
buffer_read_close()
void buffer_read_close (buffer_t * p)
buffered read close FatFS does not have a f_fgetc() and using f_read() of just 1 byte is VERY SLOW
Parameters
in p buffer structure ppointer
Returns
void
Definition at line 72 of file buffer.c.
Referenced by buffer_read_open().
buffer_read_open()
buffer_t* buffer_read_open (char * name, uint8_t * buf, int size)
FatFS does not have a f_fgetc() function Using f_read() of just 1 byte is VERY VERY SLOW.
buffered read open
Parameters
in name file name
in buf buffer to use when reading
in size buffer size
Returns
buffer_t pointer, or NULL on error
Read and process into image file
Definition at line 41 of file buffer.c.
buffer_ungetc()
void buffer_ungetc (buffer_t * p, int c)
buffered ungetc
Parameters
in p buffer structure ppointer
in c character to unget
Returns
void
Definition at line 88 of file buffer.c.
Referenced by buffer_gets().