fatfs/option/cc932.c File Reference
FatFS OEM code bidirectional converter CP932 (Japanese Shift-JIS) (C)ChaN, 2009.
#include `../ff.h`
*
Macros
#define _TINY_TABLE 0
Functions
WCHAR ff_convert (WCHAR chr, UINT dir)
WCHAR ff_wtoupper (WCHAR chr)
Variables
static const WCHAR uni2sjis []
static const WCHAR sjis2uni []
Detailed Description
FatFS OEM code bidirectional converter CP932 (Japanese Shift-JIS) (C)ChaN, 2009.
Copyright 2009 ChaN.
Definition in file cc932.c.
Macro Definition Documentation
#define _TINY_TABLE 0
Definition at line 17 of file cc932.c.
Function Documentation
WCHAR ff_convert (WCHAR chr, UINT dir)
Definition at line 3734 of file cc932.c.
Referenced by create_name(), and get_fileinfo().
WCHAR ff_wtoupper (WCHAR chr)
Definition at line 3794 of file cc932.c.
Referenced by create_name().
Variable Documentation
const WCHAR sjis2uni[] [static]
Definition at line 1879 of file cc932.c.
Referenced by ff_convert().
const WCHAR uni2sjis[] [static]
Definition at line 25 of file cc932.c.
Referenced by ff_convert().