gpib/controller.c File Reference
#include `user_config.h`
#include `defines.h`
#include `drives.h`
#include `gpib_hal.h`
#include `gpib.h`
#include `gpib_task.h`
#include `printer.h`
#include `posix.h`
#include `delay.h`
#include `controller.h`
Functions
int controller_send_str (uint8_t from, uint8_t to, char *str, int len)
Controller Mode send ASCII string Stops sending with EOI.
int controller_read_str (uint8_t from, uint8_t to, char *str, int len)
Controller Mode read ASCII string Stops reading at EOI.
int controller_read_trace (uint8_t from, uint8_t to)
Controller Mode TRACE read for debugging Stops reading at EOI.
void controller_ifc ()
Function Documentation
controller_ifc()
void controller_ifc ()
Definition at line 127 of file controller.c.
controller_read_str()
int controller_read_str (uint8_t from, uint8_t to, char * str, int len)
Controller Mode read ASCII string Stops reading at EOI.
Parameters
 in from GPIB talker
 in to GPIB listener
 in str string to read
 in len maximum number of bytes to read
Returns
number of bytes read
Definition at line 67 of file controller.c.
Referenced by plot_echo().
controller_read_trace()
int controller_read_trace (uint8_t from, uint8_t to)
Controller Mode TRACE read for debugging Stops reading at EOI.
Parameters
 in from GPIB talker
 in to GPIB listener
Returns
number of bytes read
Definition at line 99 of file controller.c.
Referenced by plot_echo().
controller_send_str()
int controller_send_str (uint8_t from, uint8_t to, char * str, int len)
Controller Mode send ASCII string Stops sending with EOI.
Parameters
 in from GPIB talker
 in to GPIB listener
 in str string to send
 in len number of bytes to send (if 0 then length of string)
Returns
number of bytes sent
Definition at line 38 of file controller.c.
Referenced by plot_echo().