hardware/delay.h File Reference
Extended delay routines for AVR.
#include `user_config.h`
Functions
void delayus (uint32_t us)
Delay microseconds using AVR acr-libc _delay_us() function.
void delayms (uint32_t ms)
Delay miliseconds using AVR acr-libc _delay_us() function.
Detailed Description
Extended delay routines for AVR.
Edit History
[1.0] [Mike Gore] Initial revision of file.
Copyright 2014-2020 Mike Gore, Inc. All rights reserved.
Function Documentation
delayms()
void delayms (uint32_t ms)
Delay miliseconds using AVR acr-libc _delay_us() function.
Depends on F_CPU and function _delay_us() _delay_us() has limited range - this extends it.
Returns
void
See also
_delay_us() is part of avr-libc
Definition at line 53 of file delay.c.
Referenced by controller_ifc(), dbf_open_read(), dbf_open_write(), gpib_user_task(), LCD_clear(), LCD_command(), LCD_createChar(), LCD_disableSplash(), LCD_disableSystemMessages(), LCD_enableSplash(), LCD_enableSystemMessages(), LCD_init(), LCD_saveSplash(), LCD_setAddress(), LCD_setContrast(), LCD_setFastBacklightRGB(), LCD_specialCommand(), LCD_specialCommandCount(), main(), and mmc_disk_initialize().
delayus()
void delayus (uint32_t us)
Delay microseconds using AVR acr-libc _delay_us() function.
Depends on F_CPU and function _delay_us() _delay_us() has limited range - this extends it.
Returns
void
See also
_delay_us() is part of avr-libc
Definition at line 26 of file delay.c.
Referenced by gpib_assert_ifc(), gpib_user_task(), i2c_done(), i2c_send_stop(), and i2c_task_done().