fatfs.hal/diskio.h File Reference
#include `ff.h`
Data Structures
struct SDIO_CTRL
Macros
#define DEV_MMC 0 /* Example: Map MMC/SD card to physical drive 1 */
#define DEV_CFC 1 /* Example: Map CF card to physical drive 2 */
#define DEV_RAM 2 /* Example: Map Ramdisk to physical drive 0 */
#define DEV_USB 3 /* Example: Map USB MSD to physical drive 2 */
#define _USE_WRITE 1 /* 1: Enable disk_write function */
#define _USE_IOCTL 1 /* 1: Enable disk_ioctl fucntion */
#define _USE_ISDIO 1 /* 1: Enable iSDIO controls via disk_ioctl */
#define STA_NOINIT 0x01	/* Drive not initialized */
#define STA_NODISK 0x02	/* No medium in the drive */
#define STA_PROTECT 0x04	/* Write protected */
#define CTRL_SYNC 0	/* Complete pending write process (needed at FF_FS_READONLY == 0) */
#define GET_SECTOR_COUNT 1	/* Get media size (needed at FF_USE_MKFS == 1) */
#define GET_SECTOR_SIZE 2	/* Get sector size (needed at FF_MAX_SS != FF_MIN_SS) */
#define GET_BLOCK_SIZE 3	/* Get erase block size (needed at FF_USE_MKFS == 1) */
#define CTRL_TRIM 4	/* Inform device that the data on the block of sectors is no longer used (needed at FF_USE_TRIM == 1) */
#define CTRL_FORMAT 5 /* Create physical format on the media */
#define CTRL_POWER_IDLE 6 /* Put the device idle state */
#define CTRL_POWER_OFF 7 /* Put the device off state */
#define CTRL_LOCK 8 /* Lock media removal */
#define CTRL_UNLOCK 9 /* Unlock media removal */
#define CTRL_EJECT 10 /* Eject media */
#define CTRL_GET_SMART 11 /* Read SMART information */
#define MMC_GET_TYPE 50 /* Get card type */
#define MMC_GET_CSD 51 /* Read CSD */
#define MMC_GET_CID 52 /* Read CID */
#define MMC_GET_OCR 53 /* Read OCR */
#define MMC_GET_SDSTAT 54 /* Read SD status */
#define ISDIO_READ 55 /* Read data form SD iSDIO register */
#define ISDIO_WRITE 56 /* Write data to SD iSDIO register */
#define ISDIO_MRITE 57 /* Masked write data to SD iSDIO register */
#define ATA_GET_REV 60 /* Get F/W revision */
#define ATA_GET_MODEL 61 /* Get model name */
#define ATA_GET_SN 62 /* Get serial number */
#define CT_MMC 0x01 /* MMC ver 3 */
#define CT_SD1 0x02 /* SD ver 1 */
#define CT_SD2 0x04 /* SD ver 2 */
#define CT_SDC (CT_SD1|CT_SD2) /* SD */
#define CT_BLOCK 0x08 /* Block addressing */
Typedefs
typedef BYTE DSTATUS
Enumerations
enum DRESULT {
RES_OK = 0,
RES_ERROR,
RES_WRPRT,
RES_NOTRDY,
RES_PARERR
 }
Functions
DSTATUS disk_status (BYTE pdrv)
DSTATUS disk_initialize (BYTE pdrv)
DRESULT disk_read (BYTE pdrv, BYTE *buff, LBA_t sector, UINT count)
DRESULT disk_write (BYTE pdrv, const BYTE *buff, LBA_t sector, UINT count)
DRESULT disk_ioctl (BYTE pdrv, BYTE cmd, void *buff)
void disk_timerproc (void)
Macro Definition Documentation
_USE_IOCTL
#define _USE_IOCTL 1 /* 1: Enable disk_ioctl fucntion */
Definition at line 21 of file diskio.h.
_USE_ISDIO
#define _USE_ISDIO 1 /* 1: Enable iSDIO controls via disk_ioctl */
Definition at line 22 of file diskio.h.
_USE_WRITE
#define _USE_WRITE 1 /* 1: Enable disk_write function */
Definition at line 20 of file diskio.h.
ATA_GET_MODEL
#define ATA_GET_MODEL 61 /* Get model name */
Definition at line 96 of file diskio.h.
ATA_GET_REV
#define ATA_GET_REV 60 /* Get F/W revision */
Definition at line 95 of file diskio.h.
ATA_GET_SN
#define ATA_GET_SN 62 /* Get serial number */
Definition at line 97 of file diskio.h.
CT_BLOCK
#define CT_BLOCK 0x08 /* Block addressing */
Definition at line 104 of file diskio.h.
Referenced by mmc_disk_initialize(), and mmc_disk_read().
CT_MMC
#define CT_MMC 0x01 /* MMC ver 3 */
Definition at line 100 of file diskio.h.
Referenced by mmc_disk_initialize().
CT_SD1
#define CT_SD1 0x02 /* SD ver 1 */
Definition at line 101 of file diskio.h.
Referenced by mmc_disk_initialize(), and mmc_disk_read().
CT_SD2
#define CT_SD2 0x04 /* SD ver 2 */
Definition at line 102 of file diskio.h.
Referenced by mmc_disk_initialize(), and mmc_disk_read().
CT_SDC
#define CT_SDC (CT_SD1|CT_SD2) /* SD */
Definition at line 103 of file diskio.h.
Referenced by mmc_disk_read().
CTRL_EJECT
#define CTRL_EJECT 10 /* Eject media */
Definition at line 81 of file diskio.h.
CTRL_FORMAT
#define CTRL_FORMAT 5 /* Create physical format on the media */
Definition at line 76 of file diskio.h.
CTRL_GET_SMART
#define CTRL_GET_SMART 11 /* Read SMART information */
Definition at line 82 of file diskio.h.
CTRL_LOCK
#define CTRL_LOCK 8 /* Lock media removal */
Definition at line 79 of file diskio.h.
CTRL_POWER_IDLE
#define CTRL_POWER_IDLE 6 /* Put the device idle state */
Definition at line 77 of file diskio.h.
CTRL_POWER_OFF
#define CTRL_POWER_OFF 7 /* Put the device off state */
Definition at line 78 of file diskio.h.
Referenced by mmc_disk_read().
CTRL_SYNC
#define CTRL_SYNC 0	/* Complete pending write process (needed at FF_FS_READONLY == 0) */
Definition at line 69 of file diskio.h.
Referenced by f_mkfs(), mmc_disk_read(), and sync_fs().
CTRL_TRIM
#define CTRL_TRIM 4	/* Inform device that the data on the block of sectors is no longer used (needed at FF_USE_TRIM == 1) */
Definition at line 73 of file diskio.h.
Referenced by f_mkfs(), mmc_disk_read(), and remove_chain().
CTRL_UNLOCK
#define CTRL_UNLOCK 9 /* Unlock media removal */
Definition at line 80 of file diskio.h.
DEV_CFC
#define DEV_CFC 1 /* Example: Map CF card to physical drive 2 */
Definition at line 16 of file diskio.h.
DEV_MMC
#define DEV_MMC 0 /* Example: Map MMC/SD card to physical drive 1 */
Definition at line 15 of file diskio.h.
DEV_RAM
#define DEV_RAM 2 /* Example: Map Ramdisk to physical drive 0 */
Definition at line 17 of file diskio.h.
DEV_USB
#define DEV_USB 3 /* Example: Map USB MSD to physical drive 2 */
Definition at line 18 of file diskio.h.
GET_BLOCK_SIZE
#define GET_BLOCK_SIZE 3	/* Get erase block size (needed at FF_USE_MKFS == 1) */
Definition at line 72 of file diskio.h.
Referenced by f_mkfs(), mmc_disk_read(), and mmc_init().
GET_SECTOR_COUNT
#define GET_SECTOR_COUNT 1	/* Get media size (needed at FF_USE_MKFS == 1) */
Definition at line 70 of file diskio.h.
Referenced by create_partition(), f_mkfs(), and mmc_disk_read().
GET_SECTOR_SIZE
#define GET_SECTOR_SIZE 2	/* Get sector size (needed at FF_MAX_SS != FF_MIN_SS) */
Definition at line 71 of file diskio.h.
Referenced by create_partition(), f_mkfs(), and mount_volume().
ISDIO_MRITE
#define ISDIO_MRITE 57 /* Masked write data to SD iSDIO register */
Definition at line 92 of file diskio.h.
Referenced by mmc_disk_read().
ISDIO_READ
#define ISDIO_READ 55 /* Read data form SD iSDIO register */
Definition at line 90 of file diskio.h.
Referenced by mmc_disk_read().
ISDIO_WRITE
#define ISDIO_WRITE 56 /* Write data to SD iSDIO register */
Definition at line 91 of file diskio.h.
Referenced by mmc_disk_read().
MMC_GET_CID
#define MMC_GET_CID 52 /* Read CID */
Definition at line 87 of file diskio.h.
Referenced by mmc_disk_read().
MMC_GET_CSD
#define MMC_GET_CSD 51 /* Read CSD */
Definition at line 86 of file diskio.h.
Referenced by mmc_disk_read().
MMC_GET_OCR
#define MMC_GET_OCR 53 /* Read OCR */
Definition at line 88 of file diskio.h.
Referenced by mmc_disk_read().
MMC_GET_SDSTAT
#define MMC_GET_SDSTAT 54 /* Read SD status */
Definition at line 89 of file diskio.h.
Referenced by mmc_disk_read().
MMC_GET_TYPE
#define MMC_GET_TYPE 50 /* Get card type */
Definition at line 85 of file diskio.h.
Referenced by mmc_disk_read().
STA_NODISK
#define STA_NODISK 0x02	/* No medium in the drive */
Definition at line 62 of file diskio.h.
Referenced by mmc_disk_initialize(), mmc_disk_timerproc(), and mmc_test_timeout().
STA_NOINIT
#define STA_NOINIT 0x01	/* Drive not initialized */
Definition at line 61 of file diskio.h.
Referenced by disk_initialize(), disk_status(), f_mkfs(), mmc_disk_initialize(), mmc_disk_read(), mmc_disk_timerproc(), mmc_test_timeout(), mount_volume(), and validate().
STA_PROTECT
#define STA_PROTECT 0x04	/* Write protected */
Definition at line 63 of file diskio.h.
Referenced by f_mkfs(), mmc_disk_read(), mmc_disk_timerproc(), and mount_volume().
Typedef Documentation
DSTATUS
typedef BYTE DSTATUS
Definition at line 25 of file diskio.h.
Enumeration Type Documentation
DRESULT
enum DRESULT
Enumerator
RES_OK
RES_ERROR
RES_WRPRT
RES_NOTRDY
RES_PARERR
Definition at line 28 of file diskio.h.
Function Documentation
disk_initialize()
DSTATUS disk_initialize (BYTE pdrv)
Definition at line 80 of file diskio.c.
Referenced by f_mkfs(), mmc_init(), and mount_volume().
disk_ioctl()
DRESULT disk_ioctl (BYTE pdrv, BYTE cmd, void * buff)
Definition at line 183 of file diskio.c.
Referenced by create_partition(), f_mkfs(), mmc_init(), mount_volume(), remove_chain(), and sync_fs().
disk_read()
DRESULT disk_read (BYTE pdrv, BYTE * buff, LBA_t sector, UINT count)
Definition at line 112 of file diskio.c.
Referenced by f_expand(), f_lseek(), f_mkfs(), f_open(), f_read(), f_write(), and move_window().
disk_status()
DSTATUS disk_status (BYTE pdrv)
Definition at line 49 of file diskio.c.
Referenced by mount_volume(), and validate().
disk_timerproc()
void disk_timerproc (void)
Definition at line 216 of file diskio.c.
disk_write()
DRESULT disk_write (BYTE pdrv, const BYTE * buff, LBA_t sector, UINT count)
Definition at line 147 of file diskio.c.
Referenced by create_partition(), dir_clear(), f_expand(), f_lseek(), f_mkfs(), f_read(), f_sync(), f_truncate(), f_write(), sync_fs(), and sync_window().