fatfs/disk.h File Reference
Allocate, Free and display FILINFO structurs, getfattime(), display error messages.
#include <hardware/hardware.h>
*
#include `ff.h`
*
#include `diskio.h`
*
Functions
void put_rc (int rc)
display FatFs return code as ascii string
FILINFO * fatfs_alloc_finfo (int allocate)
Allocate FILINFO structure and optional long file name buffer.
void fatfs_free_filinfo (FILINFO *finfo)
Free a FILINFO structure and optional long file name buffer allocated by fatfs_alloc_finfo()
int fatfs_scan_files (char *path)
Compute space used, number of directories and files contained under a specified directory.
void fatfs_status (char *ptr)
Compute space used, number of directories and files contained used by a drive.
void fatfs_filinfo_list (FILINFO *info)
Display FILINFO structure in a readable format.
Variables
DWORD AccSize
Total file space used.
WORD AccFiles
Total number or Files and Directories.
WORD AccDirs
FATFS Fatfs [_VOLUMES]
FatFs Drive Volumes.
Detailed Description
Allocate, Free and display FILINFO structurs, getfattime(), display error messages.
Copyright 2015 Mike Gore, GPL License
Copyright 2013 ChaN.
Credit: part of FatFs avr example project (C)ChaN, 2013.
You are free to use this code under the terms of GPL
please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition in file disk.h.
Function Documentation
FILINFO* fatfs_alloc_finfo (int allocate)
Allocate FILINFO structure and optional long file name buffer.
Parameters
in allocate If allocate is true use safecalloc otherwise return static __finfo
See Also
fatfs_free_finfo()
fatfs_scan_files()
fatfs_ls()
Returns
FILINFO * on success
NULL on error
Definition at line 169 of file disk.c.
Referenced by fatfs_ls(), fatfs_scan_files(), fatfs_stat(), and stat().
void fatfs_filinfo_list (FILINFO * info)
Display FILINFO structure in a readable format.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Example:
/// ----A 2014/10/16 00:39        14    test2.txt  
/// D---- 2014/10/12 21:29         0          tmp 
/// 
@param[in] : FILINFO pointer
@return  void  
Definition at line 358 of file disk.c.
Referenced by fatfs_ls(), and fatfs_stat().
void fatfs_free_filinfo (FILINFO * finfo)
Free a FILINFO structure and optional long file name buffer allocated by fatfs_alloc_finfo()
Parameters
in finfo FatFs FILINFO pointer to free
See Also
fatfs_alloc_finfo()
fatfs_scan_files()
fatfs_ls()
Returns
void
Definition at line 218 of file disk.c.
int fatfs_scan_files (char * path)
Compute space used, number of directories and files contained under a specified directory.
Credit: part of FatFs avr example project (C)ChaN, 2013
Parameters
in path
See Also
f_opendir()
f_readdir()
AccDirs: Total number of directories
AccFiles: Total number of Files
AccSize: Total size of all files
Returns
0 if no error
FafFs error code
Definition at line 246 of file disk.c.
Referenced by fatfs_scan_files(), and fatfs_status().
void fatfs_status (char * ptr)
Compute space used, number of directories and files contained used by a drive.
Credit: part of FatFs avr example project (C)ChaN, 2013
Parameters
in ptr Drive path like `/`
See Also
f_getfree() drive free space
fatfs_scan_files()
AccDirs: Total number of directories
AccFiles: Total number of Files
AccSize: Total size of all files
Returns
void
Definition at line 307 of file disk.c.
Referenced by fatfs_tests(), mmc_init(), and mmc_test().
void put_rc (int rc)
display FatFs return code as ascii string
Credit: Part of FatFs avr example project (C)ChaN, 2013
Parameters
in rc FatFs status return code
Returns
void
Definition at line 134 of file disk.c.
Referenced by dbf_close(), dbf_lseek(), dbf_open(), dbf_read(), dbf_write(), fatfs_cat(), fatfs_cd(), fatfs_copy(), fatfs_create(), fatfs_ls(), fatfs_mkdir(), fatfs_pwd(), fatfs_rename(), fatfs_rm(), fatfs_rmdir(), fatfs_stat(), fatfs_status(), fatfs_tests(), and mmc_init().
Variable Documentation
WORD AccDirs
Definition at line 150 of file disk.c.
Referenced by fatfs_scan_files(), and fatfs_status().
WORD AccFiles
Total number or Files and Directories.
Definition at line 150 of file disk.c.
Referenced by fatfs_scan_files(), and fatfs_status().
DWORD AccSize
Total file space used.
Definition at line 147 of file disk.c.
Referenced by fatfs_scan_files(), and fatfs_status().
FATFS Fatfs[_VOLUMES]
FatFs Drive Volumes.
Definition at line 34 of file disk.c.
Referenced by mmc_init().