fatfs/disk.c File Reference
FatFs utilities utilities and tests for HP85 disk emulator project.
#include `hardware/hardware.h`
*
#include `ff.h`
*
#include `diskio.h`
*
#include `posix.h`
*
Functions
void put_rc (int rc)
display FatFs return code as ascii string
FILINFO * fatfs_alloc_finfo (int allocate)
Allocate FILINFO structure and optional long file name buffer.
void fatfs_free_filinfo (FILINFO *finfo)
Free a FILINFO structure and optional long file name buffer allocated by fatfs_alloc_finfo()
int fatfs_scan_files (char *path)
Compute space used, number of directories and files contained under a specified directory.
void fatfs_status (char *ptr)
Compute space used, number of directories and files contained used by a drive.
void fatfs_filinfo_list (FILINFO *info)
Display FILINFO structure in a readable format.
Variables
FATFS Fatfs [_VOLUMES]
FatFs Drive Volumes.
static char * err_msg []
FatFs Error Messages.
DWORD AccSize
Total file space used.
WORD AccFiles
Total number or Files and Directories.
WORD AccDirs
static FILINFO __finfo
Use were FILINFO structure can be share in many functions See: fatfs_alloc_finfo(), fatfs_scan_files() and fatfs_ls()
Detailed Description
FatFs utilities utilities and tests for HP85 disk emulator project.
Edit History
[1.0] [Mike Gore] Initial revision of file.
Copyright 2014 CHaN.
Copyright 2014 Mike Gore, Inc. All rights reserved.
Credit: used parts of FatFs avr example project (C)ChaN, 2013.
Definition in file disk.c.
Function Documentation
FILINFO* fatfs_alloc_finfo (int allocate)
Allocate FILINFO structure and optional long file name buffer.
Parameters
in allocate If allocate is true use safecalloc otherwise return static __finfo
See Also
fatfs_free_finfo()
fatfs_scan_files()
fatfs_ls()
Returns
FILINFO * on success
NULL on error
Definition at line 108 of file disk.c.
Referenced by fatfs_ls(), fatfs_scan_files(), and stat().
void fatfs_filinfo_list (FILINFO * info)
Display FILINFO structure in a readable format.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Example:
/// ----A 2014/10/16 00:39        14    test2.txt  
/// D---- 2014/10/12 21:29         0          tmp 
/// 
@param[in] : FILINFO pointer
@return  void  
Definition at line 297 of file disk.c.
Referenced by fatfs_ls(), and fatfs_stat().
void fatfs_free_filinfo (FILINFO * finfo)
Free a FILINFO structure and optional long file name buffer allocated by fatfs_alloc_finfo()
Parameters
in finfo FatFs FILINFO pointer to free
See Also
fatfs_alloc_finfo()
fatfs_scan_files()
fatfs_ls()
Returns
void
Definition at line 157 of file disk.c.
int fatfs_scan_files (char * path)
Compute space used, number of directories and files contained under a specified directory.
Credit: part of FatFs avr example project (C)ChaN, 2013
Parameters
in path
See Also
f_opendir()
f_readdir()
AccDirs: Total number of directories
AccFiles: Total number of Files
AccSize: Total size of all files
Returns
0 if no error
FafFs error code
Definition at line 185 of file disk.c.
Referenced by fatfs_scan_files(), and fatfs_status().
void fatfs_status (char * ptr)
Compute space used, number of directories and files contained used by a drive.
Credit: part of FatFs avr example project (C)ChaN, 2013
Parameters
in ptr Drive path like `/`
See Also
f_getfree() drive free space
fatfs_scan_files()
AccDirs: Total number of directories
AccFiles: Total number of Files
AccSize: Total size of all files
Returns
void
Definition at line 246 of file disk.c.
Referenced by fatfs_tests(), mmc_init(), and mmc_test().
void put_rc (int rc)
display FatFs return code as ascii string
Credit: Part of FatFs avr example project (C)ChaN, 2013
Parameters
in rc FatFs status return code
Returns
void
Definition at line 73 of file disk.c.
Referenced by dbf_close(), dbf_lseek(), dbf_open(), dbf_read(), dbf_write(), fatfs_cat(), fatfs_cd(), fatfs_copy(), fatfs_create(), fatfs_ls(), fatfs_mkdir(), fatfs_pwd(), fatfs_rename(), fatfs_rm(), fatfs_rmdir(), fatfs_status(), fatfs_tests(), and mmc_init().
Variable Documentation
FILINFO __finfo [static]
Use were FILINFO structure can be share in many functions See: fatfs_alloc_finfo(), fatfs_scan_files() and fatfs_ls()
Definition at line 93 of file disk.c.
WORD AccDirs
Definition at line 89 of file disk.c.
Referenced by fatfs_scan_files(), and fatfs_status().
WORD AccFiles
Total number or Files and Directories.
Definition at line 89 of file disk.c.
Referenced by fatfs_scan_files(), and fatfs_status().
DWORD AccSize
Total file space used.
Definition at line 86 of file disk.c.
Referenced by fatfs_scan_files(), and fatfs_status().
char* err_msg[] [static]
Initial value:
=
{
    "OK",
    "DISK_ERR",
    "INT_ERR",
    "NOT_READY",
    "NO_FILE",
    "NO_PATH",
    "INVALID_NAME",
    "DENIED",
    "EXIST",
    "INVALID_OBJECT",
    "WRITE_PROTECTED",
    "INVALID_DRIVE",
    "NOT_ENABLED",
    "NO_FILE_SYSTEM",
    "MKFS_ABORTED",
    "TIMEOUT",
    "LOCKED",
    "NOT_ENOUGH_CORE",
    "TOO_MANY_OPEN_FILES",
    "INVALID_PARAMETER",
    NULL
}
FatFs Error Messages.
Credit: part of FatFs avr example project (C)ChaN, 2013
Definition at line 42 of file disk.c.
Referenced by put_rc().
FATFS Fatfs[_VOLUMES]
FatFs Drive Volumes.
Definition at line 23 of file disk.c.
Referenced by mmc_init().