fatfs.hal/diskio.c File Reference
#include `user_config.h`
#include `fatfs.h`
#include `ff.h`
#include `diskio.h`
Macros
#define DEV_MMC 0	/* Example: Map MMC/SD card to physical drive 1 */
#define DEV_CFC 1	/* Example: Map CF card to physical drive 2 */
#define DEV_RAM 2	/* Example: Map Ramdisk to physical drive 0 */
#define DEV_USB 3	/* Example: Map USB MSD to physical drive 2 */
Functions
DSTATUS disk_status (BYTE pdrv)
DSTATUS disk_initialize (BYTE pdrv)
DRESULT disk_read (BYTE pdrv, BYTE *buff, LBA_t sector, UINT count)
DRESULT disk_write (BYTE pdrv, const BYTE *buff, LBA_t sector, UINT count)
DRESULT disk_ioctl (BYTE pdrv, BYTE cmd, void *buff)
void disk_timerproc (void)
Macro Definition Documentation
DEV_CFC
#define DEV_CFC 1	/* Example: Map CF card to physical drive 2 */
Definition at line 41 of file diskio.c.
Referenced by disk_ioctl().
DEV_MMC
#define DEV_MMC 0	/* Example: Map MMC/SD card to physical drive 1 */
Definition at line 40 of file diskio.c.
Referenced by disk_initialize(), disk_ioctl(), disk_read(), disk_status(), disk_write(), and mmc_init().
DEV_RAM
#define DEV_RAM 2	/* Example: Map Ramdisk to physical drive 0 */
Definition at line 42 of file diskio.c.
Referenced by disk_initialize(), disk_ioctl(), disk_read(), disk_status(), and disk_write().
DEV_USB
#define DEV_USB 3	/* Example: Map USB MSD to physical drive 2 */
Definition at line 43 of file diskio.c.
Referenced by disk_initialize(), disk_read(), disk_status(), and disk_write().
Function Documentation
disk_initialize()
DSTATUS disk_initialize (BYTE pdrv)
Definition at line 80 of file diskio.c.
Referenced by f_mkfs(), mmc_init(), and mount_volume().
disk_ioctl()
DRESULT disk_ioctl (BYTE pdrv, BYTE cmd, void * buff)
Definition at line 183 of file diskio.c.
Referenced by create_partition(), f_mkfs(), mmc_init(), mount_volume(), remove_chain(), and sync_fs().
disk_read()
DRESULT disk_read (BYTE pdrv, BYTE * buff, LBA_t sector, UINT count)
Definition at line 112 of file diskio.c.
Referenced by f_expand(), f_lseek(), f_mkfs(), f_open(), f_read(), f_write(), and move_window().
disk_status()
DSTATUS disk_status (BYTE pdrv)
Definition at line 49 of file diskio.c.
Referenced by mount_volume(), and validate().
disk_timerproc()
void disk_timerproc (void)
Definition at line 216 of file diskio.c.
disk_write()
DRESULT disk_write (BYTE pdrv, const BYTE * buff, LBA_t sector, UINT count)
Definition at line 147 of file diskio.c.
Referenced by create_partition(), dir_clear(), f_expand(), f_lseek(), f_mkfs(), f_read(), f_sync(), f_truncate(), f_write(), sync_fs(), and sync_window().