doc.c File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include <stdarg.h>
*
#include <string.h>
*
#include <time.h>
*
#include <malloc.h>
*
#include <sys/types.h>
*
#include <sys/stat.h>
*
#include <unistd.h>
*
#include <libgen.h>
*
#include <errno.h>
*
#include <fcntl.h>
*
#include <sys/time.h>
*
#include <sys/file.h>
*
#include <signal.h>
*
#include <setjmp.h>
*
Macros
#define MAXSTR 1024
#define MAX_LINE 4096
#define DATE_LEN 23
#define PATH_LEN 1024
#define SPACES ` \t\r`
#define SPACESNL ` \t\n\r`
#define TRUE 1
#define FALSE 0
Enumerations
enum {
*
T_NULL,
T_FUNCTION,
T_BRIEF,
T_REFERENCE,
*
T_NOTES,
T_STANDARD,
T_PARAMETER,
T_RETURN,
*
T_SEE,
T_TODO,
T_FIXME
 }
Functions
void strtrim (char *str)
char * skipspaces (char *str)
char * skipchars (char *str, char *pat)
char * skipline (char *str)
void nlspace (char *str)
void uncr (char *str)
void unnl (char *str)
void uncomma (char *str)
char * readtoken (char *ptr, char *result)
int find_char_ln (char *ptr, char c)
int find_char (char *ptr, char c)
char * lastword (char *ptr)
char * param (char *ptr)
char * str_gets_comma (char *ptr, char *line, int max)
int MATCH_LEN (char *str, char *pat)
int MATCHI_LEN (char *str, char *pat)
char * stralloc (char *str)
char * file_time (char *name)
char * today_str ()
int is_empty (char *ptr)
void trim_tail (char *str)
void process (char *name)
int main (int argc, char *argv[])
Variables
char date [128] = { 0 }
Macro Definition Documentation
#define DATE_LEN 23
Definition at line 34 of file doc.c.
#define FALSE 0
Definition at line 45 of file doc.c.
#define MAX_LINE 4096
Definition at line 33 of file doc.c.
#define MAXSTR 1024
Definition at line 24 of file doc.c.
Referenced by file_time(), process(), and today_str().
#define PATH_LEN 1024
Definition at line 35 of file doc.c.
#define SPACES ` \t\r`
Definition at line 37 of file doc.c.
#define SPACESNL ` \t\n\r`
Definition at line 38 of file doc.c.
#define TRUE 1
Definition at line 41 of file doc.c.
Enumeration Type Documentation
anonymous enum
Enumerator
T_NULL
T_FUNCTION
T_BRIEF
T_REFERENCE
T_NOTES
T_STANDARD
T_PARAMETER
T_RETURN
T_SEE
T_TODO
T_FIXME
Definition at line 400 of file doc.c.
Function Documentation
char* file_time (char * name)
Definition at line 327 of file doc.c.
int find_char (char * ptr, char c)
Definition at line 193 of file doc.c.
int find_char_ln (char * ptr, char c)
Definition at line 178 of file doc.c.
int is_empty (char * ptr)
Definition at line 365 of file doc.c.
char* lastword (char * ptr)
Definition at line 208 of file doc.c.
int main (int argc, char * argv[])
Definition at line 577 of file doc.c.
int MATCH_LEN (char * str, char * pat)
Definition at line 271 of file doc.c.
int MATCHI_LEN (char * str, char * pat)
Definition at line 291 of file doc.c.
Referenced by process().
void nlspace (char * str)
Definition at line 106 of file doc.c.
char* param (char * ptr)
Definition at line 221 of file doc.c.
Referenced by process().
void process (char * name)
Definition at line 415 of file doc.c.
Referenced by main().
char* readtoken (char * ptr, char * result)
Definition at line 155 of file doc.c.
Referenced by process().
char* skipchars (char * str, char * pat)
Definition at line 73 of file doc.c.
char* skipline (char * str)
Definition at line 92 of file doc.c.
char* skipspaces (char * str)
Definition at line 62 of file doc.c.
Referenced by FatFs_Read_Config(), fatfs_tests(), gpib_tests(), gpib_trace_task(), plot_echo(), POSIX_Read_Config(), readtoken(), receive_plot(), and task().
char* str_gets_comma (char * ptr, char * line, int max)
Definition at line 241 of file doc.c.
char* stralloc (char * str)
Definition at line 309 of file doc.c.
Referenced by file_time(), and today_str().
void strtrim (char * str)
Definition at line 49 of file doc.c.
char* today_str ()
Definition at line 349 of file doc.c.
void trim_tail (char * str)
Definition at line 385 of file doc.c.
Referenced by FatFs_Read_Config(), POSIX_Read_Config(), and process().
void uncomma (char * str)
Definition at line 136 of file doc.c.
void uncr (char * str)
Definition at line 118 of file doc.c.
void unnl (char * str)
Definition at line 127 of file doc.c.
Variable Documentation
char date[128] = { 0 }
Definition at line 21 of file doc.c.
Referenced by main(), and process().