gpib/drives.c File Reference
drive definitions for HP85 disk emulator project for AVR.
#include `user_config.h`
#include <stdint.h>
#include `defines.h`
#include `drives.h`
#include `gpib_hal.h`
#include `gpib.h`
#include `gpib_task.h`
#include `amigo.h`
#include `ss80.h`
#include <time.h>
#include `lifutils.h`
#include `debug.h`
Macros
#define MAX_STACK 5
Config Parser Stack.
Functions
void print_var_P (__memx const char *str, uint32_t val)
Display Configuration File variable.
void print_str_P (__memx const char *str, char *arg)
Display Configuration File string.
int tok_index (char *str)
return the tokens index of the matching string
char * tok_name (uint8_t tok)
return string of matching token
void print_tok_val (uint8_t tok, uint8_t spaces, uint32_t val)
Display Configuration File variable.
void print_tok_str (uint8_t tok, uint8_t spaces, char *str)
Display Configuration File variable.
void print_tok (uint8_t tok, uint8_t spaces)
Display Configuration File variable
int Read_Config (char *name)
Read and parse a config file using POSIX functions Set all drive parameters and debuglevel.
void display_Addresses (int verbose)
Display Configuration device address saummary.
void display_Config (int verbose)
Display current Configuration File values.
int find_type (int type)
Seach Devices[] for ANY definitions of a disk type.
int count_drive_types (uint8_t type)
Count number of devices of a sertain type.
char * type_to_str (int type)
Convert a disk type into a string.
char * base_to_str (int base)
Convert base address into a string identifier.
int find_free ()
Find first free Devices[] slot.
int find_device (int type, int address, int base)
Find a device with matching type AND address.
int set_active_device (int index)
Set the Active disk or device pointers Since we can be called multiple times per single GPIB state we do not display state changes here. Other code displays the active state.
void SS80_Set_Defaults (int index)
Set Default Values for a new SS80 Device IF defaults have been defined Most values in the CONTROLER and UNIT are defaults that should not need to be specified Note all of the values are zeroed on allocation including strings.
int alloc_device (int type)
Allocate a Device structure for a disk or printer.
void init_Devices ()
Init Config Parser Stack Called only durring power up so we do not have to free memory.
int push_state (int state)
Push Parser State.
int pop_state ()
Pop Parser State.
bool assign_value (char *str, uint32_t minval, uint32_t maxval, uint32_t *val)
assigned a value
void set_Config_Defaults ()
Set Defaults for any missing disk or printer devices These are only used if the Config file omits them or is empty.
void hpdir_set_device (int index)
Set Device parameters from hpdir information.
void hpdir_set_parameters (int index, char *model)
Lookup model in and set drive parameters if found.
void Post_Config ()
Post Process COnfiguration file after reading.
void format_drives ()
Format devices that have no image file.
Variables
hpdir_t hpdir
hpdir.ini file processing
static int stack_ind = 0
static int stack_p [MAX_STACK]
DeviceType Devices [MAX_DEVICES]
PRINTERDeviceType * PRINTERp = NULL
Active Printer Device.
SS80DiskType * SS80p = NULL
Active SS80 Device.
SS80StateType * SS80s = NULL
token_t tokens []
int lines = 0
Config file line number.
Detailed Description
drive definitions for HP85 disk emulator project for AVR.
Edit History
[1.0] [Mike Gore] Initial revision of file.
Copyright 2014-2020 Mike Gore, All rights reserved. GPL
See also
http://github.com/magore/hp85disk
http://github.com/magore/hp85disk/COPYRIGHT.md for Copyright details
Macro Definition Documentation
MAX_STACK
#define MAX_STACK 5
Config Parser Stack.
Definition at line 28 of file drives.c.
Referenced by push_state().
Function Documentation
alloc_device()
int alloc_device (int type)
Allocate a Device structure for a disk or printer.
Parameters
type disk type
Returns
Devices[] index on sucess or -1
Definition at line 1210 of file drives.c.
Referenced by Read_Config().
assign_value()
bool assign_value (char * str, uint32_t minval, uint32_t maxval, uint32_t * val)
assigned a value
===============================================
Used only for debugging
Parameters
in str string to examine
in minval minimum value
in maxval maximum value
in *val value to set
Returns
1 is matched and value in range, 0 not matched or out of range
Definition at line 1322 of file drives.c.
base_to_str()
char* base_to_str (int base)
Convert base address into a string identifier.
Parameters
base BASE_MAL, BASE_MTA or BASE_MSA only
Returns
string `MLA`, `MTA`, `MSA` or error string
Definition at line 1029 of file drives.c.
count_drive_types()
int count_drive_types (uint8_t type)
Count number of devices of a sertain type.
Parameters
type disk type like SS80_TYPE
Definition at line 996 of file drives.c.
Referenced by main().
display_Addresses()
void display_Addresses (int verbose)
Display Configuration device address saummary.
===============================================
Returns
void
Definition at line 772 of file drives.c.
Referenced by gpib_tests(), and main().
display_Config()
void display_Config (int verbose)
Display current Configuration File values.
===============================================
Returns
void
Active Printer Device
Active SS80 Device
Definition at line 844 of file drives.c.
Referenced by gpib_tests().
find_device()
int find_device (int type, int address, int base)
Find a device with matching type AND address.
Parameters
type disk type
address GPIB device address 0 based
base BASE_MLA,BASE_MTA or BASE_MSA address range
Returns
index of Devices[] or -1 if not found
Make sure address is in expected range
convert to device address
search for device address
Definition at line 1054 of file drives.c.
Referenced by listen_cleanup(), PRINTER_is_MLA(), PRINTER_is_MSA(), PRINTER_is_MTA(), SS80_is_MLA(), SS80_is_MSA(), and SS80_is_MTA().
find_free()
int find_free (void)
Find first free Devices[] slot.
Returns
Devices[] index of free slot or -1
Definition at line 1043 of file drives.c.
Referenced by alloc_device(), and set_Config_Defaults().
find_type()
int find_type (int type)
Seach Devices[] for ANY definitions of a disk type.
Parameters
type disk type like SS80_TYPE
Definition at line 982 of file drives.c.
Referenced by find_free(), plot_echo(), set_Config_Defaults(), and SS80_Set_Defaults().
format_drives()
void format_drives (void)
Format devices that have no image file.
===============================================
Returns
void
Active SS80 Device
Definition at line 1546 of file drives.c.
Referenced by main().
hpdir_set_device()
void hpdir_set_device (int index)
Set Device parameters from hpdir information.
===============================================
Parameters
in model model string
Returns
1 on sucess or 0 on fail
Definition at line 1437 of file drives.c.
Referenced by hpdir_set_parameters().
hpdir_set_parameters()
void hpdir_set_parameters (int index, char * model)
Lookup model in and set drive parameters if found.
===============================================
Parameters
in index Devices index
in model model string
Returns
void
Definition at line 1484 of file drives.c.
Referenced by Read_Config().
init_Devices()
void init_Devices (void)
Init Config Parser Stack Called only durring power up so we do not have to free memory.
Definition at line 1266 of file drives.c.
Referenced by Read_Config().
pop_state()
int pop_state (void)
Pop Parser State.
===============================================
Returns
state
Definition at line 1300 of file drives.c.
Referenced by Read_Config().
Post_Config()
void Post_Config (void)
Post Process COnfiguration file after reading.
===============================================
Returns
void
Active SS80 Device
Definition at line 1494 of file drives.c.
Referenced by Read_Config().
print_str_P()
void print_str_P (__memx const char * str, char * arg)
Display Configuration File string.
===============================================
Parameters
*str title
*arg string
Returns
void
Definition at line 240 of file drives.c.
print_tok()
void print_tok (uint8_t tok, uint8_t spaces)
Display Configuration File variable
=============================================== Display Configuration File variable
Parameters
str title
spaces indent
Returns
void
Definition at line 320 of file drives.c.
Referenced by display_Config().
print_tok_str()
void print_tok_str (uint8_t tok, uint8_t spaces, char * str)
Display Configuration File variable.
===============================================
Parameters
tok token
spaces indent
str string
Returns
void
Definition at line 304 of file drives.c.
Referenced by display_Addresses(), and display_Config().
print_tok_val()
void print_tok_val (uint8_t tok, uint8_t spaces, uint32_t val)
Display Configuration File variable.
===============================================
Parameters
tok token
spaces indent
val variable value
Returns
void
Definition at line 289 of file drives.c.
Referenced by display_Addresses(), and display_Config().
print_var_P()
void print_var_P (__memx const char * str, uint32_t val)
Display Configuration File variable.
===============================================
Parameters
str title
val variable value
Returns
void
Definition at line 223 of file drives.c.
push_state()
int push_state (int state)
Push Parser State.
===============================================
Parameters
state parser state
Returns
state
Definition at line 1287 of file drives.c.
Referenced by Read_Config().
Read_Config()
int Read_Config (char * name)
Read and parse a config file using POSIX functions Set all drive parameters and debuglevel.
===============================================
Parameters
name config file name to process
Returns
number of parse errors
Printer Device
SS80 Device
Definition at line 335 of file drives.c.
Referenced by gpib_file_init().
set_active_device()
int set_active_device (int index)
Set the Active disk or device pointers Since we can be called multiple times per single GPIB state we do not display state changes here. Other code displays the active state.
Parameters
index Devices[] index
Returns
1 on success or 0 on fail
We also check for -1 So the result of find_device() can be used without additional tests
Definition at line 1084 of file drives.c.
Referenced by PRINTER_is_MLA(), PRINTER_is_MSA(), PRINTER_is_MTA(), SS80_init(), SS80_is_MLA(), SS80_is_MSA(), and SS80_is_MTA().
set_Config_Defaults()
void set_Config_Defaults (void)
Set Defaults for any missing disk or printer devices These are only used if the Config file omits them or is empty.
===============================================
Returns
void
Definition at line 1369 of file drives.c.
Referenced by gpib_file_init(), and Read_Config().
SS80_Set_Defaults()
void SS80_Set_Defaults (int index)
Set Default Values for a new SS80 Device IF defaults have been defined Most values in the CONTROLER and UNIT are defaults that should not need to be specified Note all of the values are zeroed on allocation including strings.
Returns
void
Definition at line 1168 of file drives.c.
Referenced by alloc_device().
tok_index()
int tok_index (char * str)
return the tokens index of the matching string
===============================================
Parameters
str string tro match
Returns
int index
Definition at line 255 of file drives.c.
Referenced by Read_Config().
tok_name()
char* tok_name (uint8_t tok)
return string of matching token
===============================================
Parameters
tok token
Returns
char *ptr;
Definition at line 271 of file drives.c.
Referenced by print_tok(), print_tok_str(), and print_tok_val().
type_to_str()
char* type_to_str (int type)
Convert a disk type into a string.
Parameters
type disk type like SS80_TYPE
Returns
string pointer
Definition at line 1012 of file drives.c.
Referenced by alloc_device(), and set_active_device().
Variable Documentation
Devices
DeviceType Devices[MAX_DEVICES]
Definition at line 32 of file drives.c.
Referenced by SS80_init().
hpdir
hpdir_t hpdir
hpdir.ini file processing
Definition at line 48 of file drives.c.
lines
int lines = 0
Config file line number.
Definition at line 1310 of file drives.c.
Referenced by assign_value(), MatRead(), and Read_Config().
PRINTERp
PRINTERDeviceType* PRINTERp = NULL
Active Printer Device.
Definition at line 35 of file drives.c.
SS80p
SS80DiskType* SS80p = NULL
Active SS80 Device.
Definition at line 38 of file drives.c.
Referenced by GPIB_SECONDARY_ADDRESS(), SS80_Amigo_Clear(), SS80_Blocks_to_Bytes(), SS80_Bytes_to_Blocks(), SS80_Cancel(), SS80_Channel_Independent_Clear(), SS80_cmd_seek(), SS80_Command_State(), SS80_COMMANDS(), SS80_Execute_State(), SS80_init(), SS80_locate_and_read(), SS80_locate_and_write(), SS80_Selected_Device_Clear(), SS80_Transparent_State(), SS80_Universal_Device_Clear(), SS80ControllerPack(), SS80UnitPack(), and SS80VolumePack().
SS80s
SS80StateType* SS80s = NULL
Definition at line 39 of file drives.c.
Referenced by Clear_Common(), GPIB(), SS80_Cancel(), SS80_Check_Unit(), SS80_Check_Volume(), SS80_cmd_seek(), SS80_Command_State(), SS80_error_return(), SS80_Execute_State(), SS80_increment(), SS80_init(), SS80_locate_and_read(), SS80_locate_and_write(), SS80_Report(), SS80_send_status(), and SS80_Transparent_State().
stack_ind
int stack_ind = 0 [static]
Definition at line 29 of file drives.c.
Referenced by init_Devices(), pop_state(), and push_state().
stack_p
int stack_p[MAX_STACK] [static]
Definition at line 30 of file drives.c.
Referenced by pop_state(), and push_state().
tokens
token_t tokens[]
Definition at line 169 of file drives.c.