gpib/drives_sup.c File Reference
drive definition parsing for HP85 disk emulator project for AVR.
#include `user_config.h`
#include `drives_sup.h`
Functions
void hpdir_init ()
hpdir.ini file processing
long lif_dir_count (long blocks)
LIF Directory blocks ~= sqrt(blocks);.
int hpdir_find_drive (char *model, int list, int verbose)
Find drive parameters in hpdir.ini file.
Variables
hpdir_t hpdir
hpdir.ini file processing
Detailed Description
drive definition parsing for HP85 disk emulator project for AVR.
Edit History
[1.0] [Mike Gore] Initial revision of file.
Copyright 2014-2020 Mike Gore, All rights reserved. GPL
See also
 http://github.com/magore/hp85disk
 http://github.com/magore/hp85disk/COPYRIGHT.md for Copyright details
Function Documentation
hpdir_find_drive()
int hpdir_find_drive (char * model, int list, int verbose)
Find drive parameters in hpdir.ini file.
===============================================
Parameters
 in model model string
Returns
1 on sucess or 0 on fail
Definition at line 79 of file drives_sup.c.
Referenced by hpdir_set_parameters(), lif_tests(), and mount().
hpdir_init()
void hpdir_init ()
hpdir.ini file processing
===========================================================
Init Disk Parameter Structure
This structure will containes the parsed and computed disk parameters from a single hpdir disk entry
Returns
void
Definition at line 25 of file drives_sup.c.
Referenced by hpdir_find_drive().
lif_dir_count()
long lif_dir_count (long blocks)
LIF Directory blocks ~= sqrt(blocks);.
We simplify BITS = MSB bit number of block count Directory size = BITS / 2
Parameters
 in blocks size of LIF image in total
Returns
Size of LIF directory in blocks
Definition at line 57 of file drives_sup.c.
Referenced by format_drives(), and lif_tests().
Variable Documentation
hpdir
hpdir_t hpdir
hpdir.ini file processing
Definition at line 15 of file drives_sup.c.
Referenced by hpdir_find_drive(), hpdir_init(), and lif_tests().