gpib/drives.h File Reference
#include `user_config.h`
#include `posix.h`
#include `drives_sup.h`
Data Structures
struct HeaderType
struct ConfigType
struct AMIGOStateType
AMIGO emulator state machine index.
struct PRINTERDeviceType
Printer structure.
struct PRINTERStateType
Plotter file data structure definition used for saving plot data.
struct AMIGOGeometryType
struct AMIGODiskType
AMIGO Disk structure - ID bytes and layout.
struct SS80ControllerType
SS80 Controller.
struct SS80UnitType
SS80 Unit.
struct SS80VolumeType
Volume Information Structure.
struct SS80DiskType
Disk Information Structure.
struct SS80StateType
SS80 Emulated disk state information.
struct DeviceType
Device Type.
union val_t
struct token_t
Macros
#define HP9134L
defulats if not drives defined in sdcard config file
#define MAX_DEVICES 12
Maximum number of emulated devices.
#define print_var(format, args...) print_var_P(PSTR(format), ##args)
@convert print_var strings into __memx space
#define print_str(format, args...) print_str_P(PSTR(format), ##args)
@convert print_var strings into __memx space
Enumerations
enum PARSE_STATES {
START_STATE,
SS80_STATE,
SS80_HEADER,
SS80_CONFIG,
SS80_CONTROLLER,
SS80_UNIT,
SS80_VOLUME,
CONTROLLER_STATE,
CONTROLLER_CONTROLLER,
CONTROLLER_UNIT,
AMIGO_STATE,
AMIGO_HEADER,
AMIGO_CONFIG,
AMIGO_GEOMETRY,
PRINTER_STATE,
PRINTER_CONFIG
 }
enum DEVICE_TYPES {
NO_TYPE,
AMIGO_TYPE,
SS80_DEFAULT_TYPE,
SS80_TYPE,
PRINTER_TYPE
 }
enum {
TOK_ACCESS_TIME = 0,
TOK_ADDRESS,
TOK_AMIGO,
TOK_BLOCKS,
TOK_BLOCK_TIME,
TOK_BUFFERED_BLOCKS,
TOK_BURST_SIZE,
TOK_BYTES_PER_BLOCK,
TOK_BYTES_PER_SECTOR,
TOK_CONFIG,
TOK_CONTINUOUS_TRANSFER_RATE,
TOK_CONTROLLER,
TOK_CS80,
TOK_CYLINDERS,
TOK_DEBUG,
TOK_DEVICE_NUMBER,
TOK_DRIVE,
TOK_END,
TOK_FILE,
TOK_FIXED_VOLUMES,
TOK_GEOMETRY,
TOK_HEADER,
TOK_HEADS,
TOK_ID,
TOK_INTERLEAVE,
TOK_MAX_BLOCK_NUMBER,
TOK_MAX_CYLINDER,
TOK_MAX_HEAD,
TOK_MAXIMUM_INTERLEAVE,
TOK_MAX_SECTOR,
TOK_OPTIMAL_RETRY_TIME,
TOK_PPR,
TOK_PRINTER,
TOK_REMOVABLE_VOLUMES,
TOK_SECTORS_PER_TRACK,
TOK_SS80,
TOK_SS80_DEFAULT,
TOK_TRANSFER_RATE,
TOK_TYPE,
TOK_UNIT,
TOK_UNITS_INSTALLED,
TOK_UNIT_TYPE,
TOK_VOLUME,
TOK_INVALID = -1
 }
Functions
void print_var_P (__memx const char *str, uint32_t val)
Display Configuration File variable.
void print_str_P (__memx const char *str, char *arg)
Display Configuration File string.
int tok_index (char *str)
return the tokens index of the matching string
char * tok_name (uint8_t tok)
return string of matching token
void print_tok_val (uint8_t tok, uint8_t spaces, uint32_t val)
Display Configuration File variable.
void print_tok_str (uint8_t tok, uint8_t spaces, char *str)
Display Configuration File variable.
void print_tok (uint8_t tok, uint8_t spaces)
Display Configuration File variable.
int Read_Config (char *name)
Read and parse a config file using POSIX functions Set all drive parameters and debuglevel.
void display_Addresses (int verbose)
Display Configuration device address saummary.
void display_Config (int verbose)
Display current Configuration File values.
int find_type (int type)
Seach Devices[] for ANY definitions of a disk type.
int count_drive_types (uint8_t type)
Count number of devices of a sertain type.
char * type_to_str (int type)
Convert a disk type into a string.
char * base_to_str (int base)
Convert base address into a string identifier.
int find_free (void)
Find first free Devices[] slot.
int find_device (int type, int address, int base)
Find a device with matching type AND address.
int set_active_device (int index)
Set the Active disk or device pointers Since we can be called multiple times per single GPIB state we do not display state changes here. Other code displays the active state.
void SS80_Set_Defaults (int index)
Set Default Values for a new SS80 Device IF defaults have been defined Most values in the CONTROLER and UNIT are defaults that should not need to be specified Note all of the values are zeroed on allocation including strings.
int alloc_device (int type)
Allocate a Device structure for a disk or printer.
void init_Devices (void)
Init Config Parser Stack Called only durring power up so we do not have to free memory.
int push_state (int state)
Push Parser State.
int pop_state (void)
Pop Parser State.
bool assign_value (char *str, uint32_t minval, uint32_t maxval, uint32_t *val)
assigned a value
void set_Config_Defaults (void)
Set Defaults for any missing disk or printer devices These are only used if the Config file omits them or is empty.
void hpdir_set_device (int index)
Set Device parameters from hpdir information.
void hpdir_set_parameters (int index, char *model)
Lookup model in and set drive parameters if found.
void Post_Config (void)
Post Process COnfiguration file after reading.
void format_drives (void)
Format devices that have no image file.
void mount (int argc, char *argv[])
mount disks - testing
void display_mounts (void)
Variables
SS80DiskType * SS80p
Active SS80 Device.
SS80StateType * SS80s
PRINTERDeviceType * PRINTERp
Active Printer Device.
DeviceType Devices [MAX_DEVICES]
Macro Definition Documentation
HP9134L
#define HP9134L
defulats if not drives defined in sdcard config file
Definition at line 33 of file drives.h.
MAX_DEVICES
#define MAX_DEVICES 12
Maximum number of emulated devices.
Definition at line 37 of file drives.h.
print_str
#define print_str(format, args...) print_str_P(PSTR(format), ##args)
@convert print_var strings into __memx space
Definition at line 270 of file drives.h.
print_var
#define print_var(format, args...) print_var_P(PSTR(format), ##args)
@convert print_var strings into __memx space
Definition at line 268 of file drives.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
TOK_ACCESS_TIME
TOK_ADDRESS
TOK_AMIGO
TOK_BLOCKS
TOK_BLOCK_TIME
TOK_BUFFERED_BLOCKS
TOK_BURST_SIZE
TOK_BYTES_PER_BLOCK
TOK_BYTES_PER_SECTOR
TOK_CONFIG
TOK_CONTINUOUS_TRANSFER_RATE
TOK_CONTROLLER
TOK_CS80
TOK_CYLINDERS
TOK_DEBUG
TOK_DEVICE_NUMBER
TOK_DRIVE
TOK_END
TOK_FILE
TOK_FIXED_VOLUMES
TOK_GEOMETRY
TOK_HEADER
TOK_HEADS
TOK_ID
TOK_INTERLEAVE
TOK_MAX_BLOCK_NUMBER
TOK_MAX_CYLINDER
TOK_MAX_HEAD
TOK_MAXIMUM_INTERLEAVE
TOK_MAX_SECTOR
TOK_OPTIMAL_RETRY_TIME
TOK_PPR
TOK_PRINTER
TOK_REMOVABLE_VOLUMES
TOK_SECTORS_PER_TRACK
TOK_SS80
TOK_SS80_DEFAULT
TOK_TRANSFER_RATE
TOK_TYPE
TOK_UNIT
TOK_UNITS_INSTALLED
TOK_UNIT_TYPE
TOK_VOLUME
TOK_INVALID
Definition at line 294 of file drives.h.
DEVICE_TYPES
enum DEVICE_TYPES
Enumerator
NO_TYPE
AMIGO_TYPE
SS80_DEFAULT_TYPE
SS80_TYPE
PRINTER_TYPE
Definition at line 245 of file drives.h.
PARSE_STATES
enum PARSE_STATES
Enumerator
START_STATE
SS80_STATE
SS80_HEADER
SS80_CONFIG
SS80_CONTROLLER
SS80_UNIT
SS80_VOLUME
CONTROLLER_STATE
CONTROLLER_CONTROLLER
CONTROLLER_UNIT
AMIGO_STATE
AMIGO_HEADER
AMIGO_CONFIG
AMIGO_GEOMETRY
PRINTER_STATE
PRINTER_CONFIG
Definition at line 223 of file drives.h.
Function Documentation
alloc_device()
int alloc_device (int type)
Allocate a Device structure for a disk or printer.
Parameters
type disk type
Returns
Devices[] index on sucess or -1
Definition at line 1212 of file drives.c.
Referenced by Read_Config().
assign_value()
bool assign_value (char * str, uint32_t minval, uint32_t maxval, uint32_t * val)
assigned a value
===============================================
Used only for debugging
Parameters
 in str string to examine
 in minval minimum value
 in maxval maximum value
 in *val value to set
Returns
1 is matched and value in range, 0 not matched or out of range
Definition at line 1324 of file drives.c.
base_to_str()
char* base_to_str (int base)
Convert base address into a string identifier.
Parameters
base BASE_MAL, BASE_MTA or BASE_MSA only
Returns
string `MLA`, `MTA`, `MSA` or error string
Definition at line 1031 of file drives.c.
count_drive_types()
int count_drive_types (uint8_t type)
Count number of devices of a sertain type.
Parameters
type disk type like SS80_TYPE
Definition at line 998 of file drives.c.
Referenced by main().
display_Addresses()
void display_Addresses (int verbose)
Display Configuration device address saummary.
===============================================
Returns
void
Definition at line 773 of file drives.c.
Referenced by gpib_tests(), and main().
display_Config()
void display_Config (int verbose)
Display current Configuration File values.
===============================================
Returns
void
Active Printer Device
Active SS80 Device
Definition at line 844 of file drives.c.
Referenced by gpib_tests().
display_mounts()
void display_mounts (void)
Active Printer Device
Active SS80 Device
Definition at line 1649 of file drives.c.
Referenced by mount().
find_device()
int find_device (int type, int address, int base)
Find a device with matching type AND address.
Parameters
type disk type
address GPIB device address 0 based
base BASE_MLA,BASE_MTA or BASE_MSA address range
Returns
index of Devices[] or -1 if not found
Make sure address is in expected range
convert to device address
search for device address
Definition at line 1056 of file drives.c.
Referenced by listen_cleanup(), PRINTER_is_MLA(), PRINTER_is_MSA(), PRINTER_is_MTA(), SS80_is_MLA(), SS80_is_MSA(), and SS80_is_MTA().
find_free()
int find_free ()
Find first free Devices[] slot.
Returns
Devices[] index of free slot or -1
Definition at line 1045 of file drives.c.
Referenced by alloc_device(), and set_Config_Defaults().
find_type()
int find_type (int type)
Seach Devices[] for ANY definitions of a disk type.
Parameters
type disk type like SS80_TYPE
Definition at line 984 of file drives.c.
Referenced by find_free(), set_Config_Defaults(), and SS80_Set_Defaults().
format_drives()
void format_drives ()
Format devices that have no image file.
===============================================
Returns
void
Active SS80 Device
Definition at line 1548 of file drives.c.
Referenced by main().
hpdir_set_device()
void hpdir_set_device (int index)
Set Device parameters from hpdir information.
===============================================
Parameters
 in model model string
Returns
1 on sucess or 0 on fail
Definition at line 1439 of file drives.c.
Referenced by hpdir_set_parameters().
hpdir_set_parameters()
void hpdir_set_parameters (int index, char * model)
Lookup model in and set drive parameters if found.
===============================================
Parameters
 in index Devices index
 in model model string
Returns
void
Definition at line 1486 of file drives.c.
Referenced by Read_Config().
init_Devices()
void init_Devices (void)
Init Config Parser Stack Called only durring power up so we do not have to free memory.
Definition at line 1268 of file drives.c.
Referenced by Read_Config().
mount()
void mount (int argc, char * argv[])
mount disks - testing
===============================================
Returns
void
Definition at line 1638 of file drives.c.
Referenced by gpib_tests().
pop_state()
int pop_state ()
Pop Parser State.
===============================================
Returns
state
Definition at line 1302 of file drives.c.
Referenced by Read_Config().
Post_Config()
void Post_Config ()
Post Process COnfiguration file after reading.
===============================================
Returns
void
Active SS80 Device
Definition at line 1496 of file drives.c.
Referenced by Read_Config().
print_str_P()
void print_str_P (__memx const char * str, char * arg)
Display Configuration File string.
===============================================
Parameters
*str title
*arg string
Returns
void
Definition at line 241 of file drives.c.
print_tok()
void print_tok (uint8_t tok, uint8_t spaces)
Display Configuration File variable.
===============================================
@brief Display Configuration File variable
Parameters
str title
spaces indent
Returns
void
Definition at line 321 of file drives.c.
Referenced by display_Config().
print_tok_str()
void print_tok_str (uint8_t tok, uint8_t spaces, char * str)
Display Configuration File variable.
===============================================
Parameters
tok token
spaces indent
str string
Returns
void
Definition at line 305 of file drives.c.
Referenced by display_Addresses(), and display_Config().
print_tok_val()
void print_tok_val (uint8_t tok, uint8_t spaces, uint32_t val)
Display Configuration File variable.
===============================================
Parameters
tok token
spaces indent
val variable value
Returns
void
Definition at line 290 of file drives.c.
Referenced by display_Addresses(), and display_Config().
print_var_P()
void print_var_P (__memx const char * str, uint32_t val)
Display Configuration File variable.
===============================================
Parameters
str title
val variable value
Returns
void
Definition at line 224 of file drives.c.
push_state()
int push_state (int state)
Push Parser State.
===============================================
Parameters
state parser state
Returns
state
Definition at line 1289 of file drives.c.
Referenced by Read_Config().
Read_Config()
int Read_Config (char * name)
Read and parse a config file using POSIX functions Set all drive parameters and debuglevel.
===============================================
Parameters
name config file name to process
Returns
number of parse errors
Printer Device
SS80 Device
Definition at line 336 of file drives.c.
Referenced by gpib_file_init().
set_active_device()
int set_active_device (int index)
Set the Active disk or device pointers Since we can be called multiple times per single GPIB state we do not display state changes here. Other code displays the active state.
Parameters
index Devices[] index
Returns
1 on success or 0 on fail
We also check for -1 So the result of find_device() can be used without additional tests
Definition at line 1086 of file drives.c.
Referenced by PRINTER_is_MLA(), PRINTER_is_MSA(), PRINTER_is_MTA(), SS80_init(), SS80_is_MLA(), SS80_is_MSA(), and SS80_is_MTA().
set_Config_Defaults()
void set_Config_Defaults ()
Set Defaults for any missing disk or printer devices These are only used if the Config file omits them or is empty.
===============================================
Returns
void
Definition at line 1371 of file drives.c.
Referenced by gpib_file_init(), and Read_Config().
SS80_Set_Defaults()
void SS80_Set_Defaults (int index)
Set Default Values for a new SS80 Device IF defaults have been defined Most values in the CONTROLER and UNIT are defaults that should not need to be specified Note all of the values are zeroed on allocation including strings.
Returns
void
Definition at line 1170 of file drives.c.
Referenced by alloc_device().
tok_index()
int tok_index (char * str)
return the tokens index of the matching string
===============================================
Parameters
str string tro match
Returns
int index
Definition at line 256 of file drives.c.
Referenced by Read_Config().
tok_name()
char* tok_name (uint8_t tok)
return string of matching token
===============================================
Parameters
tok token
Returns
char *ptr;
Definition at line 272 of file drives.c.
Referenced by print_tok(), print_tok_str(), and print_tok_val().
type_to_str()
char* type_to_str (int type)
Convert a disk type into a string.
Parameters
type disk type like SS80_TYPE
Returns
string pointer
Definition at line 1014 of file drives.c.
Referenced by alloc_device(), and set_active_device().
Variable Documentation
Devices
DeviceType Devices[MAX_DEVICES]
Definition at line 32 of file drives.c.
Referenced by alloc_device(), count_drive_types(), display_Addresses(), display_Config(), display_mounts(), find_device(), find_type(), format_drives(), hpdir_set_device(), init_Devices(), Post_Config(), Read_Config(), set_active_device(), set_Config_Defaults(), SS80_init(), and SS80_Set_Defaults().
PRINTERp
PRINTERDeviceType* PRINTERp
Active Printer Device.
Definition at line 35 of file drives.c.
Referenced by display_Config(), display_mounts(), Read_Config(), and set_active_device().
SS80p
SS80DiskType* SS80p
Active SS80 Device.
Definition at line 38 of file drives.c.
Referenced by display_Addresses(), display_Config(), display_mounts(), format_drives(), GPIB_SECONDARY_ADDRESS(), hpdir_set_device(), Post_Config(), Read_Config(), set_active_device(), SS80_Amigo_Clear(), SS80_Blocks_to_Bytes(), SS80_Bytes_to_Blocks(), SS80_Cancel(), SS80_Channel_Independent_Clear(), SS80_cmd_seek(), SS80_Command_State(), SS80_COMMANDS(), SS80_Execute_State(), SS80_init(), SS80_locate_and_read(), SS80_locate_and_write(), SS80_Selected_Device_Clear(), SS80_Set_Defaults(), SS80_Transparent_State(), SS80_Universal_Device_Clear(), SS80ControllerPack(), SS80UnitPack(), and SS80VolumePack().
SS80s
SS80StateType* SS80s
Definition at line 39 of file drives.c.
Referenced by Clear_Common(), GPIB(), set_active_device(), SS80_Cancel(), SS80_Check_Unit(), SS80_Check_Volume(), SS80_cmd_seek(), SS80_Command_State(), SS80_error_return(), SS80_Execute_State(), SS80_increment(), SS80_init(), SS80_locate_and_read(), SS80_locate_and_write(), SS80_Report(), SS80_send_status(), and SS80_Transparent_State().