gpib/drives_sup.h File Reference
Data Structures
struct hpdir_t
Macros
#define MODEL_SIZE 32
Data structure for hpdir.ini HPDir project disk parameters.
Functions
void hpdir_init (void)
hpdir.ini file processing
long lif_dir_count (long blocks)
LIF Directory blocks ~= sqrt(blocks);.
int hpdir_find_drive (char *model, int list, int verbose)
Find drive parameters in hpdir.ini file.
Macro Definition Documentation
MODEL_SIZE
#define MODEL_SIZE 32
Data structure for hpdir.ini HPDir project disk parameters.
================================================= This structure will containes the parsed and computed disk parameters from a single hpdir disk entry
; AMIGIO/CS80/SS80 disk drives ; 1 - SS80 [HP9134L] unique drive model identifier (should be identical to [fsinfo] section above) ; 2 - COMMENT descriptive string ; 3 - SS80/AMIGO: drive protocol AMIGO, CS80 or SS80 ; 4 - ID: ID returned by AMIGO identify ; 5 - mask for secondary ID returned by high byte of STAT2 ; 6 - ID returned by high byte of STAT2 ; 7 - DEVICE_NUMBER: drive number returned by CS/80 describe command ; 8 - UNITS_INSTALLED(0x8001): number of units installed ; 9 - MAX_CYLINDER: number of cylinders ;10 - MAX_HEAD: number of heads or surfaces ;11 - MAX_SECTOR: number of sectors per track ;12 - BYTES_PER_BLOCK: number of bytes per block or sector ;13 - INTERLEAVE: default interleave ;14 - media type 0=fixed media, 1=removable media ; # Removable volume byte; one bit per volume (set if removable) ; 1, x, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,13,14 Example entry 9895 = `HP9895A dual 1.15M AMIGO floppy disc`, AMIGO, 0x0081, 0x00, 0x00, 0x000000, 1, 77, 2, 30, 256, 7, 1
Returns
void
Definition at line 31 of file drives_sup.h.
Function Documentation
hpdir_find_drive()
int hpdir_find_drive (char * model, int list, int verbose)
Find drive parameters in hpdir.ini file.
===============================================
Parameters
in model model string
Returns
1 on sucess or 0 on fail
Definition at line 79 of file drives_sup.c.
Referenced by hpdir_set_parameters(), and lif_tests().
hpdir_init()
void hpdir_init (void)
hpdir.ini file processing
===========================================================Init Disk Parameter Structure
This structure will containes the parsed and computed disk parameters from a single hpdir disk entry
Returns
void
Definition at line 27 of file drives_sup.c.
Referenced by hpdir_find_drive().
lif_dir_count()
long lif_dir_count (long blocks)
LIF Directory blocks ~= sqrt(blocks);.
We simplify BITS = MSB bit number of block count Directory size = BITS / 2
Parameters
in blocks size of LIF image in total
Returns
Size of LIF directory in blocks
Definition at line 58 of file drives_sup.c.
Referenced by format_drives(), and lif_tests().