fatfs/fatfs_tests.h File Reference
FatFs utilities and tests for HP85 disk emulator project.
#include `hardware/hardware.h`
*
#include `ff.h`
*
#include `diskio.h`
*
Functions
void fatfs_ls (char *ptr)
List files under a specified directory.
void fatfs_rename (const char *oldpath, const char *newpath)
Rename a file.
void fatfs_cat (char *name)
Display the contents of a file.
void fatfs_copy (char *from, char *to)
Copy a file.
void fatfs_create (char *name, char *str)
Create a new file from a user supplied string.
void fatfs_rm (char *name)
Delete a file by name.
void fatfs_mkdir (char *name)
Make a directory.
void fatfs_rmdir (char *name)
Delete a directory.
void fatfs_stat (char *name)
Display FILINFO status of a file by name.
void fatfs_cd (char *name)
Change directory.
void fatfs_pwd (void)
Display current working directory.
Detailed Description
FatFs utilities and tests for HP85 disk emulator project.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Edit History
[1.0] [Mike Gore] Initial revision of file.
Copyright 2014 Mike Gore, Inc. All rights reserved.
Copyright 2013 ChaN.
Definition in file fatfs_tests.h.
Function Documentation
void fatfs_cat (char * name)
Display the contents of a file.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Parameters
in name file name.
Returns
void.
Todo
Todo FIXME
Definition at line 101 of file fatfs_tests.c.
Referenced by fatfs_tests(), and mmc_test().
void fatfs_cd (char * name)
Change directory.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Parameters
in name Directory name.
Returns
void.
Definition at line 328 of file fatfs_tests.c.
Referenced by fatfs_tests(), and mmc_test().
void fatfs_copy (char * from, char * to)
Copy a file.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Parameters
in from source file.
in to destination file.
Returns
void.
Definition at line 163 of file fatfs_tests.c.
Referenced by fatfs_tests(), and mmc_test().
void fatfs_create (char * name, char * str)
Create a new file from a user supplied string.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Parameters
in name name of file to create.
in str string containing file contents.
Returns
void.
Definition at line 224 of file fatfs_tests.c.
Referenced by fatfs_tests(), and mmc_test().
void fatfs_ls (char * ptr)
List files under a specified directory.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Parameters
in ptr pathname of directory to list
See Also
fatfs_filinfo_list().
Returns
void.
Definition at line 31 of file fatfs_tests.c.
Referenced by fatfs_tests(), and mmc_test().
void fatfs_mkdir (char * name)
Make a directory.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Parameters
in name Directory name.
Returns
void
Definition at line 281 of file fatfs_tests.c.
Referenced by fatfs_tests(), and mmc_test().
void fatfs_pwd (void)
Display current working directory.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Returns
void.
Definition at line 341 of file fatfs_tests.c.
Referenced by fatfs_tests(), and mmc_test().
void fatfs_rename (const char * oldpath, const char * newpath)
Rename a file.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Parameters
in oldpath old name.
in newpath new name.
Returns
void
Definition at line 82 of file fatfs_tests.c.
Referenced by fatfs_tests().
void fatfs_rm (char * name)
Delete a file by name.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Parameters
in name File name to delete.
Returns
void.
Definition at line 266 of file fatfs_tests.c.
Referenced by fatfs_tests().
void fatfs_rmdir (char * name)
Delete a directory.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Parameters
in name Directory name.
Returns
void.
Definition at line 297 of file fatfs_tests.c.
Referenced by fatfs_tests().
void fatfs_stat (char * name)
Display FILINFO status of a file by name.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Parameters
in name File name.
Returns
void
Definition at line 311 of file fatfs_tests.c.
Referenced by fatfs_tests().