fatfs.sup/fatfs_tests.c File Reference
#include `user_config.h`
#include `fatfs.h`
#include `time.h`
#include `stringsup.h`
#include `mathio.h`
Functions
MEMSPACE void fatfs_help (int full)
Display FatFs test diagnostics help menu.
MEMSPACE int fatfs_tests (int argc, char *argv[])
FatFs test parser.
MEMSPACE void mmc_test (void)
Perform key FatFs diagnostics tests.
MEMSPACE void fatfs_ls (char *name)
Function Documentation
fatfs_help()
MEMSPACE void fatfs_help (int full)
Display FatFs test diagnostics help menu.
Returns
void
Definition at line 46 of file fatfs_tests.c.
Referenced by fatfs_tests(), and help().
fatfs_ls()
MEMSPACE void fatfs_ls (char * name)
Credit: part of FatFs avr example project (C)ChaN, 2013.
Parameters
 in ptr pathname of directory to list
See also
fatfs_filinfo_list().
Returns
void.
Definition at line 313 of file fatfs_tests.c.
Referenced by fatfs_tests(), and mmc_test().
fatfs_tests()
MEMSPACE int fatfs_tests (int argc, char * argv[])
FatFs test parser.
Keywords and arguments are matched against fatfs test functions If ther are matched the function along with its argements are called.
Parameters
 in str User supplied command line with FatFs test and arguments.
Returns
1 The ruturn code indicates a command matched.
0 if no rules matched
Definition at line 102 of file fatfs_tests.c.
Referenced by user_task().
mmc_test()
MEMSPACE void mmc_test (void)
Perform key FatFs diagnostics tests.
Perform all basic file tests
Assumes the device is formatted
Returns
void
Definition at line 270 of file fatfs_tests.c.
Referenced by fatfs_tests().