fatfs/fatfs_utils.c File Reference
FatFs utilities and tests for HP85 disk emulator project.
#include `hardware/hardware.h`
*
#include `fatfs_tests.h`
*
#include `fatfs_utils.h`
*
#include `posix.h`
*
Functions
void mmc_test (void)
Perform key FatFs diagnostics tests.
void fatfs_help (void)
Display FatFs test diagnostics help menu.
int fatfs_tests (char *str)
FatFs test parser.
Detailed Description
FatFs utilities and tests for HP85 disk emulator project.
Based on FatFs AVR example library (C) ChaN 2013.
Edit History
[1.0] [Mike Gore] Initial revision of file.
Copyright 2014 Mike Gore, Inc. All rights reserved.
Copyright 2013 ChaN.
Definition in file fatfs_utils.c.
Function Documentation
void fatfs_help (void)
Display FatFs test diagnostics help menu.
See Also
fatfs_tests.c.
Returns
void
Definition at line 62 of file fatfs_utils.c.
Referenced by fatfs_tests(), and help().
int fatfs_tests (char * str)
FatFs test parser.
Keywords and arguments are matched against fatfs test functions If ther are matched the function along with its argements are called.
Parameters
in str User supplied command line with FatFs test and arguments.
See Also
fatfs_tests.c
Returns
1 The ruturn code indicates a command matched.
0 if no rules matched
Definition at line 96 of file fatfs_utils.c.
Referenced by task().
void mmc_test (void)
Perform key FatFs diagnostics tests.
Perform all basic file tests
Assumes the device is formatted
Returns
void
Definition at line 28 of file fatfs_utils.c.
Referenced by fatfs_tests().