fatfs/ff.c File Reference
#include `user_config.h`
#include `fatfs.h`
#include `ff.h`
#include `diskio.h`
Macros
#define MAX_DIR 0x200000		/* Max size of FAT directory */
#define MAX_DIR_EX 0x10000000		/* Max size of exFAT directory */
#define MAX_FAT12 0xFF5			/* Max FAT12 clusters (differs from specs, but right for real DOS/Windows behavior) */
#define MAX_FAT16 0xFFF5			/* Max FAT16 clusters (differs from specs, but right for real DOS/Windows behavior) */
#define MAX_FAT32 0x0FFFFFF5		/* Max FAT32 clusters (not specified, practical limit) */
#define MAX_EXFAT 0x7FFFFFFD		/* Max exFAT clusters (differs from specs, implementation limit) */
#define IsUpper(c) ((c) >= 'A' && (c) <= 'Z')
#define IsLower(c) ((c) >= 'a' && (c) <= 'z')
#define IsDigit(c) ((c) >= '0' && (c) <= '9')
#define IsSurrogate(c) ((c) >= 0xD800 && (c) <= 0xDFFF)
#define IsSurrogateH(c) ((c) >= 0xD800 && (c) <= 0xDBFF)
#define IsSurrogateL(c) ((c) >= 0xDC00 && (c) <= 0xDFFF)
#define FA_SEEKEND 0x20	/* Seek to end of the file on file open */
#define FA_MODIFIED 0x40	/* File has been modified */
#define FA_DIRTY 0x80	/* FIL.buf[] needs to be written-back */
#define AM_VOL 0x08	/* Volume label */
#define AM_LFN 0x0F	/* LFN entry */
#define AM_MASK 0x3F	/* Mask of defined bits */
#define NSFLAG 11		/* Index of the name status byte */
#define NS_LOSS 0x01	/* Out of 8.3 format */
#define NS_LFN 0x02	/* Force to create LFN entry */
#define NS_LAST 0x04	/* Last segment */
#define NS_BODY 0x08	/* Lower case flag (body) */
#define NS_EXT 0x10	/* Lower case flag (ext) */
#define NS_DOT 0x20	/* Dot entry */
#define NS_NOLFN 0x40	/* Do not find LFN */
#define NS_NONAME 0x80	/* Not followed */
#define ET_BITMAP 0x81	/* Allocation bitmap */
#define ET_UPCASE 0x82	/* Up-case table */
#define ET_VLABEL 0x83	/* Volume label */
#define ET_FILEDIR 0x85	/* File and directory */
#define ET_STREAM 0xC0	/* Stream extension */
#define ET_FILENAME 0xC1	/* Name extension */
#define BS_JmpBoot 0		/* x86 jump instruction (3-byte) */
#define BS_OEMName 3		/* OEM name (8-byte) */
#define BPB_BytsPerSec 11		/* Sector size [byte] (WORD) */
#define BPB_SecPerClus 13		/* Cluster size [sector] (BYTE) */
#define BPB_RsvdSecCnt 14		/* Size of reserved area [sector] (WORD) */
#define BPB_NumFATs 16		/* Number of FATs (BYTE) */
#define BPB_RootEntCnt 17		/* Size of root directory area for FAT [entry] (WORD) */
#define BPB_TotSec16 19		/* Volume size (16-bit) [sector] (WORD) */
#define BPB_Media 21		/* Media descriptor byte (BYTE) */
#define BPB_FATSz16 22		/* FAT size (16-bit) [sector] (WORD) */
#define BPB_SecPerTrk 24		/* Number of sectors per track for int13h [sector] (WORD) */
#define BPB_NumHeads 26		/* Number of heads for int13h (WORD) */
#define BPB_HiddSec 28		/* Volume offset from top of the drive (DWORD) */
#define BPB_TotSec32 32		/* Volume size (32-bit) [sector] (DWORD) */
#define BS_DrvNum 36		/* Physical drive number for int13h (BYTE) */
#define BS_NTres 37		/* WindowsNT error flag (BYTE) */
#define BS_BootSig 38		/* Extended boot signature (BYTE) */
#define BS_VolID 39		/* Volume serial number (DWORD) */
#define BS_VolLab 43		/* Volume label string (8-byte) */
#define BS_FilSysType 54		/* Filesystem type string (8-byte) */
#define BS_BootCode 62		/* Boot code (448-byte) */
#define BS_55AA 510		/* Signature word (WORD) */
#define BPB_FATSz32 36		/* FAT32: FAT size [sector] (DWORD) */
#define BPB_ExtFlags32 40		/* FAT32: Extended flags (WORD) */
#define BPB_FSVer32 42		/* FAT32: Filesystem version (WORD) */
#define BPB_RootClus32 44		/* FAT32: Root directory cluster (DWORD) */
#define BPB_FSInfo32 48		/* FAT32: Offset of FSINFO sector (WORD) */
#define BPB_BkBootSec32 50		/* FAT32: Offset of backup boot sector (WORD) */
#define BS_DrvNum32 64		/* FAT32: Physical drive number for int13h (BYTE) */
#define BS_NTres32 65		/* FAT32: Error flag (BYTE) */
#define BS_BootSig32 66		/* FAT32: Extended boot signature (BYTE) */
#define BS_VolID32 67		/* FAT32: Volume serial number (DWORD) */
#define BS_VolLab32 71		/* FAT32: Volume label string (8-byte) */
#define BS_FilSysType32 82		/* FAT32: Filesystem type string (8-byte) */
#define BS_BootCode32 90		/* FAT32: Boot code (420-byte) */
#define BPB_ZeroedEx 11		/* exFAT: MBZ field (53-byte) */
#define BPB_VolOfsEx 64		/* exFAT: Volume offset from top of the drive [sector] (QWORD) */
#define BPB_TotSecEx 72		/* exFAT: Volume size [sector] (QWORD) */
#define BPB_FatOfsEx 80		/* exFAT: FAT offset from top of the volume [sector] (DWORD) */
#define BPB_FatSzEx 84		/* exFAT: FAT size [sector] (DWORD) */
#define BPB_DataOfsEx 88		/* exFAT: Data offset from top of the volume [sector] (DWORD) */
#define BPB_NumClusEx 92		/* exFAT: Number of clusters (DWORD) */
#define BPB_RootClusEx 96		/* exFAT: Root directory start cluster (DWORD) */
#define BPB_VolIDEx 100		/* exFAT: Volume serial number (DWORD) */
#define BPB_FSVerEx 104		/* exFAT: Filesystem version (WORD) */
#define BPB_VolFlagEx 106		/* exFAT: Volume flags (WORD) */
#define BPB_BytsPerSecEx 108		/* exFAT: Log2 of sector size in unit of byte (BYTE) */
#define BPB_SecPerClusEx 109		/* exFAT: Log2 of cluster size in unit of sector (BYTE) */
#define BPB_NumFATsEx 110		/* exFAT: Number of FATs (BYTE) */
#define BPB_DrvNumEx 111		/* exFAT: Physical drive number for int13h (BYTE) */
#define BPB_PercInUseEx 112		/* exFAT: Percent in use (BYTE) */
#define BPB_RsvdEx 113		/* exFAT: Reserved (7-byte) */
#define BS_BootCodeEx 120		/* exFAT: Boot code (390-byte) */
#define DIR_Name 0		/* Short file name (11-byte) */
#define DIR_Attr 11		/* Attribute (BYTE) */
#define DIR_NTres 12		/* Lower case flag (BYTE) */
#define DIR_CrtTime10 13		/* Created time sub-second (BYTE) */
#define DIR_CrtTime 14		/* Created time (DWORD) */
#define DIR_LstAccDate 18		/* Last accessed date (WORD) */
#define DIR_FstClusHI 20		/* Higher 16-bit of first cluster (WORD) */
#define DIR_ModTime 22		/* Modified time (DWORD) */
#define DIR_FstClusLO 26		/* Lower 16-bit of first cluster (WORD) */
#define DIR_FileSize 28		/* File size (DWORD) */
#define LDIR_Ord 0		/* LFN: LFN order and LLE flag (BYTE) */
#define LDIR_Attr 11		/* LFN: LFN attribute (BYTE) */
#define LDIR_Type 12		/* LFN: Entry type (BYTE) */
#define LDIR_Chksum 13		/* LFN: Checksum of the SFN (BYTE) */
#define LDIR_FstClusLO 26		/* LFN: MBZ field (WORD) */
#define XDIR_Type 0		/* exFAT: Type of exFAT directory entry (BYTE) */
#define XDIR_NumLabel 1		/* exFAT: Number of volume label characters (BYTE) */
#define XDIR_Label 2		/* exFAT: Volume label (11-WORD) */
#define XDIR_CaseSum 4		/* exFAT: Sum of case conversion table (DWORD) */
#define XDIR_NumSec 1		/* exFAT: Number of secondary entries (BYTE) */
#define XDIR_SetSum 2		/* exFAT: Sum of the set of directory entries (WORD) */
#define XDIR_Attr 4		/* exFAT: File attribute (WORD) */
#define XDIR_CrtTime 8		/* exFAT: Created time (DWORD) */
#define XDIR_ModTime 12		/* exFAT: Modified time (DWORD) */
#define XDIR_AccTime 16		/* exFAT: Last accessed time (DWORD) */
#define XDIR_CrtTime10 20		/* exFAT: Created time subsecond (BYTE) */
#define XDIR_ModTime10 21		/* exFAT: Modified time subsecond (BYTE) */
#define XDIR_CrtTZ 22		/* exFAT: Created timezone (BYTE) */
#define XDIR_ModTZ 23		/* exFAT: Modified timezone (BYTE) */
#define XDIR_AccTZ 24		/* exFAT: Last accessed timezone (BYTE) */
#define XDIR_GenFlags 33		/* exFAT: General secondary flags (BYTE) */
#define XDIR_NumName 35		/* exFAT: Number of file name characters (BYTE) */
#define XDIR_NameHash 36		/* exFAT: Hash of file name (WORD) */
#define XDIR_ValidFileSize 40		/* exFAT: Valid file size (QWORD) */
#define XDIR_FstClus 52		/* exFAT: First cluster of the file data (DWORD) */
#define XDIR_FileSize 56		/* exFAT: File/Directory size (QWORD) */
#define SZDIRE 32		/* Size of a directory entry */
#define DDEM 0xE5	/* Deleted directory entry mark set to DIR_Name[0] */
#define RDDEM 0x05	/* Replacement of the character collides with DDEM */
#define LLEF 0x40	/* Last long entry flag in LDIR_Ord */
#define FSI_LeadSig 0		/* FAT32 FSI: Leading signature (DWORD) */
#define FSI_StrucSig 484		/* FAT32 FSI: Structure signature (DWORD) */
#define FSI_Free_Count 488		/* FAT32 FSI: Number of free clusters (DWORD) */
#define FSI_Nxt_Free 492		/* FAT32 FSI: Last allocated cluster (DWORD) */
#define MBR_Table 446		/* MBR: Offset of partition table in the MBR */
#define SZ_PTE 16		/* MBR: Size of a partition table entry */
#define PTE_Boot 0		/* MBR PTE: Boot indicator */
#define PTE_StHead 1		/* MBR PTE: Start head */
#define PTE_StSec 2		/* MBR PTE: Start sector */
#define PTE_StCyl 3		/* MBR PTE: Start cylinder */
#define PTE_System 4		/* MBR PTE: System ID */
#define PTE_EdHead 5		/* MBR PTE: End head */
#define PTE_EdSec 6		/* MBR PTE: End sector */
#define PTE_EdCyl 7		/* MBR PTE: End cylinder */
#define PTE_StLba 8		/* MBR PTE: Start in LBA */
#define PTE_SizLba 12		/* MBR PTE: Size in LBA */
#define GPTH_Sign 0		/* GPT: Header signature (8-byte) */
#define GPTH_Rev 8		/* GPT: Revision (DWORD) */
#define GPTH_Size 12		/* GPT: Header size (DWORD) */
#define GPTH_Bcc 16		/* GPT: Header BCC (DWORD) */
#define GPTH_CurLba 24		/* GPT: Main header LBA (QWORD) */
#define GPTH_BakLba 32		/* GPT: Backup header LBA (QWORD) */
#define GPTH_FstLba 40		/* GPT: First LBA for partitions (QWORD) */
#define GPTH_LstLba 48		/* GPT: Last LBA for partitions (QWORD) */
#define GPTH_DskGuid 56		/* GPT: Disk GUID (16-byte) */
#define GPTH_PtOfs 72		/* GPT: Partation table LBA (QWORD) */
#define GPTH_PtNum 80		/* GPT: Number of table entries (DWORD) */
#define GPTH_PteSize 84		/* GPT: Size of table entry (DWORD) */
#define GPTH_PtBcc 88		/* GPT: Partation table BCC (DWORD) */
#define SZ_GPTE 128		/* GPT: Size of partition table entry */
#define GPTE_PtGuid 0		/* GPT PTE: Partition type GUID (16-byte) */
#define GPTE_UpGuid 16		/* GPT PTE: Partition unique GUID (16-byte) */
#define GPTE_FstLba 32		/* GPT PTE: First LBA (QWORD) */
#define GPTE_LstLba 40		/* GPT PTE: Last LBA inclusive (QWORD) */
#define GPTE_Flags 48		/* GPT PTE: Flags (QWORD) */
#define GPTE_Name 56		/* GPT PTE: Name */
#define ABORT(fs, res) { fp->err = (BYTE)(res); LEAVE_FF(fs, res); }
#define LEAVE_FF(fs, res) return res
#define LD2PD(vol) (BYTE)(vol)	/* Each logical drive is associated with the same physical drive number */
#define LD2PT(vol) 0			/* Find first valid partition or in SFD */
#define SS(fs) ((UINT)FF_MAX_SS)	/* Fixed sector size */
#define GET_FATTIME() get_fattime()
#define TBL_CT437
#define TBL_CT720
#define TBL_CT737
#define TBL_CT771
#define TBL_CT775
#define TBL_CT850
#define TBL_CT852
#define TBL_CT855
#define TBL_CT857
#define TBL_CT860
#define TBL_CT861
#define TBL_CT862
#define TBL_CT863
#define TBL_CT864
#define TBL_CT865
#define TBL_CT866
#define TBL_CT869
#define TBL_DC932 {0x81, 0x9F, 0xE0, 0xFC, 0x40, 0x7E, 0x80, 0xFC, 0x00, 0x00}
#define TBL_DC936 {0x81, 0xFE, 0x00, 0x00, 0x40, 0x7E, 0x80, 0xFE, 0x00, 0x00}
#define TBL_DC949 {0x81, 0xFE, 0x00, 0x00, 0x41, 0x5A, 0x61, 0x7A, 0x81, 0xFE}
#define TBL_DC950 {0x81, 0xFE, 0x00, 0x00, 0x40, 0x7E, 0xA1, 0xFE, 0x00, 0x00}
#define MERGE_2STR(a, b) a ## b
#define MKCVTBL(hd, cp) MERGE_2STR(hd, cp)
#define MAXDIRB(nc) ((nc + 44U) / 15 * SZDIRE)	/* exFAT: Size of directory entry block scratchpad buffer needed for the name length */
#define DEF_NAMBUF WCHAR *lfn;	/* Pointer to LFN working buffer */
#define INIT_NAMBUF(fs) { lfn = ff_memalloc((FF_MAX_LFN+1)*2); if (!lfn) LEAVE_FF(fs, FR_NOT_ENOUGH_CORE); (fs)->lfnbuf = lfn; }
#define FREE_NAMBUF() ff_memfree(lfn)
#define LEAVE_MKFS(res) { if (!work) ff_memfree(buf); return res; }
#define MAX_MALLOC 0x8000	/* Must be >=FF_MAX_SS */
#define CODEPAGE FF_CODE_PAGE
#define DIR_READ_FILE(dp) dir_read(dp, 0)
#define DIR_READ_LABEL(dp) dir_read(dp, 1)
#define N_SEC_TRACK 63			/* Sectors per track for determination of drive CHS */
#define GPT_ALIGN 0x100000	/* Alignment of partitions in GPT [byte] (>=128KB) */
#define GPT_ITEMS 128			/* Number of GPT table size (>=128, sector aligned) */
Functions
static WORD ld_word (const BYTE *ptr)
static DWORD ld_dword (const BYTE *ptr)
static void st_word (BYTE *ptr, WORD val)
static void st_dword (BYTE *ptr, DWORD val)
static void mem_cpy (void *dst, const void *src, UINT cnt)
static void mem_set (void *dst, int val, UINT cnt)
static int mem_cmp (const void *dst, const void *src, UINT cnt)
static int chk_chr (const char *str, int chr)
static int dbc_1st (BYTE c)
static int dbc_2nd (BYTE c)
static DWORD tchar2uni (const TCHAR **str)
static BYTE put_utf (DWORD chr, TCHAR *buf, UINT szb)
static FRESULT sync_window (FATFS *fs)
static FRESULT move_window (FATFS *fs, LBA_t sect)
static FRESULT sync_fs (FATFS *fs)
static LBA_t clst2sect (FATFS *fs, DWORD clst)
static DWORD get_fat (FFOBJID *obj, DWORD clst)
static FRESULT put_fat (FATFS *fs, DWORD clst, DWORD val)
static FRESULT remove_chain (FFOBJID *obj, DWORD clst, DWORD pclst)
static DWORD create_chain (FFOBJID *obj, DWORD clst)
static DWORD clmt_clust (FIL *fp, FSIZE_t ofs)
static FRESULT dir_clear (FATFS *fs, DWORD clst)
static FRESULT dir_sdi (DIR *dp, DWORD ofs)
static FRESULT dir_next (DIR *dp, int stretch)
static FRESULT dir_alloc (DIR *dp, UINT nent)
static DWORD ld_clust (FATFS *fs, const BYTE *dir)
static void st_clust (FATFS *fs, BYTE *dir, DWORD cl)
static int cmp_lfn (const WCHAR *lfnbuf, BYTE *dir)
static int pick_lfn (WCHAR *lfnbuf, BYTE *dir)
static void put_lfn (const WCHAR *lfn, BYTE *dir, BYTE ord, BYTE sum)
static void gen_numname (BYTE *dst, const BYTE *src, const WCHAR *lfn, UINT seq)
static BYTE sum_sfn (const BYTE *dir)
static FRESULT dir_read (DIR *dp, int vol)
static FRESULT dir_find (DIR *dp)
static FRESULT dir_register (DIR *dp)
static FRESULT dir_remove (DIR *dp)
static void get_fileinfo (DIR *dp, FILINFO *fno)
static DWORD get_achar (const TCHAR **ptr)
static int pattern_matching (const TCHAR *pat, const TCHAR *nam, int skip, int inf)
static FRESULT create_name (DIR *dp, const TCHAR **path)
static FRESULT follow_path (DIR *dp, const TCHAR *path)
static int get_ldnumber (const TCHAR **path)
static UINT check_fs (FATFS *fs, LBA_t sect)
static UINT find_volume (FATFS *fs, UINT part)
static FRESULT mount_volume (const TCHAR **path, FATFS **rfs, BYTE mode)
static FRESULT validate (FFOBJID *obj, FATFS **rfs)
FRESULT f_mount (FATFS *fs, const TCHAR *path, BYTE opt)
FRESULT f_open (FIL *fp, const TCHAR *path, BYTE mode)
FRESULT f_read (FIL *fp, void *buff, UINT btr, UINT *br)
FRESULT f_write (FIL *fp, const void *buff, UINT btw, UINT *bw)
FRESULT f_sync (FIL *fp)
FRESULT f_close (FIL *fp)
FRESULT f_chdrive (const TCHAR *path)
FRESULT f_chdir (const TCHAR *path)
FRESULT f_getcwd (TCHAR *buff, UINT len)
FRESULT f_lseek (FIL *fp, FSIZE_t ofs)
FRESULT f_opendir (DIR *dp, const TCHAR *path)
FRESULT f_closedir (DIR *dp)
FRESULT f_readdir (DIR *dp, FILINFO *fno)
FRESULT f_findnext (DIR *dp, FILINFO *fno)
FRESULT f_findfirst (DIR *dp, FILINFO *fno, const TCHAR *path, const TCHAR *pattern)
FRESULT f_stat (const TCHAR *path, FILINFO *fno)
FRESULT f_getfree (const TCHAR *path, DWORD *nclst, FATFS **fatfs)
FRESULT f_truncate (FIL *fp)
FRESULT f_unlink (const TCHAR *path)
FRESULT f_mkdir (const TCHAR *path)
FRESULT f_rename (const TCHAR *path_old, const TCHAR *path_new)
FRESULT f_chmod (const TCHAR *path, BYTE attr, BYTE mask)
FRESULT f_utime (const TCHAR *path, const FILINFO *fno)
FRESULT f_getlabel (const TCHAR *path, TCHAR *label, DWORD *vsn)
FRESULT f_setlabel (const TCHAR *label)
FRESULT f_expand (FIL *fp, FSIZE_t fsz, BYTE opt)
static FRESULT create_partition (BYTE drv, const LBA_t plst[], UINT sys, BYTE *buf)
FRESULT f_mkfs (const TCHAR *path, const MKFS_PARM *opt, void *work, UINT len)
Variables
static FATFS * FatFs [FF_VOLUMES]
static WORD Fsid
static BYTE CurrVol
static const BYTE LfnOfs [] = {1,3,5,7,9,14,16,18,20,22,24,28,30}
static const BYTE ExCvt [] = MKCVTBL(TBL_CT, FF_CODE_PAGE)
Macro Definition Documentation
ABORT
#define ABORT(fs, res) { fp->err = (BYTE)(res); LEAVE_FF(fs, res); }
Definition at line 235 of file ff.c.
Referenced by f_expand(), f_lseek(), f_read(), f_truncate(), and f_write().
AM_LFN
#define AM_LFN 0x0F	/* LFN entry */
Definition at line 68 of file ff.c.
Referenced by dir_find(), dir_read(), and put_lfn().
AM_MASK
#define AM_MASK 0x3F	/* Mask of defined bits */
Definition at line 69 of file ff.c.
Referenced by dir_find(), and dir_read().
AM_VOL
#define AM_VOL 0x08	/* Volume label */
Definition at line 67 of file ff.c.
Referenced by dir_find(), dir_read(), and f_setlabel().
BPB_BkBootSec32
#define BPB_BkBootSec32 50		/* FAT32: Offset of backup boot sector (WORD) */
Definition at line 124 of file ff.c.
Referenced by f_mkfs().
BPB_BytsPerSec
#define BPB_BytsPerSec 11		/* Sector size [byte] (WORD) */
Definition at line 98 of file ff.c.
Referenced by f_mkfs(), and mount_volume().
BPB_BytsPerSecEx
#define BPB_BytsPerSecEx 108		/* exFAT: Log2 of sector size in unit of byte (BYTE) */
Definition at line 144 of file ff.c.
Referenced by f_mkfs(), and mount_volume().
BPB_DataOfsEx
#define BPB_DataOfsEx 88		/* exFAT: Data offset from top of the volume [sector] (DWORD) */
Definition at line 138 of file ff.c.
Referenced by f_mkfs(), and mount_volume().
BPB_DrvNumEx
#define BPB_DrvNumEx 111		/* exFAT: Physical drive number for int13h (BYTE) */
Definition at line 147 of file ff.c.
Referenced by f_mkfs().
BPB_ExtFlags32
#define BPB_ExtFlags32 40		/* FAT32: Extended flags (WORD) */
Definition at line 120 of file ff.c.
BPB_FatOfsEx
#define BPB_FatOfsEx 80		/* exFAT: FAT offset from top of the volume [sector] (DWORD) */
Definition at line 136 of file ff.c.
Referenced by f_mkfs(), and mount_volume().
BPB_FATSz16
#define BPB_FATSz16 22		/* FAT size (16-bit) [sector] (WORD) */
Definition at line 105 of file ff.c.
Referenced by f_mkfs(), and mount_volume().
BPB_FATSz32
#define BPB_FATSz32 36		/* FAT32: FAT size [sector] (DWORD) */
Definition at line 119 of file ff.c.
Referenced by f_mkfs(), and mount_volume().
BPB_FatSzEx
#define BPB_FatSzEx 84		/* exFAT: FAT size [sector] (DWORD) */
Definition at line 137 of file ff.c.
Referenced by f_mkfs(), and mount_volume().
BPB_FSInfo32
#define BPB_FSInfo32 48		/* FAT32: Offset of FSINFO sector (WORD) */
Definition at line 123 of file ff.c.
Referenced by f_mkfs(), and mount_volume().
BPB_FSVer32
#define BPB_FSVer32 42		/* FAT32: Filesystem version (WORD) */
Definition at line 121 of file ff.c.
Referenced by mount_volume().
BPB_FSVerEx
#define BPB_FSVerEx 104		/* exFAT: Filesystem version (WORD) */
Definition at line 142 of file ff.c.
Referenced by f_mkfs(), and mount_volume().
BPB_HiddSec
#define BPB_HiddSec 28		/* Volume offset from top of the drive (DWORD) */
Definition at line 108 of file ff.c.
Referenced by f_mkfs().
BPB_Media
#define BPB_Media 21		/* Media descriptor byte (BYTE) */
Definition at line 104 of file ff.c.
Referenced by f_mkfs().
BPB_NumClusEx
#define BPB_NumClusEx 92		/* exFAT: Number of clusters (DWORD) */
Definition at line 139 of file ff.c.
Referenced by f_mkfs(), and mount_volume().
BPB_NumFATs
#define BPB_NumFATs 16		/* Number of FATs (BYTE) */
Definition at line 101 of file ff.c.
Referenced by f_mkfs(), and mount_volume().
BPB_NumFATsEx
#define BPB_NumFATsEx 110		/* exFAT: Number of FATs (BYTE) */
Definition at line 146 of file ff.c.
Referenced by f_mkfs(), and mount_volume().
BPB_NumHeads
#define BPB_NumHeads 26		/* Number of heads for int13h (WORD) */
Definition at line 107 of file ff.c.
Referenced by f_mkfs().
BPB_PercInUseEx
#define BPB_PercInUseEx 112		/* exFAT: Percent in use (BYTE) */
Definition at line 148 of file ff.c.
Referenced by f_mkfs().
BPB_RootClus32
#define BPB_RootClus32 44		/* FAT32: Root directory cluster (DWORD) */
Definition at line 122 of file ff.c.
Referenced by f_mkfs(), and mount_volume().
BPB_RootClusEx
#define BPB_RootClusEx 96		/* exFAT: Root directory start cluster (DWORD) */
Definition at line 140 of file ff.c.
Referenced by f_mkfs(), and mount_volume().
BPB_RootEntCnt
#define BPB_RootEntCnt 17		/* Size of root directory area for FAT [entry] (WORD) */
Definition at line 102 of file ff.c.
Referenced by f_mkfs(), and mount_volume().
BPB_RsvdEx
#define BPB_RsvdEx 113		/* exFAT: Reserved (7-byte) */
Definition at line 149 of file ff.c.
BPB_RsvdSecCnt
#define BPB_RsvdSecCnt 14		/* Size of reserved area [sector] (WORD) */
Definition at line 100 of file ff.c.
Referenced by f_mkfs(), and mount_volume().
BPB_SecPerClus
#define BPB_SecPerClus 13		/* Cluster size [sector] (BYTE) */
Definition at line 99 of file ff.c.
Referenced by f_mkfs(), and mount_volume().
BPB_SecPerClusEx
#define BPB_SecPerClusEx 109		/* exFAT: Log2 of cluster size in unit of sector (BYTE) */
Definition at line 145 of file ff.c.
Referenced by f_mkfs(), and mount_volume().
BPB_SecPerTrk
#define BPB_SecPerTrk 24		/* Number of sectors per track for int13h [sector] (WORD) */
Definition at line 106 of file ff.c.
Referenced by f_mkfs().
BPB_TotSec16
#define BPB_TotSec16 19		/* Volume size (16-bit) [sector] (WORD) */
Definition at line 103 of file ff.c.
Referenced by f_mkfs(), and mount_volume().
BPB_TotSec32
#define BPB_TotSec32 32		/* Volume size (32-bit) [sector] (DWORD) */
Definition at line 109 of file ff.c.
Referenced by f_mkfs(), and mount_volume().
BPB_TotSecEx
#define BPB_TotSecEx 72		/* exFAT: Volume size [sector] (QWORD) */
Definition at line 135 of file ff.c.
Referenced by f_mkfs(), and mount_volume().
BPB_VolFlagEx
#define BPB_VolFlagEx 106		/* exFAT: Volume flags (WORD) */
Definition at line 143 of file ff.c.
Referenced by f_mkfs().
BPB_VolIDEx
#define BPB_VolIDEx 100		/* exFAT: Volume serial number (DWORD) */
Definition at line 141 of file ff.c.
Referenced by f_getlabel(), and f_mkfs().
BPB_VolOfsEx
#define BPB_VolOfsEx 64		/* exFAT: Volume offset from top of the drive [sector] (QWORD) */
Definition at line 134 of file ff.c.
Referenced by f_mkfs().
BPB_ZeroedEx
#define BPB_ZeroedEx 11		/* exFAT: MBZ field (53-byte) */
Definition at line 133 of file ff.c.
Referenced by mount_volume().
BS_55AA
#define BS_55AA 510		/* Signature word (WORD) */
Definition at line 117 of file ff.c.
Referenced by check_fs(), create_partition(), f_mkfs(), mount_volume(), and sync_fs().
BS_BootCode
#define BS_BootCode 62		/* Boot code (448-byte) */
Definition at line 116 of file ff.c.
BS_BootCode32
#define BS_BootCode32 90		/* FAT32: Boot code (420-byte) */
Definition at line 131 of file ff.c.
BS_BootCodeEx
#define BS_BootCodeEx 120		/* exFAT: Boot code (390-byte) */
Definition at line 150 of file ff.c.
Referenced by f_mkfs().
BS_BootSig
#define BS_BootSig 38		/* Extended boot signature (BYTE) */
Definition at line 112 of file ff.c.
Referenced by f_mkfs().
BS_BootSig32
#define BS_BootSig32 66		/* FAT32: Extended boot signature (BYTE) */
Definition at line 127 of file ff.c.
Referenced by f_mkfs().
BS_DrvNum
#define BS_DrvNum 36		/* Physical drive number for int13h (BYTE) */
Definition at line 110 of file ff.c.
Referenced by f_mkfs().
BS_DrvNum32
#define BS_DrvNum32 64		/* FAT32: Physical drive number for int13h (BYTE) */
Definition at line 125 of file ff.c.
Referenced by f_mkfs().
BS_FilSysType
#define BS_FilSysType 54		/* Filesystem type string (8-byte) */
Definition at line 115 of file ff.c.
Referenced by check_fs().
BS_FilSysType32
#define BS_FilSysType32 82		/* FAT32: Filesystem type string (8-byte) */
Definition at line 130 of file ff.c.
Referenced by check_fs().
BS_JmpBoot
#define BS_JmpBoot 0		/* x86 jump instruction (3-byte) */
Definition at line 96 of file ff.c.
Referenced by check_fs(), and f_mkfs().
BS_NTres
#define BS_NTres 37		/* WindowsNT error flag (BYTE) */
Definition at line 111 of file ff.c.
BS_NTres32
#define BS_NTres32 65		/* FAT32: Error flag (BYTE) */
Definition at line 126 of file ff.c.
BS_OEMName
#define BS_OEMName 3		/* OEM name (8-byte) */
Definition at line 97 of file ff.c.
BS_VolID
#define BS_VolID 39		/* Volume serial number (DWORD) */
Definition at line 113 of file ff.c.
Referenced by f_getlabel(), and f_mkfs().
BS_VolID32
#define BS_VolID32 67		/* FAT32: Volume serial number (DWORD) */
Definition at line 128 of file ff.c.
Referenced by f_getlabel(), and f_mkfs().
BS_VolLab
#define BS_VolLab 43		/* Volume label string (8-byte) */
Definition at line 114 of file ff.c.
Referenced by f_mkfs().
BS_VolLab32
#define BS_VolLab32 71		/* FAT32: Volume label string (8-byte) */
Definition at line 129 of file ff.c.
Referenced by f_mkfs().
CODEPAGE
#define CODEPAGE FF_CODE_PAGE
Definition at line 592 of file ff.c.
Referenced by create_name(), f_getlabel(), f_mkfs(), f_setlabel(), get_fileinfo(), put_utf(), and tchar2uni().
DDEM
#define DDEM 0xE5	/* Deleted directory entry mark set to DIR_Name[0] */
Definition at line 190 of file ff.c.
Referenced by create_name(), dir_alloc(), dir_find(), dir_read(), dir_remove(), f_setlabel(), and get_fileinfo().
DEF_NAMBUF
#define DEF_NAMBUF WCHAR *lfn;	/* Pointer to LFN working buffer */
Definition at line 545 of file ff.c.
Referenced by f_chdir(), f_chmod(), f_getcwd(), f_mkdir(), f_open(), f_opendir(), f_readdir(), f_rename(), f_stat(), f_sync(), f_unlink(), and f_utime().
DIR_Attr
#define DIR_Attr 11		/* Attribute (BYTE) */
Definition at line 153 of file ff.c.
Referenced by dir_find(), dir_read(), f_chmod(), f_mkdir(), f_open(), f_rename(), f_setlabel(), f_sync(), and get_fileinfo().
DIR_CrtTime
#define DIR_CrtTime 14		/* Created time (DWORD) */
Definition at line 156 of file ff.c.
Referenced by f_open().
DIR_CrtTime10
#define DIR_CrtTime10 13		/* Created time sub-second (BYTE) */
Definition at line 155 of file ff.c.
DIR_FileSize
#define DIR_FileSize 28		/* File size (DWORD) */
Definition at line 161 of file ff.c.
Referenced by f_open(), f_sync(), and get_fileinfo().
DIR_FstClusHI
#define DIR_FstClusHI 20		/* Higher 16-bit of first cluster (WORD) */
Definition at line 158 of file ff.c.
Referenced by ld_clust(), and st_clust().
DIR_FstClusLO
#define DIR_FstClusLO 26		/* Lower 16-bit of first cluster (WORD) */
Definition at line 160 of file ff.c.
Referenced by ld_clust(), and st_clust().
DIR_LstAccDate
#define DIR_LstAccDate 18		/* Last accessed date (WORD) */
Definition at line 157 of file ff.c.
Referenced by f_sync().
DIR_ModTime
#define DIR_ModTime 22		/* Modified time (DWORD) */
Definition at line 159 of file ff.c.
Referenced by f_mkdir(), f_sync(), f_utime(), and get_fileinfo().
DIR_Name
#define DIR_Name 0		/* Short file name (11-byte) */
Definition at line 152 of file ff.c.
Referenced by dir_alloc(), dir_find(), dir_read(), dir_register(), dir_remove(), f_mkdir(), and f_setlabel().
DIR_NTres
#define DIR_NTres 12		/* Lower case flag (BYTE) */
Definition at line 154 of file ff.c.
Referenced by dir_register(), and get_fileinfo().
DIR_READ_FILE
#define DIR_READ_FILE(dp) dir_read(dp, 0)
Definition at line 2366 of file ff.c.
Referenced by dir_find(), f_getcwd(), f_readdir(), and f_unlink().
DIR_READ_LABEL
#define DIR_READ_LABEL(dp) dir_read(dp, 1)
Definition at line 2367 of file ff.c.
Referenced by f_getlabel(), and f_setlabel().
ET_BITMAP
#define ET_BITMAP 0x81	/* Allocation bitmap */
Definition at line 85 of file ff.c.
Referenced by f_mkfs(), and mount_volume().
ET_FILEDIR
#define ET_FILEDIR 0x85	/* File and directory */
Definition at line 88 of file ff.c.
Referenced by dir_read(), and sum_sfn().
ET_FILENAME
#define ET_FILENAME 0xC1	/* Name extension */
Definition at line 90 of file ff.c.
Referenced by sum_sfn().
ET_STREAM
#define ET_STREAM 0xC0	/* Stream extension */
Definition at line 89 of file ff.c.
Referenced by sum_sfn().
ET_UPCASE
#define ET_UPCASE 0x82	/* Up-case table */
Definition at line 86 of file ff.c.
Referenced by f_mkfs().
ET_VLABEL
#define ET_VLABEL 0x83	/* Volume label */
Definition at line 87 of file ff.c.
Referenced by dir_read(), f_mkfs(), and f_setlabel().
FA_DIRTY
#define FA_DIRTY 0x80	/* FIL.buf[] needs to be written-back */
Definition at line 63 of file ff.c.
Referenced by f_expand(), f_lseek(), f_read(), f_sync(), f_truncate(), and f_write().
FA_MODIFIED
#define FA_MODIFIED 0x40	/* File has been modified */
Definition at line 62 of file ff.c.
Referenced by f_expand(), f_lseek(), f_open(), f_sync(), f_truncate(), and f_write().
FA_SEEKEND
#define FA_SEEKEND 0x20	/* Seek to end of the file on file open */
Definition at line 61 of file ff.c.
Referenced by f_open().
FREE_NAMBUF
#define FREE_NAMBUF() ff_memfree(lfn)
Definition at line 547 of file ff.c.
Referenced by f_chdir(), f_chmod(), f_getcwd(), f_mkdir(), f_open(), f_opendir(), f_readdir(), f_rename(), f_stat(), f_sync(), f_unlink(), and f_utime().
FSI_Free_Count
#define FSI_Free_Count 488		/* FAT32 FSI: Number of free clusters (DWORD) */
Definition at line 196 of file ff.c.
Referenced by f_mkfs(), mount_volume(), and sync_fs().
FSI_LeadSig
#define FSI_LeadSig 0		/* FAT32 FSI: Leading signature (DWORD) */
Definition at line 194 of file ff.c.
Referenced by f_mkfs(), mount_volume(), and sync_fs().
FSI_Nxt_Free
#define FSI_Nxt_Free 492		/* FAT32 FSI: Last allocated cluster (DWORD) */
Definition at line 197 of file ff.c.
Referenced by f_mkfs(), mount_volume(), and sync_fs().
FSI_StrucSig
#define FSI_StrucSig 484		/* FAT32 FSI: Structure signature (DWORD) */
Definition at line 195 of file ff.c.
Referenced by f_mkfs(), mount_volume(), and sync_fs().
GET_FATTIME
#define GET_FATTIME() get_fattime()
Definition at line 277 of file ff.c.
Referenced by create_partition(), f_mkdir(), f_mkfs(), f_open(), and f_sync().
GPT_ALIGN
#define GPT_ALIGN 0x100000	/* Alignment of partitions in GPT [byte] (>=128KB) */
Definition at line 5689 of file ff.c.
Referenced by create_partition(), and f_mkfs().
GPT_ITEMS
#define GPT_ITEMS 128			/* Number of GPT table size (>=128, sector aligned) */
Definition at line 5690 of file ff.c.
Referenced by create_partition(), and f_mkfs().
GPTE_Flags
#define GPTE_Flags 48		/* GPT PTE: Flags (QWORD) */
Definition at line 230 of file ff.c.
GPTE_FstLba
#define GPTE_FstLba 32		/* GPT PTE: First LBA (QWORD) */
Definition at line 228 of file ff.c.
Referenced by create_partition(), f_mkfs(), and find_volume().
GPTE_LstLba
#define GPTE_LstLba 40		/* GPT PTE: Last LBA inclusive (QWORD) */
Definition at line 229 of file ff.c.
Referenced by create_partition(), and f_mkfs().
GPTE_Name
#define GPTE_Name 56		/* GPT PTE: Name */
Definition at line 231 of file ff.c.
GPTE_PtGuid
#define GPTE_PtGuid 0		/* GPT PTE: Partition type GUID (16-byte) */
Definition at line 226 of file ff.c.
Referenced by create_partition(), f_mkfs(), and find_volume().
GPTE_UpGuid
#define GPTE_UpGuid 16		/* GPT PTE: Partition unique GUID (16-byte) */
Definition at line 227 of file ff.c.
Referenced by create_partition().
GPTH_BakLba
#define GPTH_BakLba 32		/* GPT: Backup header LBA (QWORD) */
Definition at line 217 of file ff.c.
Referenced by create_partition().
GPTH_Bcc
#define GPTH_Bcc 16		/* GPT: Header BCC (DWORD) */
Definition at line 215 of file ff.c.
Referenced by create_partition(), and get_ldnumber().
GPTH_CurLba
#define GPTH_CurLba 24		/* GPT: Main header LBA (QWORD) */
Definition at line 216 of file ff.c.
Referenced by create_partition().
GPTH_DskGuid
#define GPTH_DskGuid 56		/* GPT: Disk GUID (16-byte) */
Definition at line 220 of file ff.c.
Referenced by create_partition().
GPTH_FstLba
#define GPTH_FstLba 40		/* GPT: First LBA for partitions (QWORD) */
Definition at line 218 of file ff.c.
Referenced by create_partition().
GPTH_LstLba
#define GPTH_LstLba 48		/* GPT: Last LBA for partitions (QWORD) */
Definition at line 219 of file ff.c.
Referenced by create_partition().
GPTH_PtBcc
#define GPTH_PtBcc 88		/* GPT: Partation table BCC (DWORD) */
Definition at line 224 of file ff.c.
Referenced by create_partition().
GPTH_PteSize
#define GPTH_PteSize 84		/* GPT: Size of table entry (DWORD) */
Definition at line 223 of file ff.c.
Referenced by create_partition(), and get_ldnumber().
GPTH_PtNum
#define GPTH_PtNum 80		/* GPT: Number of table entries (DWORD) */
Definition at line 222 of file ff.c.
Referenced by create_partition(), f_mkfs(), find_volume(), and get_ldnumber().
GPTH_PtOfs
#define GPTH_PtOfs 72		/* GPT: Partation table LBA (QWORD) */
Definition at line 221 of file ff.c.
Referenced by create_partition(), f_mkfs(), and find_volume().
GPTH_Rev
#define GPTH_Rev 8		/* GPT: Revision (DWORD) */
Definition at line 213 of file ff.c.
GPTH_Sign
#define GPTH_Sign 0		/* GPT: Header signature (8-byte) */
Definition at line 212 of file ff.c.
Referenced by create_partition(), and get_ldnumber().
GPTH_Size
#define GPTH_Size 12		/* GPT: Header size (DWORD) */
Definition at line 214 of file ff.c.
INIT_NAMBUF
#define INIT_NAMBUF(fs) { lfn = ff_memalloc((FF_MAX_LFN+1)*2); if (!lfn) LEAVE_FF(fs, FR_NOT_ENOUGH_CORE); (fs)->lfnbuf = lfn; }
Definition at line 546 of file ff.c.
Referenced by f_chdir(), f_chmod(), f_getcwd(), f_mkdir(), f_open(), f_opendir(), f_readdir(), f_rename(), f_stat(), f_sync(), f_unlink(), and f_utime().
IsDigit
#define IsDigit(c) ((c) >= '0' && (c) <= '9')
Definition at line 54 of file ff.c.
Referenced by f_mkfs(), and get_ldnumber().
IsLower
#define IsLower(c) ((c) >= 'a' && (c) <= 'z')
Definition at line 53 of file ff.c.
Referenced by create_name(), f_mkfs(), f_setlabel(), get_achar(), and get_ldnumber().
IsSurrogate
#define IsSurrogate(c) ((c) >= 0xD800 && (c) <= 0xDFFF)
Definition at line 55 of file ff.c.
Referenced by f_getlabel(), f_mkfs(), get_fileinfo(), put_utf(), sum_sfn(), and tchar2uni().
IsSurrogateH
#define IsSurrogateH(c) ((c) >= 0xD800 && (c) <= 0xDBFF)
Definition at line 56 of file ff.c.
Referenced by f_mkfs(), put_utf(), and tchar2uni().
IsSurrogateL
#define IsSurrogateL(c) ((c) >= 0xDC00 && (c) <= 0xDFFF)
Definition at line 57 of file ff.c.
Referenced by f_mkfs(), put_utf(), and tchar2uni().
IsUpper
#define IsUpper(c) ((c) >= 'A' && (c) <= 'Z')
Definition at line 52 of file ff.c.
Referenced by create_name(), and get_fileinfo().
LD2PD
#define LD2PD(vol) (BYTE)(vol)	/* Each logical drive is associated with the same physical drive number */
Definition at line 254 of file ff.c.
Referenced by f_mkfs(), and mount_volume().
LD2PT
#define LD2PT(vol) 0			/* Find first valid partition or in SFD */
Definition at line 255 of file ff.c.
Referenced by f_mkfs(), and mount_volume().
LDIR_Attr
#define LDIR_Attr 11		/* LFN: LFN attribute (BYTE) */
Definition at line 163 of file ff.c.
Referenced by put_lfn().
LDIR_Chksum
#define LDIR_Chksum 13		/* LFN: Checksum of the SFN (BYTE) */
Definition at line 165 of file ff.c.
Referenced by dir_find(), dir_read(), and put_lfn().
LDIR_FstClusLO
#define LDIR_FstClusLO 26		/* LFN: MBZ field (WORD) */
Definition at line 166 of file ff.c.
Referenced by cmp_lfn(), pick_lfn(), and put_lfn().
LDIR_Ord
#define LDIR_Ord 0		/* LFN: LFN order and LLE flag (BYTE) */
Definition at line 162 of file ff.c.
Referenced by cmp_lfn(), pick_lfn(), and put_lfn().
LDIR_Type
#define LDIR_Type 12		/* LFN: Entry type (BYTE) */
Definition at line 164 of file ff.c.
Referenced by put_lfn().
LEAVE_FF
#define LEAVE_FF(fs, res) return res
Definition at line 245 of file ff.c.
Referenced by f_chdir(), f_chmod(), f_expand(), f_getcwd(), f_getfree(), f_getlabel(), f_lseek(), f_mkdir(), f_mount(), f_open(), f_opendir(), f_read(), f_readdir(), f_rename(), f_setlabel(), f_stat(), f_sync(), f_truncate(), f_unlink(), f_utime(), and f_write().
LEAVE_MKFS
#define LEAVE_MKFS(res) { if (!work) ff_memfree(buf); return res; }
Definition at line 549 of file ff.c.
Referenced by f_mkfs().
LLEF
#define LLEF 0x40	/* Last long entry flag in LDIR_Ord */
Definition at line 192 of file ff.c.
Referenced by cmp_lfn(), dir_find(), dir_read(), pick_lfn(), and put_lfn().
MAX_DIR
#define MAX_DIR 0x200000		/* Max size of FAT directory */
Definition at line 43 of file ff.c.
Referenced by dir_next(), and dir_sdi().
MAX_DIR_EX
#define MAX_DIR_EX 0x10000000		/* Max size of exFAT directory */
Definition at line 44 of file ff.c.
Referenced by dir_next(), and dir_sdi().
MAX_EXFAT
#define MAX_EXFAT 0x7FFFFFFD		/* Max exFAT clusters (differs from specs, implementation limit) */
Definition at line 48 of file ff.c.
Referenced by f_mkfs(), and mount_volume().
MAX_FAT12
#define MAX_FAT12 0xFF5			/* Max FAT12 clusters (differs from specs, but right for real DOS/Windows behavior) */
Definition at line 45 of file ff.c.
Referenced by f_mkfs(), and mount_volume().
MAX_FAT16
#define MAX_FAT16 0xFFF5			/* Max FAT16 clusters (differs from specs, but right for real DOS/Windows behavior) */
Definition at line 46 of file ff.c.
Referenced by f_mkfs(), and mount_volume().
MAX_FAT32
#define MAX_FAT32 0x0FFFFFF5		/* Max FAT32 clusters (not specified, practical limit) */
Definition at line 47 of file ff.c.
Referenced by f_mkfs(), and mount_volume().
MAX_MALLOC
#define MAX_MALLOC 0x8000	/* Must be >=FF_MAX_SS */
Definition at line 550 of file ff.c.
Referenced by dir_clear().
MAXDIRB
#define MAXDIRB(nc) ((nc + 44U) / 15 * SZDIRE)	/* exFAT: Size of directory entry block scratchpad buffer needed for the name length */
Definition at line 515 of file ff.c.
Referenced by sum_sfn().
MBR_Table
#define MBR_Table 446		/* MBR: Offset of partition table in the MBR */
Definition at line 199 of file ff.c.
Referenced by create_partition(), f_mkfs(), and find_volume().
MERGE_2STR
#define MERGE_2STR(a, b) a ## b
Definition at line 443 of file ff.c.
MKCVTBL
#define MKCVTBL(hd, cp) MERGE_2STR(hd, cp)
Definition at line 444 of file ff.c.
N_SEC_TRACK
#define N_SEC_TRACK 63			/* Sectors per track for determination of drive CHS */
Definition at line 5688 of file ff.c.
Referenced by create_partition(), and f_mkfs().
NS_BODY
#define NS_BODY 0x08	/* Lower case flag (body) */
Definition at line 77 of file ff.c.
Referenced by create_name(), dir_register(), and get_fileinfo().
NS_DOT
#define NS_DOT 0x20	/* Dot entry */
Definition at line 79 of file ff.c.
Referenced by create_name(), dir_register(), f_chmod(), f_mkdir(), f_rename(), f_unlink(), f_utime(), and follow_path().
NS_EXT
#define NS_EXT 0x10	/* Lower case flag (ext) */
Definition at line 78 of file ff.c.
Referenced by create_name(), dir_register(), and get_fileinfo().
NS_LAST
#define NS_LAST 0x04	/* Last segment */
Definition at line 76 of file ff.c.
Referenced by create_name(), and follow_path().
NS_LFN
#define NS_LFN 0x02	/* Force to create LFN entry */
Definition at line 75 of file ff.c.
Referenced by create_name(), and dir_register().
NS_LOSS
#define NS_LOSS 0x01	/* Out of 8.3 format */
Definition at line 74 of file ff.c.
Referenced by create_name(), dir_find(), and dir_register().
NS_NOLFN
#define NS_NOLFN 0x40	/* Do not find LFN */
Definition at line 80 of file ff.c.
Referenced by dir_find(), and dir_register().
NS_NONAME
#define NS_NONAME 0x80	/* Not followed */
Definition at line 81 of file ff.c.
Referenced by dir_register(), f_chdir(), f_chmod(), f_open(), f_opendir(), f_rename(), f_stat(), f_unlink(), f_utime(), and follow_path().
NSFLAG
#define NSFLAG 11		/* Index of the name status byte */
Definition at line 73 of file ff.c.
Referenced by create_name(), dir_find(), dir_register(), f_chdir(), f_chmod(), f_mkdir(), f_open(), f_opendir(), f_rename(), f_stat(), f_unlink(), f_utime(), and follow_path().
PTE_Boot
#define PTE_Boot 0		/* MBR PTE: Boot indicator */
Definition at line 201 of file ff.c.
PTE_EdCyl
#define PTE_EdCyl 7		/* MBR PTE: End cylinder */
Definition at line 208 of file ff.c.
Referenced by create_partition().
PTE_EdHead
#define PTE_EdHead 5		/* MBR PTE: End head */
Definition at line 206 of file ff.c.
Referenced by create_partition().
PTE_EdSec
#define PTE_EdSec 6		/* MBR PTE: End sector */
Definition at line 207 of file ff.c.
Referenced by create_partition().
PTE_SizLba
#define PTE_SizLba 12		/* MBR PTE: Size in LBA */
Definition at line 210 of file ff.c.
Referenced by create_partition(), and f_mkfs().
PTE_StCyl
#define PTE_StCyl 3		/* MBR PTE: Start cylinder */
Definition at line 204 of file ff.c.
Referenced by create_partition().
PTE_StHead
#define PTE_StHead 1		/* MBR PTE: Start head */
Definition at line 202 of file ff.c.
Referenced by create_partition().
PTE_StLba
#define PTE_StLba 8		/* MBR PTE: Start in LBA */
Definition at line 209 of file ff.c.
Referenced by create_partition(), f_mkfs(), and find_volume().
PTE_StSec
#define PTE_StSec 2		/* MBR PTE: Start sector */
Definition at line 203 of file ff.c.
Referenced by create_partition().
PTE_System
#define PTE_System 4		/* MBR PTE: System ID */
Definition at line 205 of file ff.c.
Referenced by create_partition(), f_mkfs(), and find_volume().
RDDEM
#define RDDEM 0x05	/* Replacement of the character collides with DDEM */
Definition at line 191 of file ff.c.
Referenced by create_name(), and get_fileinfo().
SS
#define SS(fs) ((UINT)FF_MAX_SS)	/* Fixed sector size */
Definition at line 264 of file ff.c.
Referenced by clmt_clust(), dir_clear(), dir_next(), dir_register(), dir_sdi(), f_expand(), f_getfree(), f_lseek(), f_mkdir(), f_open(), f_read(), f_write(), find_volume(), follow_path(), get_fat(), mount_volume(), and put_fat().
SZ_GPTE
#define SZ_GPTE 128		/* GPT: Size of partition table entry */
Definition at line 225 of file ff.c.
Referenced by create_partition(), f_mkfs(), find_volume(), and get_ldnumber().
SZ_PTE
#define SZ_PTE 16		/* MBR: Size of a partition table entry */
Definition at line 200 of file ff.c.
Referenced by create_partition(), f_mkfs(), and find_volume().
SZDIRE
#define SZDIRE 32		/* Size of a directory entry */
Definition at line 189 of file ff.c.
Referenced by dir_find(), dir_next(), dir_register(), dir_sdi(), f_getcwd(), f_mkdir(), f_mkfs(), f_rename(), f_setlabel(), mount_volume(), and sum_sfn().
TBL_CT437
#define TBL_CT437
Value:
{0x80,0x9A,0x45,0x41,0x8E,0x41,0x8F,0x80,0x45,0x45,0x45,0x49,0x49,0x49,0x8E,0x8F, \
                    0x90,0x92,0x92,0x4F,0x99,0x4F,0x55,0x55,0x59,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F, \
                    0x41,0x49,0x4F,0x55,0xA5,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF, \
                    0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF, \
                    0xC0,0xC1,0xC2,0xC3,0xC4,0xC5,0xC6,0xC7,0xC8,0xC9,0xCA,0xCB,0xCC,0xCD,0xCE,0xCF, \
                    0xD0,0xD1,0xD2,0xD3,0xD4,0xD5,0xD6,0xD7,0xD8,0xD9,0xDA,0xDB,0xDC,0xDD,0xDE,0xDF, \
                    0xE0,0xE1,0xE2,0xE3,0xE4,0xE5,0xE6,0xE7,0xE8,0xE9,0xEA,0xEB,0xEC,0xED,0xEE,0xEF, \
                    0xF0,0xF1,0xF2,0xF3,0xF4,0xF5,0xF6,0xF7,0xF8,0xF9,0xFA,0xFB,0xFC,0xFD,0xFE,0xFF}
Definition at line 296 of file ff.c.
TBL_CT720
#define TBL_CT720
Value:
{0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F, \
                    0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F, \
                    0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF, \
                    0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF, \
                    0xC0,0xC1,0xC2,0xC3,0xC4,0xC5,0xC6,0xC7,0xC8,0xC9,0xCA,0xCB,0xCC,0xCD,0xCE,0xCF, \
                    0xD0,0xD1,0xD2,0xD3,0xD4,0xD5,0xD6,0xD7,0xD8,0xD9,0xDA,0xDB,0xDC,0xDD,0xDE,0xDF, \
                    0xE0,0xE1,0xE2,0xE3,0xE4,0xE5,0xE6,0xE7,0xE8,0xE9,0xEA,0xEB,0xEC,0xED,0xEE,0xEF, \
                    0xF0,0xF1,0xF2,0xF3,0xF4,0xF5,0xF6,0xF7,0xF8,0xF9,0xFA,0xFB,0xFC,0xFD,0xFE,0xFF}
Definition at line 304 of file ff.c.
TBL_CT737
#define TBL_CT737
Value:
{0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F, \
                    0x90,0x92,0x92,0x93,0x94,0x95,0x96,0x97,0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87, \
                    0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0xAA,0x92,0x93,0x94,0x95,0x96, \
                    0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF, \
                    0xC0,0xC1,0xC2,0xC3,0xC4,0xC5,0xC6,0xC7,0xC8,0xC9,0xCA,0xCB,0xCC,0xCD,0xCE,0xCF, \
                    0xD0,0xD1,0xD2,0xD3,0xD4,0xD5,0xD6,0xD7,0xD8,0xD9,0xDA,0xDB,0xDC,0xDD,0xDE,0xDF, \
                    0x97,0xEA,0xEB,0xEC,0xE4,0xED,0xEE,0xEF,0xF5,0xF0,0xEA,0xEB,0xEC,0xED,0xEE,0xEF, \
                    0xF0,0xF1,0xF2,0xF3,0xF4,0xF5,0xF6,0xF7,0xF8,0xF9,0xFA,0xFB,0xFC,0xFD,0xFE,0xFF}
Definition at line 312 of file ff.c.
TBL_CT771
#define TBL_CT771
Value:
{0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F, \
                    0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F, \
                    0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F, \
                    0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF, \
                    0xC0,0xC1,0xC2,0xC3,0xC4,0xC5,0xC6,0xC7,0xC8,0xC9,0xCA,0xCB,0xCC,0xCD,0xCE,0xCF, \
                    0xD0,0xD1,0xD2,0xD3,0xD4,0xD5,0xD6,0xD7,0xD8,0xD9,0xDA,0xDB,0xDC,0xDC,0xDE,0xDE, \
                    0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F, \
                    0xF0,0xF0,0xF2,0xF2,0xF4,0xF4,0xF6,0xF6,0xF8,0xF8,0xFA,0xFA,0xFC,0xFC,0xFE,0xFF}
Definition at line 320 of file ff.c.
TBL_CT775
#define TBL_CT775
Value:
{0x80,0x9A,0x91,0xA0,0x8E,0x95,0x8F,0x80,0xAD,0xED,0x8A,0x8A,0xA1,0x8D,0x8E,0x8F, \
                    0x90,0x92,0x92,0xE2,0x99,0x95,0x96,0x97,0x97,0x99,0x9A,0x9D,0x9C,0x9D,0x9E,0x9F, \
                    0xA0,0xA1,0xE0,0xA3,0xA3,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF, \
                    0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF, \
                    0xC0,0xC1,0xC2,0xC3,0xC4,0xC5,0xC6,0xC7,0xC8,0xC9,0xCA,0xCB,0xCC,0xCD,0xCE,0xCF, \
                    0xB5,0xB6,0xB7,0xB8,0xBD,0xBE,0xC6,0xC7,0xA5,0xD9,0xDA,0xDB,0xDC,0xDD,0xDE,0xDF, \
                    0xE0,0xE1,0xE2,0xE3,0xE5,0xE5,0xE6,0xE3,0xE8,0xE8,0xEA,0xEA,0xEE,0xED,0xEE,0xEF, \
                    0xF0,0xF1,0xF2,0xF3,0xF4,0xF5,0xF6,0xF7,0xF8,0xF9,0xFA,0xFB,0xFC,0xFD,0xFE,0xFF}
Definition at line 328 of file ff.c.
TBL_CT850
#define TBL_CT850
Value:
{0x43,0x55,0x45,0x41,0x41,0x41,0x41,0x43,0x45,0x45,0x45,0x49,0x49,0x49,0x41,0x41, \
                    0x45,0x92,0x92,0x4F,0x4F,0x4F,0x55,0x55,0x59,0x4F,0x55,0x4F,0x9C,0x4F,0x9E,0x9F, \
                    0x41,0x49,0x4F,0x55,0xA5,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF, \
                    0xB0,0xB1,0xB2,0xB3,0xB4,0x41,0x41,0x41,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF, \
                    0xC0,0xC1,0xC2,0xC3,0xC4,0xC5,0x41,0x41,0xC8,0xC9,0xCA,0xCB,0xCC,0xCD,0xCE,0xCF, \
                    0xD1,0xD1,0x45,0x45,0x45,0x49,0x49,0x49,0x49,0xD9,0xDA,0xDB,0xDC,0xDD,0x49,0xDF, \
                    0x4F,0xE1,0x4F,0x4F,0x4F,0x4F,0xE6,0xE8,0xE8,0x55,0x55,0x55,0x59,0x59,0xEE,0xEF, \
                    0xF0,0xF1,0xF2,0xF3,0xF4,0xF5,0xF6,0xF7,0xF8,0xF9,0xFA,0xFB,0xFC,0xFD,0xFE,0xFF}
Definition at line 336 of file ff.c.
TBL_CT852
#define TBL_CT852
Value:
{0x80,0x9A,0x90,0xB6,0x8E,0xDE,0x8F,0x80,0x9D,0xD3,0x8A,0x8A,0xD7,0x8D,0x8E,0x8F, \
                    0x90,0x91,0x91,0xE2,0x99,0x95,0x95,0x97,0x97,0x99,0x9A,0x9B,0x9B,0x9D,0x9E,0xAC, \
                    0xB5,0xD6,0xE0,0xE9,0xA4,0xA4,0xA6,0xA6,0xA8,0xA8,0xAA,0x8D,0xAC,0xB8,0xAE,0xAF, \
                    0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBD,0xBF, \
                    0xC0,0xC1,0xC2,0xC3,0xC4,0xC5,0xC6,0xC6,0xC8,0xC9,0xCA,0xCB,0xCC,0xCD,0xCE,0xCF, \
                    0xD1,0xD1,0xD2,0xD3,0xD2,0xD5,0xD6,0xD7,0xB7,0xD9,0xDA,0xDB,0xDC,0xDD,0xDE,0xDF, \
                    0xE0,0xE1,0xE2,0xE3,0xE3,0xD5,0xE6,0xE6,0xE8,0xE9,0xE8,0xEB,0xED,0xED,0xDD,0xEF, \
                    0xF0,0xF1,0xF2,0xF3,0xF4,0xF5,0xF6,0xF7,0xF8,0xF9,0xFA,0xEB,0xFC,0xFC,0xFE,0xFF}
Definition at line 344 of file ff.c.
TBL_CT855
#define TBL_CT855
Value:
{0x81,0x81,0x83,0x83,0x85,0x85,0x87,0x87,0x89,0x89,0x8B,0x8B,0x8D,0x8D,0x8F,0x8F, \
                    0x91,0x91,0x93,0x93,0x95,0x95,0x97,0x97,0x99,0x99,0x9B,0x9B,0x9D,0x9D,0x9F,0x9F, \
                    0xA1,0xA1,0xA3,0xA3,0xA5,0xA5,0xA7,0xA7,0xA9,0xA9,0xAB,0xAB,0xAD,0xAD,0xAE,0xAF, \
                    0xB0,0xB1,0xB2,0xB3,0xB4,0xB6,0xB6,0xB8,0xB8,0xB9,0xBA,0xBB,0xBC,0xBE,0xBE,0xBF, \
                    0xC0,0xC1,0xC2,0xC3,0xC4,0xC5,0xC7,0xC7,0xC8,0xC9,0xCA,0xCB,0xCC,0xCD,0xCE,0xCF, \
                    0xD1,0xD1,0xD3,0xD3,0xD5,0xD5,0xD7,0xD7,0xDD,0xD9,0xDA,0xDB,0xDC,0xDD,0xE0,0xDF, \
                    0xE0,0xE2,0xE2,0xE4,0xE4,0xE6,0xE6,0xE8,0xE8,0xEA,0xEA,0xEC,0xEC,0xEE,0xEE,0xEF, \
                    0xF0,0xF2,0xF2,0xF4,0xF4,0xF6,0xF6,0xF8,0xF8,0xFA,0xFA,0xFC,0xFC,0xFD,0xFE,0xFF}
Definition at line 352 of file ff.c.
TBL_CT857
#define TBL_CT857
Value:
{0x80,0x9A,0x90,0xB6,0x8E,0xB7,0x8F,0x80,0xD2,0xD3,0xD4,0xD8,0xD7,0x49,0x8E,0x8F, \
                    0x90,0x92,0x92,0xE2,0x99,0xE3,0xEA,0xEB,0x98,0x99,0x9A,0x9D,0x9C,0x9D,0x9E,0x9E, \
                    0xB5,0xD6,0xE0,0xE9,0xA5,0xA5,0xA6,0xA6,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF, \
                    0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF, \
                    0xC0,0xC1,0xC2,0xC3,0xC4,0xC5,0xC7,0xC7,0xC8,0xC9,0xCA,0xCB,0xCC,0xCD,0xCE,0xCF, \
                    0xD0,0xD1,0xD2,0xD3,0xD4,0x49,0xD6,0xD7,0xD8,0xD9,0xDA,0xDB,0xDC,0xDD,0xDE,0xDF, \
                    0xE0,0xE1,0xE2,0xE3,0xE5,0xE5,0xE6,0xE7,0xE8,0xE9,0xEA,0xEB,0xDE,0xED,0xEE,0xEF, \
                    0xF0,0xF1,0xF2,0xF3,0xF4,0xF5,0xF6,0xF7,0xF8,0xF9,0xFA,0xFB,0xFC,0xFD,0xFE,0xFF}
Definition at line 360 of file ff.c.
TBL_CT860
#define TBL_CT860
Value:
{0x80,0x9A,0x90,0x8F,0x8E,0x91,0x86,0x80,0x89,0x89,0x92,0x8B,0x8C,0x98,0x8E,0x8F, \
                    0x90,0x91,0x92,0x8C,0x99,0xA9,0x96,0x9D,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F, \
                    0x86,0x8B,0x9F,0x96,0xA5,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF, \
                    0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF, \
                    0xC0,0xC1,0xC2,0xC3,0xC4,0xC5,0xC6,0xC7,0xC8,0xC9,0xCA,0xCB,0xCC,0xCD,0xCE,0xCF, \
                    0xD0,0xD1,0xD2,0xD3,0xD4,0xD5,0xD6,0xD7,0xD8,0xD9,0xDA,0xDB,0xDC,0xDD,0xDE,0xDF, \
                    0xE0,0xE1,0xE2,0xE3,0xE4,0xE5,0xE6,0xE7,0xE8,0xE9,0xEA,0xEB,0xEC,0xED,0xEE,0xEF, \
                    0xF0,0xF1,0xF2,0xF3,0xF4,0xF5,0xF6,0xF7,0xF8,0xF9,0xFA,0xFB,0xFC,0xFD,0xFE,0xFF}
Definition at line 368 of file ff.c.
TBL_CT861
#define TBL_CT861
Value:
{0x80,0x9A,0x90,0x41,0x8E,0x41,0x8F,0x80,0x45,0x45,0x45,0x8B,0x8B,0x8D,0x8E,0x8F, \
                    0x90,0x92,0x92,0x4F,0x99,0x8D,0x55,0x97,0x97,0x99,0x9A,0x9D,0x9C,0x9D,0x9E,0x9F, \
                    0xA4,0xA5,0xA6,0xA7,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF, \
                    0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF, \
                    0xC0,0xC1,0xC2,0xC3,0xC4,0xC5,0xC6,0xC7,0xC8,0xC9,0xCA,0xCB,0xCC,0xCD,0xCE,0xCF, \
                    0xD0,0xD1,0xD2,0xD3,0xD4,0xD5,0xD6,0xD7,0xD8,0xD9,0xDA,0xDB,0xDC,0xDD,0xDE,0xDF, \
                    0xE0,0xE1,0xE2,0xE3,0xE4,0xE5,0xE6,0xE7,0xE8,0xE9,0xEA,0xEB,0xEC,0xED,0xEE,0xEF, \
                    0xF0,0xF1,0xF2,0xF3,0xF4,0xF5,0xF6,0xF7,0xF8,0xF9,0xFA,0xFB,0xFC,0xFD,0xFE,0xFF}
Definition at line 376 of file ff.c.
TBL_CT862
#define TBL_CT862
Value:
{0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F, \
                    0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F, \
                    0x41,0x49,0x4F,0x55,0xA5,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF, \
                    0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF, \
                    0xC0,0xC1,0xC2,0xC3,0xC4,0xC5,0xC6,0xC7,0xC8,0xC9,0xCA,0xCB,0xCC,0xCD,0xCE,0xCF, \
                    0xD0,0xD1,0xD2,0xD3,0xD4,0xD5,0xD6,0xD7,0xD8,0xD9,0xDA,0xDB,0xDC,0xDD,0xDE,0xDF, \
                    0xE0,0xE1,0xE2,0xE3,0xE4,0xE5,0xE6,0xE7,0xE8,0xE9,0xEA,0xEB,0xEC,0xED,0xEE,0xEF, \
                    0xF0,0xF1,0xF2,0xF3,0xF4,0xF5,0xF6,0xF7,0xF8,0xF9,0xFA,0xFB,0xFC,0xFD,0xFE,0xFF}
Definition at line 384 of file ff.c.
TBL_CT863
#define TBL_CT863
Value:
{0x43,0x55,0x45,0x41,0x41,0x41,0x86,0x43,0x45,0x45,0x45,0x49,0x49,0x8D,0x41,0x8F, \
                    0x45,0x45,0x45,0x4F,0x45,0x49,0x55,0x55,0x98,0x4F,0x55,0x9B,0x9C,0x55,0x55,0x9F, \
                    0xA0,0xA1,0x4F,0x55,0xA4,0xA5,0xA6,0xA7,0x49,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF, \
                    0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF, \
                    0xC0,0xC1,0xC2,0xC3,0xC4,0xC5,0xC6,0xC7,0xC8,0xC9,0xCA,0xCB,0xCC,0xCD,0xCE,0xCF, \
                    0xD0,0xD1,0xD2,0xD3,0xD4,0xD5,0xD6,0xD7,0xD8,0xD9,0xDA,0xDB,0xDC,0xDD,0xDE,0xDF, \
                    0xE0,0xE1,0xE2,0xE3,0xE4,0xE5,0xE6,0xE7,0xE8,0xE9,0xEA,0xEB,0xEC,0xED,0xEE,0xEF, \
                    0xF0,0xF1,0xF2,0xF3,0xF4,0xF5,0xF6,0xF7,0xF8,0xF9,0xFA,0xFB,0xFC,0xFD,0xFE,0xFF}
Definition at line 392 of file ff.c.
TBL_CT864
#define TBL_CT864
Value:
{0x80,0x9A,0x45,0x41,0x8E,0x41,0x8F,0x80,0x45,0x45,0x45,0x49,0x49,0x49,0x8E,0x8F, \
                    0x90,0x92,0x92,0x4F,0x99,0x4F,0x55,0x55,0x59,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F, \
                    0x41,0x49,0x4F,0x55,0xA5,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF, \
                    0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF, \
                    0xC0,0xC1,0xC2,0xC3,0xC4,0xC5,0xC6,0xC7,0xC8,0xC9,0xCA,0xCB,0xCC,0xCD,0xCE,0xCF, \
                    0xD0,0xD1,0xD2,0xD3,0xD4,0xD5,0xD6,0xD7,0xD8,0xD9,0xDA,0xDB,0xDC,0xDD,0xDE,0xDF, \
                    0xE0,0xE1,0xE2,0xE3,0xE4,0xE5,0xE6,0xE7,0xE8,0xE9,0xEA,0xEB,0xEC,0xED,0xEE,0xEF, \
                    0xF0,0xF1,0xF2,0xF3,0xF4,0xF5,0xF6,0xF7,0xF8,0xF9,0xFA,0xFB,0xFC,0xFD,0xFE,0xFF}
Definition at line 400 of file ff.c.
TBL_CT865
#define TBL_CT865
Value:
{0x80,0x9A,0x90,0x41,0x8E,0x41,0x8F,0x80,0x45,0x45,0x45,0x49,0x49,0x49,0x8E,0x8F, \
                    0x90,0x92,0x92,0x4F,0x99,0x4F,0x55,0x55,0x59,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F, \
                    0x41,0x49,0x4F,0x55,0xA5,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF, \
                    0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF, \
                    0xC0,0xC1,0xC2,0xC3,0xC4,0xC5,0xC6,0xC7,0xC8,0xC9,0xCA,0xCB,0xCC,0xCD,0xCE,0xCF, \
                    0xD0,0xD1,0xD2,0xD3,0xD4,0xD5,0xD6,0xD7,0xD8,0xD9,0xDA,0xDB,0xDC,0xDD,0xDE,0xDF, \
                    0xE0,0xE1,0xE2,0xE3,0xE4,0xE5,0xE6,0xE7,0xE8,0xE9,0xEA,0xEB,0xEC,0xED,0xEE,0xEF, \
                    0xF0,0xF1,0xF2,0xF3,0xF4,0xF5,0xF6,0xF7,0xF8,0xF9,0xFA,0xFB,0xFC,0xFD,0xFE,0xFF}
Definition at line 408 of file ff.c.
TBL_CT866
#define TBL_CT866
Value:
{0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F, \
                    0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F, \
                    0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F, \
                    0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF, \
                    0xC0,0xC1,0xC2,0xC3,0xC4,0xC5,0xC6,0xC7,0xC8,0xC9,0xCA,0xCB,0xCC,0xCD,0xCE,0xCF, \
                    0xD0,0xD1,0xD2,0xD3,0xD4,0xD5,0xD6,0xD7,0xD8,0xD9,0xDA,0xDB,0xDC,0xDD,0xDE,0xDF, \
                    0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F, \
                    0xF0,0xF0,0xF2,0xF2,0xF4,0xF4,0xF6,0xF6,0xF8,0xF9,0xFA,0xFB,0xFC,0xFD,0xFE,0xFF}
Definition at line 416 of file ff.c.
TBL_CT869
#define TBL_CT869
Value:
{0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F, \
                    0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x86,0x9C,0x8D,0x8F,0x90, \
                    0x91,0x90,0x92,0x95,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF, \
                    0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF, \
                    0xC0,0xC1,0xC2,0xC3,0xC4,0xC5,0xC6,0xC7,0xC8,0xC9,0xCA,0xCB,0xCC,0xCD,0xCE,0xCF, \
                    0xD0,0xD1,0xD2,0xD3,0xD4,0xD5,0xA4,0xA5,0xA6,0xD9,0xDA,0xDB,0xDC,0xA7,0xA8,0xDF, \
                    0xA9,0xAA,0xAC,0xAD,0xB5,0xB6,0xB7,0xB8,0xBD,0xBE,0xC6,0xC7,0xCF,0xCF,0xD0,0xEF, \
                    0xF0,0xF1,0xD1,0xD2,0xD3,0xF5,0xD4,0xF7,0xF8,0xF9,0xD5,0x96,0x95,0x98,0xFE,0xFF}
Definition at line 424 of file ff.c.
TBL_DC932
#define TBL_DC932 {0x81, 0x9F, 0xE0, 0xFC, 0x40, 0x7E, 0x80, 0xFC, 0x00, 0x00}
Definition at line 436 of file ff.c.
TBL_DC936
#define TBL_DC936 {0x81, 0xFE, 0x00, 0x00, 0x40, 0x7E, 0x80, 0xFE, 0x00, 0x00}
Definition at line 437 of file ff.c.
TBL_DC949
#define TBL_DC949 {0x81, 0xFE, 0x00, 0x00, 0x41, 0x5A, 0x61, 0x7A, 0x81, 0xFE}
Definition at line 438 of file ff.c.
TBL_DC950
#define TBL_DC950 {0x81, 0xFE, 0x00, 0x00, 0x40, 0x7E, 0xA1, 0xFE, 0x00, 0x00}
Definition at line 439 of file ff.c.
XDIR_AccTime
#define XDIR_AccTime 16		/* exFAT: Last accessed time (DWORD) */
Definition at line 176 of file ff.c.
Referenced by f_sync().
XDIR_AccTZ
#define XDIR_AccTZ 24		/* exFAT: Last accessed timezone (BYTE) */
Definition at line 181 of file ff.c.
XDIR_Attr
#define XDIR_Attr 4		/* exFAT: File attribute (WORD) */
Definition at line 173 of file ff.c.
Referenced by dir_read(), f_chmod(), f_mkdir(), f_open(), f_rename(), f_sync(), and sum_sfn().
XDIR_CaseSum
#define XDIR_CaseSum 4		/* exFAT: Sum of case conversion table (DWORD) */
Definition at line 170 of file ff.c.
XDIR_CrtTime
#define XDIR_CrtTime 8		/* exFAT: Created time (DWORD) */
Definition at line 174 of file ff.c.
Referenced by f_open().
XDIR_CrtTime10
#define XDIR_CrtTime10 20		/* exFAT: Created time subsecond (BYTE) */
Definition at line 177 of file ff.c.
XDIR_CrtTZ
#define XDIR_CrtTZ 22		/* exFAT: Created timezone (BYTE) */
Definition at line 179 of file ff.c.
XDIR_FileSize
#define XDIR_FileSize 56		/* exFAT: File/Directory size (QWORD) */
Definition at line 187 of file ff.c.
Referenced by dir_register(), f_mkdir(), f_sync(), follow_path(), and sum_sfn().
XDIR_FstClus
#define XDIR_FstClus 52		/* exFAT: First cluster of the file data (DWORD) */
Definition at line 186 of file ff.c.
Referenced by f_chdir(), f_mkdir(), f_sync(), and sum_sfn().
XDIR_GenFlags
#define XDIR_GenFlags 33		/* exFAT: General secondary flags (BYTE) */
Definition at line 182 of file ff.c.
Referenced by dir_register(), f_mkdir(), f_open(), f_sync(), follow_path(), and sum_sfn().
XDIR_Label
#define XDIR_Label 2		/* exFAT: Volume label (11-WORD) */
Definition at line 169 of file ff.c.
Referenced by f_getlabel(), and f_setlabel().
XDIR_ModTime
#define XDIR_ModTime 12		/* exFAT: Modified time (DWORD) */
Definition at line 175 of file ff.c.
Referenced by f_mkdir(), f_sync(), f_utime(), and sum_sfn().
XDIR_ModTime10
#define XDIR_ModTime10 21		/* exFAT: Modified time subsecond (BYTE) */
Definition at line 178 of file ff.c.
Referenced by f_sync().
XDIR_ModTZ
#define XDIR_ModTZ 23		/* exFAT: Modified timezone (BYTE) */
Definition at line 180 of file ff.c.
XDIR_NameHash
#define XDIR_NameHash 36		/* exFAT: Hash of file name (WORD) */
Definition at line 184 of file ff.c.
Referenced by dir_find(), f_rename(), and sum_sfn().
XDIR_NumLabel
#define XDIR_NumLabel 1		/* exFAT: Number of volume label characters (BYTE) */
Definition at line 168 of file ff.c.
Referenced by f_getlabel(), and f_setlabel().
XDIR_NumName
#define XDIR_NumName 35		/* exFAT: Number of file name characters (BYTE) */
Definition at line 183 of file ff.c.
Referenced by dir_find(), f_rename(), and sum_sfn().
XDIR_NumSec
#define XDIR_NumSec 1		/* exFAT: Number of secondary entries (BYTE) */
Definition at line 171 of file ff.c.
Referenced by f_rename(), and sum_sfn().
XDIR_SetSum
#define XDIR_SetSum 2		/* exFAT: Sum of the set of directory entries (WORD) */
Definition at line 172 of file ff.c.
Referenced by sum_sfn().
XDIR_Type
#define XDIR_Type 0		/* exFAT: Type of exFAT directory entry (BYTE) */
Definition at line 167 of file ff.c.
Referenced by dir_alloc(), dir_remove(), f_setlabel(), and sum_sfn().
XDIR_ValidFileSize
#define XDIR_ValidFileSize 40		/* exFAT: Valid file size (QWORD) */
Definition at line 185 of file ff.c.
Referenced by dir_register(), f_mkdir(), and f_sync().
Function Documentation
check_fs()
static UINT check_fs (FATFS * fs, LBA_t sect) [static]
Definition at line 3298 of file ff.c.
Referenced by find_volume().
chk_chr()
static int chk_chr (const char * str, int chr) [static]
Definition at line 728 of file ff.c.
Referenced by create_name(), and f_setlabel().
clmt_clust()
static DWORD clmt_clust (FIL * fp, FSIZE_t ofs) [static]
Definition at line 1649 of file ff.c.
Referenced by f_lseek(), f_read(), and f_write().
clst2sect()
static LBA_t clst2sect (FATFS * fs, DWORD clst) [static]
Definition at line 1167 of file ff.c.
Referenced by dir_clear(), dir_next(), dir_sdi(), f_expand(), f_lseek(), f_open(), f_read(), f_rename(), f_write(), mount_volume(), and remove_chain().
cmp_lfn()
static int cmp_lfn (const WCHAR * lfnbuf, BYTE * dir) [static]
Definition at line 1906 of file ff.c.
Referenced by dir_find().
create_chain()
static DWORD create_chain (FFOBJID * obj, DWORD clst) [static]
Definition at line 1546 of file ff.c.
Referenced by dir_next(), f_lseek(), f_mkdir(), and f_write().
create_name()
static FRESULT create_name (DIR * dp, const TCHAR ** path) [static]
Definition at line 2864 of file ff.c.
Referenced by follow_path().
create_partition()
static FRESULT create_partition (BYTE drv, const LBA_t plst[], UINT sys, BYTE * buf) [static]
Definition at line 5695 of file ff.c.
Referenced by f_mkfs().
dbc_1st()
static int dbc_1st (BYTE c) [static]
Definition at line 736 of file ff.c.
Referenced by create_name(), f_getlabel(), f_mkfs(), f_setlabel(), gen_numname(), get_achar(), get_fileinfo(), and tchar2uni().
dbc_2nd()
static int dbc_2nd (BYTE c) [static]
Definition at line 756 of file ff.c.
Referenced by create_name(), f_mkfs(), f_setlabel(), get_achar(), get_fileinfo(), and tchar2uni().
dir_alloc()
static FRESULT dir_alloc (DIR * dp, UINT nent) [static]
Definition at line 1827 of file ff.c.
Referenced by dir_register(), and f_setlabel().
dir_clear()
static FRESULT dir_clear (FATFS * fs, DWORD clst) [static]
Definition at line 1679 of file ff.c.
Referenced by dir_next(), and f_mkdir().
dir_find()
static FRESULT dir_find (DIR * dp) [static]
Definition at line 2447 of file ff.c.
Referenced by dir_register(), and follow_path().
dir_next()
static FRESULT dir_next (DIR * dp, int stretch) [static]
Definition at line 1766 of file ff.c.
Referenced by dir_alloc(), dir_find(), dir_read(), dir_register(), dir_remove(), f_getcwd(), f_readdir(), and sum_sfn().
dir_read()
static FRESULT dir_read (DIR * dp, int vol) [static]
Definition at line 2369 of file ff.c.
dir_register()
static FRESULT dir_register (DIR * dp) [static]
Definition at line 2528 of file ff.c.
Referenced by f_mkdir(), f_open(), and f_rename().
dir_remove()
static FRESULT dir_remove (DIR * dp) [static]
Definition at line 2634 of file ff.c.
Referenced by f_rename(), and f_unlink().
dir_sdi()
static FRESULT dir_sdi (DIR * dp, DWORD ofs) [static]
Definition at line 1718 of file ff.c.
Referenced by dir_alloc(), dir_find(), dir_register(), dir_remove(), f_getcwd(), f_getlabel(), f_opendir(), f_readdir(), f_setlabel(), f_unlink(), follow_path(), and sum_sfn().
f_chdir()
FRESULT f_chdir (const TCHAR * path)
Definition at line 4245 of file ff.c.
Referenced by chdir(), and fatfs_ls().
f_chdrive()
FRESULT f_chdrive (const TCHAR * path)
Definition at line 4228 of file ff.c.
f_chmod()
FRESULT f_chmod (const TCHAR * path, BYTE attr, BYTE mask)
Definition at line 5217 of file ff.c.
Referenced by chmod(), and fatfs_tests().
f_close()
FRESULT f_close (FIL * fp)
Definition at line 4192 of file ff.c.
Referenced by close(), dbf_close(), fatfs_ls(), and open().
f_closedir()
FRESULT f_closedir (DIR * dp)
Definition at line 4636 of file ff.c.
Referenced by closedir().
f_expand()
FRESULT f_expand (FIL * fp, FSIZE_t fsz, BYTE opt)
Definition at line 5526 of file ff.c.
f_findfirst()
FRESULT f_findfirst (DIR * dp, FILINFO * fno, const TCHAR * path, const TCHAR * pattern)
Definition at line 4727 of file ff.c.
f_findnext()
FRESULT f_findnext (DIR * dp, FILINFO * fno)
Definition at line 4702 of file ff.c.
Referenced by f_findfirst().
f_getcwd()
FRESULT f_getcwd (TCHAR * buff, UINT len)
Definition at line 4307 of file ff.c.
Referenced by fatfs_ls(), and getcwd().
f_getfree()
FRESULT f_getfree (const TCHAR * path, DWORD * nclst, FATFS ** fatfs)
Definition at line 4789 of file ff.c.
Referenced by fatfs_ls(), and fatfs_status().
f_getlabel()
FRESULT f_getlabel (const TCHAR * path, TCHAR * label, DWORD * vsn)
Definition at line 5311 of file ff.c.
Referenced by fatfs_status().
f_lseek()
FRESULT f_lseek (FIL * fp, FSIZE_t ofs)
Definition at line 4407 of file ff.c.
Referenced by dbf_lseek(), fatfs_getc(), ftruncate(), lseek(), open(), and truncate().
f_mkdir()
FRESULT f_mkdir (const TCHAR * path)
Definition at line 5023 of file ff.c.
Referenced by fatfs_ls(), and mkdir().
f_mkfs()
FRESULT f_mkfs (const TCHAR * path, const MKFS_PARM * opt, void * work, UINT len)
Definition at line 5837 of file ff.c.
Referenced by fatfs_tests(), and mkfs().
f_mount()
FRESULT f_mount (FATFS * fs, const TCHAR * path, BYTE opt)
Definition at line 3648 of file ff.c.
Referenced by fatfs_tests(), mkfs(), and mmc_init().
f_open()
FRESULT f_open (FIL * fp, const TCHAR * path, BYTE mode)
Definition at line 3696 of file ff.c.
Referenced by dbf_open(), fatfs_ls(), open(), and truncate().
f_opendir()
FRESULT f_opendir (DIR * dp, const TCHAR * path)
Definition at line 4570 of file ff.c.
Referenced by f_findfirst(), fatfs_ls(), fatfs_scan_files(), and opendir().
f_read()
FRESULT f_read (FIL * fp, void * buff, UINT btr, UINT * br)
Definition at line 3888 of file ff.c.
Referenced by dbf_read(), f_mkfs(), fatfs_getc(), fatfs_ls(), and read().
f_readdir()
FRESULT f_readdir (DIR * dp, FILINFO * fno)
Definition at line 4666 of file ff.c.
Referenced by f_findnext(), fatfs_ls(), fatfs_scan_files(), and readdir().
f_rename()
FRESULT f_rename (const TCHAR * path_old, const TCHAR * path_new)
Definition at line 5107 of file ff.c.
Referenced by fatfs_ls(), and rename().
f_setlabel()
FRESULT f_setlabel (const TCHAR * label)
Definition at line 5406 of file ff.c.
f_stat()
FRESULT f_stat (const TCHAR * path, FILINFO * fno)
Definition at line 4754 of file ff.c.
Referenced by fatfs_ls(), and stat().
f_sync()
FRESULT f_sync (FIL * fp)
Definition at line 4111 of file ff.c.
Referenced by f_close(), and syncfs().
f_truncate()
FRESULT f_truncate (FIL * fp)
Definition at line 4879 of file ff.c.
Referenced by ftruncate(), and truncate().
f_unlink()
FRESULT f_unlink (const TCHAR * path)
Definition at line 4929 of file ff.c.
Referenced by fatfs_ls(), rmdir(), and unlink().
f_utime()
FRESULT f_utime (const TCHAR * path, const FILINFO * fno)
Definition at line 5264 of file ff.c.
Referenced by utime().
f_write()
FRESULT f_write (FIL * fp, const void * buff, UINT btw, UINT * bw)
Definition at line 3989 of file ff.c.
Referenced by dbf_write(), f_mkfs(), fatfs_ls(), fatfs_putc(), and write().
find_volume()
static UINT find_volume (FATFS * fs, UINT part) [static]
Definition at line 3321 of file ff.c.
Referenced by mount_volume().
follow_path()
static FRESULT follow_path (DIR * dp, const TCHAR * path) [static]
Definition at line 3065 of file ff.c.
Referenced by f_chdir(), f_chmod(), f_mkdir(), f_open(), f_opendir(), f_rename(), f_stat(), f_unlink(), and f_utime().
gen_numname()
static void gen_numname (BYTE * dst, const BYTE * src, const WCHAR * lfn, UINT seq) [static]
Definition at line 2017 of file ff.c.
Referenced by dir_register().
get_achar()
static DWORD get_achar (const TCHAR ** ptr) [static]
Definition at line 2786 of file ff.c.
Referenced by pattern_matching().
get_fat()
static DWORD get_fat (FFOBJID * obj, DWORD clst) [static]
Definition at line 1184 of file ff.c.
Referenced by create_chain(), dir_next(), dir_sdi(), f_expand(), f_getfree(), f_lseek(), f_open(), f_read(), f_truncate(), and remove_chain().
get_fileinfo()
static void get_fileinfo (DIR * dp, FILINFO * fno) [static]
Definition at line 2680 of file ff.c.
Referenced by f_getcwd(), f_readdir(), and f_stat().
get_ldnumber()
static int get_ldnumber (const TCHAR ** path) [static]
Definition at line 3152 of file ff.c.
Referenced by f_chdrive(), f_mkfs(), f_mount(), f_rename(), and mount_volume().
ld_clust()
static DWORD ld_clust (FATFS * fs, const BYTE * dir) [static]
Definition at line 1869 of file ff.c.
Referenced by f_chdir(), f_getcwd(), f_open(), f_opendir(), f_rename(), f_unlink(), and follow_path().
ld_dword()
static DWORD ld_dword (const BYTE * ptr) [static]
Definition at line 624 of file ff.c.
Referenced by f_chdir(), f_getfree(), f_getlabel(), f_mkfs(), f_open(), find_volume(), follow_path(), get_fat(), get_fileinfo(), get_ldnumber(), mount_volume(), put_fat(), and sum_sfn().
ld_word()
static WORD ld_word (const BYTE * ptr) [static]
Definition at line 615 of file ff.c.
Referenced by check_fs(), cmp_lfn(), dir_find(), f_getfree(), f_getlabel(), f_mkfs(), f_rename(), get_fat(), get_fileinfo(), ld_clust(), mount_volume(), pick_lfn(), and sum_sfn().
mem_cmp()
static int mem_cmp (const void * dst, const void * src, UINT cnt) [static]
Definition at line 714 of file ff.c.
Referenced by check_fs(), dir_find(), f_mkfs(), find_volume(), and get_ldnumber().
mem_cpy()
static void mem_cpy (void * dst, const void * src, UINT cnt) [static]
Definition at line 689 of file ff.c.
Referenced by create_partition(), dir_register(), f_mkdir(), f_mkfs(), f_read(), f_rename(), f_setlabel(), f_write(), gen_numname(), and sum_sfn().
mem_set()
static void mem_set (void * dst, int val, UINT cnt) [static]
Definition at line 703 of file ff.c.
Referenced by create_name(), create_partition(), dir_clear(), dir_register(), f_mkdir(), f_mkfs(), f_open(), f_setlabel(), sum_sfn(), and sync_fs().
mount_volume()
static FRESULT mount_volume (const TCHAR ** path, FATFS ** rfs, BYTE mode) [static]
Definition at line 3375 of file ff.c.
Referenced by f_chdir(), f_chmod(), f_getcwd(), f_getfree(), f_getlabel(), f_mkdir(), f_mount(), f_open(), f_opendir(), f_rename(), f_setlabel(), f_stat(), f_unlink(), and f_utime().
move_window()
static FRESULT move_window (FATFS * fs, LBA_t sect) [static]
Definition at line 1099 of file ff.c.
Referenced by check_fs(), dir_alloc(), dir_find(), dir_read(), dir_register(), dir_remove(), f_expand(), f_getcwd(), f_getfree(), f_getlabel(), f_open(), f_read(), f_rename(), f_sync(), f_write(), find_volume(), get_fat(), mount_volume(), put_fat(), and sum_sfn().
pattern_matching()
static int pattern_matching (const TCHAR * pat, const TCHAR * nam, int skip, int inf) [static]
Definition at line 2817 of file ff.c.
Referenced by f_findnext().
pick_lfn()
static int pick_lfn (WCHAR * lfnbuf, BYTE * dir) [static]
Definition at line 1942 of file ff.c.
Referenced by dir_read().
put_fat()
static FRESULT put_fat (FATFS * fs, DWORD clst, DWORD val) [static]
Definition at line 1261 of file ff.c.
Referenced by create_chain(), f_expand(), and remove_chain().
put_lfn()
static void put_lfn (const WCHAR * lfn, BYTE * dir, BYTE ord, BYTE sum) [static]
Definition at line 1980 of file ff.c.
Referenced by dir_register().
put_utf()
static BYTE put_utf (DWORD chr, TCHAR * buf, UINT szb) [static]
Definition at line 853 of file ff.c.
Referenced by f_getlabel(), get_fileinfo(), and sum_sfn().
remove_chain()
static FRESULT remove_chain (FFOBJID * obj, DWORD clst, DWORD pclst) [static]
Definition at line 1451 of file ff.c.
Referenced by f_mkdir(), f_open(), f_truncate(), and f_unlink().
st_clust()
static void st_clust (FATFS * fs, BYTE * dir, DWORD cl) [static]
Definition at line 1886 of file ff.c.
Referenced by f_mkdir(), f_open(), f_rename(), and f_sync().
st_dword()
static void st_dword (BYTE * ptr, DWORD val) [static]
Definition at line 659 of file ff.c.
Referenced by create_partition(), f_mkdir(), f_mkfs(), f_open(), f_sync(), f_utime(), put_fat(), and sync_fs().
st_word()
static void st_word (BYTE * ptr, WORD val) [static]
Definition at line 653 of file ff.c.
Referenced by create_partition(), f_mkfs(), f_rename(), f_setlabel(), f_sync(), put_fat(), put_lfn(), st_clust(), sum_sfn(), and sync_fs().
sum_sfn()
static BYTE sum_sfn (const BYTE * dir) [static]
Definition at line 2075 of file ff.c.
Referenced by dir_find(), dir_read(), and dir_register().
sync_fs()
static FRESULT sync_fs (FATFS * fs) [static]
Definition at line 1130 of file ff.c.
Referenced by f_chmod(), f_mkdir(), f_rename(), f_setlabel(), f_sync(), f_unlink(), and f_utime().
sync_window()
static FRESULT sync_window (FATFS * fs) [static]
Definition at line 1077 of file ff.c.
Referenced by dir_clear(), f_write(), move_window(), and sync_fs().
tchar2uni()
static DWORD tchar2uni (const TCHAR ** str) [static]
Definition at line 780 of file ff.c.
Referenced by create_name(), f_mkfs(), f_setlabel(), and get_achar().
validate()
static FRESULT validate (FFOBJID * obj, FATFS ** rfs) [static]
Definition at line 3604 of file ff.c.
Referenced by f_close(), f_closedir(), f_expand(), f_lseek(), f_read(), f_readdir(), f_sync(), f_truncate(), and f_write().
Variable Documentation
CurrVol
BYTE CurrVol [static]
Definition at line 469 of file ff.c.
Referenced by f_chdir(), f_chdrive(), f_getcwd(), and get_ldnumber().
ExCvt
const BYTE ExCvt[] = MKCVTBL(TBL_CT, FF_CODE_PAGE) [static]
Definition at line 593 of file ff.c.
Referenced by create_name(), f_mkfs(), f_setlabel(), and get_achar().
FatFs
FATFS* FatFs[FF_VOLUMES] [static]
Definition at line 465 of file ff.c.
Fsid
WORD Fsid [static]
Definition at line 466 of file ff.c.
Referenced by mount_volume().
LfnOfs
const BYTE LfnOfs[] = {1,3,5,7,9,14,16,18,20,22,24,28,30} [static]
Definition at line 514 of file ff.c.
Referenced by cmp_lfn(), pick_lfn(), and put_lfn().