fatfs/ffsystem.c File Reference
#include `user_config.h`
#include `fatfs.h`
#include `ff.h`
Functions
void * ff_memalloc (UINT msize)
void ff_memfree (void *mblock)
Function Documentation
ff_memalloc()
void* ff_memalloc (UINT msize)
Definition at line 23 of file ffsystem.c.
Referenced by dir_clear(), and f_mkfs().
ff_memfree()
void ff_memfree (void * mblock)
Definition at line 35 of file ffsystem.c.
Referenced by dir_clear().