gpib/format.c File Reference
LIF Disk Format.
#include `user_config.h`
*
#include `defines.h`
*
#include `drives.h`
*
#include `format.h`
*
#include <time.h>
*
Functions
int lif_closedir (lifdir_t *DIR)
Close LIF directory Modeled after Linux closedir()
lifdir_t * lif_opendir (char *name)
DirEntryType * lif_readdir (lifdir_t *DIR)
void lif_filename (char *name, DirEntryType *DE)
get LIF file name from directory entry
long lif_filelength (DirEntryType *DE)
get LIF file size from directory entry
int lif_dir (char *name)
Display a LIF image file directory.
long lif_create_image (char *name, char *label, long dirsecs, long sectors)
Create LIF disk image This can take a while to run.
Variables
static lifdir_t _lifdir
Open LIF directory for reading Modeled after Linux opendir()
static DirEntryType _lifent
Open LIF directory for reading Modeled after Linux readdir()
Detailed Description
LIF Disk Format.
Edit History
[1.0] [Mike Gore] Initial revision of file.
Copyright 2014-2017 Mike Gore, Inc. All rights reserved.
Function Documentation
int lif_closedir (lifdir_t * DIR)
Close LIF directory Modeled after Linux closedir()
Parameters
in *DIR pointer to LIF Volume/Directoy structure
Returns
0 on sucesss, -1 on error
Definition at line 25 of file format.c.
Referenced by lif_dir().
long lif_create_image (char * name, char * label, long dirsecs, long sectors)
Create LIF disk image This can take a while to run.
Parameters
in name LIF disk image name
in label LIF Volume Label name
in dirsecs Number of LIF directory sectors
in sectors total disk image size in sectors
Returns
bytes writting to disk image
Setup Volume Header
Current Date
Opne disk image for writting
Initial file position
Allocate working buffer for all writes
store Volume data into buffer
File type of 0xffff is last directory entry
FIXME this is the default that the HPdrive project uses, not sure of this
Zero out remining disk image
Definition at line 205 of file format.c.
Referenced by format_drives(), and gpib_tests().
int lif_dir (char * name)
Display a LIF image file directory.
Parameters
in name LIF disk image name -1 on error or number of files found
Definition at line 160 of file format.c.
Referenced by gpib_tests().
long lif_filelength (DirEntryType * DE)
get LIF file size from directory entry
Parameters
in name LIF disk image name
in DE LIF directory entry void
Definition at line 147 of file format.c.
Referenced by lif_dir().
void lif_filename (char * name, DirEntryType * DE)
get LIF file name from directory entry
Parameters
in name LIF disk image name
in DE LIF directory entry void
Definition at line 129 of file format.c.
Referenced by lif_dir().
lifdir_t* lif_opendir (char * name)
Initial file position
Definition at line 40 of file format.c.
Referenced by lif_dir().
DirEntryType* lif_readdir (lifdir_t * DIR)
Initial file position
Definition at line 83 of file format.c.
Referenced by lif_dir().
Variable Documentation
lifdir_t _lifdir [static]
Open LIF directory for reading Modeled after Linux opendir()
Parameters
in *name file name of LIF image
Returns
NULL on error, lifdir_t pointer to LIF Volume/Directoy structure on sucesss
Definition at line 39 of file format.c.
DirEntryType _lifent [static]
Open LIF directory for reading Modeled after Linux readdir()
Parameters
in *DIR to LIF Volume/Diractoy structure
Returns
DirEntryType filled with directory structure, or NULL on error of end of Directory
Definition at line 82 of file format.c.