gpib/gpib_tests.c File Reference
GPIB diagnostic tests for HP85 disk emulator project for AVR.
#include `user_config.h`
#include `defines.h`
#include `gpib_hal.h`
#include `gpib.h`
#include `gpib_task.h`
#include `amigo.h`
#include `ss80.h`
#include `gpib_tests.h`
#include `stringsup.h`
#include `printer.h`
#include `lifutils.h`
#include `debug.h`
Functions
void gpib_help (int full)
Help Menu for User invoked GPIB functions and tasks See: int gpib_tests(char *str)
int gpib_tests (int argc, char *argv[])
GPIB user tests User invoked GPIB functions and tasks.
Detailed Description
GPIB diagnostic tests for HP85 disk emulator project for AVR.
Edit History
[1.0] [Mike Gore] Initial revision of file.
Copyright 2014-2020 Mike Gore, All rights reserved. GPL
See also
 http://github.com/magore/hp85disk
 http://github.com/magore/hp85disk/COPYRIGHT.md for Copyright details
Function Documentation
gpib_help()
void gpib_help (int full)
Help Menu for User invoked GPIB functions and tasks See: int gpib_tests(char *str)
Returns
void
Definition at line 33 of file gpib_tests.c.
Referenced by gpib_tests(), and help().
gpib_tests()
int gpib_tests (int argc, char * argv[])
GPIB user tests User invoked GPIB functions and tasks.
Returns
1 matched token, 0 if not
Definition at line 68 of file gpib_tests.c.
Referenced by user_task().