gpib/gpib_task.h File Reference
High level GPIB command handler for HP85 disk emulator project for AVR.
#include <user_config.h>
#include `drives.h`
Functions
void gpib_file_init (void)
Read Configuration File.
void gpib_log (char *str)
Log GPIB transactions.
int SS80_is_MLA (int address)
Check if SS80 listening address.
int SS80_is_MTA (int address)
Check if SS80 talking address.
int SS80_is_MSA (int address)
Check if SS80 secondary address.
int AMIGO_is_MLA (int address)
int AMIGO_is_MTA (int address)
int AMIGO_is_MSA (int address)
int PRINTER_is_MLA (int address)
Check if PRINTER listening address.
int PRINTER_is_MTA (int address)
Check if PRINTER talking address.
int PRINTER_is_MSA (int address)
Check if PRINTER secondary address.
uint16_t gpib_trace_read_byte (void)
void gpib_trace_task (char *name, int detail)
Trace GPIB activity passively - saving to a log file.
uint16_t gpib_error_test (uint16_t val)
Check for GPIB errors and timeouts.
void gpib_init_devices (void)
Initialize ALL emulated devices SS80, AMIGO and printer.
uint16_t GPIB_COMMANDS (uint16_t val, uint8_t unread)
Process all GPIB Secondary Commands.
void gpib_task (void)
Top most main GPIB device emulator task. This is main() for GPIB state machine loop All tasks are dispatched from here.
int Send_Identify (uint8_t ch, uint16_t ID)
Send drive identify- 2 bytes.
int GPIB (uint8_t ch)
Main GPIB command handler Commands 0x00 .. 0x1f.
int GPIB_LISTEN (uint8_t ch)
Process all GPIB Listen commands.
int GPIB_TALK (uint8_t ch)
Process all GPIB Talk commands.
int GPIB_SECONDARY_ADDRESS (uint8_t ch)
Process all GPIB Secondary Addresses.
void listen_cleanup (void)
Called when the listen address changes.
void talk_cleanup (void)
Called when the GPIB talk address changes.
void DumpData (unsigned char *ptr, int length)
HEX and ASCII dump of string in human-readable format.
Detailed Description
High level GPIB command handler for HP85 disk emulator project for AVR.
Edit History
[1.0] [Mike Gore] Initial revision of file.
Copyright 2014-2020 Mike Gore, All rights reserved. GPL
See also
http://github.com/magore/hp85disk
http://github.com/magore/hp85disk/COPYRIGHT.md for Copyright details
Function Documentation
AMIGO_is_MLA()
int AMIGO_is_MLA (int address)
Referenced by GPIB(), GPIB_COMMANDS(), GPIB_LISTEN(), and SS80_is_MSA().
AMIGO_is_MSA()
int AMIGO_is_MSA (int address)
Referenced by GPIB_SECONDARY_ADDRESS(), and SS80_is_MSA().
AMIGO_is_MTA()
int AMIGO_is_MTA (int address)
Referenced by GPIB_COMMANDS(), GPIB_TALK(), and SS80_is_MSA().
DumpData()
void DumpData (unsigned char * ptr, int length)
HEX and ASCII dump of string in human-readable format.
Used only for debugging
Parameters
in ptr data
in length length of data string
Returns
void
Definition at line 975 of file gpib_task.c.
GPIB()
int GPIB (uint8_t ch)
Main GPIB command handler Commands 0x00 .. 0x1f.
We are only ever called with ATN=1 commands.
ch = GPIB command and status (ie it has the ATN_FLAG set).
Notes: We track any device states and call handelers.
Parameters
in ch 8 bit command
Returns
0 on sucess
GPIB error flags on fail
See also
gpib.h ERROR_MASK defines for a full list.
Parallel Poll Configure TODO
Parallel Poll Unconfigure TODO
Todo
Todo FIXME
Selected Device Clear
Note: Suposed to be unsupported in SS80 - pg 4-2 CS80 3-4
Todo
Todo FIXME
(Universal) Device Clear
Todo
Todo Fixme
Definition at line 613 of file gpib_task.c.
Referenced by gpib_task().
GPIB_COMMANDS()
uint16_t GPIB_COMMANDS (uint16_t val, uint8_t unread)
Process all GPIB Secondary Commands.
Dispatch emulator handler based on address
if unread is true we `unread` val so the corresponding device emulator can process it.
Unread allow us to write each emulator as a pure function.
Parameters
in val GPIB secondary command and control flags.
in unread if 1 unread val prior to emulator call.
Returns
GPIB status from emulator command.
0 if no emulator command processed.
talking ?
listening ?
Definition at line 365 of file gpib_task.c.
Referenced by gpib_task().
gpib_error_test()
uint16_t gpib_error_test (uint16_t val)
Check for GPIB errors and timeouts.
Reset GPIB bus on IFC or user keypress
Display debug messages if debuglevel permits.
Check media insert state
Parameters
val command or data byte and control or error flags.
Lower 8 bits: Data or Command.
If ATN is LOW then we strip parity from the byte.
Upper 8 bits: Status and Errors.
See also
gpib.h _FLAGS defines for a full list.
An error implies the data byte can't be trusted
Control Line Flags.
EOI_FLAG
SRQ_FLAG
ATN_FLAG
REN_FLAG
PP_FLAG
Error Flags:
IFC_FLAG
EOI_FLAG
ATN_FLAG
See also
gpib.h _FLAGS defines for a full list.
Returns
val
ABORT flag on user keypress
IFC is and important state so display it for most messages
Bus Clear, reseat all states, etc
Todo
Todo do we want to always exit here ? low level GPIB functions are still useful even without a DISK
Definition at line 271 of file gpib_task.c.
Referenced by gpib_task().
gpib_file_init()
void gpib_file_init (void)
Read Configuration File.
set any compile time defaults - but only those NOT already set by the config file
Definition at line 41 of file gpib_task.c.
Referenced by main().
gpib_init_devices()
void gpib_init_devices (void)
Initialize ALL emulated devices SS80, AMIGO and printer.
Used at power up, Bus IFC or user aborts
Returns
void
Definition at line 334 of file gpib_task.c.
Referenced by gpib_error_test(), gpib_task(), gpib_trace_task(), and task().
GPIB_LISTEN()
int GPIB_LISTEN (uint8_t ch)
Process all GPIB Listen commands.
We only ever called with ATN=1 commands.
Parameters
in ch 8 bit listen command
Returns
0
NOTE: we must track the `addressed state` of each device so we can determine its state - ie: command vs Secondary states
Universal Unlisten
NULL creates a file named based on date and time
Definition at line 732 of file gpib_task.c.
Referenced by gpib_task().
gpib_log()
void gpib_log (char * str)
Log GPIB transactions.
Parameters
str message to log
Returns
void
Definition at line 65 of file gpib_task.c.
GPIB_SECONDARY_ADDRESS()
int GPIB_SECONDARY_ADDRESS (uint8_t ch)
Process all GPIB Secondary Addresses.
We only ever called with ATN=1 commands. Secondary Address, talking == UNT
Parameters
in ch 8 bit secondary address.
Returns
0
NOTE: We now know that ch >= 0x60 && ch <= 0x7f Previous tests ensure this fact is true and because CMD_MASK == 0x7f
note: any errors will reset lastcmd Universal Talk mode Treat this as a Secondary Address ? SS80 Ident 4-31 If we have our secondary address then send IDENT
ch = secondary address
Definition at line 886 of file gpib_task.c.
Referenced by gpib_task().
GPIB_TALK()
int GPIB_TALK (uint8_t ch)
Process all GPIB Talk commands.
We only ever called with ATN=1 commands.
Parameters
in ch 8 bit talk command
Returns
0
NOTE: we must track the `addressed state` of each device so we can determine its state - ie: command vs Secondary states save talking state
Universal Untalk
Definition at line 806 of file gpib_task.c.
Referenced by gpib_task().
gpib_task()
void gpib_task (void)
Top most main GPIB device emulator task. This is main() for GPIB state machine loop All tasks are dispatched from here.
Initializes BUS, Devices, State.
Reads and processes GPIB control or data bytes and calls emulator task.
Returns
void
GPIB commands with ATN set (COMMANDS)
GPIB listen
GPIB talk
GPIB secondary Note: We know ch >= 0x60 && ch <= 0x7f because of previous tests
We have to keep track of secondary address that may happen out of order with older AMIGO protocol this method works for SS80 as well
GPIB_COMMANDS does most of the work
GPIB commands without ATN set (DATA)
GPIB_COMMANDS does most of the work
Definition at line 450 of file gpib_task.c.
Referenced by gpib_tests(), and task().
gpib_trace_read_byte()
uint16_t gpib_trace_read_byte (void)
gpib_trace_task()
void gpib_trace_task (char * name, int detail)
Trace GPIB activity passively - saving to a log file.
Parameters
in name file name to save to
in detail if non-zero do full handshake trace
We use the natural GPIB handshaking to slow GPIB talker/listeners so we can keep up
A keypress will exit the trace and close the file
Parameters
name File name to save log file to.
Returns
void Exit on Key Press
Definition at line 195 of file gpib_task.c.
Referenced by gpib_tests().
listen_cleanup()
void listen_cleanup (void)
Called when the listen address changes.
Used to cleanup or close at the end of any listen address transition.
Also called when GPIB bus reset or unlisten. For now we just use this to close printer capture
Returns
void
Definition at line 938 of file gpib_task.c.
Referenced by GPIB_LISTEN(), and gpib_state_init().
PRINTER_is_MLA()
int PRINTER_is_MLA (int address)
Check if PRINTER listening address.
Used at power up, Bus IFC or user aborts
Returns
1 if true or 0
Definition at line 150 of file gpib_task.c.
Referenced by GPIB_COMMANDS(), GPIB_LISTEN(), GPIB_TALK(), gpib_task(), and PRINTER_COMMANDS().
PRINTER_is_MSA()
int PRINTER_is_MSA (int address)
Check if PRINTER secondary address.
Used at power up, Bus IFC or user aborts
Returns
1 if true or 0
Definition at line 174 of file gpib_task.c.
PRINTER_is_MTA()
int PRINTER_is_MTA (int address)
Check if PRINTER talking address.
Used at power up, Bus IFC or user aborts
Returns
1 if true or 0
Definition at line 162 of file gpib_task.c.
Referenced by GPIB_COMMANDS(), GPIB_TALK(), and PRINTER_COMMANDS().
Send_Identify()
int Send_Identify (uint8_t ch, uint16_t ID)
Send drive identify- 2 bytes.
References
Transparent Command IDENT
SS80 4-31
CS80 pg 4-27, 3-10
A11
Parameters
in ch channel
Returns
0 on GPIB error returns error flags
See also
gpib.h ERROR_MASK for a full list.
Definition at line 580 of file gpib_task.c.
Referenced by GPIB_SECONDARY_ADDRESS().
SS80_is_MLA()
int SS80_is_MLA (int address)
Check if SS80 listening address.
Used at power up, Bus IFC or user aborts
Returns
1 if true or 0
Definition at line 76 of file gpib_task.c.
Referenced by GPIB(), GPIB_COMMANDS(), GPIB_LISTEN(), and SS80_COMMANDS().
SS80_is_MSA()
int SS80_is_MSA (int address)
Check if SS80 secondary address.
Used at power up, Bus IFC or user aborts
Returns
1 if true or 0
Definition at line 100 of file gpib_task.c.
Referenced by GPIB_SECONDARY_ADDRESS().
SS80_is_MTA()
int SS80_is_MTA (int address)
Check if SS80 talking address.
Used at power up, Bus IFC or user aborts
Returns
1 if true or 0
Definition at line 88 of file gpib_task.c.
Referenced by GPIB(), GPIB_COMMANDS(), GPIB_TALK(), and SS80_COMMANDS().
talk_cleanup()
void talk_cleanup (void)
Called when the GPIB talk address changes.
Used to cleanup or close at the end of a talk transation.
Also called when GPIB bus reset or untalk.
Not used in this emulator.
Returns
void
Definition at line 963 of file gpib_task.c.
Referenced by gpib_state_init(), and GPIB_TALK().