gpib/gpib_hal.c File Reference
GPIB emulator hardwware layer for HP85 disk emulator project for AVR.
#include `gpib_hal.h`
#include `gpib.h`
#include `fatfs.h`
#include `posix.h`
#include `defines.h`
#include `debug.h`
Functions
void gpib_timer_init ()
Install GPIB timers, Elapsed time and Timeout tasks.
uint8_t reverse_8bits (uint8_t mask)
Reverse the bits in an 8 bit value.
void ppr_set (uint8_t mask)
Enable or Disable Parallel Poll Response bits - PPR.
uint8_t ppr_reg ()
Return PPR enable register.
void ppr_init ()
Reset PPR enable register - all disable..
void ppr_bit_set (uint8_t bit)
Enable hardware PPR response for a given device.
void ppr_bit_clr (uint8_t bit)
Disbale hardware PPR response for a given device.
FRESULT dbf_open (FIL *fp, const TCHAR *path, BYTE mode)
Wrapper for FatFs f_open() that can displays errors.
FRESULT dbf_read (FIL *fp, void *buff, UINT btr, UINT *br)
Wrapper for FatFs f_read() that can display errors.
FRESULT dbf_write (FIL *fp, const void *buff, UINT btw, UINT *bw)
wrapper for FatFs f_write() that can display errors.
FRESULT dbf_lseek (FIL *fp, DWORD ofs)
Wrapper of FatFs f_seek() that can display errors.
FRESULT dbf_close (FIL *fp)
Wrapper of FatFs f_close() that can display errors.
int dbf_open_read (char *name, uint32_t pos, void *buff, int size, int *errors)
Open, Seek, Read data and Close FatFs functions.
int dbf_open_write (char *name, uint32_t pos, void *buff, int size, int *errors)
Open, Seek, Write data and Close FatFs functions.
Variables
gpib_t gpib_timer
static uint8_t _ppr_reg
Parallel Poll Response bit mask.
Detailed Description
GPIB emulator hardwware layer for HP85 disk emulator project for AVR.
Edit History
[1.0] [Mike Gore] Initial revision of file.
Copyright 2014-2020 Mike Gore, All rights reserved. GPL
See also
 http://github.com/magore/hp85disk
 http://github.com/magore/hp85disk/COPYRIGHT.md for Copyright details
Function Documentation
dbf_close()
FRESULT dbf_close (FIL * fp)
Wrapper of FatFs f_close() that can display errors.
Parameters
 in fp FatFs FIL * pointer.
See also
ff.h.
Returns
FRESULT dbf_close (FIL* fp)
Definition at line 287 of file gpib_hal.c.
Referenced by dbf_open_read(), and dbf_open_write().
dbf_lseek()
FRESULT dbf_lseek (FIL * fp, DWORD ofs)
Wrapper of FatFs f_seek() that can display errors.
Parameters
 in fp FatFs FIL * pointer.
 in ofs seek offset.
See also
ff.h.
Returns
FRESULT
Definition at line 266 of file gpib_hal.c.
Referenced by dbf_open_read(), and dbf_open_write().
dbf_open()
FRESULT dbf_open (FIL * fp, const TCHAR * path, BYTE mode)
Wrapper for FatFs f_open() that can displays errors.
Parameters
 in fp FatFs FIL handle
 in path path name of file to open
 in mode FatFs open mode flags
See also
ff.h
Returns
FRESULT f_open(fp,path, mode);
Definition at line 195 of file gpib_hal.c.
Referenced by dbf_open_read(), and dbf_open_write().
dbf_open_read()
int dbf_open_read (char * name, uint32_t pos, void * buff, int size, int * errors)
Open, Seek, Read data and Close FatFs functions.
Parameters
 in name File name to open.
 in pos file offset.
 out buff buffer to read data into.
 in size bytes to read.
 in errors error flags pointer.
Returns
bytes actually read.
-1 on error.
See also
: ff.h.
Returns
FRESULT
SEEK
Definition at line 314 of file gpib_hal.c.
Referenced by SS80_locate_and_read().
dbf_open_write()
int dbf_open_write (char * name, uint32_t pos, void * buff, int size, int * errors)
Open, Seek, Write data and Close FatFs functions.
Parameters
 in name File name to open.
 in pos file offset.
 in buff buffer to write.
 in size bytes to write.
 in errors error flags pointer.
Returns
bytes actually written.
-1 on error.
See also
: ff.h.
Returns
FRESULT
SEEK
Definition at line 379 of file gpib_hal.c.
Referenced by SS80_locate_and_write().
dbf_read()
FRESULT dbf_read (FIL * fp, void * buff, UINT btr, UINT * br)
Wrapper for FatFs f_read() that can display errors.
Parameters
 in fp FatFs FIL handle.
 in buff buffer to read data into.
 in btr bytes to read.
 in br bytes actually read.
See also
ff.h
Returns
FRESULT f_read (FIL* fp, void* buff, UINT btr, UINT* br)
Definition at line 220 of file gpib_hal.c.
Referenced by dbf_open_read().
dbf_write()
FRESULT dbf_write (FIL * fp, const void * buff, UINT btw, UINT * bw)
wrapper for FatFs f_write() that can display errors.
Parameters
 in fp FatFs FIL handle.
 in buff buffer to write data from.
 in btw bytes to write.
 in bw bytes actually written.
See also
ff.h
Returns
FRESULT f_write (FIL* fp, void* buff, UINT btw, UINT* bw)
Definition at line 244 of file gpib_hal.c.
Referenced by dbf_open_write().
gpib_timer_init()
void gpib_timer_init ()
Install GPIB timers, Elapsed time and Timeout tasks.
===================================================
Has some platform dependent code.
Returns
void
Definition at line 29 of file gpib_hal.c.
Referenced by main().
ppr_bit_clr()
void ppr_bit_clr (uint8_t bit)
Disbale hardware PPR response for a given device.
Parameters
 in bit PPR bit to disable.
HI = PPR bus LOW.
LOW = PPR bus FLOAT.
Device PPR bits are specified in reversed order in GPIB.
0 controlls GPIB D8.
1 controlls GPIB D7.
2 controlls GPIB D6.
3 controlls GPIB D5.
4 controlls GPIB D4.
5 controlls GPIB D3.
6 controlls GPIB D2.
7 controlls GPIB D1.
Returns
void
FIXME _ppr_reg = 0;
Definition at line 177 of file gpib_hal.c.
Referenced by gpib_disable_PPR(), and gpib_tests().
ppr_bit_set()
void ppr_bit_set (uint8_t bit)
Enable hardware PPR response for a given device.
Parameters
 in bit PPR bit to enable.
HI = PPR bus LOW.
LOW = PPR bus FLOAT.
Device PPR bits are specified in reversed order in GPIB.
0 controlls GPIB D8.
1 controlls GPIB D7.
2 controlls GPIB D6.
3 controlls GPIB D5.
4 controlls GPIB D4.
5 controlls GPIB D3.
6 controlls GPIB D2.
7 controlls GPIB D1.
Returns
void
FIXME _ppr_reg = 0;
Definition at line 153 of file gpib_hal.c.
Referenced by gpib_enable_PPR(), and gpib_tests().
ppr_init()
void ppr_init ()
Reset PPR enable register - all disable..
Hides the register access implimentation from the upper level.
Returns
void
Definition at line 126 of file gpib_hal.c.
Referenced by gpib_state_init(), and gpib_tests().
ppr_reg()
uint8_t ppr_reg ()
Return PPR enable register.
Hides the register access implimentation from the upper level.
Returns
PPR enable register
optionally reverse bit order in PPR mask Used only of PPR circuit board PPR bits are not reversed in hardware
Definition at line 109 of file gpib_hal.c.
Referenced by gpib_detect_PP(), gpib_disable_PPR(), and gpib_enable_PPR().
ppr_set()
void ppr_set (uint8_t mask)
Enable or Disable Parallel Poll Response bits - PPR.
V1 hardware reversed bits in hardware. V2 in software
Aside: Software PPR detection is impractical - timing is sub microsecond. That is why both V1 and V2 boards you hardware detection
Mask Bits.
HI = PPR bus LOW.
LOW = PPR bus FLOAT.
Device PPR bits are specified in reversed order in GPIB.
0 controlls GPIB D8.
1 controlls GPIB D7.
2 controlls GPIB D6.
3 controlls GPIB D5.
4 controlls GPIB D4.
5 controlls GPIB D3.
6 controlls GPIB D2.
7 controlls GPIB D1.
Parameters
 in mask Parallel Poll Response bits to enable or disable
Returns
void
optionally reverse bit order in PPR mask Used only of PPR circuit board PPR bits are not reversed in hardware
Definition at line 88 of file gpib_hal.c.
Referenced by gpib_tests(), ppr_bit_clr(), ppr_bit_set(), and ppr_init().
reverse_8bits()
uint8_t reverse_8bits (uint8_t mask)
Reverse the bits in an 8 bit value.
GPIB Parallel poll response bits are reversed.
GPIB D8 controls first device.
GPIB D1 controls last device.
Parameters
 in mask bit mask to reverse.
Returns
reversed bits
Definition at line 49 of file gpib_hal.c.
Referenced by ppr_reg(), and ppr_set().
Variable Documentation
_ppr_reg
uint8_t _ppr_reg [static]
Parallel Poll Response bit mask.
Definition at line 39 of file gpib_hal.c.
Referenced by ppr_bit_clr(), ppr_bit_set(), ppr_reg(), and ppr_set().
gpib_timer
gpib_t gpib_timer
Definition at line 22 of file gpib_hal.c.
Referenced by gpib_timeout_set(), gpib_timeout_test(), gpib_timer_elapsed_begin(), gpib_timer_elapsed_end(), gpib_timer_reset(), and gpib_timer_task().