gpib/gpib_task.c File Reference
High level GPIB command handler for HP85 disk emulator project for AVR8.
#include `user_config.h`
*
#include `defines.h`
*
#include `drives.h`
*
#include `gpib_hal.h`
*
#include `gpib.h`
*
#include `gpib_task.h`
*
#include `amigo.h`
*
#include `ss80.h`
*
#include `printer.h`
*
#include `posix.h`
*
Functions
void gpib_file_init ()
Read Configuration File.
void gpib_log (char *str)
int SS80_is_MLA (int address)
Check if SS80 listening address.
int SS80_is_MTA (int address)
Check if SS80 talking address.
int SS80_is_MSA (int address)
Check if SS80 secondary address.
int AMIGO_is_MLA (int address)
Check if AMIGO listening address.
int AMIGO_is_MTA (int address)
Check if AMIGO talking address.
int AMIGO_is_MSA (int address)
Check if AMIGO secondary address.
int PRINTER_is_MLA (int address)
Check if PRINTER listening address.
int PRINTER_is_MTA (int address)
Check if PRINTER talking address.
int PRINTER_is_MSA (int address)
Check if PRINTER secondary address.
void gpib_trace_task (char *name)
Trace GPIB activity passively - saving to a log file.
uint16_t gpib_error_test (uint16_t val)
Check for GPIB errors and timeouts.
void gpib_init_devices (void)
Initialize ALL emulated devices SS80, AMIGO and printer.
uint16_t GPIB_COMMANDS (uint16_t val, uint8_t unread)
Process all GPIB Secondary Commands.
void gpib_task (void)
Top most main GPIB device emulator task. This is main() for GPIB state machine loop All tasks are dispatched from here.
int Send_Identify (uint8_t ch, uint16_t ID)
Send drive identify- 2 bytes.
int GPIB (uint8_t ch)
Main GPIB command handler Commands 0x00 .. 0x1f.
int GPIB_LISTEN (uint8_t ch)
Process all GPIB Listen commands.
int GPIB_TALK (uint8_t ch)
Process all GPIB Talk commands.
int GPIB_SECONDARY_ADDRESS (uint8_t ch)
Process all GPIB Secondary Addresses.
void listen_cleanup ()
Called when the listen address changes.
void talk_cleanup ()
Called when the GPIB talk address changes.
void DumpData (unsigned char *ptr, int length)
HEX and ASCII dump of string in human-readable format.
Variables
char cfgfile [] = `/hpdisk.cfg`
Config file name.
FIL fp_file
int debuglevel = 1
Debug flag - used to log GPIB and emulator messages.
FILE * gpib_log_fp
GPIB log file handel.
Detailed Description
High level GPIB command handler for HP85 disk emulator project for AVR8.
Edit History
[1.0] [Mike Gore] Initial revision of file.
Copyright 2014 Mike Gore, Inc. All rights reserved.
Function Documentation
int AMIGO_is_MLA (int address)
Check if AMIGO listening address.
Used at power up, Bus IFC or user aborts
Returns
1 if true or 0
Definition at line 102 of file gpib_task.c.
Referenced by Amigo_Command(), AMIGO_COMMANDS(), Amigo_Execute(), amigo_todo(), amigo_todo_op(), GPIB(), GPIB_COMMANDS(), and GPIB_LISTEN().
int AMIGO_is_MSA (int address)
Check if AMIGO secondary address.
Used at power up, Bus IFC or user aborts
Returns
1 if true or 0
Definition at line 125 of file gpib_task.c.
Referenced by GPIB_SECONDARY_ADDRESS().
int AMIGO_is_MTA (int address)
Check if AMIGO talking address.
Used at power up, Bus IFC or user aborts
Returns
1 if true or 0
Definition at line 114 of file gpib_task.c.
Referenced by Amigo_Command(), AMIGO_COMMANDS(), Amigo_Execute(), amigo_todo(), amigo_todo_op(), GPIB_COMMANDS(), and GPIB_TALK().
void DumpData (unsigned char * ptr, int length)
HEX and ASCII dump of string in human-readable format.
Used only for debugging
Parameters
in ptr data
in length length of data string
Returns
void
Definition at line 960 of file gpib_task.c.
int GPIB (uint8_t ch)
Main GPIB command handler Commands 0x00 .. 0x1f.
We only ever called with ATN=1 commands.
ch = GPIB command and status (ie it has the ATN_FLAG set).
Notes: We track any device states and call handelers.
Parameters
in ch 8 bit command
Returns
0 on sucess
GPIB error flags on fail
See also
gpib.h ERROR_MASK defines for a full list.
Todo
Todo TODO
Parallel Poll Configure
Parallel Poll Unconfigure
Todo
Todo FIXME
Selected Device Clear
Note: Suposed to be unsupported in SS80 - pg 4-2 CS80 3-4
Todo
Todo FIXME
(Universal) Device Clear
Todo
Todo Fixme
Definition at line 600 of file gpib_task.c.
Referenced by gpib_task().
uint16_t GPIB_COMMANDS (uint16_t val, uint8_t unread)
Process all GPIB Secondary Commands.
Dispatch emulator handler based on address
if unread is true we `unread` val so the corresponding device emulator can process it.
Unread allow us to write each emulator as a pure function.
Parameters
in val GPIB secondary command and control flags.
in unread if 1 unread val prior to emulator call.
Returns
GPIB status from emulator command.
0 if no emulator command processed.
talking ?
listening ?
Definition at line 348 of file gpib_task.c.
Referenced by gpib_task().
uint16_t gpib_error_test (uint16_t val)
Check for GPIB errors and timeouts.
Reset GPIB bus on IFC or user keypress
Display debug messages if debuglevel permits.
Check media insert state
Parameters
val command or data byte and control or error flags.
Lower 8 bits: Data or Command.
If ATN is LOW then we strip parity from the byte.
Upper 8 bits: Status and Errors.
See also
gpib.h _FLAGS defines for a full list.
An error implies the data byte can't be trusted
Control Line Flags.
EOI_FLAG
SRQ_FLAG
ATN_FLAG
REN_FLAG
PP_FLAG
Error Flags:
IFC_FLAG
EOI_FLAG
ATN_FLAG
See also
gpib.h _FLAGS defines for a full list.
Returns
val
ABORT flag on user keypress
Todo
Todo do we want to always exit here ? low level GPIB functions are still useful even without a DISK
Definition at line 259 of file gpib_task.c.
Referenced by gpib_task().
void gpib_file_init (void)
Read Configuration File.
Definition at line 39 of file gpib_task.c.
Referenced by main().
void gpib_init_devices (void)
Initialize ALL emulated devices SS80, AMIGO and printer.
Used at power up, Bus IFC or user aborts
Returns
void
Definition at line 319 of file gpib_task.c.
Referenced by gpib_error_test(), gpib_task(), and gpib_trace_task().
int GPIB_LISTEN (uint8_t ch)
Process all GPIB Listen commands.
We only ever called with ATN=1 commands.
Parameters
in ch 8 bit listen command
Returns
0
NOTE: we must track the `addressed state` of each device so we can determine its state - ie: command vs Secondary states
Universal Unlisten
Definition at line 718 of file gpib_task.c.
Referenced by gpib_task().
void gpib_log (char * str)
Definition at line 55 of file gpib_task.c.
Referenced by gpib_decode(), and gpib_trace_task().
int GPIB_SECONDARY_ADDRESS (uint8_t ch)
Process all GPIB Secondary Addresses.
We only ever called with ATN=1 commands. Secondary Address, talking == UNT
Parameters
in ch 8 bit secondary address.
Returns
0
NOTE: We now know that ch >= 0x60 && ch <= 0x7f Previous tests ensure this fact is true and because CMD_MASK == 0x7f
note: any errors will reset lastcmd Universal Talk mode Treat this as a Secondary Address ? SS80 Ident 4-31 If we have our secondary address then send IDENT
ch = secondary address
Definition at line 871 of file gpib_task.c.
Referenced by gpib_task().
int GPIB_TALK (uint8_t ch)
Process all GPIB Talk commands.
We only ever called with ATN=1 commands.
Parameters
in ch 8 bit talk command
Returns
0
NOTE: we must track the `addressed state` of each device so we can determine its state - ie: command vs Secondary states save talking state
Universal Untalk
Definition at line 791 of file gpib_task.c.
Referenced by gpib_task().
void gpib_task (void)
Top most main GPIB device emulator task. This is main() for GPIB state machine loop All tasks are dispatched from here.
Initializes BUS, Devices, State.
Reads and processes GPIB control or data bytes and calls emulator task.
Returns
void
GPIB commands with ATN set
GPIB listen
GPIB talk
GPIB secondary Note: We know ch >= 0x60 && ch <= 0x7f because of previous tests
We have to keep track of secondary address that may happen out of order with older AMIGO protocol this method works for SS80 as well
GPIB_COMMANDS does most of the work
GPIB commands without ATN set
GPIB_COMMANDS does most of the work
Definition at line 433 of file gpib_task.c.
Referenced by gpib_tests(), and task().
void gpib_trace_task (char * name)
Trace GPIB activity passively - saving to a log file.
We use the natural GPIB handshaking to slow GPIB talker/listeners so we can keep up
A keypress will exit the trace and close the file
Parameters
name File name to save log file to.
Returns
void Exit on Key Press
Definition at line 179 of file gpib_task.c.
Referenced by gpib_tests().
void listen_cleanup (void)
Called when the listen address changes.
Used to cleanup or close at the end of a listen transation.
Also called when GPIB bus reset or unlisten.
Returns
void
Definition at line 923 of file gpib_task.c.
Referenced by GPIB_LISTEN(), and gpib_state_init().
int PRINTER_is_MLA (int address)
Check if PRINTER listening address.
Used at power up, Bus IFC or user aborts
Returns
1 if true or 0
Definition at line 137 of file gpib_task.c.
Referenced by GPIB_COMMANDS(), GPIB_LISTEN(), GPIB_TALK(), gpib_task(), and PRINTER_COMMANDS().
int PRINTER_is_MSA (int address)
Check if PRINTER secondary address.
Used at power up, Bus IFC or user aborts
Returns
1 if true or 0
Definition at line 161 of file gpib_task.c.
int PRINTER_is_MTA (int address)
Check if PRINTER talking address.
Used at power up, Bus IFC or user aborts
Returns
1 if true or 0
Definition at line 149 of file gpib_task.c.
Referenced by GPIB_COMMANDS(), GPIB_TALK(), and PRINTER_COMMANDS().
int Send_Identify (uint8_t ch, uint16_t ID)
Send drive identify- 2 bytes.
References
Transparent Command IDENT
SS80 4-31
CS80 pg 4-27, 3-10
A11
Parameters
in ch channel
Returns
0 on GPIB error returns error flags
See also
gpib.h ERROR_MASK for a full list.
Definition at line 567 of file gpib_task.c.
Referenced by GPIB_SECONDARY_ADDRESS().
int SS80_is_MLA (int address)
Check if SS80 listening address.
Used at power up, Bus IFC or user aborts
Returns
1 if true or 0
Definition at line 66 of file gpib_task.c.
Referenced by GPIB(), GPIB_COMMANDS(), GPIB_LISTEN(), and SS80_COMMANDS().
int SS80_is_MSA (int address)
Check if SS80 secondary address.
Used at power up, Bus IFC or user aborts
Returns
1 if true or 0
Definition at line 90 of file gpib_task.c.
Referenced by GPIB_SECONDARY_ADDRESS().
int SS80_is_MTA (int address)
Check if SS80 talking address.
Used at power up, Bus IFC or user aborts
Returns
1 if true or 0
Definition at line 78 of file gpib_task.c.
Referenced by GPIB(), GPIB_COMMANDS(), GPIB_TALK(), and SS80_COMMANDS().
void talk_cleanup (void)
Called when the GPIB talk address changes.
Used to cleanup or close at the end of a talk transation.
Also called when GPIB bus reset or untalk.
Not used in this emulator.
Returns
void
Definition at line 948 of file gpib_task.c.
Referenced by gpib_state_init(), and GPIB_TALK().
Variable Documentation
char cfgfile[] = `/hpdisk.cfg`
Config file name.
Definition at line 28 of file gpib_task.c.
Referenced by gpib_file_init().
int debuglevel = 1
Debug flag - used to log GPIB and emulator messages.
Definition at line 32 of file gpib_task.c.
Referenced by alloc_device(), amigo_buffered_read(), amigo_buffered_write(), amigo_chs_to_logical(), amigo_cmd_clear(), amigo_cmd_dsj(), amigo_cmd_wakeup(), Amigo_Command(), Amigo_Execute(), amigo_format(), amigo_overflow_check(), amigo_request_status(), amigo_send_logical_address(), amigo_send_status(), amigo_verify(), assign_value(), DisablePPR(), EnablePPR(), find_device(), GPIB(), gpib_assert_ifc(), gpib_assert_ren(), gpib_bus_init(), gpib_error_test(), gpib_file_init(), gpib_format_disk(), GPIB_LISTEN(), gpib_read_str(), GPIB_SECONDARY_ADDRESS(), gpib_state_init(), GPIB_TALK(), gpib_task(), gpib_tests(), gpib_unread(), gpib_write_byte(), gpib_write_str(), listen_cleanup(), main(), Parallel_Poll(), POSIX_Read_Config(), ppr_init(), printer_buffer(), printer_close(), PRINTER_COMMANDS(), printer_open(), receive_plot(), receive_plot_flush(), Send_Identify(), set_active_device(), SS80_Amigo_Clear(), SS80_cmd_seek(), SS80_Command_State(), SS80_COMMANDS(), SS80_describe(), SS80_error_return(), SS80_Execute_State(), SS80_increment(), SS80_init(), SS80_locate_and_read(), SS80_locate_and_write(), SS80_Report(), SS80_Selected_Device_Clear(), SS80_send_status(), SS80_Test(), and SS80_Transparent_State().
FIL fp_file
Definition at line 29 of file gpib_task.c.
FILE * gpib_log_fp
GPIB log file handel.
Log GPIB transactions.
Parameters
str message to log
Returns
void
Definition at line 35 of file gpib_task.c.
Referenced by gpib_file_init().