gpib/gpib.h File Reference
GPIB emulator for HP85 disk emulator project for AVR.
#include `user_config.h`
#include `hal.h`
#include `gpib_hal.h`
#include `posix.h`
Macros
#define GPIB_BUS_SETTLE_DELAY 2
#define HTIMEOUT (500000L / GPIB_TASK_TIC_US)
This is the default BUS timeout of 0.5 Seconds in Microseconds.
#define EOI_FLAG 0x0100
bus flags
#define SRQ_FLAG 0x0200
#define ATN_FLAG 0x0400
#define REN_FLAG 0x0800
#define IFC_FLAG 0x1000
#define PP_FLAG 0x2000
BUS state flags.
#define TIMEOUT_FLAG 0x4000
#define BUS_ERROR_FLAG 0x8000
#define DAV_FLAG 0x2000
handshake flasg used in tracing
#define NRFD_FLAG 0x4000
#define NDAC_FLAG 0x8000
#define ERROR_MASK (IFC_FLAG | TIMEOUT_FLAG | BUS_ERROR_FLAG)
#define CONTROL_MASK (EOI_FLAG | SRQ_FLAG | ATN_FLAG | REN_FLAG)
#define DATA_MASK 0x00ff
#define CMD_MASK 0x007f
#define STATUS_MASK 0xff00
#define TRACE_ALL 1 /* trace all bus states durring a read */
arguments to gpib_read_byte
#define NO_TRACE 0 /* do not trace bus states durring a read */
#define GPIB_IOBUFF_LEN 512 /* Max length of RX/TX GPIB string */
Enumerations
enum { TRACE_DISABLE,
TRACE_READ,
TRACE_BUS
 }
GPIB read trace states.
enum {
GPIB_RX_START = 0,
GPIB_RX_WAIT_FOR_DAV_LOW,
GPIB_RX_DAV_IS_LOW,
GPIB_RX_WAIT_FOR_NDAC_HI,
GPIB_RX_WAIT_FOR_DAV_HI,
GPIB_RX_DAV_IS_HI,
GPIB_RX_FINISH,
GPIB_RX_ERROR,
GPIB_RX_DONE
 }
enum {
GPIB_TX_START = 0,
GPIB_TX_WAIT_READY,
GPIB_TX_PUT_DATA,
GPIB_TX_SET_DAV_LOW,
GPIB_TX_WAIT_FOR_NRFD_LOW,
GPIB_TX_WAIT_FOR_NDAC_HI,
GPIB_TX_SET_DAV_HI,
GPIB_TX_WAIT_FOR_DAV_HI,
GPIB_TX_FINISH,
GPIB_TX_ERROR,
GPIB_TX_DONE
 }
enum { GPIB_PP_IDLE = 0,
GPIB_PP_DETECTED
 }
Functions
void gpib_timer_elapsed_begin (void)
Start measuring time - used with hpib_timer_elapsed_end()
void gpib_timer_reset (void)
Reset elapsed and timeout timers Elapses and Timeout Timers.
void gpib_timer_elapsed_end (char *msg)
Display user message and time delta since gpib_timer_elapsed_begin() call.
void gpib_timer_task (void)
Main GPIB timer task called by low level interrup hander.
void gpib_timeout_set (uint32_t time)
Set GPIB timeout timer in units of GPIB_TASK_TIC_US.
uint8_t gpib_timeout_test (void)
Test GPIB timeout timer for timeout condition.
void gpib_bus_read_init (int busy)
Initialize GPIB Bus control lines for READ Despite the name this everywhere to setup read mode.
void gpib_bus_init (void)
Initialize/Release GPIB Bus control lines for powerup or IFC reset conditions.
void gpib_state_init (void)
Reset GPIB states and related variables.
void gpib_enable_PPR (int bit)
void gpib_disable_PPR (int bit)
Disable PPR (Parallel Poll Response) for a device.
uint8_t gpib_detect_PP (void)
Attempt to detect the Parallel Poll Reposnse state Used only for debugging - it is unlikely that we will catch this state V2 hardware - this does not work unless reading BUS.
void gpib_assert_ifc (void)
Assert Interface clear for 250us.
void gpib_assert_ren (unsigned char state)
Assert REN to put instrument in remote mode.
uint16_t gpib_unread (uint16_t ch)
GPIB ungets one character and all status states.
uint8_t gpib_bus_read (void)
Read GPIB data BUS only.
uint16_t gpib_control_pin_read (void)
Read GPIB control lines only FIXME V2 boards can only read pins enabled for read by the SN75162 FIXME We could add a test for read/write state ??
uint16_t gpib_handshake_pin_read (void)
Read GPIB handshake lines only FIXME: V2 boards can only read pins enabled for read by the SN75162 FIXME We could add a test for read/write state ??
uint16_t gpib_write_byte (uint16_t ch)
Send 1 byte and control line states to GPIB BUS.
uint16_t gpib_read_byte (int trace)
read 1 byte and control line status from GPIB BUS
void gpib_decode_header (FILE *fo)
Displays help for gpib_decode() function.
void gpib_trace_display (uint16_t status, int trace_state)
decode/display all control flags and data on the GPIB BUS
void gpib_decode (uint16_t ch)
Calls gpib_decode_str() and dosplays the result.
int gpib_read_str (uint8_t *buf, int size, uint16_t *status)
Read string from GPIB BUS - controlled by status flags.
int gpib_write_str (uint8_t *buf, int size, uint16_t *status)
Send string to GPIB BUS - controlled by status flags.
Variables
uint8_t gpib_iobuff [GPIB_IOBUFF_LEN]
common IO buffer for gpib_read_str() and gpib_write_str()
int debuglevel
Debug flag - used to log GPIB and emulator messages.
uint8_t talk31
uint8_t talking
gpib talk address
uint8_t talking_last
gpib last talk address
uint8_t listening
gpib listen address
uint8_t listening_last
gpib last listen address
uint8_t spoll
gpib serial poll status
uint16_t current
uint16_t lastcmd
uint8_t secondary
gpib secondary
uint8_t device
Detailed Description
GPIB emulator for HP85 disk emulator project for AVR.
Edit History
[1.0] [Mike Gore] Initial revision of file.
Copyright 2014-2020 Mike Gore, All rights reserved. GPL
See also
 http://github.com/magore/hp85disk
 http://github.com/magore/hp85disk/COPYRIGHT.md for Copyright details
Based on work by Anders Gustafsson.
Copyright 2014 Anders Gustafsson All rights reserved..
Macro Definition Documentation
ATN_FLAG
#define ATN_FLAG 0x0400
Definition at line 34 of file gpib.h.
BUS_ERROR_FLAG
#define BUS_ERROR_FLAG 0x8000
Definition at line 41 of file gpib.h.
CMD_MASK
#define CMD_MASK 0x007f
Definition at line 52 of file gpib.h.
CONTROL_MASK
#define CONTROL_MASK (EOI_FLAG | SRQ_FLAG | ATN_FLAG | REN_FLAG)
Definition at line 49 of file gpib.h.
DATA_MASK
#define DATA_MASK 0x00ff
Definition at line 51 of file gpib.h.
DAV_FLAG
#define DAV_FLAG 0x2000
handshake flasg used in tracing
Definition at line 44 of file gpib.h.
EOI_FLAG
#define EOI_FLAG 0x0100
bus flags
Definition at line 32 of file gpib.h.
ERROR_MASK
#define ERROR_MASK (IFC_FLAG | TIMEOUT_FLAG | BUS_ERROR_FLAG)
Definition at line 48 of file gpib.h.
GPIB_BUS_SETTLE_DELAY
#define GPIB_BUS_SETTLE_DELAY 2
Definition at line 27 of file gpib.h.
GPIB_IOBUFF_LEN
#define GPIB_IOBUFF_LEN 512 /* Max length of RX/TX GPIB string */
Definition at line 101 of file gpib.h.
HTIMEOUT
#define HTIMEOUT (500000L / GPIB_TASK_TIC_US)
This is the default BUS timeout of 0.5 Seconds in Microseconds.
Definition at line 29 of file gpib.h.
IFC_FLAG
#define IFC_FLAG 0x1000
Definition at line 36 of file gpib.h.
NDAC_FLAG
#define NDAC_FLAG 0x8000
Definition at line 46 of file gpib.h.
NO_TRACE
#define NO_TRACE 0 /* do not trace bus states durring a read */
Definition at line 65 of file gpib.h.
NRFD_FLAG
#define NRFD_FLAG 0x4000
Definition at line 45 of file gpib.h.
PP_FLAG
#define PP_FLAG 0x2000
BUS state flags.
Definition at line 39 of file gpib.h.
REN_FLAG
#define REN_FLAG 0x0800
Definition at line 35 of file gpib.h.
SRQ_FLAG
#define SRQ_FLAG 0x0200
Definition at line 33 of file gpib.h.
STATUS_MASK
#define STATUS_MASK 0xff00
Definition at line 53 of file gpib.h.
TIMEOUT_FLAG
#define TIMEOUT_FLAG 0x4000
Definition at line 40 of file gpib.h.
TRACE_ALL
#define TRACE_ALL 1 /* trace all bus states durring a read */
arguments to gpib_read_byte
Definition at line 64 of file gpib.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
GPIB read trace states.
Enumerator
TRACE_DISABLE
TRACE_READ
TRACE_BUS
Definition at line 56 of file gpib.h.
anonymous enum
anonymous enum
Enumerator
GPIB_RX_START
GPIB_RX_WAIT_FOR_DAV_LOW
GPIB_RX_DAV_IS_LOW
GPIB_RX_WAIT_FOR_NDAC_HI
GPIB_RX_WAIT_FOR_DAV_HI
GPIB_RX_DAV_IS_HI
GPIB_RX_FINISH
GPIB_RX_ERROR
GPIB_RX_DONE
Definition at line 67 of file gpib.h.
anonymous enum
anonymous enum
Enumerator
GPIB_TX_START
GPIB_TX_WAIT_READY
GPIB_TX_PUT_DATA
GPIB_TX_SET_DAV_LOW
GPIB_TX_WAIT_FOR_NRFD_LOW
GPIB_TX_WAIT_FOR_NDAC_HI
GPIB_TX_SET_DAV_HI
GPIB_TX_WAIT_FOR_DAV_HI
GPIB_TX_FINISH
GPIB_TX_ERROR
GPIB_TX_DONE
Definition at line 80 of file gpib.h.
anonymous enum
anonymous enum
Enumerator
GPIB_PP_IDLE
GPIB_PP_DETECTED
Definition at line 95 of file gpib.h.
Function Documentation
gpib_assert_ifc()
void gpib_assert_ifc (void)
Assert Interface clear for 250us.
100us is the Minumum
Reference: SS80 section 3-15, pg 3-26
Returns
void
Definition at line 482 of file gpib.c.
Referenced by gpib_tests().
gpib_assert_ren()
void gpib_assert_ren (unsigned char state)
Assert REN to put instrument in remote mode.
If state != 0 -> assert REN
If state == 0 -> deassert REN
Returns
void
Definition at line 502 of file gpib.c.
gpib_bus_init()
void gpib_bus_init ()
Initialize/Release GPIB Bus control lines for powerup or IFC reset conditions.
Returns
void
FIXME verify resetting gpib_unread_f is ALWAYS correct when called
Definition at line 293 of file gpib.c.
Referenced by gpib_init_devices(), gpib_read_byte(), gpib_write_byte(), and main().
gpib_bus_read()
uint8_t gpib_bus_read ()
Read GPIB data BUS only.
Returns
bus (lower 8 bits)
if a command byte (ATN low) then strip partity
Definition at line 550 of file gpib.c.
Referenced by gpib_read_byte().
gpib_bus_read_init()
void gpib_bus_read_init (int busy)
Initialize GPIB Bus control lines for READ Despite the name this everywhere to setup read mode.
Set busy = 0 after powerup everying floating or high
If busy = 1 NRFD/NDAC are set to busy low
References:
HP-IB Tutorial
HP-IB pg 8-11
Returns
void
release handshake lines References: HP-IB Tutorial pg 12,13 HP-IB pg 8-11
Definition at line 232 of file gpib.c.
Referenced by gpib_read_byte(), and gpib_write_byte().
gpib_control_pin_read()
uint16_t gpib_control_pin_read ()
Read GPIB control lines only FIXME V2 boards can only read pins enabled for read by the SN75162 FIXME We could add a test for read/write state ??
Returns
control lines (upper 8 bits)
See also
gpib_bus_read_init()
Definition at line 568 of file gpib.c.
Referenced by gpib_read_byte().
gpib_decode()
void gpib_decode (uint16_t ch)
Calls gpib_decode_str() and dosplays the result.
Display: decode/display all control flags and data on GPIB BUS.
See also
gpib_decode_str()
Returns
void
Definition at line 1279 of file gpib.c.
Referenced by controller_read_trace(), gpib_read_str(), gpib_task(), gpib_trace_task(), and gpib_write_str().
gpib_decode_header()
void gpib_decode_header (FILE * fo)
Displays help for gpib_decode() function.
You would call this once at the start of a trace for example.
See also
: gpib.h _FLAGS defines for a full list is control lines we track
: gpib_trace()
Returns
void
Parameters
 in fo FILE pointer or `stdout`
Definition at line 1095 of file gpib.c.
Referenced by gpib_trace_task(), and plot_echo().
gpib_detect_PP()
uint8_t gpib_detect_PP ()
Attempt to detect the Parallel Poll Reposnse state Used only for debugging - it is unlikely that we will catch this state V2 hardware - this does not work unless reading BUS.
PPR is short for `Parellel Poll Response`
PPR happens when the CIC (controller in charge) holds BOTH of ATN == 0 and EOI == 0
PPR Response happens using hardware The hardware pulls a bit low on the GPIB bus corresponding to the device. But only if any PPR mask bits are set in the hardware
Note: EOI is never used in command mode (ATN = 0) 1) Hardware will automatically hold GPIB DATA BUS lines low
ppr_reg() determines if we have PPR enabled.
References:
SS80 pg 3-4, section 3-3
See also
gpib_enable_PPR()
gpib_disable_PPR()
Returns
1 if we see a PPR, 0 if not
FIXME we can only read EOI in bus READ mode
Bus pin states but do not alter port direction state
debugging - read the ddr data direction bits to determine read/write state
FIXME we can only read EOI in bus READ mode FIXME We add a test for read/write state ??
Definition at line 415 of file gpib.c.
Referenced by gpib_read_byte(), and gpib_write_byte().
gpib_disable_PPR()
void gpib_disable_PPR (int bit)
Disable PPR (Parallel Poll Response) for a device.
Reference: SS80 pg 3-4, section 3-3
Returns
void
Definition at line 382 of file gpib.c.
Referenced by GPIB_SECONDARY_ADDRESS(), SS80_Command_State(), SS80_COMMANDS(), SS80_Execute_State(), SS80_init(), and SS80_Transparent_State().
gpib_enable_PPR()
void gpib_enable_PPR (int bit)
Reference: SS80 pg 3-4, section 3-3
Returns
void
Definition at line 362 of file gpib.c.
Referenced by SS80_Amigo_Clear(), SS80_Cancel(), SS80_Channel_Independent_Clear(), SS80_Command_State(), SS80_Execute_State(), SS80_Selected_Device_Clear(), SS80_Transparent_State(), and SS80_Universal_Device_Clear().
gpib_handshake_pin_read()
uint16_t gpib_handshake_pin_read ()
Read GPIB handshake lines only FIXME: V2 boards can only read pins enabled for read by the SN75162 FIXME We could add a test for read/write state ??
Returns
handshake lines (upper 8 bits)
for tracing we can reuse the error flag bit values for DAV,NRFD and NDAC FYI: This has no impact on the gpib_read_byte() functions and return values
Definition at line 589 of file gpib.c.
Referenced by gpib_read_byte().
gpib_read_byte()
uint16_t gpib_read_byte (int trace)
read 1 byte and control line status from GPIB BUS
Parameters
 in trace if non-zero do full bus handshake trace of read
References: HP-IB Tutorial pg 13, 14.
Notes: Their diagram is a bit misleading - they start in the BUS init phase. The init happens much earlier in other code - we NEVER want to do that here or bad things will happen - we could step on the sender NRFD test and false trigger it. We instead start with NRFD FLOAT, and NDAC LOW. See loop in send diagram it has NDAC == 0 and NRFD == 1 in the return to send (beginning) part of the loop.
The HP-IB reference has an error: Read ready actually starts when NRFD = 1 and NDAC = 0. If you look at the Write state diagram that can be confirmed.
Returns
Lower 8 bits: Data or Command.
If ATN is LOW then we strip parity from the byte.
Upper 8 bits: Status and Errors.
See also
gpib.h _FLAGS defines for a full list.
An error implies the data byte can't be trusted
Control Line Flags.
EOI_FLAG
SRQ_FLAG
ATN_FLAG
REN_FLAG
PP_FLAG
Error Flags:
IFC_FLAG
Returns
(data bus, control and error status)
V2 boards can NOT read all bits on the control bus at once FIXME We could add a test for read/write state ?? NRFD,NDAC SRQ are outputs
FIXME only enabled on V1 hardware
Signal that we are ready to ready
Wait for Ready acknowledge
gpib_bus_read strips command parity if ATN is low at read time
V2 boards can NOT read all bits on the control bus at once FIXME could add a test for read/write state ?? NRFD,NDAC SRQ are outputs
V2 boards can NOT read all bits on the control bus at once FIXME We could add a test for read/write state ?? NRFD,NDAC SRQ are outputs
FIXME - we can read on V1 hardware rx_state = GPIB_RX_WAIT_FOR_DAV_HI;
FIXME do we want to keep the next state ? V1 boards can read and wait for NDAC to go HI FIXME We clould add a test for read/write state ?? V2 boards we can't - not a big deal as the DAV test works anyway Wait for NDAC float HI
Wait for DAV HI
Ready for next byte
V2 boards can not read all control and handshake bits at once FIXME We could add a test for read/write state ?? NRFD,NDAC SRQ are outputs durring write phase, but not at very start
Note: see: HP-IB Tutorial pg 13
Remember that NDAC and NRFD are now both LOW!
The spec says to KEEP BOTH LOW when NOT ready to read otherwise we may miss a transfer and cause a controller timeout!
GPIB TX state expects NRFD LOW on entry or it is an ERROR!
Definition at line 886 of file gpib.c.
Referenced by controller_read_trace(), gpib_read_str(), gpib_task(), and gpib_trace_task().
gpib_read_str()
int gpib_read_str (uint8_t * buf, int size, uint16_t * status)
Read string from GPIB BUS - controlled by status flags.
Status flags used when reading
If EOI is set then EOI detection will end reading when EOI is detected.
If an early or unexpected EOI is detected a warning is displayed.
The state of ATN controls the type of data read.
If ATN is set then parity is stripped.
Only data matching the ATN flag state set by user is read.
If we see a mismatch we `unread` it and exit.
Unreading saves data AND status to be reread later on.
See also
: gpib_read_byte()
: gpib_unread()
Parameters
 in buf Binary gpib string to read
 in size Size of string we want to read
 in status controls sending modes and returns status
Returns
bytes read
status
Errors TIMEOUT_FLAG or IFC_FLAG will cause early exit and set status.
Lower 8 bits: Data or Command.
If ATN is LOW then we strip parity from the byte.
Upper 8 bits: Status and Errors.
See also
gpib.h _FLAGS defines for a full list.
An error implies the data byte can't be trusted
Control Line Flags.
EOI_FLAG
SRQ_FLAG
ATN_FLAG
REN_FLAG
PP_FLAG
Error Flags:
IFC_FLAG
Todo
Todo TODO decode this state - for now I just set the EOI_FLAG
Definition at line 1320 of file gpib.c.
Referenced by controller_read_str(), SS80_Amigo_Clear(), SS80_Command_State(), SS80_locate_and_write(), and SS80_Transparent_State().
gpib_state_init()
void gpib_state_init (void)
Reset GPIB states and related variables.
Called at powerup and IFC or reset states.
Does not reset BUS
Returns
void
Definition at line 335 of file gpib.c.
Referenced by gpib_init_devices(), and main().
gpib_timeout_set()
void gpib_timeout_set (uint32_t time)
Set GPIB timeout timer in units of GPIB_TASK_TIC_US.
See also
: gpib_timeout_test()
Returns
void
Definition at line 204 of file gpib.c.
Referenced by gpib_read_byte(), and gpib_write_byte().
gpib_timeout_test()
uint8_t gpib_timeout_test ()
Test GPIB timeout timer for timeout condition.
See also
: gpib_timeout_set()
Returns
1 if timeout, 0 if not
Definition at line 217 of file gpib.c.
Referenced by gpib_read_byte(), and gpib_write_byte().
gpib_timer_elapsed_begin()
void gpib_timer_elapsed_begin (void)
Start measuring time - used with hpib_timer_elapsed_end()
See gpib_hal.c for CPU specific code Provide Elapsed timer and Timeout timer - both in Microseconds We use the lower level clock elapsed timer functions here
Returns
void
Definition at line 130 of file gpib.c.
Referenced by gpib_detect_PP(), gpib_tests(), SS80_locate_and_read(), and SS80_locate_and_write().
gpib_timer_elapsed_end()
void gpib_timer_elapsed_end (char * msg)
Display user message and time delta since gpib_timer_elapsed_begin() call.
Display a message
Returns
void
Definition at line 161 of file gpib.c.
Referenced by gpib_detect_PP(), gpib_tests(), SS80_locate_and_read(), and SS80_locate_and_write().
gpib_timer_reset()
void gpib_timer_reset (void)
Reset elapsed and timeout timers Elapses and Timeout Timers.
Returns
void
Definition at line 147 of file gpib.c.
Referenced by gpib_timer_init().
gpib_timer_task()
void gpib_timer_task ()
Main GPIB timer task called by low level interrup hander.
Provides Down timers and Elapsed timers
Called every GPIB_TASK_TIC_US Micro Seconds
Returns
void
Definition at line 187 of file gpib.c.
Referenced by gpib_timer_init().
gpib_trace_display()
void gpib_trace_display (uint16_t status, int trace_state)
decode/display all control flags and data on the GPIB BUS
Parameters
 in status data bus value (lower 8 bits) control bus (upper 8 bits)
 in trace_state level of trace detail TRACE_DISABLE = normal bus and control status report from read state only TRACE_READ = trace bus and control reporting from read state only TRACE_BUS = trace control reporting from all non-read states, data bus values are omiited Note: trace states add DAV,NRFD,NDAC and ommit PPR status, BUS error and timeout given that gpib_read_byte() report these anyway
Lower 8 bits: Data or Command.
If ATN is LOW then we strip parity from the byte.
Upper 8 bits: Status and Errors.
See also
gpib.h _FLAGS defines for a full list.
An error implies the data byte can't be trusted
Control Line Flags.
EOI_FLAG
SRQ_FLAG
ATN_FLAG
REN_FLAG
PP_FLAG
Error Flags:
IFC_FLAG
Parameters
 in str string pointer to store the decoded result in.
See also
: gpib_read_byte()
: gpib_write_byte(int ch)
: gpib_decode_header()
Returns
void Note the bits we can read depends on what hardware verions we have V2 hardware can only read status bits based on GPIB control buffer direction FIXME We could add a test for read/write state ??
Definition at line 1148 of file gpib.c.
Referenced by gpib_decode(), and gpib_read_byte().
gpib_unread()
uint16_t gpib_unread (uint16_t ch)
GPIB ungets one character and all status states.
Pushes a character back into the read buffer
Parameters
 in ch
Lower 8 bits: Data or Command.
If ATN is LOW then we strip parity from the byte.
Upper 8 bits: Status and Errors present.
See also
gpib.h _FLAGS defines for a full list.
Returns
ch
Definition at line 532 of file gpib.c.
Referenced by GPIB_COMMANDS(), and gpib_read_str().
gpib_write_byte()
uint16_t gpib_write_byte (uint16_t ch)
Send 1 byte and control line states to GPIB BUS.
We assume we are talking to an active controller already in read state
Any error flags set on return imply the data was not likely sent
You can OR the control flags ATN_FLAG, EOI_FLAG with (ch) to send them these states.
Results can be displayed for debugging with the decode(ch) funnction
We always exit with NRFD and NDAC LOW
References: HP-IB Tutorial pg13. HP-IB Tutorial pg 13 for the receive and send control line states Correction: The send routine MUST also wait for NDAC LOW before exit. (You can verify this by checking the receive part of the handshake diagram just before it returns to the start of the loop) Failing to wait will cause problems that may masqurade as timing issues.
(It caused problems with my HP85 before I added the code)
Parameters
 out ch (Data or Command) and control flags
Upper 8 bits: contril flags
Flags:
EOI_FLAG
ATN_FLAG
EOI and ATN can only be used in controller mode
Returns
Lower 8 bits: Data or Command.
If ATN is LOW then we strip parity from the byte.
Upper 8 bits: Status and Errors.
See also
gpib.h _FLAGS defines for a full list.
An error implies the data byte can't be trusted
Control Line Flags.
EOI_FLAG
SRQ_FLAG
ATN_FLAG
REN_FLAG
PP_FLAG
Error Flags:
IFC_FLAG
NRFD,NDAC SRQ are outputs
first device is ready
ALL devices are ready
@release BUS
We are in read mode now @wait for DAV to finish float HI - finishing floating HI
Definition at line 641 of file gpib.c.
Referenced by controller_ifc(), controller_read_str(), controller_read_trace(), controller_send_str(), and gpib_write_str().
gpib_write_str()
int gpib_write_str (uint8_t * buf, int size, uint16_t * status)
Send string to GPIB BUS - controlled by status flags.
Status flags used when sending
If EOI is set then EOI is sent at last character
Parameters
 in buf Binary gpib string to send
 in size Size of string
 in status User status flags that control the sending process.
Returns
bytes sent
will match size on success (no other tests needed).
Any size mismatch impiles error flags IFC_FLAG and TIMEOUT_FLAG.
Errors TIMEOUT_FLAG or IFC_FLAG will cause early exit and set status.
Lower 8 bits: Data or Command.
If ATN is LOW then we strip parity from the byte.
Upper 8 bits: Status and Errors.
See also
gpib.h _FLAGS defines for a full list.
An error implies the data byte can't be trusted
Control Line Flags.
EOI_FLAG
SRQ_FLAG
ATN_FLAG
REN_FLAG
PP_FLAG
Error Flags:
IFC_FLAG
See also
: gpib_write_byte()
: gpib.h _FLAGS defines for a full list)
Returns
Returns
Definition at line 1409 of file gpib.c.
Referenced by controller_send_str(), Send_Identify(), SS80_describe(), SS80_error_return(), SS80_locate_and_read(), SS80_Report(), and SS80_send_status().
Variable Documentation
current
uint16_t current
Definition at line 94 of file gpib.c.
Referenced by clock_elapsed_end(), gpib_read_byte(), and gpib_state_init().
debuglevel
int debuglevel
Debug flag - used to log GPIB and emulator messages.
Definition at line 33 of file gpib_task.c.
device
uint8_t device
gpib_iobuff
uint8_t gpib_iobuff[GPIB_IOBUFF_LEN]
common IO buffer for gpib_read_str() and gpib_write_str()
References: Documenation and related sources of information
Web Resources:
 http://www.hp9845.net
 http://www.hpmuseum.net
 http://www.hpmusuem.org
 http://bitsavers.trailing-edge.com
 http://en.wikipedia.org/wiki/IEEE-488
SS80 References:
`SS80` is the short form used in the project
`Subset 80 from Fixed and flexible disc drives`
Printed November, 1985
HP Part# 5958-4129
CS80 References:
`CS80` is the short form used in the project
`CS/80 Instruction Set Programming Manual`
Printed: APR 1983
HP Part# 5955-3442
Amigo References:
`Amigo` is the short form used in the project
`Appendix A of 9895A Flexible Disc Memory Service Manual`
HP Part# 09895-90030
HP-IB
`HP-IB` is the short form used in the project
`Condensed Description of the Hewlett Packard Interface Bus`
Printed March 1975
HP Part# 59401-90030
Tutorial Description of The Hewllet Packard Interface Bus`
  - `HP-IB Tutorial" is the short form used in the project
 http://www.hpmemory.org/an/pdf/hp-ib_tutorial_1980.pdf
Printed January 1983
 http://www.ko4bb.com/Manuals/HP_Agilent/HPIB_tutorial_HP.pdf
Printed 1987
GPIB / IEEE 488 Tutorial by Ian Poole
 http://www.radio-electronics.com/info/t_and_m/gpib/ieee488-basics-tutorial.php
Definition at line 74 of file gpib.c.
Referenced by SS80_Command_State(), SS80_locate_and_read(), SS80_locate_and_write(), and SS80_Transparent_State().
lastcmd
uint16_t lastcmd
Definition at line 112 of file gpib.h.
listening
uint8_t listening
gpib listen address
Definition at line 87 of file gpib.c.
listening_last
uint8_t listening_last
gpib last listen address
Definition at line 89 of file gpib.c.
Referenced by GPIB_LISTEN(), gpib_state_init(), and listen_cleanup().
secondary
uint8_t secondary
gpib secondary
Definition at line 97 of file gpib.c.
Referenced by GPIB_COMMANDS(), gpib_state_init(), and gpib_task().
spoll
uint8_t spoll
gpib serial poll status
Definition at line 92 of file gpib.c.
talk31
uint8_t talk31
talking
uint8_t talking
gpib talk address
Definition at line 82 of file gpib.c.
talking_last
uint8_t talking_last
gpib last talk address
Definition at line 84 of file gpib.c.
Referenced by gpib_state_init(), and GPIB_TALK().