gpib/gpib.c File Reference
GPIB emulator for HP85 disk emulator project for AVR8.
#include <avr/pgmspace.h>
*
#include <avr/portpins.h>
*
#include <avr/io.h>
*
#include `user_config.h`
*
#include `hardware/hal.h`
*
#include `gpib_hal.h`
*
#include `defines.h`
*
#include `gpib.h`
*
#include `gpib_task.h`
*
#include `amigo.h`
*
#include `ss80.h`
*
Macros
#define HTIMEOUT (500000L / GPIB_TASK_TIC_US)
This is the default BUS timeout of 0.5 Seconds in Microseconds.
Functions
void gpib_timer_elapsed_begin (void)
Start measuring time - used with hpib_timer_elapsed_end()
void gpib_timer_reset (void)
Reset elapsed and timeout timers Elapses and Timeout Timers.
void gpib_timer_elapsed_end (char *msg)
Display user message and time delta since gpib_timer_elapsed_begin() call.
void gpib_timer_task ()
Main GPIB timer task called by low level interrup hander.
void gpib_timeout_set (uint32_t time)
Set GPIB timeout timer in units of GPIB_TASK_TIC_US.
uint8_t gpib_timeout_test ()
Test GPIB timeout timer for timeout condition.
void gpib_bus_init (int cold)
Initialize GPIB Bus control lines for powerup or reset conditions.
void gpib_state_init (void)
Reset GPIB states and related variables.
int address_to_device (uint8_t address)
Map device address, MLA,MTA,MSA to PPR address TODO include lookup array.
int device_to_PPR (uint8_t address)
Map device address, MLA,MTA,MSA to PPR address TODO include lookup array.
void EnablePPR (uint8_t bit)
void DisablePPR (uint8_t bit)
Disable PPR (Parallel Poll Response) for a device.
uint8_t Parallel_Poll ()
Detect Parallel Poll state.
void gpib_assert_ifc (void)
Assert Interface clear for 250us.
void gpib_assert_ren (unsigned char state)
Assert REN to put instrument in remote mode.
uint16_t gpib_write_byte (uint16_t ch)
Send 1 byte and control line states to GPIB BUS.
uint16_t gpib_unread (uint16_t ch)
GPIB ungets one character and all status states.
uint16_t gpib_read_byte (void)
read 1 byte and control line status from GPIB BUS
void gpib_decode_header (void)
Displays help for gpib_decode() function.
void gpib_decode_str (uint16_t ch, char *str)
decode/display all control flags and data on the GPIB BUS
void gpib_decode (uint16_t ch)
Calls gpib_decode_str() and dosplays the result.
int gpib_read_str (uint8_t *buf, int size, uint16_t *status)
Read string from GPIB BUS - controlled by status flags.
int gpib_write_str (uint8_t *buf, int size, uint16_t *status)
Send string to GPIB BUS - controlled by status flags.
Variables
uint8_t gpib_iobuff [GPIB_IOBUFF_LEN]
common IO buffer for gpib_read_str() and gpib_write_str()
uint8_t gpib_unread_f = 0
gpib_unread() flag
uint16_t gpib_unread_data
gpib_unread() data
BYTE device
Device number - working to support more then one device support.
uint8_t talking
gpib talk address
uint8_t talking_last
gpib last talk address
uint8_t listening
gpib listen address
uint8_t listening_last
gpib last listen address
uint8_t spoll
gpib serial poll status
uint16_t lastcmd
gpib current and last command
uint16_t current
uint8_t secondary
gpib secondary
Detailed Description
GPIB emulator for HP85 disk emulator project for AVR8.
Edit History - [1.0] [Mike Gore] Initial revision of file.
Copyright 2014 Mike Gore, Inc. All rights reserved.
Based on work by Anders Gustafsson.
Copyright 2014 Anders Gustafsson All rights reserved..
Macro Definition Documentation
#define HTIMEOUT (500000L / GPIB_TASK_TIC_US)
This is the default BUS timeout of 0.5 Seconds in Microseconds.
References: Documenation and related sources of information
Web Resources:
http://www.hp9845.net
http://www.hpmuseum.net
http://www.hpmusuem.org
http://bitsavers.trailing-edge.com
http://en.wikipedia.org/wiki/IEEE-488
SS80 References:
`SS80` is the short form used in the project
`Subset 80 from Fixed and flexible disc drives`
Printed November, 1985
HP Part# 5958-4129
CS80 References:
`CS80` is the short form used in the project
`CS/80 Instruction Set Programming Manual`
Printed: APR 1983
HP Part# 5955-3442
Amigo References:
`Amigo` is the short form used in the project
`Appendix A of 9895A Flexible Disc Memory Service Manual`
HP Part# 09895-90030
HP-IB
`HP-IB` is the short form used in the project
`Condensed Description of the Hewlett Packard Interface Bus`
Printed March 1975
HP Part# 59401-90030
Tutorial Description of The Hewllet Packard Interface Bus`
  - `HP-IB Tutorial" is the short form used in the project
http://www.hpmemory.org/an/pdf/hp-ib_tutorial_1980.pdf
Printed January 1983
http://www.ko4bb.com/Manuals/HP_Agilent/HPIB_tutorial_HP.pdf
Printed 1987
GPIB / IEEE 488 Tutorial by Ian Poole
http://www.radio-electronics.com/info/t_and_m/gpib/ieee488-basics-tutorial.php
Definition at line 73 of file gpib.c.
Referenced by gpib_read_byte(), and gpib_write_byte().
Function Documentation
int address_to_device (uint8_t address)
Map device address, MLA,MTA,MSA to PPR address TODO include lookup array.
Returns
device number index or -1 if no match
Definition at line 276 of file gpib.c.
Referenced by device_to_PPR().
int device_to_PPR (uint8_t address)
Map device address, MLA,MTA,MSA to PPR address TODO include lookup array.
Returns
device number index or -1 if no match
Definition at line 285 of file gpib.c.
void DisablePPR (uint8_t bit)
Disable PPR (Parallel Poll Response) for a device.
Reference: SS80 pg 3-4, section 3-3
Returns
void
Definition at line 319 of file gpib.c.
Referenced by Amigo_Command(), AMIGO_COMMANDS(), Amigo_Execute(), amigo_init(), GPIB_SECONDARY_ADDRESS(), SS80_Command_State(), SS80_COMMANDS(), SS80_Execute_State(), SS80_init(), and SS80_Transparent_State().
void EnablePPR (uint8_t bit)
Reference: SS80 pg 3-4, section 3-3
Returns
void
Definition at line 304 of file gpib.c.
Referenced by amigo_buffered_read(), amigo_buffered_write(), amigo_cmd_clear(), amigo_cmd_wakeup(), Amigo_Command(), amigo_format(), amigo_request_status(), amigo_seek(), amigo_send_logical_address(), amigo_send_status(), amigo_todo(), amigo_todo_op(), amigo_verify(), SS80_Amigo_Clear(), SS80_Cancel(), SS80_Channel_Independent_Clear(), SS80_Command_State(), SS80_Execute_State(), SS80_Selected_Device_Clear(), SS80_Transparent_State(), and SS80_Universal_Device_Clear().
void gpib_assert_ifc (void)
Assert Interface clear for 250us.
100us is the Minumum
Reference: SS80 section 3-15, pg 3-26
Returns
void
Definition at line 397 of file gpib.c.
Referenced by task().
void gpib_assert_ren (unsigned char state)
Assert REN to put instrument in remote mode.
If state != 0 -> assert REN
If state == 0 -> deassert REN
Returns
void
Definition at line 417 of file gpib.c.
void gpib_bus_init (int cold)
Initialize GPIB Bus control lines for powerup or reset conditions.
Set cold = 1 at powerup
set cold = 0 in operation to reset bus state
If cold = 0 NRFD/NDAC is setto 0 busy
References:
HP-IB Tutorial
HP-IB pg 8-11
Returns
void
References: HP-IB Tutorial pg 12,13 HP-IB pg 8-11
Definition at line 212 of file gpib.c.
Referenced by gpib_error_test(), gpib_task(), gpib_trace_task(), main(), plot_echo(), receive_plot(), and SS80_init().
void gpib_decode (uint16_t ch)
Calls gpib_decode_str() and dosplays the result.
Display: decode/display all control flags and data on GPIB BUS.
See also
gpib_decode_str()
Returns
void
Definition at line 981 of file gpib.c.
Referenced by gpib_read_str(), gpib_unread(), gpib_write_str(), SS80_Command_State(), and SS80_Transparent_State().
void gpib_decode_header (void)
Displays help for gpib_decode() function.
You would call this once at the start of a trace for example.
See also
: gpib.h _FLAGS defines for a full list is control lines we track
: gpib_trace()
Returns
void
Definition at line 879 of file gpib.c.
Referenced by gpib_trace_task(), and plot_echo().
void gpib_decode_str (uint16_t ch, char * str)
decode/display all control flags and data on the GPIB BUS
Parameters
in ch
Lower 8 bits: Data or Command.
If ATN is LOW then we strip parity from the byte.
Upper 8 bits: Status and Errors.
See also
gpib.h _FLAGS defines for a full list.
An error implies the data byte can't be trusted
Control Line Flags.
EOI_FLAG
SRQ_FLAG
ATN_FLAG
REN_FLAG
PP_FLAG
Error Flags:
IFC_FLAG
Parameters
in str string pointer to store the decoded result in.
See also
: gpib_read_byte()
: gpib_write_byte(int ch)
: gpib_decode_header()
Returns
void
Returns
return
Definition at line 920 of file gpib.c.
Referenced by gpib_decode(), gpib_task(), gpib_trace_task(), plot_echo(), printer_buffer(), and receive_plot().
uint16_t gpib_read_byte (void)
read 1 byte and control line status from GPIB BUS
References: HP-IB Tutorial pg 13, 14.
Notes: Their diagram is a bit misleading - they start in the BUS init phase. The init happens much earlier in other code - we NEVER want to do that here or bad things will happen - we could step on the sender NRFD test and false trigger it. We instead start with NRFD FLOAT, and NDAC LOW. See loop in send diagram it has NDAC == 0 and NRFD == 1 in the return to send (beginning) part of the loop.
The HP-IB reference has an error: Read ready actually starts when NRFD = 1 and NDAC = 0. If you look at the Write state diagram that can be confirmed.
Returns
Lower 8 bits: Data or Command.
If ATN is LOW then we strip parity from the byte.
Upper 8 bits: Status and Errors.
See also
gpib.h _FLAGS defines for a full list.
An error implies the data byte can't be trusted
Control Line Flags.
EOI_FLAG
SRQ_FLAG
ATN_FLAG
REN_FLAG
PP_FLAG
Error Flags:
IFC_FLAG
Note: see: HP-IB Tutorial pg 13
Remember that NDAC and NRFD are now both LOW!
The spec says to KEEP BOTH LOW when NOT ready to read otherwise we may miss a transfer and cause a controller timeout!
GPIB TX state expects NRFD LOW on entry or it is an ERROR!
Definition at line 742 of file gpib.c.
Referenced by gpib_read_str(), gpib_task(), gpib_trace_task(), plot_echo(), and receive_plot().
int gpib_read_str (uint8_t * buf, int size, uint16_t * status)
Read string from GPIB BUS - controlled by status flags.
Status flags used when reading
If EOI is set then EOI detection will end reading when EOI is detected.
If an early or unexpected EOI is detected a warning is displayed.
The state of ATN controls the type of data read.
If ATN is set then parity is stripped.
Only data matching the ATN flag state set by user is read.
If we see a mismatch we `unread` it and exit.
Unreading saves data AND status to be reread later on.
See also
: gpib_read_byte()
: gpib_unread()
Parameters
in buf Binary gpib string to read
in size Size of string we want to read
in status controls sending modes and returns status
Returns
bytes read
status
Errors TIMEOUT_FLAG or IFC_FLAG will cause early exit and set status.
Lower 8 bits: Data or Command.
If ATN is LOW then we strip parity from the byte.
Upper 8 bits: Status and Errors.
See also
gpib.h _FLAGS defines for a full list.
An error implies the data byte can't be trusted
Control Line Flags.
EOI_FLAG
SRQ_FLAG
ATN_FLAG
REN_FLAG
PP_FLAG
Error Flags:
IFC_FLAG
Todo
Todo TODO decode this state - for now I just set the EOI_FLAG
Definition at line 1027 of file gpib.c.
Referenced by amigo_buffered_write(), Amigo_Command(), SS80_Amigo_Clear(), SS80_Command_State(), SS80_locate_and_write(), and SS80_Transparent_State().
void gpib_state_init (void)
Reset GPIB states and related variables.
Called at powerup and IFC or reset states.
Does not reset BUS
Returns
void
Definition at line 249 of file gpib.c.
Referenced by gpib_error_test(), gpib_task(), gpib_trace_task(), main(), plot_echo(), and receive_plot().
void gpib_timeout_set (uint32_t time)
Set GPIB timeout timer in units of GPIB_TASK_TIC_US.
See also
: gpib_timeout_test()
Returns
void
Definition at line 186 of file gpib.c.
Referenced by gpib_read_byte(), and gpib_write_byte().
uint8_t gpib_timeout_test (void)
Test GPIB timeout timer for timeout condition.
See also
: gpib_timeout_set()
Returns
1 if timeout, 0 if not
Definition at line 198 of file gpib.c.
Referenced by gpib_read_byte(), and gpib_write_byte().
void gpib_timer_elapsed_begin (void)
Start measuring time - used with hpib_timer_elapsed_end()
See gpib_hal.c for CPU specific code Provide Elapsed timer and Timeout timer - both in Microseconds We use the lower level clock elapsed timer functions here
Returns
void
Definition at line 112 of file gpib.c.
Referenced by amigo_buffered_read(), amigo_buffered_write(), Amigo_Command(), amigo_format(), amigo_verify(), gpib_tests(), SS80_locate_and_read(), and SS80_locate_and_write().
void gpib_timer_elapsed_end (char * msg)
Display user message and time delta since gpib_timer_elapsed_begin() call.
Display a message
Returns
void
Definition at line 143 of file gpib.c.
Referenced by amigo_buffered_read(), amigo_buffered_write(), Amigo_Command(), amigo_format(), amigo_verify(), gpib_tests(), SS80_locate_and_read(), and SS80_locate_and_write().
void gpib_timer_reset (void)
Reset elapsed and timeout timers Elapses and Timeout Timers.
Returns
void
Definition at line 129 of file gpib.c.
Referenced by gpib_timer_init().
void gpib_timer_task (void)
Main GPIB timer task called by low level interrup hander.
Provides Down timers and Elapsed timers
Called every GPIB_TASK_TIC_US Micro Seconds
Returns
void
Definition at line 169 of file gpib.c.
Referenced by gpib_timer_init().
uint16_t gpib_unread (uint16_t ch)
GPIB ungets one character and all status states.
Pushes a character back into the read buffer
Parameters
in ch
Lower 8 bits: Data or Command.
If ATN is LOW then we strip parity from the byte.
Upper 8 bits: Status and Errors present.
See also
gpib.h _FLAGS defines for a full list.
Returns
ch
Definition at line 690 of file gpib.c.
Referenced by GPIB_COMMANDS(), and gpib_read_str().
uint16_t gpib_write_byte (uint16_t ch)
Send 1 byte and control line states to GPIB BUS.
We assume we are talking to an active controller already in read state
Any error flags set on return imply the data was not likely sent
You can OR the control flags ATN_FLAG, EOI_FLAG with (ch) to send them these states.
Results can be displayed for debugging with the decode(ch) funnction
We always exit with NRFD and NDAC LOW
References: HP-IB Tutorial pg13. HP-IB Tutorial pg 13 for the receive and send control line states Correction: The send routine MUST also wait for NDAC LOW before exit. (You can verify this by checking the receive part of the handshake diagram just before it returns to the start of the loop) Failing to wait will cause problems that may masqurade as timing issues.
(It caused problems with my HP85 before I added the code)
Parameters
out ch (Data or Command) and control flags
Upper 8 bits: contril flags
Flags:
EOI_FLAG
ATN_FLAG
Returns
Lower 8 bits: Data or Command.
If ATN is LOW then we strip parity from the byte.
Upper 8 bits: Status and Errors.
See also
gpib.h _FLAGS defines for a full list.
An error implies the data byte can't be trusted
Control Line Flags.
EOI_FLAG
SRQ_FLAG
ATN_FLAG
REN_FLAG
PP_FLAG
Error Flags:
IFC_FLAG
See HP-IB Tutorial pg 13 for the receive and send control line states
Todo
Todo FIXME If we test NRFD == 1 and NDAC == 1 and exit rather then waiting we frequently fail. Why does this happen ??? Disabling the test and waiting fixes the problem. Why ???
Todo
Todo FIXME
Definition at line 474 of file gpib.c.
Referenced by gpib_write_str().
int gpib_write_str (uint8_t * buf, int size, uint16_t * status)
Send string to GPIB BUS - controlled by status flags.
Status flags used when sending
If EOI is set then EOI is sent at last character
Parameters
in buf Binary gpib string to send
in size Size of string
in status User status flags that control the sending process.
Returns
bytes sent
will match size on success (no other tests needed).
Any size mismatch impiles error flags IFC_FLAG and TIMEOUT_FLAG.
Errors TIMEOUT_FLAG or IFC_FLAG will cause early exit and set status.
Lower 8 bits: Data or Command.
If ATN is LOW then we strip parity from the byte.
Upper 8 bits: Status and Errors.
See also
gpib.h _FLAGS defines for a full list.
An error implies the data byte can't be trusted
Control Line Flags.
EOI_FLAG
SRQ_FLAG
ATN_FLAG
REN_FLAG
PP_FLAG
Error Flags:
IFC_FLAG
See also
: gpib_write_byte()
: gpib.h _FLAGS defines for a full list)
Returns
Returns
Definition at line 1124 of file gpib.c.
Referenced by amigo_buffered_read(), amigo_cmd_dsj(), amigo_cmd_wakeup(), Amigo_Command(), amigo_send_logical_address(), amigo_send_status(), plot_echo(), Send_Identify(), SS80_describe(), SS80_error_return(), SS80_locate_and_read(), SS80_Report(), and SS80_send_status().
uint8_t Parallel_Poll (void)
Detect Parallel Poll state.
PPR is short for `Parellel Poll Response`
PPR happens when the CIC (controller in charge) holds both
ATN == 0 and EOI == 0
EOI is never used in command mode (ATN = 0)
PPR state is happening if we see both ATN and EOI LOW at once If PPR is enabled we have two options: 1) If software Parrallel Poll is defined we save DATA BUS state and hold PPR DATA BUS lines LOW. 2) Hardware will automatically hold DATA BUS lines low.
Nest We go to the DETECTED state
In the DETECTED state we wait for ATN and EOI to change Once this happens: 1) If software Parrallel Poll is defined we restore the DATA BUS state. 2) Hardware will automatically release DATA BUS state. We report detecting if(debug_level)
ppr_reg() determines if we have PPR enabled.
References:
SS80 pg 3-4, section 3-3
See also
EnablePPR()
DisablePPR()
Returns
1 if we see a PPR, 0 if not
Definition at line 354 of file gpib.c.
Referenced by gpib_read_byte(), and gpib_write_byte().
Variable Documentation
uint16_t current
Definition at line 99 of file gpib.c.
Referenced by clock_elapsed_end(), gpib_read_byte(), and gpib_state_init().
BYTE device
Device number - working to support more then one device support.
Definition at line 84 of file gpib.c.
Referenced by address_to_device(), device_to_PPR(), GPIB_LISTEN(), GPIB_SECONDARY_ADDRESS(), and gpib_state_init().
uint8_t gpib_iobuff[GPIB_IOBUFF_LEN]
common IO buffer for gpib_read_str() and gpib_write_str()
Definition at line 76 of file gpib.c.
Referenced by amigo_buffered_read(), amigo_buffered_write(), Amigo_Command(), amigo_format(), amigo_verify(), SS80_Command_State(), SS80_locate_and_read(), SS80_locate_and_write(), and SS80_Transparent_State().
uint16_t gpib_unread_data
gpib_unread() data
Definition at line 81 of file gpib.c.
Referenced by gpib_read_byte(), and gpib_unread().
uint8_t gpib_unread_f = 0
gpib_unread() flag
Definition at line 79 of file gpib.c.
Referenced by gpib_bus_init(), gpib_read_byte(), and gpib_unread().
uint16_t lastcmd
gpib current and last command
Definition at line 99 of file gpib.c.
Referenced by GPIB_LISTEN(), gpib_read_byte(), gpib_state_init(), and gpib_task().
uint8_t listening
gpib listen address
Definition at line 92 of file gpib.c.
Referenced by Amigo_Command(), AMIGO_COMMANDS(), Amigo_Execute(), amigo_todo(), amigo_todo_op(), GPIB(), GPIB_COMMANDS(), GPIB_LISTEN(), GPIB_SECONDARY_ADDRESS(), gpib_state_init(), GPIB_TALK(), gpib_task(), PRINTER_COMMANDS(), and SS80_COMMANDS().
uint8_t listening_last
gpib last listen address
Definition at line 94 of file gpib.c.
Referenced by GPIB_LISTEN(), gpib_state_init(), and listen_cleanup().
uint8_t secondary
gpib secondary
Definition at line 102 of file gpib.c.
Referenced by GPIB_COMMANDS(), gpib_state_init(), and gpib_task().
uint8_t spoll
gpib serial poll status
Definition at line 97 of file gpib.c.
Referenced by GPIB(), gpib_state_init(), and GPIB_TALK().
uint8_t talking
gpib talk address
GPIB BUS states.
/// SS80 References: ("SS80" is the short form used in the project)
///  "Subset 80 from Fixed and flexible disc drives"
///   Printed November, 1985
///   HP Part# 5958-4129
///
/// CS80 References: ("CS80" is the short form used in the project)
///   "CS/80 Instruction Set Programming Manual"
///   Printed: APR 1983
///   HP Part# 5955-3442
///
/// Amigo References: ("Amigo" is the short form used in the project)
///   "Appendix A of 9895A Flexible Disc Memory Service Manual"
///   HP Part# 09895-90030
/// 
///  Reference: Amigo Command Set Reference used in this document
///  Short Form         Title
///  SS80       "Subset 80 from Fixed and flexible disc drives" 5958-4129
///  HP9123         9123 disc drive manual addendum 5957-6584
///  A          Appendix A "HP 9895A Disc Memory Commends Set"
///             See Receive Status A16
///  L    Buffered Read             0x05    2       A33     Y
///  L    Request Physical Address  0x14    2       A21     Y 0x68
///             See Send Address A20
/// 
///  0x6B Command Op Codes          OP      bytes
///  L    Buffered Read Verify      0x05    2       A37     Y
///  L    ID Triggered Read         0x06    2       A41     Y
/// 
///  0x6C Command Op Codes          OP      bytes
///  L    Unbuffered Read Verify    0x05    2       A38     Y
///  L    Request Physical Address  0x14    2       A21     Y 0x68
///  L    Format Request            0x18    2       A50     N
///  L    Door Lock                 0x19    2       A30     N
///  L    Door Unlock               0x1A    2       A31     N
/// 
///  0x6F Command Op Codes          OP      bytes
///  L    Download Controller       ---     1..256  A26     N
/// 
///  0x70 Command Op Codes          OP      bytes
///  L    HP-300 Clear              ---     1       A23     N
///  T    DSJ                       ---     1       A11     N
/// 
///  0x77 Command Op Codes          OP      bytes
///  T/L  HP-IB CRC                 ---     ---     A30     N
/// 
///  0x7E Command Op Codes          OP      bytes
///  L    Write Loopback Record     ---     1..256  A25     N
///  T    Read Loopback Record      ---     1..256  A14     N
/// 
///  0x7F Command Op Codes          OP      bytes
///  T    Read Self Test Results    ---     2       A13     N
///  L    Initiat Self Test         ---     2       A24     N
/// 
/// Secondary_Commands and OP Code processing
///
/// 0x60 Command Op Codes           OP      bytes
/// L    Receive Data               ---     ---
///         Execute of most receive data requests
///         All Disk Write
/// T    Send Data                  ---     ---
///         Execute of most send data requests
///         All Disk Read
///
/// 0x68 Command Op Codes           OP      bytes   Ref     Execute Phase
/// L    Cold Load Read             0x00    2       A40     Y
/// L    Seek                       0x02    6       A27     N
/// L    Request Status buffered        0x03    2       A15     Y 0x68
/// L    Unbuffered Read            0x05    2       A35     Y
/// L    Verify                     0x07    4       A36     N
/// L    Unbuffered Write Request   0x08    2       A45     Y
/// L    Initialize                 0x0B    2       A46     Y
/// L    Initialize DBIT                0x2B    2       A46     Y
/// L    Request Logical Address    0x14    2       A20     Y 0x68
/// L   End                         0x15    2       A29     N
/// T    Send Status or Address         ----    4       A20     N
///         Execute of all Address and Status Requests 
///         (Y 0x68)
///
/// 0x69 Command Op Codes           OP      bytes
/// L    Buffered Write Request     0x08    2       A43     Y
///
/// 0x6A Command Op Codes           OP      bytes
/// L    Request Status Unbuffered   0x03    2      A15     Y 0x68
///         See Receive Status A16
/// L    Buffered Read              0x05    2       A33     Y
/// L    Request Physical Address   0x14    2       A21     Y 0x68
///         See Send Address A20
///
/// 0x6B Command Op Codes           OP      bytes
/// L    Buffered Read Verify       0x05    2       A37     Y
/// L    ID Triggered Read          0x06    2       A41     Y
///
/// 0x6C Command Op Codes           OP      bytes
/// L    Unbuffered Read Verify     0x05    2       A38     Y
/// L    Request Physical Address   0x14    2       A21     Y 0x68
/// L    Format Request                 0x18    2       A50     N
/// L    Door Lock                  0x19    2       A30     N
/// L    Door Unlock                0x1A    2       A31     N
///
/// 0x6F Command Op Codes           OP      bytes
/// L    Download Controller        ---     1..256  A26     N
///
/// 0x70 Command Op Codes           OP      bytes
/// L    HP-300 Clear               ---     1       A23     N
/// T    DSJ                        ---     1       A11     N
///
/// 0x77 Command Op Codes           OP      bytes
/// T/L  HP-IB CRC                  ---     ---     A30     N
///
/// 0x7E Command Op Codes           OP      bytes
/// L    Write Loopback Record      ---     1..256  A25     N
/// T    Read Loopback Record       ---     1..256  A14     N
///
/// 0x7F Command Op Codes           OP      bytes
/// T    Read Self Test Results         ---     2       A13     N
/// L    Initiat Self Test          ---     2       A24     N
/// 
Definition at line 87 of file gpib.c.
Referenced by Amigo_Command(), AMIGO_COMMANDS(), Amigo_Execute(), amigo_todo(), amigo_todo_op(), GPIB(), GPIB_COMMANDS(), GPIB_LISTEN(), GPIB_SECONDARY_ADDRESS(), gpib_state_init(), GPIB_TALK(), PRINTER_COMMANDS(), and SS80_COMMANDS().
uint8_t talking_last
gpib last talk address
Definition at line 89 of file gpib.c.
Referenced by gpib_state_init(), and GPIB_TALK().