gpib/gpib_hal.h File Reference
GPIB emulator hardwware layer for HP85 disk emulator project for AVR.
#include `user_config.h`
Data Structures
struct _gpib_t
Macros
#define GPIB_BUS_SETTLE() _delay_us(GPIB_BUS_SETTLE_DELAY)
#define GPIB_TASK_TIC_US SYSTEM_TASK_TIC_US /* Interrupt time in US */
#define SYSTEM_ELAPSED_TIMER /* We have a system elapsed time function */
#define EOI GPIO_B0
#define DAV GPIO_B1
#define NRFD GPIO_D2
#define NDAC GPIO_D3
#define IFC GPIO_D4
#define SRQ GPIO_D5
#define ATN GPIO_D6
#define REN GPIO_D7
#define TE GPIO_C2
#define PE GPIO_C3
#define DC GPIO_C4
#define SC GPIO_C5
#define LED1 GPIO_C6
#define LED2 GPIO_C7
#define PPE GPIO_B2
#define GPIB_BUS_OUT() GPIO_PORT_DIR_OUT(GPIO_A)
changes to state of full 8bit port to out
#define GPIB_BUS_IN() GPIO_PORT_DIR_IN(GPIO_A)
changes to state of full 8bit port to in
#define GPIB_BUS_RD() GPIO_PORT_RD(GPIO_A)
changes to state of full 8bit port to in then read
#define GPIB_BUS_LATCH_WR(val) GPIO_PORT_LATCH_WR(GPIO_A,val)
writes GPIB port latch without changing to write direction
#define GPIB_BUS_WR(val) GPIO_PORT_WR(GPIO_A,val)
changes to state of full 8bit port to out then write
#define GPIB_PIN_FLOAT(a) GPIO_PIN_FLOAT(a)
changes pin mode to read
#define GPIB_PIN_FLOAT_UP(a) GPIO_PIN_FLOAT_UP(a)
changes pin mode to read
#define GPIB_PIN_TST(a) GPIO_PIN_TST(a)
checks the pin state without changing read/write mode
#define GPIB_IO_LOW(a) GPIO_PIN_LOW(a)
changes pin mode to write then set low
#define GPIB_IO_HI(a) GPIO_PIN_HI(a)
changes pin mode to write then set hi
#define GPIB_IO_RD(a) GPIO_PIN_RD(a)
changes pin mode to read, then read
#define GPIB_LATCH_HI(a) GPIO_PIN_LATCH_LOW(a)
Update pin latch state without changing read/write mode.
#define GPIB_LATCH_LOW(a) GPIO_PIN_LATCH_HI(a)
Update pin latch state without changing read/write mode.
#define GPIB_LATCH_RD(a) GPIO_PIN_LATCH_RD(a)
Read the pin latch state without changing read/write mode.
#define GPIB_PPR_RD() GPIO_PORT_PINS_RD(GPIO_A)
We attempt to detect PPR states for logging only PPR is handled in hardware - but useful if we can detect for logging Optional - see gpib_detect_PPR.
#define GPIB_PPR_DDR_RD() GPIO_PORT_DDR_RD(GPIO_A)
read full port direction register state Optional - see gpib_detect_PPR
Typedefs
typedef struct _gpib_t gpib_t
Functions
void gpib_clock_task (void)
void gpib_timer_init (void)
===================================================
uint8_t reverse_8bits (uint8_t mask)
Reverse the bits in an 8 bit value.
void ppr_set (uint8_t mask)
Enable or Disable Parallel Poll Response bits - PPR.
void soft_ppr_assert (void)
void soft_ppr_restore (void)
uint8_t ppr_reg (void)
Return PPR enable register.
void ppr_init (void)
Reset PPR enable register - all disable..
void ppr_bit_set (uint8_t bit)
Enable hardware PPR response for a given device.
void ppr_bit_clr (uint8_t bit)
Disbale hardware PPR response for a given device.
FRESULT dbf_open (FIL *fp, const TCHAR *path, BYTE mode)
Wrapper for FatFs f_open() that can displays errors.
FRESULT dbf_read (FIL *fp, void *buff, UINT btr, UINT *br)
Wrapper for FatFs f_read() that can display errors.
FRESULT dbf_write (FIL *fp, const void *buff, UINT btw, UINT *bw)
wrapper for FatFs f_write() that can display errors.
FRESULT dbf_lseek (FIL *fp, DWORD ofs)
Wrapper of FatFs f_seek() that can display errors.
FRESULT dbf_close (FIL *fp)
Wrapper of FatFs f_close() that can display errors.
int dbf_open_read (char *name, uint32_t pos, void *buff, int size, int *errors)
Open, Seek, Read data and Close FatFs functions.
int dbf_open_write (char *name, uint32_t pos, void *buff, int size, int *errors)
Open, Seek, Write data and Close FatFs functions.
Variables
gpib_t gpib_timer
Detailed Description
GPIB emulator hardwware layer for HP85 disk emulator project for AVR.
Edit History
[1.0] [Mike Gore] Initial revision of file.
Copyright 2014-2020 Mike Gore, All rights reserved. GPL
See also
 http://github.com/magore/hp85disk
 http://github.com/magore/hp85disk/COPYRIGHT.md for Copyright details
Macro Definition Documentation
ATN
#define ATN GPIO_D6
Definition at line 66 of file gpib_hal.h.
DAV
#define DAV GPIO_B1
Definition at line 61 of file gpib_hal.h.
DC
#define DC GPIO_C4
Definition at line 73 of file gpib_hal.h.
EOI
#define EOI GPIO_B0
Notes: `EOI` gets convereted into the required DDR and BIT definitions. We use the comma operator to return the PIN test. We do not use {} around the statements so they behave like functions. Consider what would happen if you used breaces (should be obviious) if (GPIB_IO_RD(EOI)) { printf`EOI`); } else { do stuff } Notes about AVR and PIC differences Your CPU mave have other differences AVR PIC DDR 1=out, 0 =in TRIS 0=out,1=in PORT=val same as LATCH=val PORT=val same as LATCH=val val=PORT, reads LATCH val=PORT reads PIN state val=PIN, reads PIN state val=LATCH reads latch
Definition at line 60 of file gpib_hal.h.
GPIB_BUS_IN
#define GPIB_BUS_IN() GPIO_PORT_DIR_IN(GPIO_A)
changes to state of full 8bit port to in
Definition at line 88 of file gpib_hal.h.
GPIB_BUS_LATCH_WR
#define GPIB_BUS_LATCH_WR(val) GPIO_PORT_LATCH_WR(GPIO_A,val)
writes GPIB port latch without changing to write direction
Definition at line 94 of file gpib_hal.h.
GPIB_BUS_OUT
#define GPIB_BUS_OUT() GPIO_PORT_DIR_OUT(GPIO_A)
changes to state of full 8bit port to out
Definition at line 85 of file gpib_hal.h.
GPIB_BUS_RD
#define GPIB_BUS_RD() GPIO_PORT_RD(GPIO_A)
changes to state of full 8bit port to in then read
Definition at line 91 of file gpib_hal.h.
GPIB_BUS_SETTLE
#define GPIB_BUS_SETTLE() _delay_us(GPIB_BUS_SETTLE_DELAY)
Definition at line 21 of file gpib_hal.h.
GPIB_BUS_WR
#define GPIB_BUS_WR(val) GPIO_PORT_WR(GPIO_A,val)
changes to state of full 8bit port to out then write
Definition at line 97 of file gpib_hal.h.
GPIB_IO_HI
#define GPIB_IO_HI(a) GPIO_PIN_HI(a)
changes pin mode to write then set hi
Definition at line 112 of file gpib_hal.h.
GPIB_IO_LOW
#define GPIB_IO_LOW(a) GPIO_PIN_LOW(a)
changes pin mode to write then set low
Definition at line 109 of file gpib_hal.h.
GPIB_IO_RD
#define GPIB_IO_RD(a) GPIO_PIN_RD(a)
changes pin mode to read, then read
Definition at line 115 of file gpib_hal.h.
GPIB_LATCH_HI
#define GPIB_LATCH_HI(a) GPIO_PIN_LATCH_LOW(a)
Update pin latch state without changing read/write mode.
Definition at line 118 of file gpib_hal.h.
GPIB_LATCH_LOW
#define GPIB_LATCH_LOW(a) GPIO_PIN_LATCH_HI(a)
Update pin latch state without changing read/write mode.
Definition at line 121 of file gpib_hal.h.
GPIB_LATCH_RD
#define GPIB_LATCH_RD(a) GPIO_PIN_LATCH_RD(a)
Read the pin latch state without changing read/write mode.
Definition at line 124 of file gpib_hal.h.
GPIB_PIN_FLOAT
#define GPIB_PIN_FLOAT(a) GPIO_PIN_FLOAT(a)
changes pin mode to read
Definition at line 100 of file gpib_hal.h.
GPIB_PIN_FLOAT_UP
#define GPIB_PIN_FLOAT_UP(a) GPIO_PIN_FLOAT_UP(a)
changes pin mode to read
Definition at line 103 of file gpib_hal.h.
GPIB_PIN_TST
#define GPIB_PIN_TST(a) GPIO_PIN_TST(a)
checks the pin state without changing read/write mode
Definition at line 106 of file gpib_hal.h.
GPIB_PPR_DDR_RD
#define GPIB_PPR_DDR_RD() GPIO_PORT_DDR_RD(GPIO_A)
read full port direction register state Optional - see gpib_detect_PPR
Definition at line 136 of file gpib_hal.h.
GPIB_PPR_RD
#define GPIB_PPR_RD() GPIO_PORT_PINS_RD(GPIO_A)
We attempt to detect PPR states for logging only PPR is handled in hardware - but useful if we can detect for logging Optional - see gpib_detect_PPR.
read full port pins Optional - see gpib_detect_PPR
Definition at line 132 of file gpib_hal.h.
GPIB_TASK_TIC_US
#define GPIB_TASK_TIC_US SYSTEM_TASK_TIC_US /* Interrupt time in US */
Definition at line 23 of file gpib_hal.h.
IFC
#define IFC GPIO_D4
Definition at line 64 of file gpib_hal.h.
LED1
#define LED1 GPIO_C6
Definition at line 75 of file gpib_hal.h.
LED2
#define LED2 GPIO_C7
Definition at line 76 of file gpib_hal.h.
NDAC
#define NDAC GPIO_D3
Definition at line 63 of file gpib_hal.h.
NRFD
#define NRFD GPIO_D2
Definition at line 62 of file gpib_hal.h.
PE
#define PE GPIO_C3
Definition at line 72 of file gpib_hal.h.
PPE
#define PPE GPIO_B2
Definition at line 81 of file gpib_hal.h.
REN
#define REN GPIO_D7
Definition at line 67 of file gpib_hal.h.
SC
#define SC GPIO_C5
Definition at line 74 of file gpib_hal.h.
SRQ
#define SRQ GPIO_D5
Definition at line 65 of file gpib_hal.h.
SYSTEM_ELAPSED_TIMER
#define SYSTEM_ELAPSED_TIMER /* We have a system elapsed time function */
Definition at line 25 of file gpib_hal.h.
TE
#define TE GPIO_C2
Definition at line 71 of file gpib_hal.h.
Typedef Documentation
gpib_t
typedef struct _gpib_t gpib_t
Function Documentation
dbf_close()
FRESULT dbf_close (FIL * fp)
Wrapper of FatFs f_close() that can display errors.
Parameters
 in fp FatFs FIL * pointer.
See also
ff.h.
Returns
FRESULT dbf_close (FIL* fp)
Definition at line 287 of file gpib_hal.c.
Referenced by dbf_open_read(), and dbf_open_write().
dbf_lseek()
FRESULT dbf_lseek (FIL * fp, DWORD ofs)
Wrapper of FatFs f_seek() that can display errors.
Parameters
 in fp FatFs FIL * pointer.
 in ofs seek offset.
See also
ff.h.
Returns
FRESULT
Definition at line 266 of file gpib_hal.c.
Referenced by dbf_open_read(), and dbf_open_write().
dbf_open()
FRESULT dbf_open (FIL * fp, const TCHAR * path, BYTE mode)
Wrapper for FatFs f_open() that can displays errors.
Parameters
 in fp FatFs FIL handle
 in path path name of file to open
 in mode FatFs open mode flags
See also
ff.h
Returns
FRESULT f_open(fp,path, mode);
Definition at line 195 of file gpib_hal.c.
Referenced by dbf_open_read(), and dbf_open_write().
dbf_open_read()
int dbf_open_read (char * name, uint32_t pos, void * buff, int size, int * errors)
Open, Seek, Read data and Close FatFs functions.
Parameters
 in name File name to open.
 in pos file offset.
 out buff buffer to read data into.
 in size bytes to read.
 in errors error flags pointer.
Returns
bytes actually read.
-1 on error.
See also
: ff.h.
Returns
FRESULT
SEEK
Definition at line 314 of file gpib_hal.c.
Referenced by SS80_locate_and_read().
dbf_open_write()
int dbf_open_write (char * name, uint32_t pos, void * buff, int size, int * errors)
Open, Seek, Write data and Close FatFs functions.
Parameters
 in name File name to open.
 in pos file offset.
 in buff buffer to write.
 in size bytes to write.
 in errors error flags pointer.
Returns
bytes actually written.
-1 on error.
See also
: ff.h.
Returns
FRESULT
SEEK
Definition at line 379 of file gpib_hal.c.
Referenced by SS80_locate_and_write().
dbf_read()
FRESULT dbf_read (FIL * fp, void * buff, UINT btr, UINT * br)
Wrapper for FatFs f_read() that can display errors.
Parameters
 in fp FatFs FIL handle.
 in buff buffer to read data into.
 in btr bytes to read.
 in br bytes actually read.
See also
ff.h
Returns
FRESULT f_read (FIL* fp, void* buff, UINT btr, UINT* br)
Definition at line 220 of file gpib_hal.c.
Referenced by dbf_open_read().
dbf_write()
FRESULT dbf_write (FIL * fp, const void * buff, UINT btw, UINT * bw)
wrapper for FatFs f_write() that can display errors.
Parameters
 in fp FatFs FIL handle.
 in buff buffer to write data from.
 in btw bytes to write.
 in bw bytes actually written.
See also
ff.h
Returns
FRESULT f_write (FIL* fp, void* buff, UINT btw, UINT* bw)
Definition at line 244 of file gpib_hal.c.
Referenced by dbf_open_write().
gpib_clock_task()
void gpib_clock_task (void)
gpib_timer_init()
void gpib_timer_init ()
===================================================
===================================================
Has some platform dependent code.
Returns
void
Definition at line 29 of file gpib_hal.c.
Referenced by main().
ppr_bit_clr()
void ppr_bit_clr (uint8_t bit)
Disbale hardware PPR response for a given device.
Parameters
 in bit PPR bit to disable.
HI = PPR bus LOW.
LOW = PPR bus FLOAT.
Device PPR bits are specified in reversed order in GPIB.
0 controlls GPIB D8.
1 controlls GPIB D7.
2 controlls GPIB D6.
3 controlls GPIB D5.
4 controlls GPIB D4.
5 controlls GPIB D3.
6 controlls GPIB D2.
7 controlls GPIB D1.
Returns
void
FIXME _ppr_reg = 0;
Definition at line 177 of file gpib_hal.c.
Referenced by gpib_disable_PPR(), and gpib_tests().
ppr_bit_set()
void ppr_bit_set (uint8_t bit)
Enable hardware PPR response for a given device.
Parameters
 in bit PPR bit to enable.
HI = PPR bus LOW.
LOW = PPR bus FLOAT.
Device PPR bits are specified in reversed order in GPIB.
0 controlls GPIB D8.
1 controlls GPIB D7.
2 controlls GPIB D6.
3 controlls GPIB D5.
4 controlls GPIB D4.
5 controlls GPIB D3.
6 controlls GPIB D2.
7 controlls GPIB D1.
Returns
void
FIXME _ppr_reg = 0;
Definition at line 153 of file gpib_hal.c.
Referenced by gpib_enable_PPR(), and gpib_tests().
ppr_init()
void ppr_init ()
Reset PPR enable register - all disable..
Hides the register access implimentation from the upper level.
Returns
void
Definition at line 126 of file gpib_hal.c.
Referenced by gpib_state_init(), and gpib_tests().
ppr_reg()
uint8_t ppr_reg ()
Return PPR enable register.
Hides the register access implimentation from the upper level.
Returns
PPR enable register
optionally reverse bit order in PPR mask Used only of PPR circuit board PPR bits are not reversed in hardware
Definition at line 109 of file gpib_hal.c.
Referenced by gpib_detect_PP(), gpib_disable_PPR(), and gpib_enable_PPR().
ppr_set()
void ppr_set (uint8_t mask)
Enable or Disable Parallel Poll Response bits - PPR.
V1 hardware reversed bits in hardware. V2 in software
Aside: Software PPR detection is impractical - timing is sub microsecond. That is why both V1 and V2 boards you hardware detection
Mask Bits.
HI = PPR bus LOW.
LOW = PPR bus FLOAT.
Device PPR bits are specified in reversed order in GPIB.
0 controlls GPIB D8.
1 controlls GPIB D7.
2 controlls GPIB D6.
3 controlls GPIB D5.
4 controlls GPIB D4.
5 controlls GPIB D3.
6 controlls GPIB D2.
7 controlls GPIB D1.
Parameters
 in mask Parallel Poll Response bits to enable or disable
Returns
void
optionally reverse bit order in PPR mask Used only of PPR circuit board PPR bits are not reversed in hardware
Definition at line 88 of file gpib_hal.c.
Referenced by gpib_tests(), ppr_bit_clr(), ppr_bit_set(), and ppr_init().
reverse_8bits()
uint8_t reverse_8bits (uint8_t mask)
Reverse the bits in an 8 bit value.
GPIB Parallel poll response bits are reversed.
GPIB D8 controls first device.
GPIB D1 controls last device.
Parameters
 in mask bit mask to reverse.
Returns
reversed bits
Definition at line 49 of file gpib_hal.c.
Referenced by ppr_reg(), and ppr_set().
soft_ppr_assert()
void soft_ppr_assert (void)
soft_ppr_restore()
void soft_ppr_restore (void)
Variable Documentation
gpib_timer
gpib_t gpib_timer
Definition at line 22 of file gpib_hal.c.
Referenced by gpib_timeout_set(), gpib_timeout_test(), gpib_timer_elapsed_begin(), gpib_timer_elapsed_end(), gpib_timer_reset(), and gpib_timer_task().