hardware/i2c.h File Reference
#include `user_config.h`
#include <util/twi.h>
Data Structures
struct i2c_op_t
struct i2c_task_t
Macros
#define TW_ARB_LOST TW_MT_ARB_LOST
#define I2C_OPS 16
#define I2C_TIMEOUT 20
#define I2C_OP_TIMEOUT _BV(0)
#define I2C_OP_LEN _BV(1)
#define I2C_OP_ERROR _BV(2)
#define I2C_TW_MT_SLA_NACK _BV(3)
#define I2C_TW_MR_SLA_NACK _BV(4)
#define I2C_TW_MT_DATA_NACK _BV(5)
#define I2C_BUS_ERROR _BV(6)
Typedefs
typedef int8_t(* i2c_callback_t) (void)
Functions
uint8_t i2c_check_op (int8_t index)
Check if I2C structure pointer is valid.
void i2c_task_init (void)
Initialize I2C task op list NOTE: We ASSUME all i2c_task_op[].buf are statically allocated.
void i2c_task_free_ops (void)
Free all allocated memory for i2c_[] pointers NOTE: We ASSUME all i2c_task_op[].buf are statically allocated.
i2c_op_t * i2c_task_op_add (uint8_t address, uint8_t mode, uint8_t *buf, uint8_t len)
I2C setup new OP but do not run it yet.
int8_t i2c_task_next_op (void)
I2C task ISR callback function.
void i2c_task_run (void)
Run all valid i2c_task_op[] tasks.
void i2c_init (uint32_t speed)
I2C initialize Clear all i2c_task_op[] pointers and disables I2C tasks.
int8_t i2c_ok (void)
check if I2C trasnaction detected an error
int8_t i2c_done (void)
Is i2c structure done sending/receiving ?
int8_t i2c_task_done (void)
Are all i2c_task_op[] pointers done sending/receiving ?
uint8_t i2c_fn (uint8_t address, uint8_t mode, uint8_t *buf, uint8_t len)
I2C setup new OP but do not run it yet.
void i2c_send_start (void)
Send I2C START and enable interrupts.
void i2c_send_stop (void)
Send I2C STOP and disable interrupts.
void i2c_timer (void)
I2C timer task - check for I2C operation timeouts.
void i2c_print_error (i2c_op_t *o)
Display Errors for i2c_task_op[index].
void i2c_display_task_errors (void)
Display any task errors.
Variables
i2c_op_t i2c
I2C interrupt state registers.
i2c_callback_t i2c_callback
i2c_task_t i2c_task
I2C task state.
i2c_op_t * i2c_task_op [I2C_OPS]
I2C task list.
Macro Definition Documentation
I2C_BUS_ERROR
#define I2C_BUS_ERROR _BV(6)
Definition at line 38 of file i2c.h.
Referenced by ISR().
I2C_OP_ERROR
#define I2C_OP_ERROR _BV(2)
Definition at line 34 of file i2c.h.
Referenced by i2c_print_error().
I2C_OP_LEN
#define I2C_OP_LEN _BV(1)
Definition at line 33 of file i2c.h.
Referenced by i2c_print_error().
I2C_OP_TIMEOUT
#define I2C_OP_TIMEOUT _BV(0)
Definition at line 32 of file i2c.h.
Referenced by i2c_print_error(), and ISR().
I2C_OPS
#define I2C_OPS 16
Definition at line 28 of file i2c.h.
Referenced by i2c_check_op(), i2c_display_task_errors(), i2c_init(), and i2c_task_init().
I2C_TIMEOUT
#define I2C_TIMEOUT 20
Definition at line 30 of file i2c.h.
Referenced by i2c_send_start(), i2c_task_next_op(), i2c_task_op_add(), and i2c_task_run().
I2C_TW_MR_SLA_NACK
#define I2C_TW_MR_SLA_NACK _BV(4)
Definition at line 36 of file i2c.h.
Referenced by i2c_print_error(), and ISR().
I2C_TW_MT_DATA_NACK
#define I2C_TW_MT_DATA_NACK _BV(5)
Definition at line 37 of file i2c.h.
Referenced by i2c_print_error(), and ISR().
I2C_TW_MT_SLA_NACK
#define I2C_TW_MT_SLA_NACK _BV(3)
Definition at line 35 of file i2c.h.
Referenced by i2c_print_error(), and ISR().
TW_ARB_LOST
#define TW_ARB_LOST TW_MT_ARB_LOST
Definition at line 25 of file i2c.h.
Referenced by ISR().
Typedef Documentation
i2c_callback_t
typedef int8_t(* i2c_callback_t) (void)
@ brief I2C callback function Used when automattically sending several transactions
Definition at line 61 of file i2c.h.
Function Documentation
i2c_check_op()
uint8_t i2c_check_op (int8_t index)
Check if I2C structure pointer is valid.
Parameters
in index index of i2c_task_op[] array
Returns
1 if OK, 0 if NOT
Definition at line 40 of file i2c.c.
Referenced by i2c_task_free_ops(), i2c_task_next_op(), and i2c_task_run().
i2c_display_task_errors()
void i2c_display_task_errors (void)
Display any task errors.
Definition at line 684 of file i2c.c.
Referenced by main().
i2c_done()
int8_t i2c_done (void)
Is i2c structure done sending/receiving ?
Returns
1 DONE, 0 NOT DONE
Definition at line 379 of file i2c.c.
Referenced by i2c_fn().
i2c_fn()
uint8_t i2c_fn (uint8_t address, uint8_t mode, uint8_t * buf, uint8_t len)
I2C setup new OP but do not run it yet.
Parameters
in address I2C address
in mode TW_READ or TW_WRITE
in *buf pointer to buffer for send or receive
in len size of buffer to read or write
Returns
1 = OK, 0 = ERROR
Definition at line 407 of file i2c.c.
Referenced by i2c_rtc_read(), and i2c_rtc_write().
i2c_init()
void i2c_init (uint32_t speed)
I2C initialize Clear all i2c_task_op[] pointers and disables I2C tasks.
=========================================================================
Returns
void
Definition at line 316 of file i2c.c.
Referenced by i2c_rtc_init(), and main().
i2c_ok()
int8_t i2c_ok (void)
check if I2C trasnaction detected an error
Did we get an error durring any i2c_task_op[] seand/receive operations
Returns
1 OK, 0 NOT OK
Definition at line 369 of file i2c.c.
i2c_print_error()
void i2c_print_error (i2c_op_t * o)
Display Errors for i2c_task_op[index].
Parameters
in index index of i2c_task_op[] array
Returns
void
Definition at line 660 of file i2c.c.
Referenced by i2c_display_task_errors().
i2c_send_start()
void i2c_send_start (void)
Send I2C START and enable interrupts.
Returns
void
Definition at line 451 of file i2c.c.
Referenced by i2c_fn(), i2c_task_next_op(), and i2c_task_run().
i2c_send_stop()
void i2c_send_stop (void)
Send I2C STOP and disable interrupts.
Returns
void
Definition at line 468 of file i2c.c.
Referenced by i2c_next(), i2c_task_next_op(), and ISR().
i2c_task_done()
int8_t i2c_task_done (void)
Are all i2c_task_op[] pointers done sending/receiving ?
Returns
1 DONE, 0 NOT DONE
Definition at line 390 of file i2c.c.
i2c_task_free_ops()
void i2c_task_free_ops (void)
Free all allocated memory for i2c_[] pointers NOTE: We ASSUME all i2c_task_op[].buf are statically allocated.
Returns
void
Definition at line 92 of file i2c.c.
i2c_task_init()
void i2c_task_init (void)
Initialize I2C task op list NOTE: We ASSUME all i2c_task_op[].buf are statically allocated.
Returns
void
Definition at line 69 of file i2c.c.
i2c_task_next_op()
int8_t i2c_task_next_op (void)
I2C task ISR callback function.
Returns
void
Definition at line 163 of file i2c.c.
Referenced by i2c_task_run().
i2c_task_op_add()
i2c_op_t* i2c_task_op_add (uint8_t address, uint8_t mode, uint8_t * buf, uint8_t len)
I2C setup new OP but do not run it yet.
Parameters
in address I2C address
in mode TW_READ or TW_WRITE
in *buf pointer to buffer for send or receive
in len size of buffer to read or write
Returns
i2c_op_t * pointer
Definition at line 135 of file i2c.c.
i2c_task_run()
void i2c_task_run (void)
Run all valid i2c_task_op[] tasks.
Returns
void
Definition at line 225 of file i2c.c.
Referenced by main().
i2c_timer()
void i2c_timer (void)
I2C timer task - check for I2C operation timeouts.
Returns
void
Definition at line 503 of file i2c.c.
Referenced by i2c_init().
Variable Documentation
i2c
i2c_op_t i2c
I2C interrupt state registers.
Definition at line 22 of file i2c.c.
Referenced by i2c_task_next_op().
i2c_callback
i2c_callback_t i2c_callback
Definition at line 28 of file i2c.c.
Referenced by i2c_fn(), i2c_next(), and i2c_task_run().
i2c_task
i2c_task_t i2c_task
I2C task state.
Definition at line 31 of file i2c.c.
Referenced by main().
i2c_task_op
i2c_op_t* i2c_task_op[I2C_OPS]
I2C task list.
Definition at line 33 of file i2c.c.