hardware/LCD.h File Reference
Macros
#define DISPLAY_ADDRESS1 0x72
#define MAX_ROWS 4
#define MAX_COLUMNS 20
#define SPECIAL_COMMAND 254
#define SETTING_COMMAND 0x7C
#define CLEAR_COMMAND 0x2D
#define CONTRAST_COMMAND 0x18
#define ADDRESS_COMMAND 0x19
#define SET_RGB_COMMAND 0x2B
#define ENABLE_SYSTEM_MESSAGE_DISPLAY 0x2E
#define DISABLE_SYSTEM_MESSAGE_DISPLAY 0x2F
#define ENABLE_SPLASH_DISPLAY 0x30
#define DISABLE_SPLASH_DISPLAY 0x31
#define SAVE_CURRENT_DISPLAY_AS_SPLASH 0x0A
#define LCD_RETURNHOME 0x02
#define LCD_ENTRYMODESET 0x04
#define LCD_DISPLAYCONTROL 0x08
#define LCD_CURSORSHIFT 0x10
#define LCD_SETDDRAMADDR 0x80
#define LCD_ENTRYRIGHT 0x00
#define LCD_ENTRYLEFT 0x02
#define LCD_ENTRYSHIFTINCREMENT 0x01
#define LCD_ENTRYSHIFTDECREMENT 0x00
#define LCD_DISPLAYON 0x04
#define LCD_DISPLAYOFF 0x00
#define LCD_CURSORON 0x02
#define LCD_CURSOROFF 0x00
#define LCD_BLINKON 0x01
#define LCD_BLINKOFF 0x00
#define LCD_DISPLAYMOVE 0x08
#define LCD_CURSORMOVE 0x00
#define LCD_MOVERIGHT 0x04
#define LCD_MOVELEFT 0x00
#define LCD_ADDR (DISPLAY_ADDRESS1<<1)
Typedefs
typedef uint8_t byte
Functions
bool I2C_Start (uint8_t addr)
void I2C_Stop (void)
bool I2C_Send (uint8_t data)
bool I2C_SendMessage (uint8_t addr, const uint8_t *buffer, size_t size)
bool LCD_putb (uint8_t b)
bool LCD_write (const uint8_t *buffer, size_t size)
void LCD_puts (const uint8_t *buffer)
void LCD_pos (uint8_t x, uint8_t y)
Character and String functions
bool LCD_init (uint8_t addr)
end of I2C HAL for hp85disk
void LCD_command (byte command)
void LCD_specialCommand (byte command)
void LCD_specialCommandCount (byte command, byte count)
void LCD_clear (void)
void LCD_home (void)
void LCD_setCursor (byte col, byte row)
void LCD_createChar (byte location, byte charmap [])
void LCD_writeChar (byte location)
void LCD_noDisplay (void)
void LCD_display (void)
void LCD_noCursor (void)
void LCD_cursor (void)
void LCD_noBlink (void)
void LCD_blink (void)
void LCD_scrollDisplayLeftCount (byte count)
void LCD_scrollDisplayLeft (void)
void LCD_scrollDisplayRightCOunt (byte count)
void LCD_scrollDisplayRight (void)
void LCD_moveCursorLeftCount (byte count)
void LCD_moveCursorLeft (void)
void LCD_moveCursorRightCount (byte count)
void LCD_moveCursorRight (void)
void LCD_setFastBacklightRGB (byte r, byte g, byte b)
void LCD_setFastBacklight (unsigned long rgb)
void LCD_enableSystemMessages (void)
void LCD_disableSystemMessages (void)
void LCD_enableSplash (void)
void LCD_disableSplash (void)
void LCD_saveSplash (void)
void LCD_leftToRight (void)
void LCD_rightToLeft (void)
void LCD_autoscroll (void)
void LCD_noAutoscroll (void)
void LCD_setContrast (byte new_val)
void LCD_setAddress (byte new_addr)
Macro Definition Documentation
ADDRESS_COMMAND
#define ADDRESS_COMMAND 0x19
Definition at line 17 of file LCD.h.
Referenced by LCD_setAddress().
CLEAR_COMMAND
#define CLEAR_COMMAND 0x2D
Definition at line 15 of file LCD.h.
Referenced by LCD_clear(), and LCD_init().
CONTRAST_COMMAND
#define CONTRAST_COMMAND 0x18
Definition at line 16 of file LCD.h.
Referenced by LCD_setContrast().
DISABLE_SPLASH_DISPLAY
#define DISABLE_SPLASH_DISPLAY 0x31
Definition at line 22 of file LCD.h.
Referenced by LCD_disableSplash().
DISABLE_SYSTEM_MESSAGE_DISPLAY
#define DISABLE_SYSTEM_MESSAGE_DISPLAY 0x2F
Definition at line 20 of file LCD.h.
Referenced by LCD_disableSystemMessages(), and LCD_init().
DISPLAY_ADDRESS1
#define DISPLAY_ADDRESS1 0x72
Definition at line 6 of file LCD.h.
ENABLE_SPLASH_DISPLAY
#define ENABLE_SPLASH_DISPLAY 0x30
Definition at line 21 of file LCD.h.
Referenced by LCD_enableSplash().
ENABLE_SYSTEM_MESSAGE_DISPLAY
#define ENABLE_SYSTEM_MESSAGE_DISPLAY 0x2E
Definition at line 19 of file LCD.h.
Referenced by LCD_enableSystemMessages().
LCD_ADDR
#define LCD_ADDR (DISPLAY_ADDRESS1<<1)
Definition at line 54 of file LCD.h.
LCD_BLINKOFF
#define LCD_BLINKOFF 0x00
Definition at line 44 of file LCD.h.
LCD_BLINKON
#define LCD_BLINKON 0x01
Definition at line 43 of file LCD.h.
Referenced by LCD_blink(), and LCD_noBlink().
LCD_CURSORMOVE
#define LCD_CURSORMOVE 0x00
Definition at line 48 of file LCD.h.
Referenced by LCD_moveCursorLeftCount(), and LCD_moveCursorRightCount().
LCD_CURSOROFF
#define LCD_CURSOROFF 0x00
Definition at line 42 of file LCD.h.
LCD_CURSORON
#define LCD_CURSORON 0x02
Definition at line 41 of file LCD.h.
Referenced by LCD_cursor(), and LCD_noCursor().
LCD_CURSORSHIFT
#define LCD_CURSORSHIFT 0x10
Definition at line 29 of file LCD.h.
Referenced by LCD_moveCursorLeftCount(), LCD_moveCursorRightCount(), LCD_scrollDisplayLeftCount(), and LCD_scrollDisplayRightCOunt().
LCD_DISPLAYCONTROL
#define LCD_DISPLAYCONTROL 0x08
Definition at line 28 of file LCD.h.
Referenced by LCD_blink(), LCD_cursor(), LCD_display(), LCD_init(), LCD_noBlink(), LCD_noCursor(), and LCD_noDisplay().
LCD_DISPLAYMOVE
#define LCD_DISPLAYMOVE 0x08
Definition at line 47 of file LCD.h.
Referenced by LCD_scrollDisplayLeftCount(), and LCD_scrollDisplayRightCOunt().
LCD_DISPLAYOFF
#define LCD_DISPLAYOFF 0x00
Definition at line 40 of file LCD.h.
LCD_DISPLAYON
#define LCD_DISPLAYON 0x04
Definition at line 39 of file LCD.h.
Referenced by LCD_display(), and LCD_noDisplay().
LCD_ENTRYLEFT
#define LCD_ENTRYLEFT 0x02
Definition at line 34 of file LCD.h.
Referenced by LCD_leftToRight(), and LCD_rightToLeft().
LCD_ENTRYMODESET
#define LCD_ENTRYMODESET 0x04
Definition at line 27 of file LCD.h.
Referenced by LCD_autoscroll(), LCD_init(), LCD_leftToRight(), LCD_noAutoscroll(), and LCD_rightToLeft().
LCD_ENTRYRIGHT
#define LCD_ENTRYRIGHT 0x00
Definition at line 33 of file LCD.h.
LCD_ENTRYSHIFTDECREMENT
#define LCD_ENTRYSHIFTDECREMENT 0x00
Definition at line 36 of file LCD.h.
LCD_ENTRYSHIFTINCREMENT
#define LCD_ENTRYSHIFTINCREMENT 0x01
Definition at line 35 of file LCD.h.
Referenced by LCD_autoscroll(), and LCD_noAutoscroll().
LCD_MOVELEFT
#define LCD_MOVELEFT 0x00
Definition at line 50 of file LCD.h.
Referenced by LCD_moveCursorLeftCount(), and LCD_scrollDisplayLeftCount().
LCD_MOVERIGHT
#define LCD_MOVERIGHT 0x04
Definition at line 49 of file LCD.h.
Referenced by LCD_moveCursorRightCount(), and LCD_scrollDisplayRightCOunt().
LCD_RETURNHOME
#define LCD_RETURNHOME 0x02
Definition at line 26 of file LCD.h.
Referenced by LCD_home().
LCD_SETDDRAMADDR
#define LCD_SETDDRAMADDR 0x80
Definition at line 30 of file LCD.h.
Referenced by LCD_init(), and LCD_setCursor().
MAX_COLUMNS
#define MAX_COLUMNS 20
Definition at line 8 of file LCD.h.
MAX_ROWS
#define MAX_ROWS 4
Definition at line 7 of file LCD.h.
Referenced by LCD_setCursor().
SAVE_CURRENT_DISPLAY_AS_SPLASH
#define SAVE_CURRENT_DISPLAY_AS_SPLASH 0x0A
Definition at line 23 of file LCD.h.
Referenced by LCD_saveSplash().
SET_RGB_COMMAND
#define SET_RGB_COMMAND 0x2B
Definition at line 18 of file LCD.h.
Referenced by LCD_setFastBacklightRGB().
SETTING_COMMAND
#define SETTING_COMMAND 0x7C
Definition at line 12 of file LCD.h.
Referenced by LCD_command(), LCD_createChar(), LCD_disableSplash(), LCD_disableSystemMessages(), LCD_enableSplash(), LCD_enableSystemMessages(), LCD_init(), LCD_saveSplash(), LCD_setAddress(), LCD_setContrast(), and LCD_setFastBacklightRGB().
SPECIAL_COMMAND
#define SPECIAL_COMMAND 254
Definition at line 11 of file LCD.h.
Referenced by LCD_init(), LCD_specialCommand(), and LCD_specialCommandCount().
Typedef Documentation
byte
typedef uint8_t byte
Definition at line 4 of file LCD.h.
Function Documentation
I2C_Send()
bool I2C_Send (uint8_t data)
Definition at line 131 of file LCD.c.
Referenced by LCD_command(), LCD_createChar(), LCD_disableSplash(), LCD_disableSystemMessages(), LCD_enableSplash(), LCD_enableSystemMessages(), LCD_init(), LCD_putb(), LCD_saveSplash(), LCD_setAddress(), LCD_setContrast(), LCD_setFastBacklightRGB(), LCD_specialCommand(), and LCD_specialCommandCount().
I2C_SendMessage()
bool I2C_SendMessage (uint8_t addr, const uint8_t * buffer, size_t size)
Definition at line 143 of file LCD.c.
Referenced by LCD_write().
I2C_Start()
bool I2C_Start (uint8_t addr)
Definition at line 105 of file LCD.c.
Referenced by I2C_SendMessage(), LCD_command(), LCD_createChar(), LCD_disableSplash(), LCD_disableSystemMessages(), LCD_enableSplash(), LCD_enableSystemMessages(), LCD_init(), LCD_putb(), LCD_saveSplash(), LCD_setAddress(), LCD_setContrast(), LCD_setFastBacklightRGB(), LCD_specialCommand(), and LCD_specialCommandCount().
I2C_Stop()
void I2C_Stop (void)
Definition at line 118 of file LCD.c.
Referenced by I2C_SendMessage(), LCD_command(), LCD_createChar(), LCD_disableSplash(), LCD_disableSystemMessages(), LCD_enableSplash(), LCD_enableSystemMessages(), LCD_init(), LCD_putb(), LCD_saveSplash(), LCD_setAddress(), LCD_setContrast(), LCD_setFastBacklightRGB(), LCD_specialCommand(), and LCD_specialCommandCount().
LCD_autoscroll()
void LCD_autoscroll (void)
Definition at line 649 of file LCD.c.
LCD_blink()
void LCD_blink (void)
Definition at line 442 of file LCD.c.
LCD_clear()
void LCD_clear (void)
Definition at line 313 of file LCD.c.
LCD_command()
void LCD_command (byte command)
Definition at line 256 of file LCD.c.
Referenced by LCD_clear(), and LCD_writeChar().
LCD_createChar()
void LCD_createChar (byte location, byte charmap[])
Definition at line 360 of file LCD.c.
LCD_cursor()
void LCD_cursor (void)
Definition at line 422 of file LCD.c.
LCD_disableSplash()
void LCD_disableSplash (void)
Definition at line 599 of file LCD.c.
LCD_disableSystemMessages()
void LCD_disableSystemMessages (void)
Definition at line 575 of file LCD.c.
LCD_display()
void LCD_display (void)
Definition at line 402 of file LCD.c.
LCD_enableSplash()
void LCD_enableSplash (void)
Definition at line 587 of file LCD.c.
LCD_enableSystemMessages()
void LCD_enableSystemMessages (void)
Definition at line 562 of file LCD.c.
LCD_home()
void LCD_home (void)
Definition at line 326 of file LCD.c.
LCD_init()
bool LCD_init (uint8_t addr)
end of I2C HAL for hp85disk
Definition at line 214 of file LCD.c.
LCD_leftToRight()
void LCD_leftToRight (void)
Definition at line 628 of file LCD.c.
LCD_moveCursorLeft()
void LCD_moveCursorLeft (void)
Definition at line 507 of file LCD.c.
LCD_moveCursorLeftCount()
void LCD_moveCursorLeftCount (byte count)
Definition at line 498 of file LCD.c.
Referenced by LCD_moveCursorLeft().
LCD_moveCursorRight()
void LCD_moveCursorRight (void)
Definition at line 527 of file LCD.c.
LCD_moveCursorRightCount()
void LCD_moveCursorRightCount (byte count)
Definition at line 518 of file LCD.c.
Referenced by LCD_moveCursorRight().
LCD_noAutoscroll()
void LCD_noAutoscroll (void)
Definition at line 659 of file LCD.c.
LCD_noBlink()
void LCD_noBlink (void)
Definition at line 432 of file LCD.c.
LCD_noCursor()
void LCD_noCursor (void)
Definition at line 412 of file LCD.c.
LCD_noDisplay()
void LCD_noDisplay (void)
Definition at line 392 of file LCD.c.
LCD_pos()
void LCD_pos (uint8_t x, uint8_t y)
Character and String functions
====================================
Definition at line 198 of file LCD.c.
Referenced by LCD_clear().
LCD_putb()
bool LCD_putb (uint8_t b)
Definition at line 162 of file LCD.c.
LCD_puts()
void LCD_puts (const uint8_t * buffer)
Definition at line 189 of file LCD.c.
LCD_rightToLeft()
void LCD_rightToLeft (void)
Definition at line 638 of file LCD.c.
LCD_saveSplash()
void LCD_saveSplash (void)
Definition at line 611 of file LCD.c.
LCD_scrollDisplayLeft()
void LCD_scrollDisplayLeft (void)
Definition at line 465 of file LCD.c.
LCD_scrollDisplayLeftCount()
void LCD_scrollDisplayLeftCount (byte count)
Definition at line 455 of file LCD.c.
Referenced by LCD_scrollDisplayLeft().
LCD_scrollDisplayRight()
void LCD_scrollDisplayRight (void)
Definition at line 487 of file LCD.c.
LCD_scrollDisplayRightCOunt()
void LCD_scrollDisplayRightCOunt (byte count)
Definition at line 477 of file LCD.c.
Referenced by LCD_scrollDisplayRight().
LCD_setAddress()
void LCD_setAddress (byte new_addr)
Definition at line 693 of file LCD.c.
LCD_setContrast()
void LCD_setContrast (byte new_val)
Definition at line 671 of file LCD.c.
LCD_setCursor()
void LCD_setCursor (byte col, byte row)
Definition at line 340 of file LCD.c.
Referenced by LCD_pos().
LCD_setFastBacklight()
void LCD_setFastBacklight (unsigned long rgb)
Definition at line 550 of file LCD.c.
LCD_setFastBacklightRGB()
void LCD_setFastBacklightRGB (byte r, byte g, byte b)
Definition at line 534 of file LCD.c.
Referenced by LCD_init(), and LCD_setFastBacklight().
LCD_specialCommand()
void LCD_specialCommand (byte command)
Definition at line 273 of file LCD.c.
Referenced by LCD_autoscroll(), LCD_blink(), LCD_cursor(), LCD_display(), LCD_home(), LCD_leftToRight(), LCD_noAutoscroll(), LCD_noBlink(), LCD_noCursor(), LCD_noDisplay(), LCD_rightToLeft(), and LCD_setCursor().
LCD_specialCommandCount()
void LCD_specialCommandCount (byte command, byte count)
Definition at line 292 of file LCD.c.
Referenced by LCD_moveCursorLeftCount(), LCD_moveCursorRightCount(), LCD_scrollDisplayLeftCount(), and LCD_scrollDisplayRightCOunt().
LCD_write()
bool LCD_write (const uint8_t * buffer, size_t size)
Definition at line 177 of file LCD.c.
Referenced by LCD_puts().
LCD_writeChar()
void LCD_writeChar (byte location)
Definition at line 382 of file LCD.c.