hardware/LCD.c File Reference
#include `user_config.h`
#include `LCD.h`
Macros
#define LCD_ADDR (DISPLAY_ADDRESS1<<1)
Functions
bool I2C_Start (uint8_t addr)
void I2C_Stop ()
bool I2C_Send (uint8_t data)
bool I2C_SendMessage (uint8_t addr, const uint8_t *buffer, size_t size)
bool LCD_putb (uint8_t b)
bool LCD_write (const uint8_t *buffer, size_t size)
void LCD_puts (const uint8_t *buffer)
void LCD_pos (uint8_t x, uint8_t y)
Character and String functions
bool LCD_init (uint8_t addr)
end of I2C HAL for hp85disk
void LCD_command (byte command)
void LCD_specialCommand (byte command)
void LCD_specialCommandCount (byte command, byte count)
void LCD_clear ()
void LCD_home ()
void LCD_setCursor (byte col, byte row)
void LCD_createChar (byte location, byte charmap[])
void LCD_writeChar (byte location)
void LCD_noDisplay ()
void LCD_display ()
void LCD_noCursor ()
void LCD_cursor ()
void LCD_noBlink ()
void LCD_blink ()
void LCD_scrollDisplayLeftCount (byte count)
void LCD_scrollDisplayLeft ()
void LCD_scrollDisplayRightCOunt (byte count)
void LCD_scrollDisplayRight ()
void LCD_moveCursorLeftCount (byte count)
void LCD_moveCursorLeft ()
void LCD_moveCursorRightCount (byte count)
void LCD_moveCursorRight ()
void LCD_setFastBacklightRGB (byte r, byte g, byte b)
void LCD_setFastBacklight (unsigned long rgb)
void LCD_enableSystemMessages ()
void LCD_disableSystemMessages ()
void LCD_enableSplash ()
void LCD_disableSplash ()
void LCD_saveSplash ()
void LCD_leftToRight ()
void LCD_rightToLeft ()
void LCD_autoscroll ()
void LCD_noAutoscroll ()
void LCD_setContrast (byte new_val)
void LCD_setAddress (byte new_addr)
Variables
static byte _displayControl = LCD_DISPLAYON | LCD_CURSOROFF | LCD_BLINKOFF
static byte _displayMode = LCD_ENTRYLEFT | LCD_ENTRYSHIFTDECREMENT
static uint8_t lcd_address = LCD_ADDR
window lcd
bool LCD_ok = 1
I2C HAL for hp85disk Interface with the project TWI code.
Macro Definition Documentation
LCD_ADDR
#define LCD_ADDR (DISPLAY_ADDRESS1<<1)
Definition at line 103 of file LCD.c.
Referenced by LCD_putb(), LCD_write(), and main().
Function Documentation
I2C_Send()
bool I2C_Send (uint8_t data)
Definition at line 129 of file LCD.c.
Referenced by LCD_command(), LCD_createChar(), LCD_disableSplash(), LCD_disableSystemMessages(), LCD_enableSplash(), LCD_enableSystemMessages(), LCD_init(), LCD_putb(), LCD_saveSplash(), LCD_setAddress(), LCD_setContrast(), LCD_setFastBacklightRGB(), LCD_specialCommand(), and LCD_specialCommandCount().
I2C_SendMessage()
bool I2C_SendMessage (uint8_t addr, const uint8_t * buffer, size_t size)
Definition at line 141 of file LCD.c.
Referenced by LCD_write().
I2C_Start()
bool I2C_Start (uint8_t addr)
Definition at line 105 of file LCD.c.
Referenced by I2C_SendMessage(), LCD_command(), LCD_createChar(), LCD_disableSplash(), LCD_disableSystemMessages(), LCD_enableSplash(), LCD_enableSystemMessages(), LCD_init(), LCD_putb(), LCD_saveSplash(), LCD_setAddress(), LCD_setContrast(), LCD_setFastBacklightRGB(), LCD_specialCommand(), and LCD_specialCommandCount().
I2C_Stop()
void I2C_Stop (void)
Definition at line 117 of file LCD.c.
Referenced by I2C_SendMessage(), LCD_command(), LCD_createChar(), LCD_disableSplash(), LCD_disableSystemMessages(), LCD_enableSplash(), LCD_enableSystemMessages(), LCD_init(), LCD_putb(), LCD_saveSplash(), LCD_setAddress(), LCD_setContrast(), LCD_setFastBacklightRGB(), LCD_specialCommand(), and LCD_specialCommandCount().
LCD_autoscroll()
void LCD_autoscroll (void)
Definition at line 612 of file LCD.c.
LCD_blink()
void LCD_blink (void)
Definition at line 421 of file LCD.c.
LCD_clear()
void LCD_clear (void)
Definition at line 301 of file LCD.c.
LCD_command()
void LCD_command (byte command)
Definition at line 247 of file LCD.c.
Referenced by LCD_clear(), and LCD_writeChar().
LCD_createChar()
void LCD_createChar (byte location, byte charmap[])
Definition at line 346 of file LCD.c.
LCD_cursor()
void LCD_cursor (void)
Definition at line 403 of file LCD.c.
LCD_disableSplash()
void LCD_disableSplash (void)
Definition at line 566 of file LCD.c.
LCD_disableSystemMessages()
void LCD_disableSystemMessages (void)
Definition at line 544 of file LCD.c.
LCD_display()
void LCD_display (void)
Definition at line 385 of file LCD.c.
LCD_enableSplash()
void LCD_enableSplash (void)
Definition at line 555 of file LCD.c.
LCD_enableSystemMessages()
void LCD_enableSystemMessages (void)
Definition at line 532 of file LCD.c.
LCD_home()
void LCD_home (void)
Definition at line 313 of file LCD.c.
LCD_init()
bool LCD_init (uint8_t addr)
end of I2C HAL for hp85disk
Definition at line 207 of file LCD.c.
Referenced by main().
LCD_leftToRight()
void LCD_leftToRight (void)
Definition at line 593 of file LCD.c.
LCD_moveCursorLeft()
void LCD_moveCursorLeft (void)
Definition at line 481 of file LCD.c.
LCD_moveCursorLeftCount()
void LCD_moveCursorLeftCount (byte count)
Definition at line 472 of file LCD.c.
Referenced by LCD_moveCursorLeft().
LCD_moveCursorRight()
void LCD_moveCursorRight (void)
Definition at line 499 of file LCD.c.
LCD_moveCursorRightCount()
void LCD_moveCursorRightCount (byte count)
Definition at line 491 of file LCD.c.
Referenced by LCD_moveCursorRight().
LCD_noAutoscroll()
void LCD_noAutoscroll (void)
Definition at line 621 of file LCD.c.
LCD_noBlink()
void LCD_noBlink (void)
Definition at line 412 of file LCD.c.
LCD_noCursor()
void LCD_noCursor (void)
Definition at line 394 of file LCD.c.
LCD_noDisplay()
void LCD_noDisplay (void)
Definition at line 376 of file LCD.c.
LCD_pos()
void LCD_pos (uint8_t x, uint8_t y)
Character and String functions
====================================
Definition at line 192 of file LCD.c.
Referenced by LCD_clear(), and main().
LCD_putb()
bool LCD_putb (uint8_t b)
Definition at line 159 of file LCD.c.
LCD_puts()
void LCD_puts (const uint8_t * buffer)
Definition at line 184 of file LCD.c.
LCD_rightToLeft()
void LCD_rightToLeft (void)
Definition at line 602 of file LCD.c.
LCD_saveSplash()
void LCD_saveSplash (void)
Definition at line 577 of file LCD.c.
LCD_scrollDisplayLeft()
void LCD_scrollDisplayLeft (void)
Definition at line 442 of file LCD.c.
LCD_scrollDisplayLeftCount()
void LCD_scrollDisplayLeftCount (byte count)
Definition at line 433 of file LCD.c.
Referenced by LCD_scrollDisplayLeft().
LCD_scrollDisplayRight()
void LCD_scrollDisplayRight (void)
Definition at line 462 of file LCD.c.
LCD_scrollDisplayRightCOunt()
void LCD_scrollDisplayRightCOunt (byte count)
Definition at line 453 of file LCD.c.
Referenced by LCD_scrollDisplayRight().
LCD_setAddress()
void LCD_setAddress (byte new_addr)
Definition at line 653 of file LCD.c.
LCD_setContrast()
void LCD_setContrast (byte new_val)
Definition at line 632 of file LCD.c.
LCD_setCursor()
void LCD_setCursor (byte col, byte row)
Definition at line 327 of file LCD.c.
Referenced by LCD_pos().
LCD_setFastBacklight()
void LCD_setFastBacklight (unsigned long rgb)
Definition at line 521 of file LCD.c.
LCD_setFastBacklightRGB()
void LCD_setFastBacklightRGB (byte r, byte g, byte b)
Definition at line 506 of file LCD.c.
Referenced by LCD_init(), and LCD_setFastBacklight().
LCD_specialCommand()
void LCD_specialCommand (byte command)
Definition at line 263 of file LCD.c.
Referenced by LCD_autoscroll(), LCD_blink(), LCD_cursor(), LCD_display(), LCD_home(), LCD_leftToRight(), LCD_noAutoscroll(), LCD_noBlink(), LCD_noCursor(), LCD_noDisplay(), LCD_rightToLeft(), and LCD_setCursor().
LCD_specialCommandCount()
void LCD_specialCommandCount (byte command, byte count)
Definition at line 281 of file LCD.c.
Referenced by LCD_moveCursorLeftCount(), LCD_moveCursorRightCount(), LCD_scrollDisplayLeftCount(), and LCD_scrollDisplayRightCOunt().
LCD_write()
bool LCD_write (const uint8_t * buffer, size_t size)
Definition at line 173 of file LCD.c.
Referenced by LCD_puts().
LCD_writeChar()
void LCD_writeChar (byte location)
Definition at line 367 of file LCD.c.
Variable Documentation
_displayControl
byte _displayControl = LCD_DISPLAYON | LCD_CURSOROFF | LCD_BLINKOFF [static]
Definition at line 93 of file LCD.c.
Referenced by LCD_blink(), LCD_cursor(), LCD_display(), LCD_init(), LCD_noBlink(), LCD_noCursor(), and LCD_noDisplay().
_displayMode
byte _displayMode = LCD_ENTRYLEFT | LCD_ENTRYSHIFTDECREMENT [static]
Definition at line 94 of file LCD.c.
Referenced by LCD_autoscroll(), LCD_init(), LCD_leftToRight(), LCD_noAutoscroll(), and LCD_rightToLeft().
lcd
window lcd
Referenced by LCD_init(), and LCD_pos().
lcd_address
uint8_t lcd_address = LCD_ADDR [static]
Definition at line 95 of file LCD.c.
Referenced by LCD_command(), LCD_createChar(), LCD_disableSplash(), LCD_disableSystemMessages(), LCD_enableSplash(), LCD_enableSystemMessages(), LCD_init(), LCD_saveSplash(), LCD_setAddress(), LCD_setContrast(), LCD_setFastBacklightRGB(), LCD_specialCommand(), and LCD_specialCommandCount().
LCD_ok
bool LCD_ok = 1
I2C HAL for hp85disk Interface with the project TWI code.
Definition at line 102 of file LCD.c.
Referenced by I2C_Send(), I2C_Start(), and I2C_Stop().