lif/lifsup.h File Reference
LIF file utilities - utilities extracted from hp85disk project for stand alone use.
Functions
struct tm * gmtime_r (const time_t *timep, struct tm *result)
char * asctime_r (const struct tm *tm, char *buf)
time_t timegm (struct tm *a_tm)
Convert tm_t structure as GMT time into GMT seconds since 1900. All calculactions are in GMT regardless of timezoe settings.
int MATCHARGS (char *str, char *pat, int min, int argc)
Match two strings and compare argument index Display message if the number of arguments is too few.
MEMSPACE void trim_tail (char *str)
Trim White space and control characters from end of string.
MEMSPACE void V2B_MSB (uint8_t *B, int index, int size, uint32_t val)
Convert Value into byte array bytes are MSB ... LSB order.
MEMSPACE void V2B_LSB (uint8_t *B, int index, int size, uint32_t val)
Convert Value into byte array bytes are LSB ... MSB order.
MEMSPACE uint32_t B2V_MSB (uint8_t *B, int index, int size)
Convert a byte array into a value bytes are MSB ... LSB order.
MEMSPACE uint32_t B2V_LSB (uint8_t *B, int index, int size)
Convert a byte array into a value bytes are LSB ... MSB order.
void B2S (uint8_t *B, int index, uint8_t *name, int size)
void BITSET_LSB (uint8_t *p, int bit)
void BITCLR_LSB (uint8_t *p, int bit)
int BITTST_LSB (uint8_t *p, int bit)
uint16_t crc16 (uint8_t *B, uint16_t crc, uint16_t poly, int size)
MEMSPACE void hexdump (uint8_t *data, int size)
void td02lif_usage (char *name)
Detailed Description
LIF file utilities - utilities extracted from hp85disk project for stand alone use.
Copyright 2014-2017 Mike Gore, All rights reserved. GPL
See also
http://github.com/magore/hp85disk
http://github.com/magore/hp85disk/COPYRIGHT.md for Copyright details
Edit History
[1.0] [Mike Gore] Initial revision of file.
Function Documentation
char* asctime_r (const struct tm * tm, char * buf)
void B2S (uint8_t * B, int index, uint8_t * name, int size)
Referenced by td0_unpack_disk_header().
MEMSPACE uint32_t B2V_LSB (uint8_t * B, int index, int size)
Convert a byte array into a value bytes are LSB ... MSB order.
Parameters
B byte array
index offset into byte array
size number of bytes to process
Returns
value
Definition at line 271 of file drives.c.
Referenced by lif_str2dir(), td0_read_image(), td0_rle(), td0_unpack_comment_header(), td0_unpack_disk_header(), td0_unpack_sector_header(), and td0_unpack_track_header().
MEMSPACE uint32_t B2V_MSB (uint8_t * B, int index, int size)
Convert a byte array into a value bytes are MSB ... LSB order.
Parameters
B byte array
index offset into byte array
size number of bytes to process
Returns
value
Definition at line 252 of file drives.c.
Referenced by lif_str2dir(), lif_str2vol(), and SS80_Command_State().
void BITCLR_LSB (uint8_t * p, int bit)
void BITSET_LSB (uint8_t * p, int bit)
int BITTST_LSB (uint8_t * p, int bit)
uint16_t crc16 (uint8_t * B, uint16_t crc, uint16_t poly, int size)
Referenced by td0_read_image(), td0_unpack_comment_header(), td0_unpack_disk_header(), and td0_unpack_track_header().
struct tm* gmtime_r (const time_t * timep, struct tm * result)
MEMSPACE void hexdump (uint8_t * data, int size)
int MATCHARGS (char * str, char * pat, int min, int argc)
Match two strings and compare argument index Display message if the number of arguments is too few.
Parameters
str string to test
pat pattern to match
min minumum number or arguments
argc actual number of arguments
Returns
1 on match, 0 on no match or too few arguments
Definition at line 471 of file stringsup.c.
Referenced by fatfs_tests(), gpib_tests(), lif_tests(), posix_tests(), and task().
void td02lif_usage (char * name)
time_t timegm (tm_t * t)
Convert tm_t structure as GMT time into GMT seconds since 1900. All calculactions are in GMT regardless of timezoe settings.
Standards: GNU and BSD.
Limits: year(1900..2199).
Assume: epoch size is time_t;
See also
mktime() POSIX function.
timegm() POSIX function.
normalize() and tm2epoch non POSIX functions
Returns
Seconds since EPOCH_YEAR Jan 1st.
-1 on error.
Definition at line 347 of file time.c.
Referenced by display_clock(), fat_time_to_unix(), find_dst(), initialize_clock(), lif_lifbcd2time(), setdate_r(), and td0_read_image().
MEMSPACE void trim_tail (char * str)
Trim White space and control characters from end of string.
Parameters
in str string
Returns
void
Warning
Overwrites White space and control characters with EOS.
Definition at line 271 of file stringsup.c.
Referenced by cat(), lif_add_ascii_file_as_e010_wrapper(), lif_B2S(), lif_ctime_gmt(), and POSIX_Read_Config().
MEMSPACE void V2B_LSB (uint8_t * B, int index, int size, uint32_t val)
Convert Value into byte array bytes are LSB ... MSB order.
Parameters
B byte array
index offset into byte array
size number of bytes to process
val Value to convert
Returns
void
Definition at line 236 of file drives.c.
Referenced by lif_dir2str().
MEMSPACE void V2B_MSB (uint8_t * B, int index, int size, uint32_t val)
Convert Value into byte array bytes are MSB ... LSB order.
Parameters
B byte array
index offset into byte array
size number of bytes to process
val Value to convert
Returns
void
Definition at line 219 of file drives.c.
Referenced by lif_dir2str(), lif_vol2str(), Send_Identify(), SS80_send_status(), and V2B_MSB_Index1().