lif/lifutils.c File Reference
LIF file utilities.
#include `hardware/user_config.h`
#include `vector.h`
#include `drives_sup.h`
#include `lifsup.h`
#include `lifutils.h`
Functions
MEMSPACE void lif_help (int full)
Help Menu for User invoked GPIB functions and tasks See: int gpib_tests(char *str)
MEMSPACE int lif_tests (int argc, char *argv[])
LIF user tests.
MEMSPACE void * lif_calloc (long size)
Allocate and clear memory Displays message on errors.
MEMSPACE void lif_free (void *p)
Free allocated memory Displays message on errors.
MEMSPACE char * lif_stralloc (char *str)
Allocate and copy a string Displays message on errors.
MEMSPACE FILE * lif_open (char *name, char *mode)
Open a file that must exist Displays message on errors.
MEMSPACE stat_t * lif_stat (char *name, stat_t *p)
Stat a file Displays message on errors.
MEMSPACE int lif_seek_msg (FILE *fp, long offset, char *msg)
MEMSPACE long lif_read (lif_t *LIF, void *buf, long offset, int bytes)
Read data from a LIF image Displays message on errors.
MEMSPACE int lif_write (lif_t *LIF, void *buf, long offset, int bytes)
Write data to an LIF image Displays message on errors.
MEMSPACE int lif_chars (int c, int index __attribute__((unused)))
Check if characters in a LIF volume or LIF file name are valid.
MEMSPACE int lif_B2S (uint8_t *B, uint8_t *name, int size)
Convert LIF space padded string name into normal string.
MEMSPACE int lif_checkname (char *name)
Check volume LIF name or directory name is valid.
MEMSPACE void lif_S2B (uint8_t *B, uint8_t *name, int size)
Convert string to LIF directory record.
MEMSPACE int lif_fixname (uint8_t *B, char *name, int size)
Convert name into a valid LIF name Only use the basename() part of the string and remove any file name extentions LIF names may have only these characters: [A-Z][A-Z0-09_]+ LIF names are converted to upper case LIF names are padded at the end with spaces Any invalid input characters are converted into spaces.
MEMSPACE void lif_vol2str (lif_t *LIF, uint8_t *B)
Convert LIF volume records into byte vector.
MEMSPACE void lif_str2vol (uint8_t *B, lif_t *LIF)
Convert byte vector into LIF volume records.
MEMSPACE void lif_dir2str (lif_t *LIF, uint8_t *B)
Convert LIF directory records into byte vector.
MEMSPACE void lif_str2dir (uint8_t *B, lif_t *LIF)
Convert byte vector into byte vector.
MEMSPACE uint8_t lif_BIN2BCD (uint8_t data)
Convert number >= 0 and <= 99 to BCD.
MEMSPACE int lif_BCD2BIN (uint8_t bin)
Convert BCD in the range 0 and <= 99 to BIN BCD format: each hex nibble has a digit 0 .. 9.
MEMSPACE void lif_time2lifbcd (time_t t, uint8_t *bcd)
UNIX time to LIF BCD time format The BCD year is only the lower 2 digits of the year So We assume that values <= 70 are years >= 2000 BCD Day and Month start at 1 Note: If t == 0 we set ALL BCD digits to 0.
MEMSPACE time_t lif_lifbcd2time (uint8_t *bcd)
convert BCD date into time_t value The BCD year is only the lower 2 digits of the year So We assume that values <= 70 are years >= 2000 BCD Day and Month start at 1 If ALL BCD digits are 0 we return 0
MEMSPACE char * lif_ctime_gmt (time_t *tp)
GMT version of POSIX ctime().
MEMSPACE char * lif_lifbcd2timestr (uint8_t *bcd)
MEMSPACE void lif_image_clear (lif_t *LIF)
File seek with error message.
MEMSPACE void lif_dir_clear (lif_t *LIF)
Clear DIR part of LIF structure.
MEMSPACE void lif_vol_clear (lif_t *LIF)
Clear VOL part of LIF structure.
MEMSPACE void lif_dump_vol (lif_t *LIF, char *msg)
Dump LIF struture data for debugging.
MEMSPACE int lif_check_volume (lif_t *LIF)
Check Volume Table for values in range.
MEMSPACE int lif_check_dir (lif_t *LIF)
Validate Directory record values We only do basic out of bounds tests for this record Purged or EOF directory records are NOT checked and always return 1.
MEMSPACE lif_t * lif_create_volume (char *imagename, char *liflabel, long dirstart, long dirsectors, long filesectors)
Create LIF image with Volume, Directory and optional empty filespace.
MEMSPACE void lif_close_volume (lif_t *LIF)
Free LIF structure and close any files.
MEMSPACE uint32_t lif_bytes2sectors (uint32_t bytes)
Convert bytes into used sectors.
MEMSPACE void lif_rewinddir (lif_t *LIF)
Rewind LIF directory Note readdir pre-increments the directory pointer index so we start at -1.
MEMSPACE void lif_closedir (lif_t *LIF)
Close LIF directory clear and free lif_t structure.
MEMSPACE int lif_checkdirindex (lif_t *LIF, int index)
Check directory index limits.
MEMSPACE int lif_readdirindex (lif_t *LIF, int index)
Read LIF directory record number N.
MEMSPACE int lif_writedirindex (lif_t *LIF, int index)
Write LIF drectory record number N.
MEMSPACE int lif_writedirEOF (lif_t *LIF, int index)
Write LIF drectory EOF.
MEMSPACE lifdir_t * lif_readdir (lif_t *LIF)
Read a directory records from LIF image advancind directory index.
MEMSPACE lif_t * lif_updatefree (lif_t *LIF)
Update free space @parameter[in] *LIF: LIF structure.
MEMSPACE int lif_newdir (lif_t *LIF, long sectors)
Allocate index of free directory record.
MEMSPACE lif_t * lif_open_volume (char *name, char *mode)
Open LIF directory for reading.
MEMSPACE void lif_dir (char *lifimagename)
Display a LIF image file directory.
MEMSPACE int lif_find_file (lif_t *LIF, char *liflabel)
Find a LIF image file by name.
MEMSPACE int lif_e010_pad_sector (long offset, uint8_t *wbuf)
HP85 E010 ASCII LIF records ef [ff]* = no more data in this sector df size [ASCII] = data must fit inside this sector cf size [ASCII] = split data accross sector boundry, `6f` record continues at start of next sector Note: The 6f header is INSIDE the `cf` record and not included in the `cf` size value (yuck!) 6f size [ASCII] = split continue (always starts at sector boundry) df 00 00 ef [ff]* = EOF (df size = 0) pad with `ef` and `ff` until sector end size = 16 bits LSB MSB.
MEMSPACE int lif_ascii_string_to_e010 (char *str, long offset, uint8_t *wbuf)
Convert an ASCII string into HP85 E010 format.
MEMSPACE long lif_add_ascii_file_as_e010_wrapper (lif_t *LIF, uint32_t offset, char *username)
Add ASCII file as E010 data to LIF image - or compute converted data size To find size of formatted result only, without writting, set LIF to NULL.
MEMSPACE long lif_add_ascii_file_as_e010 (char *lifimagename, char *lifname, char *userfile)
Convert and add ASCII file to the LIF image as type E010 format The basename of the lifname, without extensions, is used as the LIF file name.
MEMSPACE int lif_extract_e010_as_ascii (char *lifimagename, char *lifname, char *username)
Extract E010 type file from LIF image and save as user ASCII file.
MEMSPACE int lif_extract_lif_as_lif (char *lifimagename, char *lifname, char *username)
Extract a file from LIF image entry as standalone LIF image.
MEMSPACE long lif_add_lif_file (char *lifimagename, char *lifname, char *userfile)
Add LIF file from another LIF image.
MEMSPACE int lif_del_file (char *lifimagename, char *lifname)
Delete LIF file in LIF image.
MEMSPACE int lif_rename_file (char *lifimagename, char *oldlifname, char *newlifname)
Rename LIF file in LIF image.
MEMSPACE long lif_create_image (char *lifimagename, char *liflabel, uint32_t dirsectors, uint32_t sectors)
Create/Format a LIF new disk image This can take a while to run, about 1 min for 10,000,000 bytes.
Variables
int debuglevel
Debug flag - used to log GPIB and emulator messages.
hpdir_t hpdir
hpdir.ini file processing
Detailed Description
LIF file utilities.
Copyright 2014-2020 Mike Gore, All rights reserved. GPL
See also
 http://github.com/magore/hp85disk
 http://github.com/magore/hp85disk/COPYRIGHT.md for Copyright details
Edit History
[1.0] [Mike Gore] Initial revision of file.
LIF command help lif add lifimage lifname from_ascii_file Add ASCII file converted to E010 format to existing LIF image on SD card lif add /amigo1.lif TEST1 /test.bas lif add /amigo1.lif TREK85 /TREK85/TREK85.BAS Notes: Strings must be no longer then sector size - 3 Any trailing `\n` and/or `\r` are coverted to `\n` when stored in LIF file
lif addbin lifimage lifname from_lif_image Adding a binary LIF image files to another LIF image Examples lif addbin /amigo1.lif TEST /test.lif lif addbin /amigo1.lif TREK85 /TREK85/trek.lif Notes about TREK85 in the examples Author: TREK85 port was done by Martin Hepperle https://groups.io/g/hpseries80/topic/star_trek_game_for_hp_85/4845241
lif create lifimage liflabel directory_sectors total_sectors Create a new LIF image Example lif create /amigo3.lif AMIGO3 15 1120 This formats an LIF image file with 15 directory sectors and a length of 1120 (16 * 2 * 35) sectors
lif del lifimage lifname Delete a file from LIF image on SD card Example lif del /amigo1.lif TREK85
lif dir lifimage Directory listing of LIF image Example:
lif dir amigo1.lif
Volume:[AMIGO2] Date:[<EMPTY>]
NAME TYPE START SECTOR SIZE RECSIZE DATE
HELLO e020h 10h 512 256 <EMPTY>
CIRCLE e020h 12h 256 256 <EMPTY>
GPIB-S e020h 13h 512 256 <EMPTY>
GPIB-T e020h 15h 1536 256 <EMPTY>
GPIB7 e020h 1bh 256 256 <EMPTY>
AMIGO2 e020h 1ch 256 256 <EMPTY>
TREK85 e010h 1dh 27615 256 Tue Jun 27 16:28:28 2017
HELLO3 e010h 8bh 344 256 Sun Jun 18 18:13:24 2017
TREK85B e010h 8dh 27615 256 Tue Jun 27 16:28:28 2017
9 Files 0 Purged 231 Used sectors 873 Free sectors
  lif extract lifimage lifname to_ascii_file
  Extracts E010 file from LIF image converting to ASCII file on SD card
  Example
lif extract /amigo1.lif HELLO3 /HELLO3.BAS
  lif extractbin lifimage lifname to_lif_image
  Extracts LIF file from a LIF image and saves it as new LIF image
  Example
  lif extractbin /amigo1.lif HELLO3 /hello3.lif
  lif rename lifimage oldlifname newlifname
  Renames file in LIF image
  Example
  lif rename /amigo1.lif HELLO3 HELLO4
   OPTIONAL - compile time add on
   lif td02lif image.td0 image.lif
   Convert TeleDIsk LIF encoded disk into pure LIF file
   Uses code from external HxCFloppyEmulator library to decode TELEDISK format
   The HxCFloppyEmulator library is Copyright (C) 2006-2014 Jean-Franâois DEL NERO
   See: https://github.com/xXorAa/hxc-software/tree/master/HxCFloppyEmulator/libhxcfe/trunk/sources/loaders/teledisk_loader
Function Documentation
lif_add_ascii_file_as_e010()
MEMSPACE long lif_add_ascii_file_as_e010 (char * lifimagename, char * lifname, char * userfile)
Convert and add ASCII file to the LIF image as type E010 format The basename of the lifname, without extensions, is used as the LIF file name.
Parameters
 in lifimagename LIF image name
 in lifname LIF file name
 in userfile userfile name
Returns
size of data written into to LIF image, or -1 on error FIXME assumes 256 byte secors
Definition at line 2098 of file lifutils.c.
Referenced by lif_tests().
lif_add_ascii_file_as_e010_wrapper()
MEMSPACE long lif_add_ascii_file_as_e010_wrapper (lif_t * LIF, uint32_t offset, char * username)
Add ASCII file as E010 data to LIF image - or compute converted data size To find size of formatted result only, without writting, set LIF to NULL.
Parameters
 in userfile User ASCII file source
 in *LIF Where to write file if set (not NULL)
Returns
size of formatted result FIXME assumes 256 byte secors
Definition at line 2001 of file lifutils.c.
Referenced by lif_add_ascii_file_as_e010().
lif_add_lif_file()
MEMSPACE long lif_add_lif_file (char * lifimagename, char * lifname, char * userfile)
Add LIF file from another LIF image.
Parameters
 in lifimagename LIF image name
 in lifname LIF file name to copy file to
 in userfile LIF mage name copy file from
Returns
size of data written into to LIF image, or -1 on error FIXME assumes 256 byte secors
Definition at line 2480 of file lifutils.c.
Referenced by lif_tests().
lif_ascii_string_to_e010()
MEMSPACE int lif_ascii_string_to_e010 (char * str, long offset, uint8_t * wbuf)
Convert an ASCII string into HP85 E010 format.
Parameters
 in str ASCII string to write
 in offset E010 data sector offset, only used in formatting wbuf with headers
 in wbuf E010 data result
Returns
size of E010 data FIXME assumes 256 byte secors
We ALWAYS pad a sector if: There is no room for a 0xdf single header
OR - Spliting a string takes more space then padding here (extra header)
Definition at line 1906 of file lifutils.c.
Referenced by lif_add_ascii_file_as_e010_wrapper().
lif_B2S()
MEMSPACE int lif_B2S (uint8_t * B, uint8_t * name, int size)
Convert LIF space padded string name into normal string.
Parameters
 in *B LIF name space padded
 out *name string result with traling spaces removed
 in size max size of name @retrun 1 if string i ok or 0 if bad characters were found
Definition at line 474 of file lifutils.c.
Referenced by lif_str2dir(), and lif_str2vol().
lif_BCD2BIN()
MEMSPACE int lif_BCD2BIN (uint8_t bin)
Convert BCD in the range 0 and <= 99 to BIN BCD format: each hex nibble has a digit 0 .. 9.
Parameters
 in data number to convert to binary
Definition at line 667 of file lifutils.c.
Referenced by lif_lifbcd2time().
lif_BIN2BCD()
MEMSPACE uint8_t lif_BIN2BCD (uint8_t data)
Convert number >= 0 and <= 99 to BCD.
Warning
we assume the number is in range. BCD format: each hex nibble has a digit 0 .. 9
Parameters
 in data number to convert.
Returns
BCD value
Definition at line 657 of file lifutils.c.
Referenced by lif_time2lifbcd().
lif_bytes2sectors()
MEMSPACE uint32_t lif_bytes2sectors (uint32_t bytes)
Convert bytes into used sectors.
Parameters
 in bytes size in bytes
Returns
sectors FIXME assumes 256 byte sectors
Definition at line 1236 of file lifutils.c.
Referenced by lif_add_ascii_file_as_e010(), lif_check_dir(), lif_checkdirindex(), lif_dir(), lif_extract_e010_as_ascii(), and lif_open_volume().
lif_calloc()
MEMSPACE void* lif_calloc (long size)
Allocate and clear memory Displays message on errors.
Parameters
 in size size of memory to allocate
Returns
pointer to allocated memory
Definition at line 287 of file lifutils.c.
Referenced by lif_create_volume(), lif_open_volume(), lif_stralloc(), and td02lif().
lif_chars()
MEMSPACE int lif_chars (int c, int index __attribute__(unused))
Check if characters in a LIF volume or LIF file name are valid.
Parameters
 in c character to test
 in index index of character in volume or file name @retrun c (optionally upper cased) or 0 if no match
Definition at line 443 of file lifutils.c.
Referenced by lif_B2S(), lif_checkname(), and lif_fixname().
lif_check_dir()
MEMSPACE int lif_check_dir (lif_t * LIF)
Validate Directory record values We only do basic out of bounds tests for this record Purged or EOF directory records are NOT checked and always return 1.
Parameters
 in *LIF Image structure
 in debug dispaly diagostice messages
Returns
1 of ok, 0 on eeror
Definition at line 935 of file lifutils.c.
Referenced by lif_readdirindex(), lif_writedirindex(), and td0_save_lif_sector().
lif_check_volume()
MEMSPACE int lif_check_volume (lif_t * LIF)
Check Volume Table for values in range.
Parameters
 in *LIF Image structure
Returns
1 of ok, 0 on eeror
Definition at line 861 of file lifutils.c.
Referenced by lif_create_volume(), lif_open_volume(), and td0_save_lif_sector().
lif_checkdirindex()
MEMSPACE int lif_checkdirindex (lif_t * LIF, int index)
Check directory index limits.
Parameters
 in *LIF LIF Volume/Diractoy structure
 in index directory index
Returns
1 inside, 0 outside
Definition at line 1273 of file lifutils.c.
Referenced by lif_readdirindex(), and lif_writedirindex().
lif_checkname()
MEMSPACE int lif_checkname (char * name)
Check volume LIF name or directory name is valid.
Parameters
 in *name name to test @retrun 1 if the string is ok or 0 if invalid LIF name characters on input string
Definition at line 496 of file lifutils.c.
Referenced by lif_check_dir(), lif_check_volume(), lif_find_file(), and lif_rename_file().
lif_close_volume()
MEMSPACE void lif_close_volume (lif_t * LIF)
Free LIF structure and close any files.
Parameters
 in *LIF pointer to LIF Volume/Directoy structure
Returns
void
Definition at line 1209 of file lifutils.c.
Referenced by lif_closedir(), lif_create_image(), lif_create_volume(), and td02lif().
lif_closedir()
MEMSPACE void lif_closedir (lif_t * LIF)
Close LIF directory clear and free lif_t structure.
Parameters
 in *LIF pointer to LIF Volume/Directoy structure
Returns
0 on sucesss, -1 on error
Definition at line 1262 of file lifutils.c.
Referenced by lif_add_ascii_file_as_e010(), lif_add_lif_file(), lif_create_volume(), lif_del_file(), lif_dir(), lif_extract_e010_as_ascii(), lif_extract_lif_as_lif(), lif_open_volume(), and lif_rename_file().
lif_create_image()
MEMSPACE long lif_create_image (char * lifimagename, char * liflabel, uint32_t dirsectors, uint32_t sectors)
Create/Format a LIF new disk image This can take a while to run, about 1 min for 10,000,000 bytes.
Parameters
 in lifimagename LIF disk image name
 in liflabel LIF Volume Label name
 in dirsectors Number of LIF directory sectors
 in sectors total disk image size in sectors
Returns
bytes writting to disk image
Definition at line 2722 of file lifutils.c.
Referenced by format_drives(), and lif_tests().
lif_create_volume()
MEMSPACE lif_t* lif_create_volume (char * imagename, char * liflabel, long dirstart, long dirsectors, long filesectors)
Create LIF image with Volume, Directory and optional empty filespace.
Parameters
 in imagename Image name
 in liflabel Volume Label
 in dirstart Directory start sector
 in dirsectors Directory sectors
Returns
pointer to LIF structure
0 causes time to return the current date
Definition at line 1051 of file lifutils.c.
Referenced by lif_create_image(), and lif_extract_lif_as_lif().
lif_ctime_gmt()
MEMSPACE char* lif_ctime_gmt (time_t * tp)
GMT version of POSIX ctime().
Parameters
 in tp time_t * time input.
Returns
buf[].
Example: `Thu Dec 8 21:45:05 EST 2011`.
See also
ctime()
Warning
result is overwritten on each call.
Definition at line 755 of file lifutils.c.
Referenced by lif_lifbcd2timestr().
lif_del_file()
MEMSPACE int lif_del_file (char * lifimagename, char * lifname)
Delete LIF file in LIF image.
Parameters
 in lifimagename LIF image name
 in lifname LIF file name
Returns
1 if deleted, 0 if not found, -1 error
Definition at line 2598 of file lifutils.c.
Referenced by lif_tests().
lif_dir()
MEMSPACE void lif_dir (char * lifimagename)
Display a LIF image file directory.
Parameters
 in lifimagename LIF disk image name
Returns
-1 on error or number of files found
Definition at line 1723 of file lifutils.c.
Referenced by lif_tests(), and td02lif().
lif_dir2str()
MEMSPACE void lif_dir2str (lif_t * LIF, uint8_t * B)
Convert LIF directory records into byte vector.
Parameters
 in *LIF LIF image pointer
 out B byte vector to pack data into
Returns
void
Definition at line 620 of file lifutils.c.
Referenced by lif_create_volume(), lif_writedirindex(), and td0_save_lif_sector().
lif_dir_clear()
MEMSPACE void lif_dir_clear (lif_t * LIF)
Clear DIR part of LIF structure.
Parameters
 in *LIF pointer to LIF structure
Returns
void
Definition at line 805 of file lifutils.c.
Referenced by lif_create_volume(), lif_newdir(), and lif_writedirEOF().
lif_dump_vol()
MEMSPACE void lif_dump_vol (lif_t * LIF, char * msg)
Dump LIF struture data for debugging.
Parameters
 in *LIF pointer to LIF structure
Returns
void
Definition at line 825 of file lifutils.c.
Referenced by lif_add_ascii_file_as_e010(), lif_checkdirindex(), lif_create_volume(), lif_open_volume(), lif_readdirindex(), lif_writedirindex(), and td0_save_lif_sector().
lif_e010_pad_sector()
MEMSPACE int lif_e010_pad_sector (long offset, uint8_t * wbuf)
HP85 E010 ASCII LIF records ef [ff]* = no more data in this sector df size [ASCII] = data must fit inside this sector cf size [ASCII] = split data accross sector boundry, `6f` record continues at start of next sector Note: The 6f header is INSIDE the `cf` record and not included in the `cf` size value (yuck!) 6f size [ASCII] = split continue (always starts at sector boundry) df 00 00 ef [ff]* = EOF (df size = 0) pad with `ef` and `ff` until sector end size = 16 bits LSB MSB.
Example: 000080e0 : 4b 7c 22 0d cf 29 00 31 34 20 44 49 53 50 20 22 : K|`..).14 DISP ` 000080f0 : 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 5f : _ 00008100 : 6f 10 00 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f : o.._____________ 00008110 : 5f 22 0d df 2b 00 31 35 20 44 49 53 50 20 22 20 : _`..+.15 DISP `
cf 29 00 (19 is to sector end) (new sector start with 6F 10 00 (10 is remainder) So 29 = 19 and 10 (yuck!)
PAD wbuf to sector boundry
Parameters
 in offset sector offset
 in wbuf E010 PAD data
Returns
size of E010 PAD data FIXME assumes 256 byte secors
Definition at line 1866 of file lifutils.c.
Referenced by lif_add_ascii_file_as_e010_wrapper(), and lif_ascii_string_to_e010().
lif_extract_e010_as_ascii()
MEMSPACE int lif_extract_e010_as_ascii (char * lifimagename, char * lifname, char * username)
Extract E010 type file from LIF image and save as user ASCII file.
Parameters
 in lifimagename LIF disk image name
 in lifname name of file in LIF image
 in username name to call the extracted image
Returns
1 on sucess or 0 on error FIXME assumes 256 byte secors
Definition at line 2202 of file lifutils.c.
Referenced by lif_tests().
lif_extract_lif_as_lif()
MEMSPACE int lif_extract_lif_as_lif (char * lifimagename, char * lifname, char * username)
Extract a file from LIF image entry as standalone LIF image.
Parameters
 in lifimagename LIF disk image name to extract file from
 in lifname name of file in LIF image we want to extract
 in username new LIF file to create
Returns
1 on sucess or 0 on error FIXME assumes 256 byte secors
Definition at line 2379 of file lifutils.c.
Referenced by lif_tests().
lif_find_file()
MEMSPACE int lif_find_file (lif_t * LIF, char * liflabel)
Find a LIF image file by name.
Parameters
 in *LIF directory pointer
 in liflabel File name in LIF image
Returns
Directory index of record
Definition at line 1804 of file lifutils.c.
Referenced by lif_add_lif_file(), lif_del_file(), lif_extract_e010_as_ascii(), lif_extract_lif_as_lif(), and lif_rename_file().
lif_fixname()
MEMSPACE int lif_fixname (uint8_t * B, char * name, int size)
Convert name into a valid LIF name Only use the basename() part of the string and remove any file name extentions LIF names may have only these characters: [A-Z][A-Z0-09_]+ LIF names are converted to upper case LIF names are padded at the end with spaces Any invalid input characters are converted into spaces.
Parameters
 out *B output LIF string
 in *name input string
 in size maximum size of output string
Returns
length of result
Definition at line 538 of file lifutils.c.
Referenced by lif_add_ascii_file_as_e010(), lif_create_volume(), and lif_rename_file().
lif_free()
MEMSPACE void lif_free (void * p)
Free allocated memory Displays message on errors.
Parameters
 in p pointer to memory to free
Returns
pointer to allocated memory
Definition at line 302 of file lifutils.c.
Referenced by lif_close_volume().
lif_help()
MEMSPACE void lif_help (int full)
Help Menu for User invoked GPIB functions and tasks See: int gpib_tests(char *str)
Returns
void
Definition at line 111 of file lifutils.c.
Referenced by help(), and lif_tests().
lif_image_clear()
MEMSPACE void lif_image_clear (lif_t * LIF)
File seek with error message.
Clear LIF structure
Parameters
 in *LIF pointer to LIF structure
Returns
void
Definition at line 795 of file lifutils.c.
Referenced by lif_create_volume(), and td02lif().
lif_lifbcd2time()
MEMSPACE time_t lif_lifbcd2time (uint8_t * bcd)
convert BCD date into time_t value The BCD year is only the lower 2 digits of the year So We assume that values <= 70 are years >= 2000 BCD Day and Month start at 1 If ALL BCD digits are 0 we return 0
Parameters
 in *bcd packed 6 byte BCD LIF time YY MM DD HH MM SS
Returns
time_t result or 0 if all bcd digits were 0
Definition at line 713 of file lifutils.c.
Referenced by lif_extract_e010_as_ascii(), and lif_lifbcd2timestr().
lif_lifbcd2timestr()
MEMSPACE char* lif_lifbcd2timestr (uint8_t * bcd)
@breif convert BCD time into a date string The BCD year is only the lower 2 digits of the year So We assume that values <= 70 are years >= 2000 BCD Day and Month start at 1 If BCD string is all zero we return <EMPTY>
Parameters
 in *bcd pcked 6 byte BCD LIF time YY MM DD HH MM SS
Returns
string result
Definition at line 775 of file lifutils.c.
Referenced by lif_dir(), lif_dump_vol(), and td0_save_lif_sector().
lif_newdir()
MEMSPACE int lif_newdir (lif_t * LIF, long sectors)
Allocate index of free directory record.
Parameters
 in *LIF LIF pointer
 in sectors try to find specified free space
Returns
index or free record or -1 on error
Definition at line 1496 of file lifutils.c.
Referenced by lif_add_ascii_file_as_e010(), and lif_add_lif_file().
lif_open()
MEMSPACE FILE* lif_open (char * name, char * mode)
Open a file that must exist Displays message on errors.
Parameters
 in *name file name of LIF image
 in *mode open mode - see fopen
Returns
FILE * pointer
Definition at line 333 of file lifutils.c.
Referenced by lif_add_ascii_file_as_e010_wrapper(), lif_create_volume(), lif_extract_e010_as_ascii(), and lif_open_volume().
lif_open_volume()
MEMSPACE lif_t* lif_open_volume (char * name, char * mode)
Open LIF directory for reading.
Parameters
 in *name file name of LIF image
 in *mode `rb` = read, `rb+` = read/write
Returns
LIF pointer on sucesses or NULL on error
Definition at line 1633 of file lifutils.c.
Referenced by lif_add_ascii_file_as_e010(), lif_add_lif_file(), lif_del_file(), lif_dir(), lif_extract_e010_as_ascii(), lif_extract_lif_as_lif(), and lif_rename_file().
lif_read()
MEMSPACE long lif_read (lif_t * LIF, void * buf, long offset, int bytes)
Read data from a LIF image Displays message on errors.
Parameters
 in *LIF lif_t structure with file pointers
 out *buf read buffer
 in offset read offset
 in bytes number of bytes to read
Returns
bytes read or 0 on error
Initial file position
Definition at line 390 of file lifutils.c.
Referenced by lif_add_lif_file(), lif_extract_e010_as_ascii(), lif_extract_lif_as_lif(), lif_open_volume(), and lif_readdirindex().
lif_readdir()
MEMSPACE lifdir_t* lif_readdir (lif_t * LIF)
Read a directory records from LIF image advancind directory index.
See also
lif_open_volume() nOte: skip all purged LIF directory records
Parameters
 in *LIF to LIF Volume/Diractoy structure
Returns
directory structure or NULL
Definition at line 1392 of file lifutils.c.
lif_readdirindex()
MEMSPACE int lif_readdirindex (lif_t * LIF, int index)
Read LIF directory record number N.
Parameters
 in *LIF to LIF Volume/Diractoy structure
 in index director record number
Returns
1 on success, 0 if error, bad directory record or outside of directory limits
Definition at line 1291 of file lifutils.c.
Referenced by lif_dir(), lif_find_file(), lif_newdir(), lif_readdir(), and lif_updatefree().
lif_rename_file()
MEMSPACE int lif_rename_file (char * lifimagename, char * oldlifname, char * newlifname)
Rename LIF file in LIF image.
Parameters
 in lifimagename LIF image name
 in oldlifname old LIF file name
 in newlifname new LIF file name
Returns
1 if renamed, 0 if not found, -1 error
Definition at line 2658 of file lifutils.c.
Referenced by lif_tests().
lif_rewinddir()
MEMSPACE void lif_rewinddir (lif_t * LIF)
Rewind LIF directory Note readdir pre-increments the directory pointer index so we start at -1.
Parameters
 in *LIF pointer to LIF Volume/Directoy structure
Returns
void
Definition at line 1250 of file lifutils.c.
Referenced by lif_create_volume(), and lif_updatefree().
lif_S2B()
MEMSPACE void lif_S2B (uint8_t * B, uint8_t * name, int size)
Convert string to LIF directory record.
Parameters
 out *B LIF result with added trailing spaces
 in *name string
 in size max size of B @retrun 1 if the string is ok or 0 if invalid LIF name characters on input string
Definition at line 515 of file lifutils.c.
Referenced by lif_dir2str(), and lif_vol2str().
lif_seek_msg()
MEMSPACE int lif_seek_msg (FILE * fp, long offset, char * msg)
Displays message on errors
Parameters
 in *fp FILE pointer
 in offset file offset
 in mesg user string as part of error message
Returns
1 on success, 0 on error
Definition at line 368 of file lifutils.c.
Referenced by lif_read(), and lif_write().
lif_stat()
MEMSPACE stat_t* lif_stat (char * name, stat_t * p)
Stat a file Displays message on errors.
Parameters
 in *name file name of LIF image
 in *p start_t structure pointer for result
Returns
NULL on error or copy of p
Definition at line 351 of file lifutils.c.
Referenced by lif_add_ascii_file_as_e010(), and lif_open_volume().
lif_str2dir()
MEMSPACE void lif_str2dir (uint8_t * B, lif_t * LIF)
Convert byte vector into byte vector.
Parameters
 in B byte vector to extract data from
 out LIF lifdir_t structure pointer
Returns
void
Definition at line 638 of file lifutils.c.
Referenced by lif_readdirindex(), and td0_save_lif_sector().
lif_str2vol()
MEMSPACE void lif_str2vol (uint8_t * B, lif_t * LIF)
Convert byte vector into LIF volume records.
Parameters
 in B byte vector
 out *LIF LIF image structure
Returns
void
Definition at line 597 of file lifutils.c.
Referenced by lif_open_volume(), and td0_save_lif_sector().
lif_stralloc()
MEMSPACE char* lif_stralloc (char * str)
Allocate and copy a string Displays message on errors.
Parameters
 in str String to allocate and copy
Returns
pointer to allocated memory with string copy
Definition at line 316 of file lifutils.c.
Referenced by lif_create_volume(), lif_open_volume(), td02lif(), and td0_open().
lif_tests()
MEMSPACE int lif_tests (int argc, char * argv[])
LIF user tests.
Returns
1 matched token, 0 if not
format LIF image
format LIF image
Definition at line 139 of file lifutils.c.
Referenced by user_task().
lif_time2lifbcd()
MEMSPACE void lif_time2lifbcd (time_t t, uint8_t * bcd)
UNIX time to LIF BCD time format The BCD year is only the lower 2 digits of the year So We assume that values <= 70 are years >= 2000 BCD Day and Month start at 1 Note: If t == 0 we set ALL BCD digits to 0.
Parameters
 in t UNIX time_t time value
 out *bcd pcked 6 byte BCD LIF time YY MM DD HH MM SS
See also
time() in time.c
Returns
void
Definition at line 683 of file lifutils.c.
Referenced by lif_add_ascii_file_as_e010(), and lif_create_volume().
lif_updatefree()
MEMSPACE lif_t* lif_updatefree (lif_t * LIF)
Update free space @parameter[in] *LIF: LIF structure.
Returns
: LIF or NULL on error
Update free
Definition at line 1419 of file lifutils.c.
Referenced by lif_create_volume(), lif_del_file(), lif_newdir(), and lif_open_volume().
lif_vol2str()
MEMSPACE void lif_vol2str (lif_t * LIF, uint8_t * B)
Convert LIF volume records into byte vector.
Parameters
 in *LIF LIF image structure
 out B byte vector to pack data into
Returns
void
Definition at line 575 of file lifutils.c.
Referenced by lif_create_volume().
lif_vol_clear()
MEMSPACE void lif_vol_clear (lif_t * LIF)
Clear VOL part of LIF structure.
Parameters
 in *LIF pointer to LIF structure
Returns
void
Definition at line 815 of file lifutils.c.
Referenced by lif_close_volume().
lif_write()
MEMSPACE int lif_write (lif_t * LIF, void * buf, long offset, int bytes)
Write data to an LIF image Displays message on errors.
Parameters
 in *LIF lif_t structure with file pointers
 in *buf write buffer
 in offset write offset
 in bytes number of bytes to write
Returns
bytes read or 0 on error
Initial file position
Definition at line 418 of file lifutils.c.
Referenced by lif_add_ascii_file_as_e010_wrapper(), lif_add_lif_file(), lif_create_volume(), lif_extract_lif_as_lif(), and lif_writedirindex().
lif_writedirEOF()
MEMSPACE int lif_writedirEOF (lif_t * LIF, int index)
Write LIF drectory EOF.
Parameters
 in *LIF LIF Volume/Diractoy structure
 in index director record number
Returns
1 on success, 0 on error and outsize directory limits
Definition at line 1376 of file lifutils.c.
Referenced by lif_extract_lif_as_lif(), lif_newdir(), and lif_updatefree().
lif_writedirindex()
MEMSPACE int lif_writedirindex (lif_t * LIF, int index)
Write LIF drectory record number N.
Parameters
 in *LIF LIF Volume/Diractoy structure
 in index director record number
Returns
1 on success, 0 if error, bad directory record or outside of directory limits
Definition at line 1338 of file lifutils.c.
Referenced by lif_add_ascii_file_as_e010(), lif_add_lif_file(), lif_del_file(), lif_extract_lif_as_lif(), lif_newdir(), lif_rename_file(), and lif_writedirEOF().
Variable Documentation
debuglevel
int debuglevel
Debug flag - used to log GPIB and emulator messages.
Definition at line 33 of file gpib_task.c.
Referenced by lif_add_ascii_file_as_e010(), lif_add_lif_file(), lif_ascii_string_to_e010(), lif_check_dir(), lif_check_volume(), lif_checkdirindex(), lif_create_volume(), lif_del_file(), lif_dir(), lif_e010_pad_sector(), lif_find_file(), lif_newdir(), lif_open_volume(), lif_read(), lif_readdirindex(), lif_tests(), lif_updatefree(), lif_write(), and lif_writedirindex().
hpdir
hpdir_t hpdir
hpdir.ini file processing
Definition at line 48 of file drives.c.
Referenced by hpdir_find_drive(), hpdir_init(), hpdir_set_device(), lif_tests(), and mount().