main.c File Reference
Main for GPIB emulator for HP85 disk emulator project for AVR8.
#include <hardware/hardware.h>
*
#include `gpib/defines.h`
*
#include `gpib/gpib_hal.h`
*
#include `gpib/gpib.h`
*
#include `gpib/gpib_task.h`
*
#include `gpib/gpib_tests.h`
*
#include `gpib/amigo.h`
*
#include `gpib/ss80.h`
*
#include <math.h>
*
Macros
#define DEFAULT_TIME (1406357902L - 3600L * 4L)
Defines a default EPOCH time to set the RTC if not initialied.
#define TIMEZONE 300L /* west */
Timezone west in minutes.
Functions
void uart_put (uint8_t c)
line buffer for user input
char uart_get (void)
Receive a character from UART 0.
void get_line (char *buff, int len)
Get a line from UART 0 up to a maximum of len bytes.
void help ()
Display the main help menu - calls all other help menus.
void delay_tests ()
perform tests on delay functions
void setup_clock ()
Read RTC DS1307.
void display_time ()
Display current DS1307 RTC time.
void task (char *line, uint8_t gpib)
User command handler - called as main task.
int main (void)
main() for gpib project
Detailed Description
Main for GPIB emulator for HP85 disk emulator project for AVR8.
Edit History
[1.0] [Mike Gore] Initial revision of file.
Copyright 2014 Mike Gore, Inc. All rights reserved.
Definition in file main.c.
Macro Definition Documentation
#define DEFAULT_TIME (1406357902L - 3600L * 4L)
Defines a default EPOCH time to set the RTC if not initialied.
Definition at line 144 of file main.c.
Referenced by setup_clock().
#define TIMEZONE 300L /* west */
Timezone west in minutes.
Definition at line 146 of file main.c.
Function Documentation
void delay_tests ()
perform tests on delay functions
This included measurement of avr-libc delays
Returns
void
Definition at line 108 of file main.c.
Referenced by task().
void display_time ()
Display current DS1307 RTC time.
Returns
void
See Also
: rtc_read
: timegm()
: ascitime()
Definition at line 194 of file main.c.
Referenced by main(), and task().
void get_line (char * buff, int len)
Get a line from UART 0 up to a maximum of len bytes.
Parameters
in buff line input buffer
in len line length maximum
Returns
void
Definition at line 45 of file main.c.
Referenced by plot_echo(), setdate(), and task().
void help (void)
Display the main help menu - calls all other help menus.
Returns
void
See Also
gpib_help()
fatfs_help()
Definition at line 92 of file main.c.
Referenced by task().
int main (void)
main() for gpib project
Returns
should never return!
Definition at line 300 of file main.c.
void setup_clock ()
Read RTC DS1307.
If not initialized set default time
Returns
void
See Also
: clock_settime()
Definition at line 153 of file main.c.
Referenced by main().
void task (char * line, uint8_t gpib)
User command handler - called as main task.
If a keypress is detected read a line from the uart parse the result and call various user functions. ? will return a list of fuctions and paramters permitted
Parameters
in gpib
Returns
void
Definition at line 236 of file main.c.
Referenced by main().
char uart_get (void)
Receive a character from UART 0.
Returns
character
Definition at line 36 of file main.c.
Referenced by get_line().
void uart_put (uint8_t c)
line buffer for user input
Transmit a character on UART 0
Parameters
in c character to write
Returns
void
Definition at line 29 of file main.c.
Referenced by get_line(), plot_echo(), and task().