main.h File Reference
Main for GPIB emulator for HP85 disk emulator project for AVR8.
Functions
void uart_put (uint8_t c)
Transmit a character on UART 0.
char uart_get (void)
Receive a character from UART 0.
void get_line (char *buff, int len)
Get a line from UART 0 up to a maximum of len bytes.
void help (void)
Display the main help menu - calls all other help menus.
void time_test (void)
void task (void)
Detailed Description
Main for GPIB emulator for HP85 disk emulator project for AVR8.
Edit History
[1.0] [user name] Initial revision of file.
Copyright 2014 Mike Gore, Inc. All rights reserved.
Definition in file main.h.
Function Documentation
void get_line (char * buff, int len)
Get a line from UART 0 up to a maximum of len bytes.
Parameters
in buff line input buffer
in len line length maximum
Returns
void
Definition at line 375 of file rs232.c.
Referenced by plot_echo(), setdate(), and task().
void help (void)
Display the main help menu - calls all other help menus.
Returns
void
See Also
gpib_help()
fatfs_help()
Definition at line 28 of file main.c.
Referenced by task().
void task (void)
void time_test (void)
char uart_get (void)
Receive a character from UART 0.
Returns
character
Definition at line 365 of file rs232.c.
void uart_put (uint8_t c)
Transmit a character on UART 0.
Parameters
in c character to write
Returns
void
Definition at line 358 of file rs232.c.
Referenced by plot_echo(), and task().