main.doxit.c File Reference
#include <hardware/hardware.h>
*
#include `gpib/defines.h`
*
#include `gpib/gpib_hal.h`
*
#include `gpib/gpib.h`
*
#include `gpib/gpib_task.h`
*
#include `gpib/gpib_tests.h`
*
#include `gpib/amigo.h`
*
#include `gpib/ss80.h`
*
#include <math.h>
*
Macros
#define DEFAULT_TIME (1406357902L - 3600L * 4L)
#define TIMEZONE 300L /* west */
Functions
void uart_put (uint8_t c)
Transmit a character on UART 0.
char uart_get (void)
Receive a character from UART 0.
void get_line (char *buff, int len)
Get a line from UART 0 up to a maximum of len bytes.
void help ()
Display main help menu.
void delay_tests ()
void setup_clock ()
void display_time ()
void task (uint8_t gpib)
int main (void)
Variables
char Line [512+2]
Macro Definition Documentation
#define DEFAULT_TIME (1406357902L - 3600L * 4L)
Definition at line 133 of file main.doxit.c.
Referenced by setup_clock().
#define TIMEZONE 300L /* west */
Definition at line 134 of file main.doxit.c.
Function Documentation
void delay_tests ()
Definition at line 98 of file main.doxit.c.
Referenced by task().
void display_time ()
Definition at line 178 of file main.doxit.c.
Referenced by main(), and task().
void get_line (char * buff, int len)
Get a line from UART 0 up to a maximum of len bytes.
Parameters
line input buffer
line length maximum
Definition at line 38 of file main.doxit.c.
Referenced by task().
void help (void)
Display main help menu.
Returns
void
Definition at line 82 of file main.doxit.c.
Referenced by task().
int main (void)
Definition at line 285 of file main.doxit.c.
void setup_clock ()
Definition at line 140 of file main.doxit.c.
Referenced by main().
void task (uint8_t gpib)
Definition at line 220 of file main.doxit.c.
Referenced by main().
char uart_get (void)
Receive a character from UART 0.
Returns
character
Definition at line 27 of file main.doxit.c.
Referenced by get_line().
void uart_put (uint8_t c)
Transmit a character on UART 0.
Parameters
character to write
Returns
void
Definition at line 19 of file main.doxit.c.
Referenced by get_line(), and task().
Variable Documentation
char Line[512+2]
Definition at line 13 of file main.doxit.c.
Referenced by task().