main.doxygen.c File Reference
#include <hardware/hardware.h>
*
#include `gpib/defines.h`
*
#include `gpib/gpib_hal.h`
*
#include `gpib/gpib.h`
*
#include `gpib/gpib_task.h`
*
#include `gpib/gpib_tests.h`
*
#include `gpib/amigo.h`
*
#include `gpib/ss80.h`
*
#include <math.h>
*
Macros
#define DEFAULT_TIME (1406357902L - 3600L * 4L)
#define TIMEZONE 300L /* west */
Functions
void uart_put (uint8_t c)
Transmit a character on UART 0.
char uart_get (void)
Receive a character from UART 0.
void get_line (char *buff, int len)
Get a line from UART 0 up to a maximum of len bytes.
void help ()
Display main help menu.
void delay_tests ()
perform tests on delay functions This included measurement of avr-libc delays
void setup_clock ()
Read RTC DS1307 If not initialized set default time.
void display_time ()
Display current DS1307 RTC time.
void task (uint8_t gpib)
User task handler If a keypress is detected read a line from the uart parse the result and call various user functions. ? will return a list of fuctions and paramters permitted.
int main (void)
main() for gpib project
Variables
char Line [512+2]
Macro Definition Documentation
#define DEFAULT_TIME (1406357902L - 3600L * 4L)
Definition at line 128 of file main.doxygen.c.
Referenced by setup_clock().
#define TIMEZONE 300L /* west */
Definition at line 129 of file main.doxygen.c.
Function Documentation
void delay_tests ()
perform tests on delay functions This included measurement of avr-libc delays
Returns
void
Definition at line 93 of file main.doxygen.c.
Referenced by task().
void display_time ()
Display current DS1307 RTC time.
Returns
void
Definition at line 171 of file main.doxygen.c.
Referenced by main(), and task().
void get_line (char * buff, int len)
Get a line from UART 0 up to a maximum of len bytes.
Parameters
   line input buffer
   line length maximum
Definition at line 35 of file main.doxygen.c.
Referenced by task().
void help (void)
Display main help menu.
Returns
void
Definition at line 78 of file main.doxygen.c.
Referenced by task().
int main (void)
main() for gpib project
Returns
should never return!
Definition at line 276 of file main.doxygen.c.
void setup_clock ()
Read RTC DS1307 If not initialized set default time.
Returns
void
Definition at line 134 of file main.doxygen.c.
Referenced by main().
void task (uint8_t gpib)
User task handler If a keypress is detected read a line from the uart parse the result and call various user functions. ? will return a list of fuctions and paramters permitted.
Parameters
gpib
Returns
void
Definition at line 212 of file main.doxygen.c.
Referenced by main().
char uart_get (void)
Receive a character from UART 0.
Returns
character
Definition at line 25 of file main.doxygen.c.
Referenced by get_line().
void uart_put (uint8_t c)
Transmit a character on UART 0.
Parameters
   character to write
Returns
void
Definition at line 18 of file main.doxygen.c.
Referenced by get_line(), and task().
Variable Documentation
char Line[512+2]
Definition at line 13 of file main.doxygen.c.
Referenced by task().