printf/mathio.c File Reference
String to number conversions with floating point support.
#include <stdint.h>
#include <stdarg.h>
#include <string.h>
#include `mathio.h`
#include <math.h>
Functions
MEMSPACE int atodigit (int c, int radix)
Convert ASCII character to radix based digit , or -1.
MEMSPACE long atoh (const char *p)
Convert ASCII hex string to long integer.
MEMSPACE long aton (char *str, int base)
Convert ASCII string to number in a given base.
MEMSPACE int mul10str (uint8_t *str, int size)
Fast multiply number of any size by 10.
MEMSPACE long strtol (const char *nptr, char **endptr, int base)
Convert ASCII string to number in a given base.
MEMSPACE long long strtoll (const char *nptr, char **endptr, int base)
Convert ASCII string to number in a given base.
MEMSPACE int atoi (const char *str)
Convert ASCII string to number in base 10.
MEMSPACE long atol (const char *str)
Convert ASCII string to number in base 10.
Detailed Description
String to number conversions with floating point support.
Copyright 2014-2020 Mike Gore, All rights reserved. GPL License
See also
 http://github.com/magore/hp85disk
 http://github.com/magore/hp85disk/COPYRIGHT.md for specific Copyright details
You are free to use this code under the terms of GPL
please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Function Documentation
atodigit()
MEMSPACE int atodigit (int c, int radix)
Convert ASCII character to radix based digit , or -1.
Parameters
 in c character
 in radix radix
Returns
radix based digit , or -1
See also
strtol
Definition at line 58 of file mathio.c.
Referenced by strtol(), and strtoll().
atoh()
MEMSPACE long atoh (const char * p)
Convert ASCII hex string to long integer.
Parameters
 in p String to convert.
Returns
long integer result.
See also
strtol() for return overflow and underflow results.
Definition at line 80 of file mathio.c.
Referenced by gpib_tests().
atoi()
MEMSPACE int atoi (const char * str)
Convert ASCII string to number in base 10.
Parameters
 in str string
Returns
int value
See also
strtol
Definition at line 284 of file mathio.c.
Referenced by gpib_tests(), mount(), posix_tests(), td02lif(), and umount().
atol()
MEMSPACE long atol (const char * str)
Convert ASCII string to number in base 10.
Parameters
 in str string
Returns
long value
See also
strtol
Definition at line 299 of file mathio.c.
Referenced by fatfs_tests(), lif_tests(), and main().
aton()
MEMSPACE long aton (char * str, int base)
Convert ASCII string to number in a given base.
Parameters
 in str string
 in base radix
Returns
long value
See also
strtol
Definition at line 94 of file mathio.c.
mul10str()
MEMSPACE int mul10str (uint8_t * str, int size)
Fast multiply number of any size by 10.
Parameters
 in str string
 in size string size
Returns
non-zero on overflow , 0 if ok
Definition at line 110 of file mathio.c.
strtol()
MEMSPACE long strtol (const char * nptr, char ** endptr, int base)
Convert ASCII string to number in a given base.
Parameters
 in nptr string
 in endptr pointer to string pointer return value
 in base radix
Returns
long value
Definition at line 139 of file mathio.c.
Referenced by atoh(), atoi(), atol(), aton(), get_value(), posix_tests(), and setdate_r().
strtoll()
MEMSPACE long long strtoll (const char * nptr, char ** endptr, int base)
Convert ASCII string to number in a given base.
Parameters
 in nptr string
 in endptr pointer to string pointer return value
 in base radix
Returns
long long
Definition at line 187 of file mathio.c.