printf/mathio.h File Reference
Math IO functions, and verious conversion code with floating point support.
Data Structures
struct _printf_t
undefine any potential macro version of these functions
union f_t
format specifier flags
struct p_ch_t
Data structure for character buffer with limits.
Macros
#define MEMSPACE
#define __memx
#define WEAK_ATR __attribute__((weak))
#define PSTR_X(a) ((__memx const char *) PSTR(a))
Typedefs
typedef struct _printf_t printf_t
undefine any potential macro version of these functions
Functions
int putchar (int c)
put a character to stdout See fdevopen() sets stream->put get for TTY devices
MEMSPACE int atodigit (int c, int radix)
Convert ASCII character to radix based digit , or -1.
MEMSPACE long atoh (const char *p)
Convert ASCII hex string to long integer.
MEMSPACE long aton (char *str, int base)
Convert ASCII string to number in a given base.
MEMSPACE int mul10str (uint8_t *str, int size)
Fast multiply number of any size by 10.
MEMSPACE long strtol (const char *nptr, char **endptr, int base)
Convert ASCII string to number in a given base.
MEMSPACE long long strtoll (const char *nptr, char **endptr, int base)
Convert ASCII string to number in a given base.
MEMSPACE int atoi (const char *str)
Convert ASCII string to number in base 10.
MEMSPACE long atol (const char *str)
Convert ASCII string to number in base 10.
MEMSPACE double iexp (double num, int exp)
MEMSPACE double scale10 (double num, int *exp)
MEMSPACE double strtod (const char *nptr, char **endptr)
MEMSPACE double atof (const char *str)
MEMSPACE size_t WEAK_ATR strlen (const char *str)
String Length.
MEMSPACE int WEAK_ATR isdigit (int c)
test if a character is a digit
MEMSPACE void WEAK_ATR reverse (char *str)
Reverse a string in place Example: abcdef -> fedcba.
MEMSPACE void WEAK_ATR strupper (char *str)
UPPERCASE a string.
MEMSPACE int bin2num (uint8_t *str, int strmax, int nummin, int base, uint8_t *nump, int numsize, int sign_ch)
Convert an unsigned number (numsize bytes in size) to ASCII in specified base Notes: No limit except available memory on number size.
MEMSPACE void pch_init (p_ch_t *p, char *str, int max)
Initialize character buffer with limits.
MEMSPACE int pch (p_ch_t *p, char ch)
Put character in buffer with limits.
MEMSPACE int pch_ind (p_ch_t *p)
Return current index of character buffer with limits.
MEMSPACE int pch_max_ind (p_ch_t *p)
Return maximum valid index for character buffer.
MEMSPACE void print_flags (f_t f)
print flags set in t_t structure
MEMSPACE int p_ntoa (uint8_t *nump, int numsize, char *str, int strmax, int radix, int width, int prec, f_t f)
Convert number an base 2 .. 16 to ASCII with optional sign Notes: 1) Numbers can be any number of digits long - limited only by memory available To print negative numbers convert to positive before calling this function and set f.b.neg 2) Warning: as with printf width and prec are only minimum sizes - results can be bigger We assume all numbers are positive:
MEMSPACE int p_ftoa (double val, char *str, int max, int width, int prec, f_t f)
MEMSPACE int p_etoa (double val, char *str, int max, int width, int prec, f_t f)
MEMSPACE void _puts_pad (printf_t *fn, char *s, int width, int count, int left)
put string, via user function, count bytes long, padded up to width, left or right aligned
MEMSPACE void _printf_fn (printf_t *fn, __memx const char *fmt, va_list va)
vsnprintf function
MEMSPACE void _putc_buffer_fn (struct _printf_t *p, char ch)
_putc_buffer_fn - character output to a string buffer Used by snprintf and vsnprintf You can make _printf_fn call this helper for each character
MEMSPACE int vsnprintf (char *str, size_t size, const char *format, va_list va)
vsnprintf function
MEMSPACE int snprintf (char *str, size_t size, const char *format,...)
snprintf function
MEMSPACE int printf (const char *format,...)
int sscanf (const char *strp, const char *fmt,...)
Detailed Description
Math IO functions, and verious conversion code with floating point support.
Copyright 2014-2020 Mike Gore, All rights reserved. GPL License
See also
 http://github.com/magore/hp85disk
 http://github.com/magore/hp85disk/COPYRIGHT.md for specific Copyright details
You are free to use this code under the terms of GPL
please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Macro Definition Documentation
__memx
#define __memx
Definition at line 38 of file mathio.h.
MEMSPACE
#define MEMSPACE
Definition at line 33 of file mathio.h.
PSTR_X
#define PSTR_X(a) ((__memx const char *) PSTR(a))
Definition at line 115 of file mathio.h.
WEAK_ATR
#define WEAK_ATR __attribute__((weak))
Definition at line 45 of file mathio.h.
Typedef Documentation
printf_t
typedef struct _printf_t printf_t
undefine any potential macro version of these functions
We let printf use user defined I/O functions
Function Documentation
_printf_fn()
MEMSPACE void _printf_fn (printf_t * fn, __memx const char * fmt, va_list va)
vsnprintf function
Parameters
 out fn output character function pointer
 in fmt printf forat string
 in va va_list arguments
Returns
size of string
Calling Variadic Functions
excerpt from https://www.gnu.org/software/libc/manual/html_node/Calling-Variadics.html Since the prototype doesnât specify types for optional arguments, in a call to a variadic function the default argument promotions are performed on the optional argument values. This means the objects of type char or short int (whether signed or not) are promoted to either int or unsigned int, as appropriate; and that objects of type float are promoted to type double. So, if the caller passes a char as an optional argument, it is promoted to an int, and the function can access it with va_arg (ap, int).
Definition at line 806 of file printf.c.
Referenced by fprintf(), and vsnprintf().
_putc_buffer_fn()
MEMSPACE void _putc_buffer_fn (struct _printf_t * p, char ch)
_putc_buffer_fn - character output to a string buffer Used by snprintf and vsnprintf You can make _printf_fn call this helper for each character
Parameters
 in *p structure with pointers and buffer to be written to
 in ch character to place in buffer
Returns
void
Definition at line 1187 of file printf.c.
Referenced by vsnprintf().
_puts_pad()
MEMSPACE void _puts_pad (printf_t * fn, char * s, int width, int count, int left)
put string, via user function, count bytes long, padded up to width, left or right aligned
Parameters
 out fn output character function pointer
 in s string
 in width of characters to pad up to - if needed
 in count number of characters to copy from buff
 in left string is left aligned
Definition at line 678 of file printf.c.
Referenced by _printf_fn().
atodigit()
MEMSPACE int atodigit (int c, int radix)
Convert ASCII character to radix based digit , or -1.
Parameters
 in c character
 in radix radix
Returns
radix based digit , or -1
See also
strtol
Definition at line 58 of file mathio.c.
Referenced by strtol(), and strtoll().
atof()
MEMSPACE double atof (const char * str)
atoh()
MEMSPACE long atoh (const char * p)
Convert ASCII hex string to long integer.
Parameters
 in p String to convert.
Returns
long integer result.
See also
strtol() for return overflow and underflow results.
Definition at line 80 of file mathio.c.
Referenced by gpib_tests().
atoi()
MEMSPACE int atoi (const char * str)
Convert ASCII string to number in base 10.
Parameters
 in str string
Returns
int value
See also
strtol
Definition at line 284 of file mathio.c.
Referenced by gpib_tests(), posix_tests(), and td02lif().
atol()
MEMSPACE long atol (const char * str)
Convert ASCII string to number in base 10.
Parameters
 in str string
Returns
long value
See also
strtol
Definition at line 299 of file mathio.c.
Referenced by fatfs_tests(), lif_tests(), and main().
aton()
MEMSPACE long aton (char * str, int base)
Convert ASCII string to number in a given base.
Parameters
 in str string
 in base radix
Returns
long value
See also
strtol
Definition at line 94 of file mathio.c.
bin2num()
MEMSPACE int bin2num (uint8_t * str, int strmax, int nummin, int base, uint8_t * nump, int numsize, int sign_ch)
Convert an unsigned number (numsize bytes in size) to ASCII in specified base Notes: No limit except available memory on number size.
Does not use divide or of multiply instructions - great on 8bit CPU's How it works: Say you have a table of powers of 2 in a given base base
To get the result add each table entry, in the base, that corresponds to each 1 bit in the binary number.
Now instead of a table we can start with 1 and multiple by 2 contraining each digit into the base we want - this is the same as using the table except we build it on the fly
Parameters
 out str ASCII number string result
 in strmax maximum size of str in bytes
 in nummin minimum number of digits to display
 in *nump Pointer to binary number
 in numsize size of binary number in bytes
 in sign_ch sign of binary number return converted number string numsize in bytes
Definition at line 143 of file printf.c.
Referenced by p_ntoa().
iexp()
MEMSPACE double iexp (double num, int exp)
isdigit()
MEMSPACE int WEAK_ATR isdigit (int c)
test if a character is a digit
undo any existing macros
Parameters
 in c character
Returns
true or false
Definition at line 40 of file stringsup.c.
Referenced by _printf_fn().
mul10str()
MEMSPACE int mul10str (uint8_t * str, int size)
Fast multiply number of any size by 10.
Parameters
 in str string
 in size string size
Returns
non-zero on overflow , 0 if ok
Definition at line 110 of file mathio.c.
p_etoa()
MEMSPACE int p_etoa (double val, char * str, int max, int width, int prec, f_t f)
Referenced by _printf_fn().
p_ftoa()
MEMSPACE int p_ftoa (double val, char * str, int max, int width, int prec, f_t f)
Referenced by _printf_fn().
p_ntoa()
MEMSPACE int p_ntoa (uint8_t * nump, int numsize, char * str, int strmax, int radix, int width, int prec, f_t f)
Convert number an base 2 .. 16 to ASCII with optional sign Notes: 1) Numbers can be any number of digits long - limited only by memory available To print negative numbers convert to positive before calling this function and set f.b.neg 2) Warning: as with printf width and prec are only minimum sizes - results can be bigger We assume all numbers are positive:
Parameters
 in nump number pointer
 in numsize number size in bytes
 out *str string result
 in strmax strmaximum length of string result
 in radix Radix may be 2 .. 16
 in width Width of result padded if needed
 in prec minumum number of digits, zero padded if needed
 in f flags f.b.left justify left f.b.plus display + for positive number, - for negative numbers f.b.space display ' ' for positive, - for negative f.b.zero pad with zeros if needed f.b.alt Alternate display form - work in progress f.b.width Width of result - pad if required f.b.prec Zero padd to prec if sepcified f.b.neg Sign of number is negative
Definition at line 314 of file printf.c.
Referenced by _printf_fn().
pch()
MEMSPACE int pch (p_ch_t * p, char ch)
Put character in buffer with limits.
Parameters
 in str string
 in max maximum number of characters plus EOS @See init_p_ch
Returns
void
Definition at line 233 of file printf.c.
pch_ind()
MEMSPACE int pch_ind (p_ch_t * p)
Return current index of character buffer with limits.
Returns
Buffer index
Definition at line 247 of file printf.c.
pch_init()
MEMSPACE void pch_init (p_ch_t * p, char * str, int max)
Initialize character buffer with limits.
Parameters
 in str string
 in max maximum number of characters plus EOS
Returns
void
base of string to write to
current string index
maximum string size including EOS
Definition at line 218 of file printf.c.
pch_max_ind()
MEMSPACE int pch_max_ind (p_ch_t * p)
Return maximum valid index for character buffer.
Returns
Buffer index
Definition at line 256 of file printf.c.
print_flags()
MEMSPACE void print_flags (f_t f)
print flags set in t_t structure
Parameters
 in f f_t flags structure
Returns
void
Definition at line 269 of file printf.c.
printf()
MEMSPACE int printf (const char * format, ...)
Referenced by alloc_device(), assign_value(), buffer_read_open(), cat(), clock_elapsed_end(), copy(), dbf_close(), dbf_lseek(), dbf_open(), dbf_read(), dbf_write(), DeleteRowCol(), Determinant(), display_Addresses(), display_clock(), display_Config(), display_mount(), display_ts(), dump_stat(), DumpData(), fatfs_filinfo_list(), fatfs_help(), fatfs_ls(), fatfs_status(), fatfs_tests(), fgetc(), format_drives(), fputc(), GPIB(), gpib_bus_init(), gpib_detect_PP(), gpib_disable_PPR(), gpib_enable_PPR(), gpib_error_test(), gpib_file_init(), gpib_help(), GPIB_LISTEN(), gpib_read_byte(), gpib_read_str(), GPIB_SECONDARY_ADDRESS(), gpib_state_init(), GPIB_TALK(), gpib_tests(), gpib_timer_elapsed_end(), gpib_timer_init(), gpib_trace_task(), gpib_unread(), gpib_write_byte(), gpib_write_str(), help(), hpdir_find_drive(), hpdir_set_device(), i2c_check_op(), i2c_display_task_errors(), i2c_fn(), i2c_init(), i2c_print_error(), i2c_rtc_read(), i2c_rtc_write(), init_timers(), initialize_clock(), Invert(), lif_add_ascii_file_as_e010(), lif_add_ascii_file_as_e010_wrapper(), lif_add_lif_file(), lif_ascii_string_to_e010(), lif_calloc(), lif_check_dir(), lif_check_volume(), lif_checkdirindex(), lif_create_image(), lif_create_volume(), lif_del_file(), lif_dir(), lif_dump_vol(), lif_e010_pad_sector(), lif_extract_e010_as_ascii(), lif_extract_lif_as_lif(), lif_find_file(), lif_free(), lif_help(), lif_newdir(), lif_open(), lif_open_volume(), lif_read(), lif_readdirindex(), lif_rename_file(), lif_seek_msg(), lif_stat(), lif_tests(), lif_updatefree(), lif_write(), listen_cleanup(), ls(), ls_info(), lseek(), main(), MatAlloc(), MATCHARGS(), MatFree(), MatMul(), MatPrint(), MatRead(), mkfs(), mmc_init(), mmc_install_timer(), mmc_test(), mmc_test_timeout(), normalize(), perror(), posix_help(), posix_tests(), Post_Config(), ppr_init(), print_dst(), print_dst_gmt(), print_flags(), print_str_P(), print_tok(), print_tok_str(), print_tok_val(), print_var_P(), printer_buffer(), printer_close(), PRINTER_COMMANDS(), printer_open(), PrintFree(), put_rc(), Read_Config(), receive_plot_flush(), rtc_init(), rtc_read(), rtc_run(), rtc_write(), safecalloc(), safefree(), safemalloc(), select(), Send_Identify(), sep(), set_active_device(), set_Config_Defaults(), set_timers(), setdate(), setdate_r(), SPI0_Init(), SPI0_Mode(), spi_begin(), spi_end(), SS80_Amigo_Clear(), SS80_Check_Unit(), SS80_Check_Volume(), SS80_cmd_seek(), SS80_Command_State(), SS80_COMMANDS(), SS80_describe(), SS80_display_extended_status(), SS80_error_return(), SS80_Execute_State(), SS80_increment(), SS80_init(), SS80_locate_and_read(), SS80_locate_and_write(), SS80_Report(), SS80_Selected_Device_Clear(), SS80_send_status(), SS80_Test(), SS80_Transparent_State(), td02lif(), td0_analize_format(), td0_help(), td0_hexdump(), td0_open(), td0_read_disk(), td0_rle(), td0_save_lif(), td0_save_lif_sector(), td0_sectorinfo(), td0_trackinfo(), td0_unpack_disk_header(), td0_unpack_track_header(), testpage(), timetests(), tm2epoch(), and user_task().
putchar()
int putchar (int c)
put a character to stdout See fdevopen() sets stream->put get for TTY devices
man page putchar (3).
Parameters
 in stream POSIX stream pointer.
Returns
character.
Definition at line 363 of file posix.c.
Referenced by print_tok(), print_tok_str(), print_tok_val(), and td0_hexdump().
reverse()
MEMSPACE void WEAK_ATR reverse (char * str)
Reverse a string in place Example: abcdef -> fedcba.
Parameters
 in str string
Returns
string length
Definition at line 233 of file stringsup.c.
Referenced by bin2num().
scale10()
MEMSPACE double scale10 (double num, int * exp)
snprintf()
MEMSPACE int snprintf (char * str, size_t size, const char * format, ...)
snprintf function
Parameters
 out str string buffer for result
 in size maximum length of converted string
 in format printf forat string
 in ... list of arguments
Returns
string size
Definition at line 1250 of file printf.c.
sscanf()
int sscanf (const char * strp, const char * fmt, ...)
Referenced by MatRead(), and setdate_r().
strlen()
MEMSPACE size_t WEAK_ATR strlen (const char * str)
String Length.
Parameters
 in str string
Returns
string length
Definition at line 144 of file stringsup.c.
Referenced by _printf_fn(), cat(), fatfs_scan_files(), get_line(), gpib_trace_display(), hpdir_find_drive(), lif_ascii_string_to_e010(), lif_find_file(), lif_fixname(), lif_stralloc(), ls(), MATCH(), MATCH_LEN(), MATCHI(), MATCHI_LEN(), mctime(), readdir(), reverse(), stralloc(), td02lif(), token(), trim_tail(), and vsnprintf().
strtod()
MEMSPACE double strtod (const char * nptr, char ** endptr)
Referenced by MatRead().
strtol()
MEMSPACE long strtol (const char * nptr, char ** endptr, int base)
Convert ASCII string to number in a given base.
Parameters
 in nptr string
 in endptr pointer to string pointer return value
 in base radix
Returns
long value
Definition at line 139 of file mathio.c.
Referenced by atoh(), atoi(), atol(), aton(), get_value(), posix_tests(), and setdate_r().
strtoll()
MEMSPACE long long strtoll (const char * nptr, char ** endptr, int base)
Convert ASCII string to number in a given base.
Parameters
 in nptr string
 in endptr pointer to string pointer return value
 in base radix
Returns
long long
Definition at line 187 of file mathio.c.
strupper()
MEMSPACE void WEAK_ATR strupper (char * str)
UPPERCASE a string.
Parameters
 in str string
Returns
void
Definition at line 256 of file stringsup.c.
Referenced by _printf_fn().
vsnprintf()
MEMSPACE int vsnprintf (char * str, size_t size, const char * format, va_list va)
vsnprintf function
Parameters
 out str string buffer for result
 in size maximum length of converted string
 in format printf forat string
 in va va_list list of arguments
Returns
string size
Definition at line 1220 of file printf.c.
Referenced by snprintf().