lib/matrix.h File Reference
matrix functions
Data Structures
struct _mat
Typedefs
typedef struct _mat mat_t
Functions
MEMSPACE int TestSquare (mat_t MatA)
Credits: https://www.cs.rochester.edu/~brown/Crypto/assts/projects/adj.html.
MEMSPACE mat_t MatAlloc (int rows, int cols)
Allocate a matrix.
MEMSPACE mat_t MatAllocSQ (int size)
Allocate a matrix.
MEMSPACE void MatFree (mat_t matF)
Free a matrix.
MEMSPACE mat_t MatLoad (void *V, int rows, int cols)
Load a matrix.
MEMSPACE mat_t MatLoadSQ (void *V, int size)
Load a square matrix.
MEMSPACE void MatPrint (mat_t matrix)
Print a matrix.
MEMSPACE mat_t DeleteRowCol (mat_t MatA, int row, int col)
Create smaller matrix by deleatting specified row and colume Used by Minor and Cofactor.
MEMSPACE mat_t Transpose (mat_t MatA)
Transpose matrix.
MEMSPACE float Minor (mat_t MatA, int row, int col)
Compute determinate of the minor submatrix Minor submatrix has one less row and column as a result.
MEMSPACE float Cofactor (mat_t MatA, int row, int col)
Cofactor is determinate of minor submatrix * (-1)exp(row+col) Minor submatrix has one less row and column as a result.
MEMSPACE mat_t Adjugate (mat_t MatA)
Adjugate is transpose of cofactor matrix of A.
MEMSPACE float Determinant (mat_t MatA)
Determinant by recursion using Cofactors.
MEMSPACE mat_t Invert (mat_t MatA)
Calculate Matrix Inverse.
MEMSPACE mat_t PseudoInvert (mat_t MatA)
Calculate Pseudo Matrix Inverse Used for least square fitting of non square matrix with excess solutions Pseudo Inverse matrix(A) = 1/(AT Ã A) Ã AT.
MEMSPACE mat_t MatMul (mat_t MatA, mat_t MatB)
Multiply two matrix.
MEMSPACE mat_t MatRead (char *name)
Read a matrix.
MEMSPACE int MatWrite (char *name, mat_t MatW)
Write a matrix.
Detailed Description
matrix functions
Copyright 2016 Mike Gore, GPL License
You are free to use this code under the terms of GPL
please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Typedef Documentation
mat_t
typedef struct _mat mat_t
Function Documentation
Adjugate()
MEMSPACE mat_t Adjugate (mat_t MatA)
Adjugate is transpose of cofactor matrix of A.
See also
 https://en.wikipedia.org/wiki/Adjugate_matrix
Parameters
 in MatA matrix A
Returns
Adjugate or A
Definition at line 333 of file matrix.c.
Referenced by Invert().
Cofactor()
MEMSPACE float Cofactor (mat_t MatA, int row, int col)
Cofactor is determinate of minor submatrix * (-1)exp(row+col) Minor submatrix has one less row and column as a result.
See also
 https://en.wikipedia.org/wiki/Cofactor
Parameters
 in MatA matrix A
 in row row to delete
 in col col to delete
Returns
Determinate * (-1)exp(row + col)
Definition at line 317 of file matrix.c.
Referenced by Adjugate(), and Determinant().
DeleteRowCol()
MEMSPACE mat_t DeleteRowCol (mat_t MatA, int row, int col)
Create smaller matrix by deleatting specified row and colume Used by Minor and Cofactor.
Parameters
 in MatA matrix A - row and col must be >= 2
 in row row to delete
 in col col to delete
Returns
submatrix
Definition at line 216 of file matrix.c.
Referenced by Minor().
Determinant()
MEMSPACE float Determinant (mat_t MatA)
Determinant by recursion using Cofactors.
See also
 https://en.wikipedia.org/wiki/Determinant
Parameters
 in MatA square matrix A
Returns
Determinant or 0
Definition at line 358 of file matrix.c.
Referenced by Invert(), and Minor().
Invert()
MEMSPACE mat_t Invert (mat_t MatA)
Calculate Matrix Inverse.
See also
 https://en.wikipedia.org/wiki/Invertible_matrix Method used: Adjugate(MatA) / Det(MatA)
Parameters
 in MatA square matrix A input
Returns
Inverse of MatA or error
Definition at line 408 of file matrix.c.
Referenced by PseudoInvert().
MatAlloc()
MEMSPACE mat_t MatAlloc (int rows, int cols)
Allocate a matrix.
Parameters
 in size size of square matrix to allocate
Returns
float **
Definition at line 48 of file matrix.c.
Referenced by Adjugate(), DeleteRowCol(), MatAllocSQ(), MatLoad(), MatMul(), MatRead(), and Transpose().
MatAllocSQ()
MEMSPACE mat_t MatAllocSQ (int size)
Allocate a matrix.
Parameters
 in size size of square matrix to allocate
Returns
float **
Definition at line 106 of file matrix.c.
MatFree()
MEMSPACE void MatFree (mat_t matF)
Free a matrix.
Parameters
 in **Mat Matrix to free
Definition at line 117 of file matrix.c.
Referenced by MatAlloc(), MatRead(), Minor(), and PseudoInvert().
MatLoad()
MEMSPACE mat_t MatLoad (void * V, int rows, int cols)
Load a matrix.
Parameters
 in *V matrix data
 in size size of square matrix
Definition at line 154 of file matrix.c.
Referenced by MatLoadSQ().
MatLoadSQ()
MEMSPACE mat_t MatLoadSQ (void * V, int size)
Load a square matrix.
Parameters
 in *V square matrix data
 in size size of square matrix
Definition at line 179 of file matrix.c.
MatMul()
MEMSPACE mat_t MatMul (mat_t MatA, mat_t MatB)
Multiply two matrix.
See also
 https://en.wikipedia.org/wiki/Matrix_multiplication_algorithm C = AB, A is n Ã m matrix, B is m Ã p matrix C result n Ã p matrix (dimensions row size of A, column size of B) Cij = Sum(k=1 .. m) Aik * Bik
Parameters
 in MatA matrix A
 in MatB matrix B
Returns
MatA * MatB Result dimensions is (row size of A, column size of B)
Definition at line 500 of file matrix.c.
Referenced by PseudoInvert().
MatPrint()
MEMSPACE void MatPrint (mat_t matrix)
Print a matrix.
Parameters
 in Mat Matrix to print
Definition at line 190 of file matrix.c.
Referenced by Invert().
MatRead()
MEMSPACE mat_t MatRead (char * name)
Read a matrix.
Parameters
 in *name matrix data
Returns
mat_t matrix data Note: on error rows and cols = 0, data = NULL;
Definition at line 538 of file matrix.c.
MatWrite()
MEMSPACE int MatWrite (char * name, mat_t MatW)
Write a matrix.
Parameters
 in *name matrix data
 in MatW Matrix
Returns
status 1 = success, 0 = fail
Definition at line 617 of file matrix.c.
Minor()
MEMSPACE float Minor (mat_t MatA, int row, int col)
Compute determinate of the minor submatrix Minor submatrix has one less row and column as a result.
See also
 https://en.wikipedia.org/wiki/Minor_(linear_algebra)
Parameters
 in MatA matrix A
 in row row to delete
 in col col to delete
Returns
Determinate
Definition at line 297 of file matrix.c.
Referenced by Cofactor().
PseudoInvert()
MEMSPACE mat_t PseudoInvert (mat_t MatA)
Calculate Pseudo Matrix Inverse Used for least square fitting of non square matrix with excess solutions Pseudo Inverse matrix(A) = 1/(AT Ã A) Ã AT.
Parameters
 in MatA matrix A input - does not have to be square
Returns
Pseudo Inverse of MatA or error
Definition at line 466 of file matrix.c.
TestSquare()
MEMSPACE int TestSquare (mat_t MatA)
Credits: https://www.cs.rochester.edu/~brown/Crypto/assts/projects/adj.html.
Author
Paul Bourke 2002
Test is a matrix is square
Parameters
 in MatA matrix A
Returns
1 if ssquare, 0 if not
Definition at line 36 of file matrix.c.
Transpose()
MEMSPACE mat_t Transpose (mat_t MatA)
Transpose matrix.
Parameters
 in MatA matrix A
Returns
Transpose matrix
Definition at line 268 of file matrix.c.
Referenced by PseudoInvert().