fatfs/mmc_hal.c File Reference
#include <hardware/hardware.h>
*
#include `diskio.h`
*
#include `disk.h`
*
#include `ff.h`
*
#include `mmc_hal.h`
*
Functions
LOCAL void mmc_task (void)
1000HZ timer task
MEMSPACE void mmc_install_timer (void)
Install MMC timer task: mmc_task()
MEMSPACE void mmc_spi_TX_buffer (const uint8_t *data, int count)
SPI write buffer.
MEMSPACE void mmc_spi_RX_buffer (const uint8_t *data, int count)
SPI read buffer.
MEMSPACE uint8_t mmc_spi_RX ()
SPI read 1 byte.
MEMSPACE void mmc_spi_TX (uint8_t data)
SPI write 1 byte.
MEMSPACE uint8_t mmc_spi_TXRX (uint8_t data)
SPI read and write 1 byte.
MEMSPACE void mmc_set_ms_timeout (uint16_t ms)
Set MMC timeout timer in Milliseconds.
MEMSPACE int mmc_test_timeout ()
Wait for timeout.
MEMSPACE int mmc_init (int verbose)
Initialize MMC and FatFs interface, display diagnostics.
MEMSPACE void mmc_spi_init (int32_t clock)
MMC SPI bus init.
MEMSPACE void mmc_slow ()
MMC set slow SPI bus speed.
MEMSPACE void mmc_fast ()
MMC fast SPI bus speed.
MEMSPACE void mmc_power_on ()
MMC power ON initialize.
MEMSPACE void mmc_power_off ()
MMC power off.
MEMSPACE int mmc_power_status ()
MMC power status.
MEMSPACE void mmc_cs_enable ()
MMC CS enable.
MEMSPACE void mmc_cs_disable ()
MMC CS disable.
MEMSPACE int mmc_ins_status ()
MMC Card Inserted status.
MEMSPACE int mmc_wp_status ()
MMC Card Write Protect status.
Variables
DSTATUS Stat
MMC timer tic in Microseconds.
volatile int32_t mmc_us_timeout
MMC timeout timer used to detect timeout error conditions.
uint16_t _mmc_timeout = 0
MMC timeout counter.
uint32_t _mmc_clock = 0
MMC SPI CLOCK cache.
uint16_t _mmc_pre = 0
static int mmc_init_flag = 0
uint8_t _mmc_spi_init_flag = 0
hs the mmc SPI bus been initialized yet ?
Function Documentation
MEMSPACE void mmc_cs_disable (void)
MMC CS disable.
MMC SPI chip select
Returns
void
Definition at line 360 of file mmc_hal.c.
Referenced by mmc_deselect().
MEMSPACE void mmc_cs_enable (void)
MMC CS enable.
MMC SPI chip select
Returns
void
Definition at line 346 of file mmc_hal.c.
Referenced by mmc_select().
MEMSPACE void mmc_fast (void)
MMC fast SPI bus speed.
Used during normal file IO phases
Returns
void
Definition at line 292 of file mmc_hal.c.
Referenced by mmc_disk_initialize().
MEMSPACE int mmc_init (int verbose)
Initialize MMC and FatFs interface, display diagnostics.
Parameters
in cold 1 also initailize MMC timer.
Returns
Definition at line 186 of file mmc_hal.c.
Referenced by fatfs_tests(), main(), and open().
MEMSPACE int mmc_ins_status (void)
MMC Card Inserted status.
We do not detect card insert status in this project.
Returns
1 card inserted
Definition at line 372 of file mmc_hal.c.
Referenced by gpib_error_test(), and mmc_task().
MEMSPACE void mmc_install_timer (void)
Install MMC timer task: mmc_task()
See Also
mmc_task()
Returns
void
Definition at line 91 of file mmc_hal.c.
Referenced by mmc_init().
MEMSPACE void mmc_power_off (void)
MMC power off.
We do not control power to the MMC device in this project.
Returns
void
Definition at line 322 of file mmc_hal.c.
Referenced by mmc_disk_initialize(), and mmc_disk_ioctl().
MEMSPACE void mmc_power_on (void)
MMC power ON initialize.
We do not control power to the MMC device in this project.
Returns
void
Definition at line 305 of file mmc_hal.c.
Referenced by mmc_disk_initialize().
MEMSPACE int mmc_power_status (void)
MMC power status.
We do not control power to the MMC device in this project.
Returns
1 power is alwasy on
Definition at line 334 of file mmc_hal.c.
MEMSPACE void mmc_set_ms_timeout (uint16_t ms)
Set MMC timeout timer in Milliseconds.
Parameters
in ms timeout in Milliseconds
See Also
mmc_test_timeout ()
Returns
void
Definition at line 154 of file mmc_hal.c.
Referenced by mmc_disk_initialize(), rcvr_datablock(), and wait_ready().
MEMSPACE void mmc_slow (void)
MMC set slow SPI bus speed.
Used during card detect phase
Returns
void
Definition at line 279 of file mmc_hal.c.
Referenced by mmc_disk_initialize(), mmc_init(), and mmc_power_on().
MEMSPACE void mmc_spi_init (int32_t clock)
MMC SPI bus init.
Returns
void
Definition at line 265 of file mmc_hal.c.
Referenced by mmc_cs_enable().
MEMSPACE uint8_t mmc_spi_RX (void)
SPI read 1 byte.
Returns
uint8_t value
Definition at line 120 of file mmc_hal.c.
MEMSPACE void mmc_spi_RX_buffer (const uint8_t * data, int count)
SPI read buffer.
Parameters
in *data transmit buffer
in count number of bytes to write
Returns
void
Definition at line 112 of file mmc_hal.c.
Referenced by rcvr_datablock().
MEMSPACE void mmc_spi_TX (uint8_t data)
SPI write 1 byte.
Parameters
in data value to transmit
Returns
void
Definition at line 130 of file mmc_hal.c.
Referenced by mmc_deselect(), mmc_disk_initialize(), mmc_disk_ioctl(), mmc_fast(), mmc_power_off(), mmc_select(), mmc_slow(), rcvr_datablock(), send_cmd(), and xmit_datablock().
MEMSPACE void mmc_spi_TX_buffer (const uint8_t * data, int count)
SPI write buffer.
Parameters
in *data transmit buffer
in count number of bytes to write
Returns
void
Definition at line 103 of file mmc_hal.c.
Referenced by xmit_datablock().
MEMSPACE uint8_t mmc_spi_TXRX (uint8_t data)
SPI read and write 1 byte.
Parameters
in data value to transmit
Returns
uint8_t value read
Definition at line 140 of file mmc_hal.c.
Referenced by mmc_disk_initialize(), mmc_disk_ioctl(), rcvr_datablock(), send_cmd(), wait_ready(), and xmit_datablock().
LOCAL void mmc_task (void)
1000HZ timer task
Parameters
in *arg ignored
Returns
void
Definition at line 54 of file mmc_hal.c.
Referenced by mmc_install_timer().
MEMSPACE int mmc_test_timeout (void)
Wait for timeout.
Returns
1 ready
0 timeout
Definition at line 165 of file mmc_hal.c.
Referenced by mmc_disk_initialize(), rcvr_datablock(), and wait_ready().
MEMSPACE int mmc_wp_status (void)
MMC Card Write Protect status.
We do not detect card write protect status in this project.
Returns
0 == not write protected
Definition at line 385 of file mmc_hal.c.
Referenced by amigo_request_status(), gpib_file_init(), mmc_task(), and SS80_locate_and_write().
Variable Documentation
uint32_t _mmc_clock = 0
MMC SPI CLOCK cache.
Definition at line 44 of file mmc_hal.c.
Referenced by mmc_cs_enable(), mmc_fast(), and mmc_slow().
uint16_t _mmc_pre = 0
Definition at line 47 of file mmc_hal.c.
Referenced by mmc_task().
uint8_t _mmc_spi_init_flag = 0
hs the mmc SPI bus been initialized yet ?
Definition at line 261 of file mmc_hal.c.
Referenced by mmc_spi_init().
uint16_t _mmc_timeout = 0
MMC timeout counter.
Definition at line 41 of file mmc_hal.c.
Referenced by mmc_install_timer(), mmc_set_ms_timeout(), mmc_task(), and mmc_test_timeout().
int mmc_init_flag = 0 [static]
Definition at line 180 of file mmc_hal.c.
Referenced by mmc_init().
volatile int32_t mmc_us_timeout
MMC timeout timer used to detect timeout error conditions.
Definition at line 38 of file mmc_hal.c.
Referenced by mmc_task().
DSTATUS Stat
MMC timer tic in Microseconds.
Definition at line 73 of file mmc.c.
Referenced by mmc_disk_initialize(), mmc_disk_ioctl(), mmc_disk_read(), mmc_disk_status(), mmc_disk_write(), mmc_init(), mmc_task(), and mmc_test_timeout().