fatfs/mmc_hal.h File Reference
MMC Hardware Layer for FatFs.
#include `hardware/hardware.h`
*
Macros
#define _MMC_HAL_
#define MMC_TIMER_TIC_US CLOCK_TIC_US /*< Define MMC time task in Microseconds - using AVR clock routines. */
#define mmc_cli cli /*< interrupt disable */
#define mmc_sei sei /*< interrupt enable */
#define mmc_disk_initialize disk_initialize	/*< disk_initialize() */
#define mmc_disk_status disk_status			/*< disk_status() */
#define mmc_disk_read disk_read /*< disk_read() */
#define mmc_disk_write disk_write			/*< disk_read() */
#define mmc_disk_ioctl disk_ioctl /*< disk_ioctl */
Functions
void mmc_install_timer (void)
Install MMC timer task: mmc_task()
void mmc_set_ms_timeout (int16_t ms)
Set MMC timeout timer in Milliseconds.
void mmc_set_us_timeout (int32_t us)
See MMC timeout timer in Microseconds.
int mmc_test_timeout (void)
Test MMC timeout status.
void mmc_clear_timeout (void)
Clear/Initialize MMC timeout value.
void mmc_task (void)
This function is called every MMC_TIMER_TIC_US.
uint8_t mmc_xchg_spi (uint8_t a)
MMC SPI send and receive character.
void mmc_spi_init (void)
MMC SPI bus init.
void mmc_slow (void)
MMC set slow SPI bus speed.
void mmc_fast (void)
MMC fast SPI bus speed.
void mmc_power_on (void)
MMC power ON initialize.
void mmc_power_off (void)
MMC power off.
int mmc_power_status (void)
MMC power status.
void mmc_cs_enable (void)
MMC CS enable.
void mmc_cs_disable (void)
MMC CS disable.
int mmc_ins_status (void)
MMC Card Inserted status.
int mmc_wp_status (void)
MMC Card Write Protect status.
int mmc_init (int cold)
Initialize MMC and FatFs interface, display diagnostics.
Detailed Description
MMC Hardware Layer for FatFs.
Edit History
[1.0] [Mike Gore] Initial revision of file.
Copyright 2014 Mike Gore, Inc. All rights reserved.
Definition in file mmc_hal.h.
Macro Definition Documentation
#define _MMC_HAL_
Definition at line 14 of file mmc_hal.h.
#define mmc_cli cli /*< interrupt disable */
Definition at line 23 of file mmc_hal.h.
Referenced by mmc_clear_timeout(), mmc_set_ms_timeout(), mmc_set_us_timeout(), and mmc_test_timeout().
#define mmc_disk_initialize disk_initialize	/*< disk_initialize() */
Definition at line 26 of file mmc_hal.h.
#define mmc_disk_ioctl disk_ioctl /*< disk_ioctl */
Definition at line 30 of file mmc_hal.h.
Referenced by mmc_init().
#define mmc_disk_read disk_read /*< disk_read() */
Definition at line 28 of file mmc_hal.h.
#define mmc_disk_status disk_status			/*< disk_status() */
Definition at line 27 of file mmc_hal.h.
#define mmc_disk_write disk_write			/*< disk_read() */
Definition at line 29 of file mmc_hal.h.
#define mmc_sei sei /*< interrupt enable */
Definition at line 24 of file mmc_hal.h.
Referenced by mmc_clear_timeout(), mmc_set_ms_timeout(), mmc_set_us_timeout(), and mmc_test_timeout().
#define MMC_TIMER_TIC_US CLOCK_TIC_US /*< Define MMC time task in Microseconds - using AVR clock routines. */
See Also
timer.c
time.c
Definition at line 21 of file mmc_hal.h.
Referenced by mmc_set_ms_timeout(), mmc_set_us_timeout(), and mmc_task().
Function Documentation
void mmc_clear_timeout (void)
Clear/Initialize MMC timeout value.
See Also
mmc_set_us_timeout()
mmc_set_ms_timeout()
Returns
void
Definition at line 98 of file mmc_hal.c.
void mmc_cs_disable (void)
MMC CS disable.
MMC SPI chip sellect
Returns
void
Definition at line 246 of file mmc_hal.c.
Referenced by mmc_deselect().
void mmc_cs_enable (void)
MMC CS enable.
MMC SPI chip sellect
Returns
void
Definition at line 235 of file mmc_hal.c.
Referenced by mmc_select().
void mmc_fast (void)
MMC fast SPI bus speed.
Used during normal file IO phases
Returns
void
Definition at line 188 of file mmc_hal.c.
Referenced by mmc_disk_initialize().
int mmc_init (int cold)
Initialize MMC and FatFs interface, display diagnostics.
Parameters
in cold 1 also initailize MMC timer.
Returns
Definition at line 281 of file mmc_hal.c.
Referenced by fatfs_tests(), main(), and open().
int mmc_ins_status (void)
MMC Card Inserted status.
We do not detect card insert status in this project.
Returns
1 card inserted
Definition at line 257 of file mmc_hal.c.
Referenced by gpib_error_test(), and mmc_task().
void mmc_install_timer (void)
Install MMC timer task: mmc_task()
See Also
mmc_task()
Returns
void
Definition at line 34 of file mmc_hal.c.
Referenced by mmc_init().
void mmc_power_off (void)
MMC power off.
We do not control power to the MMC device in this project.
Returns
void
Definition at line 213 of file mmc_hal.c.
Referenced by mmc_disk_initialize(), and mmc_disk_ioctl().
void mmc_power_on (void)
MMC power ON initialize.
We do not control power to the MMC device in this project.
Returns
void
Definition at line 199 of file mmc_hal.c.
Referenced by mmc_disk_initialize(), and mmc_init().
int mmc_power_status (void)
MMC power status.
We do not control power to the MMC device in this project.
Returns
1 power is alwasy on
Definition at line 223 of file mmc_hal.c.
void mmc_set_ms_timeout (int16_t ms)
Set MMC timeout timer in Milliseconds.
Parameters
in ms timeout in Milliseconds
See Also
mmc_test_timeout ()
Returns
void
Definition at line 48 of file mmc_hal.c.
Referenced by mmc_disk_initialize(), rcvr_datablock(), and wait_ready().
void mmc_set_us_timeout (int32_t us)
See MMC timeout timer in Microseconds.
Parameters
in us timeout in Microseconds
See Also
mmc_test_timeout ()
Returns
void
Definition at line 66 of file mmc_hal.c.
void mmc_slow (void)
MMC set slow SPI bus speed.
Used during card detect phase
Returns
void
Definition at line 177 of file mmc_hal.c.
Referenced by mmc_disk_initialize(), mmc_power_on(), and mmc_spi_init().
void mmc_spi_init (void)
MMC SPI bus init.
Returns
void
Definition at line 164 of file mmc_hal.c.
Referenced by mmc_init(), and mmc_power_on().
void mmc_task (void)
This function is called every MMC_TIMER_TIC_US.
Monitor timeouts, write protect and card detect status
Returns
void
Definition at line 117 of file mmc_hal.c.
Referenced by mmc_install_timer().
int mmc_test_timeout (void)
Test MMC timeout status.
See Also
mmc_set_us_timeout()
mmc_set_ms_timeout()
Returns
0 still counting
1 timeout reached
Definition at line 82 of file mmc_hal.c.
Referenced by mmc_disk_initialize(), rcvr_datablock(), and wait_ready().
int mmc_wp_status (void)
MMC Card Write Protect status.
We do not detect card write protect status in this project.
Returns
0 == not write protected
Definition at line 268 of file mmc_hal.c.
Referenced by amigo_request_status(), gpib_file_init(), mmc_task(), and SS80_locate_and_write().
uint8_t mmc_xchg_spi (uint8_t a)
MMC SPI send and receive character.
Parameters
in a Character to send
Returns
uint8_t Received character
Note: when reading only call with 0xff
Definition at line 154 of file mmc_hal.c.
Referenced by mmc_deselect(), mmc_disk_initialize(), mmc_disk_ioctl(), mmc_power_on(), mmc_select(), rcvr_datablock(), rcvr_spi_multi(), send_cmd(), wait_ready(), xmit_datablock(), and xmit_spi_multi().