fatfs.hal/mmc.c File Reference
#include `user_config.h`
#include `mmc_hal.h`
#include `mathio.h`
#include `fatfs.h`
Macros
#define CS_LOW() mmc_spi_begin() /* Set MMC_CS = low */
#define CS_HIGH() mmc_spi_end() /* Set MMC_CS = high */
#define MMC_CD mmc_ins_status() /* Test if card detected. yes:true, no:false, default:true */
#define MMC_WP mmc_wp_status() /* Test if write protected. yes:true, no:false, default:false */
#define FCLK_SLOW() mmc_slow() /* Set SPI slow clock (100-400kHz) */
#define FCLK_FAST() mmc_fast() /* Set SPI fast clock (20MHz max) */
#define CMD0 (0) /* GO_IDLE_STATE */
#define CMD1 (1) /* SEND_OP_COND (MMC) */
#define ACMD41 (0x80+41) /* SEND_OP_COND (SDC) */
#define CMD8 (8) /* SEND_IF_COND */
#define CMD9 (9) /* SEND_CSD */
#define CMD10 (10) /* SEND_CID */
#define CMD12 (12) /* STOP_TRANSMISSION */
#define ACMD13 (0x80+13) /* SD_STATUS (SDC) */
#define CMD16 (16) /* SET_BLOCKLEN */
#define CMD17 (17) /* READ_SINGLE_BLOCK */
#define CMD18 (18) /* READ_MULTIPLE_BLOCK */
#define CMD23 (23) /* SET_BLOCK_COUNT (MMC) */
#define ACMD23 (0x80+23) /* SET_WR_BLK_ERASE_COUNT (SDC) */
#define CMD24 (24) /* WRITE_BLOCK */
#define CMD25 (25) /* WRITE_MULTIPLE_BLOCK */
#define CMD32 (32) /* ERASE_ER_BLK_START */
#define CMD33 (33) /* ERASE_ER_BLK_END */
#define CMD38 (38) /* ERASE */
#define CMD48 (48) /* READ_EXTR_SINGLE */
#define CMD49 (49) /* WRITE_EXTR_SINGLE */
#define CMD55 (55) /* APP_CMD */
#define CMD58 (58) /* READ_OCR */
Functions
static MEMSPACE void power_on (void)
power on
static MEMSPACE void power_off (void)
power off
static BYTE xchg_spi (BYTE dat)
send/receive a SPI byte
static void rcvr_spi_multi (BYTE *p, UINT cnt)
Receive a data block fast.
static void xmit_spi_multi (const BYTE *p, UINT cnt)
Send a data block fast.
MEMSPACE int wait_ready (UINT wt)
wait for card ready
static MEMSPACE void deselect (void)
Deselect the card and release SPI bus.
static MEMSPACE int select (void)
Select the card and wait for ready.
static MEMSPACE int rcvr_datablock (BYTE *buff, UINT btr)
Receive a data packet from MMC.
static MEMSPACE BYTE send_cmd (BYTE cmd, DWORD arg)
Send a data packet to MMC.
MEMSPACE DSTATUS mmc_disk_initialize (void)
Public Functions.
MEMSPACE DSTATUS mmc_disk_status (void)
Get Disk Status.
MEMSPACE DRESULT mmc_disk_read (BYTE *buff, DWORD sector, UINT count)
Read Sector(s)
void mmc_disk_timerproc (void)
Write Sector(s)
Variables
volatile DSTATUS Stat = STA_NOINIT
static volatile BYTE Timer1
static volatile BYTE Timer2
static BYTE CardType
Macro Definition Documentation
ACMD13
#define ACMD13 (0x80+13) /* SD_STATUS (SDC) */
Definition at line 61 of file mmc.c.
Referenced by mmc_disk_read().
ACMD23
#define ACMD23 (0x80+23) /* SET_WR_BLK_ERASE_COUNT (SDC) */
Definition at line 66 of file mmc.c.
Referenced by mmc_disk_read().
ACMD41
#define ACMD41 (0x80+41) /* SEND_OP_COND (SDC) */
Definition at line 56 of file mmc.c.
Referenced by mmc_disk_initialize().
CMD0
#define CMD0 (0) /* GO_IDLE_STATE */
Definition at line 54 of file mmc.c.
Referenced by mmc_disk_initialize(), and send_cmd().
CMD1
#define CMD1 (1) /* SEND_OP_COND (MMC) */
Definition at line 55 of file mmc.c.
Referenced by mmc_disk_initialize().
CMD10
#define CMD10 (10) /* SEND_CID */
Definition at line 59 of file mmc.c.
Referenced by mmc_disk_read().
CMD12
#define CMD12 (12) /* STOP_TRANSMISSION */
Definition at line 60 of file mmc.c.
Referenced by mmc_disk_read(), and send_cmd().
CMD16
#define CMD16 (16) /* SET_BLOCKLEN */
Definition at line 62 of file mmc.c.
Referenced by mmc_disk_initialize().
CMD17
#define CMD17 (17) /* READ_SINGLE_BLOCK */
Definition at line 63 of file mmc.c.
Referenced by mmc_disk_read().
CMD18
#define CMD18 (18) /* READ_MULTIPLE_BLOCK */
Definition at line 64 of file mmc.c.
Referenced by mmc_disk_read().
CMD23
#define CMD23 (23) /* SET_BLOCK_COUNT (MMC) */
Definition at line 65 of file mmc.c.
CMD24
#define CMD24 (24) /* WRITE_BLOCK */
Definition at line 67 of file mmc.c.
Referenced by mmc_disk_read().
CMD25
#define CMD25 (25) /* WRITE_MULTIPLE_BLOCK */
Definition at line 68 of file mmc.c.
Referenced by mmc_disk_read().
CMD32
#define CMD32 (32) /* ERASE_ER_BLK_START */
Definition at line 69 of file mmc.c.
Referenced by mmc_disk_read().
CMD33
#define CMD33 (33) /* ERASE_ER_BLK_END */
Definition at line 70 of file mmc.c.
Referenced by mmc_disk_read().
CMD38
#define CMD38 (38) /* ERASE */
Definition at line 71 of file mmc.c.
Referenced by mmc_disk_read().
CMD48
#define CMD48 (48) /* READ_EXTR_SINGLE */
Definition at line 72 of file mmc.c.
Referenced by mmc_disk_read().
CMD49
#define CMD49 (49) /* WRITE_EXTR_SINGLE */
Definition at line 73 of file mmc.c.
Referenced by mmc_disk_read().
CMD55
#define CMD55 (55) /* APP_CMD */
Definition at line 74 of file mmc.c.
Referenced by send_cmd().
CMD58
#define CMD58 (58) /* READ_OCR */
Definition at line 75 of file mmc.c.
Referenced by mmc_disk_initialize(), and mmc_disk_read().
CMD8
#define CMD8 (8) /* SEND_IF_COND */
Definition at line 57 of file mmc.c.
Referenced by mmc_disk_initialize(), and send_cmd().
CMD9
#define CMD9 (9) /* SEND_CSD */
Definition at line 58 of file mmc.c.
Referenced by mmc_disk_read().
CS_HIGH
#define CS_HIGH() mmc_spi_end() /* Set MMC_CS = high */
Definition at line 40 of file mmc.c.
Referenced by deselect().
CS_LOW
#define CS_LOW() mmc_spi_begin() /* Set MMC_CS = low */
Definition at line 39 of file mmc.c.
Referenced by select().
FCLK_FAST
#define FCLK_FAST() mmc_fast() /* Set SPI fast clock (20MHz max) */
Definition at line 45 of file mmc.c.
Referenced by mmc_disk_initialize().
FCLK_SLOW
#define FCLK_SLOW() mmc_slow() /* Set SPI slow clock (100-400kHz) */
Definition at line 44 of file mmc.c.
Referenced by mmc_disk_initialize().
MMC_CD
#define MMC_CD mmc_ins_status() /* Test if card detected. yes:true, no:false, default:true */
Definition at line 42 of file mmc.c.
Referenced by mmc_disk_timerproc().
MMC_WP
#define MMC_WP mmc_wp_status() /* Test if write protected. yes:true, no:false, default:false */
Definition at line 43 of file mmc.c.
Referenced by mmc_disk_timerproc().
Function Documentation
deselect()
static MEMSPACE void deselect (void) [static]
Deselect the card and release SPI bus.
Returns
void
Definition at line 189 of file mmc.c.
Referenced by mmc_disk_initialize(), mmc_disk_read(), select(), and send_cmd().
mmc_disk_initialize()
MEMSPACE DSTATUS mmc_disk_initialize (void)
Public Functions.
Initialize Disk Drive
Returns
Stat
Definition at line 348 of file mmc.c.
Referenced by disk_initialize().
mmc_disk_read()
MEMSPACE DRESULT mmc_disk_read (BYTE * buff, DWORD sector, UINT count)
Read Sector(s)
Parameters
in buff read buffer
in sector start sector number
in count sector count
Returns
0 ok
non zero error
Definition at line 441 of file mmc.c.
Referenced by disk_read().
mmc_disk_status()
MEMSPACE DSTATUS mmc_disk_status (void)
Get Disk Status.
Returns
Stat
STA_NOINIT if no drive
Definition at line 428 of file mmc.c.
Referenced by disk_status().
mmc_disk_timerproc()
void mmc_disk_timerproc (void)
Write Sector(s)
Parameters
out buff write buffer
in sector start sector number
in count sector count
Returns
0 ok
non zero error Miscellaneous Functions
Parameters
in cmd Control code
   [in|out] buff: Send/Receive buffer
Returns
result mmc timer processes
Definition at line 716 of file mmc.c.
Referenced by disk_timerproc(), and mmc_task().
power_off()
static MEMSPACE void power_off (void) [static]
power off
Returns
void
Definition at line 110 of file mmc.c.
Referenced by mmc_disk_initialize(), and mmc_disk_read().
power_on()
static MEMSPACE void power_on (void) [static]
power on
Returns
void
Definition at line 97 of file mmc.c.
rcvr_datablock()
static MEMSPACE int rcvr_datablock (BYTE * buff, UINT btr) [static]
Receive a data packet from MMC.
Parameters
in buff Data buffer to read data into
in btr Bytes to read
Returns
1 Successful
0 Error
Definition at line 224 of file mmc.c.
Referenced by mmc_disk_read().
rcvr_spi_multi()
static void rcvr_spi_multi (BYTE * p, UINT cnt) [static]
Receive a data block fast.
Parameters
in p Data block to be read
in cnt Bytes to read
Returns
void
Definition at line 139 of file mmc.c.
Referenced by rcvr_datablock().
select()
static MEMSPACE int select (void) [static]
Select the card and wait for ready.
Returns
1 Successful
0 Timeout
Definition at line 202 of file mmc.c.
Referenced by mmc_disk_read(), and send_cmd().
send_cmd()
static MEMSPACE BYTE send_cmd (BYTE cmd, DWORD arg) [static]
Send a data packet to MMC.
Parameters
in buff Data buffer to write
in btr Bytes to write
Returns
1 Successful
0 Error Send a command packet to MMC
Parameters
in send_cmd Commend Index
in cmd Argument
Returns
R1 resp
bit7==1Send failed
Definition at line 296 of file mmc.c.
Referenced by mmc_disk_initialize(), and mmc_disk_read().
wait_ready()
MEMSPACE int wait_ready (UINT wt)
wait for card ready
Parameters
in wt ms to wait
Returns
1 Ready
0 Timeout
Definition at line 169 of file mmc.c.
Referenced by mmc_disk_read(), rcvr_datablock(), and select().
xchg_spi()
static BYTE xchg_spi (BYTE dat) [static]
send/receive a SPI byte
Parameters
in dat data to send
Returns
Data read
Definition at line 126 of file mmc.c.
Referenced by deselect(), mmc_disk_initialize(), mmc_disk_read(), rcvr_datablock(), select(), send_cmd(), and wait_ready().
xmit_spi_multi()
static void xmit_spi_multi (const BYTE * p, UINT cnt) [static]
Send a data block fast.
Parameters
out p Data block to be sent
in cnt Bytes to send
Returns
void
Definition at line 152 of file mmc.c.
Referenced by rcvr_datablock().
Variable Documentation
CardType
BYTE CardType [static]
Definition at line 85 of file mmc.c.
Referenced by mmc_disk_initialize(), and mmc_disk_read().
Stat
volatile DSTATUS Stat = STA_NOINIT
Definition at line 79 of file mmc.c.
Referenced by mmc_disk_initialize(), mmc_disk_read(), mmc_disk_status(), mmc_disk_timerproc(), mmc_init(), and mmc_test_timeout().
Timer1
volatile BYTE Timer1 [static]
Definition at line 82 of file mmc.c.
Referenced by mmc_disk_timerproc().
Timer2
volatile BYTE Timer2 [static]
Definition at line 82 of file mmc.c.
Referenced by mmc_disk_timerproc().