fatfs.hal/mmc.h File Reference
Functions
MEMSPACE int wait_ready (UINT wt)
wait for card ready
MEMSPACE DSTATUS mmc_disk_initialize (void)
Public Functions.
MEMSPACE DSTATUS mmc_disk_status (void)
Get Disk Status.
MEMSPACE DRESULT mmc_disk_read (BYTE *buff, DWORD sector, UINT count)
Read Sector(s)
MEMSPACE DRESULT mmc_disk_write (const BYTE *buff, DWORD sector, UINT count)
MEMSPACE DRESULT mmc_disk_ioctl (BYTE cmd, void *buff)
void mmc_disk_timerproc (void)
Write Sector(s)
Function Documentation
mmc_disk_initialize()
MEMSPACE DSTATUS mmc_disk_initialize (void)
Public Functions.
Initialize Disk Drive
Returns
Stat
Definition at line 343 of file mmc.c.
Referenced by disk_initialize().
mmc_disk_ioctl()
MEMSPACE DRESULT mmc_disk_ioctl (BYTE cmd, void * buff)
Referenced by disk_ioctl(), and mmc_disk_read().
mmc_disk_read()
MEMSPACE DRESULT mmc_disk_read (BYTE * buff, DWORD sector, UINT count)
Read Sector(s)
Parameters
in buff read buffer
in sector start sector number
in count sector count
Returns
0 ok
non zero error
Definition at line 433 of file mmc.c.
Referenced by disk_read().
mmc_disk_status()
MEMSPACE DSTATUS mmc_disk_status (void)
Get Disk Status.
Returns
Stat
STA_NOINIT if no drive
Definition at line 420 of file mmc.c.
Referenced by disk_status().
mmc_disk_timerproc()
void mmc_disk_timerproc (void)
Write Sector(s)
Parameters
out buff write buffer
in sector start sector number
in count sector count
Returns
0 ok
non zero error Miscellaneous Functions
Parameters
in cmd Control code
   [in|out] buff: Send/Receive buffer
Returns
result mmc timer processes
Definition at line 711 of file mmc.c.
Referenced by disk_timerproc(), and mmc_task().
mmc_disk_write()
MEMSPACE DRESULT mmc_disk_write (const BYTE * buff, DWORD sector, UINT count)
Referenced by disk_write(), and mmc_disk_read().
wait_ready()
MEMSPACE int wait_ready (UINT wt)
wait for card ready
Parameters
in wt ms to wait
Returns
1 Ready
0 Timeout
Definition at line 168 of file mmc.c.
Referenced by mmc_disk_read(), rcvr_datablock(), and select().