lib/parsing.h File Reference
Various string and character functions.
Functions
MEMSPACE void sep (void)
print seperator
MEMSPACE void trim_tail (char *str)
Trim White space and control characters from end of string.
MEMSPACE char * skipspaces (char *ptr)
Skip white space in a string - tabs and spaces.
MEMSPACE char * nextspace (char *ptr)
Skip to first white space in a string - tabs and spaces.
MEMSPACE char * skipchars (char *str, char *pat)
Skip characters defined in user string.
MEMSPACE int MATCH (char *str, char *pat)
Compare two strings.
MEMSPACE int MATCHARGS (char *str, char *pat, int min, int argc)
Match two strings and compare argument index Display message if the number of arguments is too few.
MEMSPACE int MATCHI (char *str, char *pat)
Compare two strings without case.
MEMSPACE int MATCH_LEN (char *str, char *pat)
Compare two strings limted to length of pattern.
MEMSPACE int MATCHI_LEN (char *str, char *pat)
Compare two strings without case limted to length of pattern.
MEMSPACE int split_args (char *str, char *argv[], int max)
Split string into arguments stored in argv[] We split source string into arguments Warning: source string is modified! To save memory each gap in the source string is terminated with an EOS This becomes the end of string for each argument returned Warning: Do NOT modify the source string or argument contents while using them You can reassign new pointers to the arguments if you like.
MEMSPACE char * get_token (char *str, char *token, int max)
return next token
MEMSPACE int token (char *str, char *pat)
Search for token in a string matching user pattern.
MEMSPACE int32_t get_value (char *str)
get a number
Detailed Description
Various string and character functions.
Copyright 2016 Mike Gore, GPL License
You are free to use this code under the terms of GPL
please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Function Documentation
get_token()
MEMSPACE char* get_token (char * str, char * token, int max)
return next token
Skips all non printable ASCII characters before token
Token returns only printable ASCII
Parameters
 in str string to search.
 out token token to return
 in max maximum token size
Returns
pointer past token on success .
NULL if no token found
Definition at line 323 of file parsing.c.
Referenced by hpdir_find_drive(), and Read_Config().
get_value()
MEMSPACE int32_t get_value (char * str)
get a number
Used only for debugging
Parameters
 in str string to examine
Returns
value
Definition at line 432 of file parsing.c.
Referenced by assign_value(), gpib_tests(), hpdir_find_drive(), Read_Config(), and user_task().
MATCH()
MEMSPACE int MATCH (char * str, char * pat)
Compare two strings.
Parameters
 in str string to match.
 in pat pattern to compare.
Returns
string lenth on match.
0 on no match.
Definition at line 143 of file parsing.c.
Referenced by gpib_tests(), ls(), mkfs(), mount(), posix_tests(), Read_Config(), stat(), td02lif(), td0_open(), and user_task().
MATCH_LEN()
MEMSPACE int MATCH_LEN (char * str, char * pat)
Compare two strings limted to length of pattern.
Parameters
 in str string to match.
 in pat pattern to compare.
Returns
string lenth on match.
0 on no match.
Warning
Matches sub strings so be caeful.
Definition at line 203 of file parsing.c.
MATCHARGS()
MEMSPACE int MATCHARGS (char * str, char * pat, int min, int argc)
Match two strings and compare argument index Display message if the number of arguments is too few.
Parameters
str string to test
pat pattern to match
min minumum number or arguments
argc actual number of arguments
Returns
1 on match, 0 on no match or too few arguments
Definition at line 161 of file parsing.c.
Referenced by fatfs_tests(), gpib_tests(), lif_tests(), and posix_tests().
MATCHI()
MEMSPACE int MATCHI (char * str, char * pat)
Compare two strings without case.
Parameters
 in str string to match.
 in pat pattern to compare.
Returns
string lenth on match.
0 on no match.
Definition at line 183 of file parsing.c.
Referenced by fatfs_tests(), gpib_tests(), hpdir_find_drive(), lif_tests(), MATCHARGS(), mount(), posix_tests(), td02lif(), tok_index(), and user_task().
MATCHI_LEN()
MEMSPACE int MATCHI_LEN (char * str, char * pat)
Compare two strings without case limted to length of pattern.
Parameters
 in str string to match.
 in pat pattern to compare.
Returns
string lenth on match.
0 on no match.
Warning
Matches sub strings so be caeful.
Definition at line 230 of file parsing.c.
Referenced by get_value(), and lif_tests().
nextspace()
MEMSPACE char* nextspace (char * ptr)
Skip to first white space in a string - tabs and spaces.
Parameters
 in ptr input string
Returns
pointer to first white space character
Definition at line 88 of file parsing.c.
sep()
MEMSPACE void sep (void)
print seperator
Definition at line 35 of file parsing.c.
Referenced by format_drives(), main(), mmc_test(), and SS80_Test().
skipchars()
MEMSPACE char* skipchars (char * str, char * pat)
Skip characters defined in user string.
Parameters
 in str string
 in pat pattern string
Returns
pointer to string after skipped characters.
Definition at line 111 of file parsing.c.
skipspaces()
MEMSPACE char* skipspaces (char * ptr)
Skip white space in a string - tabs and spaces.
Parameters
 in ptr input string
Returns
pointer to first non white space character
Definition at line 70 of file parsing.c.
Referenced by assign_value(), get_token(), get_value(), gpib_trace_task(), hpdir_find_drive(), split_args(), timetests(), and token().
split_args()
MEMSPACE int split_args (char * str, char * argv[], int max)
Split string into arguments stored in argv[] We split source string into arguments Warning: source string is modified! To save memory each gap in the source string is terminated with an EOS This becomes the end of string for each argument returned Warning: Do NOT modify the source string or argument contents while using them You can reassign new pointers to the arguments if you like.
Parameters
   [in|out] str: string to break up into arguments
 out *argv[] token array
 in max maximum argument count
Returns
count
Definition at line 260 of file parsing.c.
Referenced by user_task().
token()
MEMSPACE int token (char * str, char * pat)
Search for token in a string matching user pattern.
Skips all non printable ASCII characters before trying match.
Parameters
 in str string to search.
 in pat pattern to search for.
Returns
string lenth on match.
0 on no match.
Definition at line 392 of file parsing.c.
Referenced by get_token(), hpdir_find_drive(), rcvr_datablock(), and Read_Config().
trim_tail()
MEMSPACE void trim_tail (char * str)
Trim White space and control characters from end of string.
Parameters
 in str string
Returns
void
Warning
Overwrites White space and control characters with EOS.
Definition at line 49 of file parsing.c.
Referenced by cat(), get_token(), hpdir_find_drive(), lif_add_ascii_file_as_e010_wrapper(), lif_B2S(), lif_ctime_gmt(), and user_task().