hardware/portio.h File Reference
Functions
void portio_help (int full)
Help Menu for AVR PORT IO functions See: int port_tests(char *str)
int portio_tests (int argc __attribute__((unused)), char *argv[])
PORT user tests User invoked PORT functions and tasks.
Function Documentation
portio_help()
void portio_help (int full)
Help Menu for AVR PORT IO functions See: int port_tests(char *str)
Returns
void
Definition at line 25 of file portio.c.
Referenced by help(), and portio_tests().
portio_tests()
int portio_tests (int argc __attribute__(unused), char * argv[])
PORT user tests User invoked PORT functions and tasks.
Returns
1 matched token, 0 if not
Definition at line 44 of file portio.c.
Referenced by user_task().