hardware/portio.c File Reference
PORTIO diagnostic tests for HP85 disk emulator project for AVR.
#include `user_config.h`
#include `defines.h`
#include `stringsup.h`
#include `debug.h`
Functions
void portio_help (int full)
Help Menu for AVR PORT IO functions See: int port_tests(char *str)
int portio_tests (int argc __attribute__((unused)), char *argv[])
PORT user tests User invoked PORT functions and tasks.
Detailed Description
PORTIO diagnostic tests for HP85 disk emulator project for AVR.
Edit History
[1.0] [Mike Gore] Initial revision of file.
Copyright 2014-2020 Mike Gore, All rights reserved. GPL
See also
 http://github.com/magore/hp85disk
 http://github.com/magore/hp85disk/COPYRIGHT.md for Copyright details
Function Documentation
portio_help()
void portio_help (int full)
Help Menu for AVR PORT IO functions See: int port_tests(char *str)
Returns
void
Definition at line 25 of file portio.c.
Referenced by help(), and portio_tests().
portio_tests()
int portio_tests (int argc __attribute__(unused), char * argv[])
PORT user tests User invoked PORT functions and tasks.
Returns
1 matched token, 0 if not
Definition at line 44 of file portio.c.
Referenced by user_task().