posix/posix.c File Reference
POSIX wrapper for FatFS.
#include `user_config.h`
#include `stringsup.h`
#include `fatfs.h`
#include `posix.h`
Functions
MEMSPACE int isatty (int fileno)
Test POSIX fileno if it is a Serial Console/TTY.
MEMSPACE int fgetc (FILE *stream)
Get byte from a TTY device or FatFs file stream open() or fopen() sets stream->get = fatfs_getc() for FatFs functions See fdevopen() sets stream->get for TTY devices.
MEMSPACE int fputc (int c, FILE *stream)
Put a byte to TTY device or FatFs file stream open() or fopen() sets stream->put = fatfs_outc() for FatFs functions See fdevopen() sets stream->put get for TTY devices.
MEMSPACE int getchar ()
functions normally defined as macros
MEMSPACE int putchar (int c)
put a character to stdout See fdevopen() sets stream->put get for TTY devices
MEMSPACE int ungetc (int c, FILE *stream)
Un-Get byte from a TTY device or FatFs file stream.
MEMSPACE int putc (int c, FILE *stream)
Put a character to a stream See fdevopen() sets stream->put get for TTY devices.
MEMSPACE char * fgets (char *str, int size, FILE *stream)
get a string from stdin See fdevopen() sets stream->put get for TTY devices
MEMSPACE int fputs (const char *str, FILE *stream)
put a string to stdout See fdevopen() sets stream->put get for TTY devices
MEMSPACE int puts (const char *str)
put a string to stdout See fdevopen() sets stream->put get for TTY devices
MEMSPACE int feof (FILE *stream)
feof reports if the stream is at EOF
MEMSPACE int fgetpos (FILE *stream, size_t *pos)
POSIX get position of file stream.
MEMSPACE int fseek (FILE *stream, long offset, int whence)
POSIX seek to file possition.
MEMSPACE int fsetpos (FILE *stream, size_t *pos)
POSIX set position of file stream.
MEMSPACE long ftell (FILE *stream)
POSIX file position of open stream.
MEMSPACE off_t lseek (int fileno, off_t position, int whence)
POSIX seek to file position.
MEMSPACE void rewind (FILE *stream)
POSIX rewind file to the beginning.
MEMSPACE int close (int fileno)
POSIX Close a file with fileno handel.
MEMSPACE int fileno (FILE *stream)
Convert POSIX stream pointer to POSIX fileno (index of __iob[])
MEMSPACE FILE * fileno_to_stream (int fileno)
Convert POSIX fileno to POSIX FILE stream pointer. NOT POSIX.
MEMSPACE FILE * fopen (const char *path, const char *mode)
POSIX Open a file with path name and ascii file mode string.
MEMSPACE size_t fread (void *ptr, size_t size, size_t nmemb, FILE *stream)
POSIX read nmemb elements from buf, size bytes each, to the stream fd.
MEMSPACE int ftruncate (int fd, off_t length)
POSIX truncate open file to length.
MEMSPACE size_t fwrite (const void *ptr, size_t size, size_t nmemb, FILE *stream)
POSIX write nmemb elements from buf, size bytes each, to the stream fd.
MEMSPACE int open (const char *pathname, int flags)
POSIX Open a file with integer mode flags.
MEMSPACE ssize_t read (int fd, const void *buf, size_t count)
POSIX read count bytes from *buf to fileno fd.
MEMSPACE void sync (void)
POSIX Sync all pending file changes and metadata on ALL files.
MEMSPACE int syncfs (int fd)
POSIX Sync pending file changes and metadata for specified fileno.
MEMSPACE int truncate (const char *path, off_t length)
POSIX truncate named file to length.
MEMSPACE ssize_t write (int fd, const void *buf, size_t count)
POSIX Write count bytes from *buf to fileno fd.
MEMSPACE int fclose (FILE *stream)
POSIX close a file stream.
MEMSPACE void dump_stat (struct stat *sp)
Display struct stat, from POSIX stat(0 or fstat(), in ASCII. NOT POSIX.
MEMSPACE char * mctime (time_t timev)
Display Ascii formatted time from timev seconds NOT POSIX.
MEMSPACE int stat (char *name, struct stat *buf)
POSIX stat - get file status of named file.
MEMSPACE int utime (const char *filename, const struct utimbuf *times)
Set Modification and Access time of a file.
MEMSPACE char * basename (char *str)
POSIX Basename of filename.
MEMSPACE char * baseext (char *str)
File extention of a file name. NOT POSIX.
MEMSPACE int chdir (const char *pathname)
POSIX change directory.
MEMSPACE int chmod (const char *pathname, mode_t mode)
POSIX chmod function - change file access permission Unfortunately file f_open modes and f_chmod modes are not the same Files that are open have way more options - but only while the file is open.
MEMSPACE int dirname (char *str)
POSIX directory name of a filename. Return the index of the last '/' character.
MEMSPACE char * getcwd (char *pathname, int len)
POSIX get current working directory.
MEMSPACE int mkdir (const char *pathname, mode_t mode)
POSIX make a directory.
MEMSPACE int rename (const char *oldpath, const char *newpath)
POSIX rename a file by name.
MEMSPACE int rmdir (const char *pathname)
POSIX delete a directory.
MEMSPACE int unlink (const char *pathname)
POSIX delete a file.
int closedir (DIR *dirp)
POSIX closedir.
DIR * opendir (const char *pathdir)
dirent_t * readdir (DIR *dirp)
MEMSPACE void clrerror (FILE *stream)
clrerror resets stream EOF and error flags
MEMSPACE int ferror (FILE *stream)
ferror reports if the stream has an error flag set
MEMSPACE void perror (const char *s)
POSIX perror() - convert POSIX errno to text with user message.
MEMSPACE char WEAK_ATR * strerror (int errnum)
POSIX strerror() - convert POSIX errno to text with user message.
MEMSPACE char * strerror_r (int errnum, char *buf, size_t buflen)
POSIX strerror_r() - convert POSIX errno to text with user message.
MEMSPACE FILE * fdevopen (int(*put)(char, FILE *), int(*get)(FILE *))
Device open functions.
int mkfs (char *name)
Formt SD card.
MEMSPACE int fatfs_getc (FILE *stream)
Private FatFs function called by fgetc() to get a byte from file stream FIXME buffer this function call NOT POSIX open() assigns stream->get = fatfs_getc()
MEMSPACE int fatfs_putc (char c, FILE *stream)
Private FatFs function called by fputc() to put a byte from file stream NOT POSIX open() assigns stream->put = fatfs_putc()
MEMSPACE int fatfs_to_errno (FRESULT Result)
Convert FafFs error result to POSIX errno. NOT POSIX.
MEMSPACE int fatfs_to_fileno (FIL *fh)
Convert FatFS file handle to POSIX fileno. NOT POSIX.
MEMSPACE time_t fat_time_to_unix (uint16_t date, uint16_t time)
Convert FatFs file date and time to POSIX epoch seconds. NOT POSIX.
MEMSPACE void unix_time_to_fat (time_t epoch, uint16_t *date, uint16_t *time)
Convert Linux POSIX time_t to FAT32 date and time. NOT POSIX.
MEMSPACE FIL * fileno_to_fatfs (int fileno)
Convert POSIX fileno to FatFS handle NOT POSIX.
MEMSPACE int free_file_descriptor (int fileno)
Free POSIX fileno FILE descriptor. NOT POSIX.
MEMSPACE int new_file_descriptor (void)
Allocate a POSIX FILE descriptor. NOT POSIX.
MEMSPACE int posix_fopen_modes_to_open (const char *mode)
Convert POSIX fopen mode to POSIX open mode flags. NOT POSIX.
static MEMSPACE void _fprintf_putc (struct _printf_t *p, char ch)
fprintf character write function
MEMSPACE int fprintf (FILE *fp, const char *format,...)
fprintf function Example user defined printf function using fputc for I/O This method allows I/O to devices and strings without typical C++ overhead
Variables
int errno
Note: fdevopen assigns stdin,stdout,stderr.
FILE * __iob [MAX_FILES]
POSIX fileno to POSIX FILE stream table.
const char * sys_errlist []
POSIX error messages for each errno value.
static DIR _dp
POSIX opendir.
static dirent_t _de
POSIX opendir.
Detailed Description
POSIX wrapper for FatFS.
Copyright 2014-2020 Mike Gore, All rights reserved. GPL License
See also
 http://github.com/magore/hp85disk
 http://github.com/magore/hp85disk/COPYRIGHT.md for specific Copyright details
You are free to use this code under the terms of GPL
please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Provides many of the common Posix/linux functions
POSIX character I/O functions
isatty
fgetc
fputc
getchar
putc
putchar
ungetc
POSIX string I/O functions
fgets
fputs
puts
POSIX file position functions
feof
fgetpos
fseek
fsetpos
ftell
lseek
rewind
POSIX file functions
close
fileno
fileno_to_stream NOT POSIX
fopen
fread
ftruncate
fwrite
open
read
sync
syncfs
truncate
write
fclose
POSIX file information functions
dump_stat - NOT POSIX
fstat
mctime - NOT POSIX
stat
POSIX file and directory manipulation
basename
baseext - NOT POSIX
chmod
chdir
dirname
getcwd
mkdir
rename
rmdir
unlink
utime
POSIX - directory scanning functions
closedir
opendir
readdir
POSIX error functions
clrerror
ferror
perror
strerror
strerror_r
Device open functions
fdevopen - NOT POSIX
FatFS to POSIX bridge functions - NOT POSIX
fatfs_getc
fatfs_putc
fatfs_to_errno
fatfs_to_fileno
fat_time_to_unix
fileno_to_fatfs
free_file_descriptor
new_file_descriptor
mkfs
posix_fopen_modes_to_open
unix_time_to_fat
Function Documentation
_fprintf_putc()
static MEMSPACE void _fprintf_putc (struct _printf_t * p, char ch) [static]
fprintf character write function
POSIX fprintf function
Parameters
 in *p printf user buffer
 in ch character TODO if fputc fails we might want to also set an error in the *p structure - error in the stream will already be set
Definition at line 2517 of file posix.c.
Referenced by fprintf().
baseext()
MEMSPACE char* baseext (char * str)
File extention of a file name. NOT POSIX.
Parameters
 in str string to find extension in.
Returns
pointer to basename extension.
Definition at line 1490 of file posix.c.
basename()
MEMSPACE char* basename (char * str)
POSIX Basename of filename.
POSIX file and directory manipulation
man page (3).
Parameters
 in str string to find basename in.
Returns
pointer to basename of string.
Definition at line 1469 of file posix.c.
Referenced by lif_fixname(), and ls_info().
chdir()
MEMSPACE int chdir (const char * pathname)
POSIX change directory.
man page chdir (2).
Parameters
 in pathname directory to change to
Returns
0 on sucess.
-1 on error with errno set.
Definition at line 1512 of file posix.c.
Referenced by posix_tests().
chmod()
MEMSPACE int chmod (const char * pathname, mode_t mode)
POSIX chmod function - change file access permission Unfortunately file f_open modes and f_chmod modes are not the same Files that are open have way more options - but only while the file is open.
so this is a bit of a hack - we can only set read only - if on one has write perms
man page chmod (2).
Parameters
 in pathname filename string.
 in mode POSIX chmod modes.
Returns
fileno on success.
Definition at line 1538 of file posix.c.
Referenced by mkdir(), and posix_tests().
close()
MEMSPACE int close (int fileno)
POSIX Close a file with fileno handel.
POSIX file functions
man page close (2).
Parameters
 in fileno fileno of file.
Returns
0 on sucess.
-1 on error with errno set.
Definition at line 701 of file posix.c.
Referenced by fclose().
closedir()
int closedir (DIR * dirp)
POSIX closedir.
POSIX - directory scanning functions
man page closedir (2).
Parameters
 in dirp DIR * directory handle
Returns
0 on sucess.
-1 on error with errno set.
Definition at line 1748 of file posix.c.
Referenced by ls().
clrerror()
MEMSPACE void clrerror (FILE * stream)
clrerror resets stream EOF and error flags
POSIX error functions
man page clrerror(3).
Parameters
 in stream POSIX stream pointer.
Returns
EOF on error with errno set.
Definition at line 1820 of file posix.c.
dirname()
MEMSPACE int dirname (char * str)
POSIX directory name of a filename. Return the index of the last '/' character.
Example:
dir[0] = 0;
ret = dirname(path)
if(ret)
 strncpy(dir,path,ret);
Parameters
 in str string to examine.
Returns
0 if no directory part.
index of last '/' character.
Definition at line 1577 of file posix.c.
Referenced by hpdir_find_drive().
dump_stat()
MEMSPACE void dump_stat (struct stat * sp)
Display struct stat, from POSIX stat(0 or fstat(), in ASCII. NOT POSIX.
POSIX file information functions
Parameters
 in sp struct stat pointer.
Returns
void.
Definition at line 1283 of file posix.c.
Referenced by posix_tests().
fat_time_to_unix()
MEMSPACE time_t fat_time_to_unix (uint16_t date, uint16_t time)
Convert FatFs file date and time to POSIX epoch seconds. NOT POSIX.
man page timegm (3).
Parameters
 in date FatFs date.
 in time FatFs time.
See also
timegm()
Returns
epoch seconds
Definition at line 2276 of file posix.c.
Referenced by stat().
fatfs_getc()
MEMSPACE int fatfs_getc (FILE * stream)
Private FatFs function called by fgetc() to get a byte from file stream FIXME buffer this function call NOT POSIX open() assigns stream->get = fatfs_getc()
man page fgetc (3).
Notes: fgetc does all tests prior to caling us, including ungetc.
Parameters
 in stream POSIX stream pointer.
Returns
character.
EOF on error with errno set.
Definition at line 2031 of file posix.c.
Referenced by open().
fatfs_putc()
MEMSPACE int fatfs_putc (char c, FILE * stream)
Private FatFs function called by fputc() to put a byte from file stream NOT POSIX open() assigns stream->put = fatfs_putc()
man page fputc (3).
Notes: fputc does all tests prior to caling us.
Parameters
 in c character.
 in stream POSIX stream pointer.
Returns
character
EOF on error with errno set.
Definition at line 2122 of file posix.c.
Referenced by fputc(), and open().
fatfs_to_errno()
MEMSPACE int fatfs_to_errno (FRESULT Result)
Convert FafFs error result to POSIX errno. NOT POSIX.
man page errno (3).
Parameters
 in Result FatFs Result code.
Returns
POSIX errno.
EBADMSG if no conversion possible.
Definition at line 2163 of file posix.c.
Referenced by chdir(), chmod(), close(), closedir(), fatfs_getc(), fatfs_putc(), ftruncate(), getcwd(), lseek(), mkdir(), open(), opendir(), read(), readdir(), rename(), rmdir(), stat(), syncfs(), truncate(), unlink(), utime(), and write().
fatfs_to_fileno()
MEMSPACE int fatfs_to_fileno (FIL * fh)
Convert FatFS file handle to POSIX fileno. NOT POSIX.
Parameters
 in fh FatFS file pointer.
Returns
fileno on success.
-1 on error with errno set to EBADF.
Definition at line 2238 of file posix.c.
fclose()
MEMSPACE int fclose (FILE * stream)
POSIX close a file stream.
man page flose (3).
Parameters
 in stream POSIX stream pointer.
Returns
0 on sucess.
-1 on error witrh errno set.
Definition at line 1261 of file posix.c.
Referenced by buffer_read_close(), cat(), copy(), gpib_trace_task(), hpdir_find_drive(), lif_add_ascii_file_as_e010_wrapper(), lif_close_volume(), lif_extract_e010_as_ascii(), MatRead(), MatWrite(), printer_close(), Read_Config(), td02lif(), and timetests().
fdevopen()
MEMSPACE FILE* fdevopen (int(*)(char, FILE *) put, int(*)(FILE *) get)
Device open functions.
Assign stdin,stdout,stderr or any use defined I/O NOT POSIX
Parameters
 in *put putc function pointer
 in *get gutc function pointer
Definition at line 1912 of file posix.c.
Referenced by uart_init().
feof()
MEMSPACE int feof (FILE * stream)
feof reports if the stream is at EOF
POSIX file position functions
man page feof (3).
Parameters
 in stream POSIX stream pointer.
Returns
1 if EOF set, 0 otherwise.
Definition at line 516 of file posix.c.
ferror()
MEMSPACE int ferror (FILE * stream)
ferror reports if the stream has an error flag set
man page ferror (3).
Parameters
 in stream POSIX stream pointer.
Returns
1 if EOF set, 0 otherwise.
Definition at line 1833 of file posix.c.
fgetc()
MEMSPACE int fgetc (FILE * stream)
Get byte from a TTY device or FatFs file stream open() or fopen() sets stream->get = fatfs_getc() for FatFs functions See fdevopen() sets stream->get for TTY devices.
man page fgetc (3).
Parameters
 in stream POSIX stream pointer.
Returns
character.
EOF on error with errno set.
Definition at line 216 of file posix.c.
Referenced by fgets(), getchar(), and read().
fgetpos()
MEMSPACE int fgetpos (FILE * stream, size_t * pos)
POSIX get position of file stream.
man page fgetpos (3).
Parameters
 in stream POSIX file stream.
 in pos position pointer for return.
Returns
0 on sucess.
-1 on error with errno set.
Definition at line 534 of file posix.c.
fgets()
MEMSPACE char* fgets (char * str, int size, FILE * stream)
get a string from stdin See fdevopen() sets stream->put get for TTY devices
POSIX string I/O
man page fgets (3).
Parameters
 in stream POSIX stream pointer.
Returns
character.
Definition at line 432 of file posix.c.
Referenced by cat(), hpdir_find_drive(), lif_add_ascii_file_as_e010_wrapper(), MatRead(), Read_Config(), setdate(), and user_task().
fileno()
MEMSPACE int fileno (FILE * stream)
Convert POSIX stream pointer to POSIX fileno (index of __iob[])
man page fileno (3)
Parameters
 in stream stream pointer
Returns
int fileno on success
-1 with errno = EBAFD if stream is NULL or not found
Definition at line 741 of file posix.c.
Referenced by close(), fclose(), fileno(), fileno_to_fatfs(), fileno_to_stream(), fopen(), fread(), free_file_descriptor(), fseek(), ftell(), fwrite(), isatty(), lseek(), open(), receive_plot_flush(), and ungetc().
fileno_to_fatfs()
MEMSPACE FIL* fileno_to_fatfs (int fileno)
Convert POSIX fileno to FatFS handle NOT POSIX.
FatFS file handle is pointed to by the avr-libc stream->udata.
Parameters
 in fileno fileno of file
Returns
FIL * FatFS file handle on success.
NULL if POSIX fileno is invalid NULL
Definition at line 2327 of file posix.c.
Referenced by close(), ftell(), ftruncate(), lseek(), open(), read(), sync(), syncfs(), and write().
fileno_to_stream()
MEMSPACE FILE* fileno_to_stream (int fileno)
Convert POSIX fileno to POSIX FILE stream pointer. NOT POSIX.
inverse of POSIX fileno()
man page fileno (3)
Parameters
 in fileno POSIX fileno is the index of __iob[].
See also
fileno()
Returns
FILE * on success
NULL on error with errno set, NULL if fileno out of bounds
Definition at line 772 of file posix.c.
Referenced by close(), fileno_to_fatfs(), fopen(), free_file_descriptor(), lseek(), open(), read(), syncfs(), and write().
fopen()
MEMSPACE FILE* fopen (const char * path, const char * mode)
POSIX Open a file with path name and ascii file mode string.
man page fopen(3).
Parameters
 in path filename string.
 in mode POSIX open mode strings.
Returns
stream * on success.
NULL on error with errno set.
Definition at line 801 of file posix.c.
Referenced by buffer_read_open(), cat(), copy(), gpib_trace_task(), hpdir_find_drive(), lif_open(), MatRead(), MatWrite(), printer_open(), Read_Config(), td02lif(), td0_open(), and timetests().
fprintf()
MEMSPACE int fprintf (FILE * fp, const char * format, ...)
fprintf function Example user defined printf function using fputc for I/O This method allows I/O to devices and strings without typical C++ overhead
Parameters
 in *fp FILE stream pointer
 in fmt printf forat string
 in ... vararg list or arguments
Returns
size of printed result
Definition at line 2533 of file posix.c.
Referenced by gpib_decode_header(), gpib_log(), gpib_trace_display(), MatWrite(), and timetests().
fputc()
MEMSPACE int fputc (int c, FILE * stream)
Put a byte to TTY device or FatFs file stream open() or fopen() sets stream->put = fatfs_outc() for FatFs functions See fdevopen() sets stream->put get for TTY devices.
man page fputc (3).
Parameters
 in stream POSIX stream pointer.
Returns
character.
Definition at line 287 of file posix.c.
Referenced by _fprintf_putc(), fputs(), putc(), putchar(), puts(), and write().
fputs()
MEMSPACE int fputs (const char * str, FILE * stream)
put a string to stdout See fdevopen() sets stream->put get for TTY devices
man page fputs (3).
Parameters
 in stream POSIX stream pointer.
Returns
character.
Definition at line 470 of file posix.c.
fread()
MEMSPACE size_t fread (void * ptr, size_t size, size_t nmemb, FILE * stream)
POSIX read nmemb elements from buf, size bytes each, to the stream fd.
man page fread (3).
Parameters
 in ptr buffer.
 in nmemb number of items to read.
 in size size of each item in bytes.
 in stream POSIX file stream.
Returns
count on sucess.
0 or < size on error with errno set.
Definition at line 823 of file posix.c.
Referenced by buffer_getc(), copy(), lif_read(), td0_open(), and td0_read().
free_file_descriptor()
MEMSPACE int free_file_descriptor (int fileno)
Free POSIX fileno FILE descriptor. NOT POSIX.
Parameters
 in fileno POSIX file number __iob[] index.
Returns
fileno on success.
-1 on failure.
Definition at line 2361 of file posix.c.
Referenced by close(), and open().
fseek()
MEMSPACE int fseek (FILE * stream, long offset, int whence)
POSIX seek to file possition.
man page fseek (3).
Parameters
 in stream POSIX file stream.
 in offset offset to seek to.
 in whence
SEEK_SET The offset is set to offset bytes.
SEEK_CUR The offset is set to its current location plus offset bytes.
SEEK_END The offset is set to the size of the file plus offset bytes.
Returns
file position on sucess.
-1 on error.
Definition at line 558 of file posix.c.
Referenced by fsetpos(), lif_close_volume(), lif_seek_msg(), and rewind().
fsetpos()
MEMSPACE int fsetpos (FILE * stream, size_t * pos)
POSIX set position of file stream.
man page fsetpos (3).
Parameters
 in stream POSIX file stream.
 in pos position pointer.
Returns
0 with *pos set to position on sucess.
-1 on error with errno set.
Definition at line 585 of file posix.c.
ftell()
MEMSPACE long ftell (FILE * stream)
POSIX file position of open stream.
man page fteel (3).
Parameters
 in stream POSIX file stream.
Returns
file position on sucess.
-1 on error with errno set.
Definition at line 600 of file posix.c.
Referenced by fgetpos(), and lif_seek_msg().
ftruncate()
MEMSPACE int ftruncate (int fd, off_t length)
POSIX truncate open file to length.
man page ftruncate (3).
Parameters
 in fd open file number.
 in length length to truncate to.
Returns
0 on success.
-1 on fail.
Definition at line 848 of file posix.c.
fwrite()
MEMSPACE size_t fwrite (const void * ptr, size_t size, size_t nmemb, FILE * stream)
POSIX write nmemb elements from buf, size bytes each, to the stream fd.
man page write (2).
Parameters
 in ptr buffer.
 in nmemb number of items to write.
 in size size of each item in bytes.
 in stream POSIX file stream.
Returns
count written on sucess.
0 or < size on error with errno set.
Definition at line 890 of file posix.c.
Referenced by copy(), lif_extract_e010_as_ascii(), lif_write(), receive_plot_flush(), and td0_save_lif_sector().
getchar()
MEMSPACE int getchar ()
functions normally defined as macros
get a character from stdin See fdevopen() sets stream->get for TTY devices
man page getchar (3).
Parameters
 in stream POSIX stream pointer.
Returns
character.
Definition at line 347 of file posix.c.
Referenced by testpage().
getcwd()
MEMSPACE char* getcwd (char * pathname, int len)
POSIX get current working directory.
man page getcwd (2).
Parameters
 in pathname directory to change to
Returns
0 on sucess.
-1 on error with errno set.
Definition at line 1623 of file posix.c.
Referenced by ls(), and posix_tests().
isatty()
MEMSPACE int isatty (int fileno)
Test POSIX fileno if it is a Serial Console/TTY.
POSIX character I/O functions
man page isatty (3).
Parameters
 in fileno POSIX fileno of open file.
Returns
1 if fileno is a serial TTY/Console (uart in avr-libc terms).
0 if POSIX fileno is NOT a Serial TTY.
Todo
Todo Perhaps we should verify console functions have been added ?
Definition at line 195 of file posix.c.
Referenced by fileno_to_fatfs(), free_file_descriptor(), ftell(), ftruncate(), lseek(), new_file_descriptor(), sync(), syncfs(), and ungetc().
lseek()
MEMSPACE off_t lseek (int fileno, off_t position, int whence)
POSIX seek to file position.
man page lseek (2).
Parameters
 in fileno POSIX fileno of open file.
 in position offset to seek to.
 in whence
SEEK_SET The offset is set to offset bytes.
SEEK_CUR The offset is set to its current location plus offset bytes.
SEEK_END The offset is set to the size of the file plus offset bytes.
Returns
file position on sucess.
-1 on error.
Definition at line 633 of file posix.c.
Referenced by fseek().
mctime()
MEMSPACE char* mctime (time_t timev)
Display Ascii formatted time from timev seconds NOT POSIX.
Assumes no timezone offset.
man page ctime (3).
Parameters
 in timev epoch time in seconds
Returns
ascii string pointer of POSIX ctime()
See also
ctime()
Definition at line 1346 of file posix.c.
Referenced by dump_stat(), and ls_info().
mkdir()
MEMSPACE int mkdir (const char * pathname, mode_t mode)
POSIX make a directory.
man page mkdir (2).
Parameters
 in pathname directory to create
Returns
0 on sucess.
-1 on error with errno set.
Definition at line 1647 of file posix.c.
Referenced by posix_tests().
mkfs()
int mkfs (char * name)
Formt SD card.
FatFS to POSIX bridge functions
Parameters
 in *name device name @retrun void
Definition at line 1960 of file posix.c.
Referenced by posix_tests().
new_file_descriptor()
MEMSPACE int new_file_descriptor (void)
Allocate a POSIX FILE descriptor. NOT POSIX.
Returns
fileno on success.
-1 on failure with errno set.
Definition at line 2404 of file posix.c.
Referenced by open().
open()
MEMSPACE int open (const char * pathname, int flags)
POSIX Open a file with integer mode flags.
man page open (2).
Parameters
 in pathname filename string.
 in flags POSIX open modes.
Returns
fileno on success.
-1 on error with errno set.
Seek to end of the file
Definition at line 916 of file posix.c.
Referenced by fopen().
opendir()
DIR* opendir (const char * pathdir)
Definition at line 1768 of file posix.c.
Referenced by ls().
perror()
MEMSPACE void perror (const char * s)
POSIX perror() - convert POSIX errno to text with user message.
man page errno (3).
Parameters
 in s User message displayed before the error message
See also
sys_errlist[].
Returns
void.
Definition at line 1850 of file posix.c.
Referenced by gpib_trace_task(), printer_open(), Read_Config(), receive_plot_flush(), and timetests().
posix_fopen_modes_to_open()
MEMSPACE int posix_fopen_modes_to_open (const char * mode)
Convert POSIX fopen mode to POSIX open mode flags. NOT POSIX.
man page fopen (3).
man page open (2).
Valid modes.
Read
`r`, `rb`
Read and Write
`r+`, `r+b`, `rb+`
Write
`w`, `wb`
Write and Read.
`w+`, `w+b`, `wb+`
`w+` implies write/read access.
Append
`a`, `ab`
Append and Read
`a+`, `a+b`, `ab+`
Note: ORDER IS IMPORTANT! so w+ is NOT the same as r+.
ALWAYS do a fflush or fseek between rear write operations if + is used..
Parameters
 in mode POSIX file mode string.
Returns
open mode flags.
-1 on error.
Warning
read and write BOTH share the same stream buffer and buffer index pointers.
Definition at line 2468 of file posix.c.
Referenced by fopen().
putc()
MEMSPACE int putc (int c, FILE * stream)
Put a character to a stream See fdevopen() sets stream->put get for TTY devices.
man page putc (3).
Parameters
 in stream POSIX stream pointer.
Definition at line 414 of file posix.c.
putchar()
MEMSPACE int putchar (int c)
put a character to stdout See fdevopen() sets stream->put get for TTY devices
man page putchar (3).
Parameters
 in stream POSIX stream pointer.
Returns
character.
Definition at line 363 of file posix.c.
Referenced by print_tok(), print_tok_str(), print_tok_val(), and td0_hexdump().
puts()
MEMSPACE int puts (const char * str)
put a string to stdout See fdevopen() sets stream->put get for TTY devices
man page puts (3).
Parameters
 in stream POSIX stream pointer.
Returns
character.
Definition at line 493 of file posix.c.
Referenced by cat(), and gpib_trace_display().
read()
MEMSPACE ssize_t read (int fd, const void * buf, size_t count)
POSIX read count bytes from *buf to fileno fd.
man page read (2).
Parameters
 in fd POSIX fileno.
 in buf buffer.
 in count number of bytes to write.
Returns
count on sucess.
-1 on error with errno set.
Definition at line 1028 of file posix.c.
Referenced by fread().
readdir()
dirent_t* readdir (DIR * dirp)
Definition at line 1788 of file posix.c.
Referenced by ls().
rename()
MEMSPACE int rename (const char * oldpath, const char * newpath)
POSIX rename a file by name.
man page (2).
Parameters
 in oldpath original name.
 in newpath new name.
Returns
0 on success.
-1 on error with errno set.
Definition at line 1677 of file posix.c.
Referenced by posix_tests().
rewind()
MEMSPACE void rewind (FILE * stream)
POSIX rewind file to the beginning.
man page rewind (3).
Parameters
 in stream POSIX file stream.
Returns
void.
Definition at line 681 of file posix.c.
rmdir()
MEMSPACE int rmdir (const char * pathname)
POSIX delete a directory.
man page rmdir (2).
Parameters
 in pathname directory to delete.
Returns
0 on sucess.
-1 on error with errno set.
Definition at line 1701 of file posix.c.
Referenced by posix_tests().
stat()
MEMSPACE int stat (char * name, struct stat * buf)
POSIX stat - get file status of named file.
man page (2).
Parameters
 in name file name.
 in buf struct stat buffer to return results in.
Returns
0 on success.
-1 on error with errno set.
Definition at line 1368 of file posix.c.
Referenced by f_getfree(), format_drives(), lif_stat(), ls(), ls_info(), mount_volume(), and posix_tests().
strerror()
MEMSPACE char WEAK_ATR* strerror (int errnum)
POSIX strerror() - convert POSIX errno to text with user message.
man page strerror (3).
Parameters
 in errnum index for sys_errlist[]
See also
sys_errlist[].
Returns
char *
Definition at line 1876 of file posix.c.
strerror_r()
MEMSPACE char* strerror_r (int errnum, char * buf, size_t buflen)
POSIX strerror_r() - convert POSIX errno to text with user message.
man page strerror (3).
Parameters
 in errnum index for sys_errlist[]
 in buf user buffer for error message
 in buflen length of user buffer for error message
See also
sys_errlist[].
Returns
char *
Definition at line 1893 of file posix.c.
sync()
MEMSPACE void sync (void)
POSIX Sync all pending file changes and metadata on ALL files.
man page sync (2).
Returns
void.
Definition at line 1091 of file posix.c.
Referenced by lif_close_volume(), and lif_extract_e010_as_ascii().
syncfs()
MEMSPACE int syncfs (int fd)
POSIX Sync pending file changes and metadata for specified fileno.
man page syncfs (2).
Parameters
 in fd POSIX fileno to sync.
Returns
0.
-1 on error witrh errno set.
Definition at line 1119 of file posix.c.
Referenced by receive_plot_flush(), and sync().
truncate()
MEMSPACE int truncate (const char * path, off_t length)
POSIX truncate named file to length.
man page truncate (2).
Parameters
 in path file name to truncate.
 in length length to truncate to.
Returns
0 on sucess.
-1 n fail.
Definition at line 1164 of file posix.c.
ungetc()
MEMSPACE int ungetc (int c, FILE * stream)
Un-Get byte from a TTY device or FatFs file stream.
man page ungetc (3).
Parameters
 in c Character to unget
 in stream POSIX stream pointer.
Returns
character.
EOF on error with errno set.
Definition at line 380 of file posix.c.
unix_time_to_fat()
MEMSPACE void unix_time_to_fat (time_t epoch, uint16_t * date, uint16_t * time)
Convert Linux POSIX time_t to FAT32 date and time. NOT POSIX.
man page gmtime (3).
Parameters
 in epoch unix epoch seconds
 in *date fat32 date
 in *time fat32 time
Returns
void
Definition at line 2302 of file posix.c.
Referenced by utime().
unlink()
MEMSPACE int unlink (const char * pathname)
POSIX delete a file.
man page unlink (2).
Parameters
 in pathname filename to delete.
Returns
0 on sucess.
-1 on error with errno set.
Definition at line 1723 of file posix.c.
Referenced by posix_tests().
utime()
MEMSPACE int utime (const char * filename, const struct utimbuf * times)
Set Modification and Access time of a file.
Parameters
 in filename file name
   [in *times: access and modication utimbuf structure, if NULL use current time
Returns
0 if ok, -1 on error
Definition at line 1432 of file posix.c.
Referenced by lif_extract_e010_as_ascii().
write()
MEMSPACE ssize_t write (int fd, const void * buf, size_t count)
POSIX Write count bytes from *buf to fileno fd.
man page write (2).
Parameters
 in fd POSIX fileno.
 in buf buffer.
 in count number of bytes to write.
Returns
count on sucess.
-1 on error with errno set.
Definition at line 1202 of file posix.c.
Referenced by fwrite().
Variable Documentation
__iob
FILE* __iob[MAX_FILES]
POSIX fileno to POSIX FILE stream table.
Note: the index of __iob[] is reffered to `fileno`.
Reference: libc/avr-libc-1.8.0/libc/stdio.
stdin = __iob[0].
__iob[1] = stdout.
__iob[2] = stderr.
Definition at line 138 of file posix.c.
Referenced by fatfs_to_fileno(), fileno(), fileno_to_stream(), free_file_descriptor(), and new_file_descriptor().
_de
dirent_t _de [static]
POSIX opendir.
man page readdir(2).
Parameters
 in dirp DIR * directory handle
Returns
DIR * on sucess.
NULL on error with errno set.
Definition at line 1787 of file posix.c.
Referenced by readdir().
_dp
DIR _dp [static]
POSIX opendir.
man page opendir (2).
Parameters
 in pathname directory to delete.
Returns
DIR * on sucess.
NULL on error with errno set.
Definition at line 1767 of file posix.c.
Referenced by opendir().
errno
int errno
Note: fdevopen assigns stdin,stdout,stderr.
POSIX errno.
Definition at line 129 of file posix.c.
Referenced by chdir(), chmod(), close(), closedir(), fatfs_getc(), fatfs_putc(), fatfs_to_fileno(), fgetc(), fileno(), fileno_to_fatfs(), fileno_to_stream(), fputc(), free_file_descriptor(), ftell(), ftruncate(), getcwd(), lseek(), mctime(), mkdir(), new_file_descriptor(), open(), opendir(), perror(), read(), readdir(), rename(), rmdir(), stat(), syncfs(), truncate(), unlink(), and write().
sys_errlist
const char* sys_errlist[]
POSIX error messages for each errno value.
man page errno (3)
Definition at line 143 of file posix.c.
Referenced by perror(), strerror(), and strerror_r().