posix/posix_tests.c File Reference
fatfs test utilities with user interface
#include `user_config.h`
#include `fatfs.h`
#include `time.h`
#include `stringsup.h`
#include `mathio.h`
#include `posix.h`
#include `posix_tests.h`
Macros
#define BUFSIZE 512
Functions
MEMSPACE void posix_help (int full)
MEMSPACE int posix_tests (int argc, char *argv[])
POSIX tests.
MEMSPACE long cat (char *name, int dopage)
Display the contents of a file.
MEMSPACE long copy (char *from, char *to)
Copy a file.
MEMSPACE int setpage (int count)
MEMSPACE int testpage (int count)
Used to page output of functions like cat, hexdump, etc.
MEMSPACE int ls_info (char *name, int verbose)
list one file
MEMSPACE int ls (char *name, int verbose)
Directory listing.
Variables
static int _pagesize = 25
Used to page output of functions like cat, hexdump, etc.
Detailed Description
fatfs test utilities with user interface
Copyright 2014-2020 Mike Gore, All rights reserved. GPL License
See also
 http://github.com/magore/hp85disk
 http://github.com/magore/hp85disk/COPYRIGHT.md for specific Copyright details
You are free to use this code under the terms of GPL
please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Macro Definition Documentation
BUFSIZE
#define BUFSIZE 512
Definition at line 43 of file posix_tests.c.
Function Documentation
cat()
MEMSPACE long cat (char * name, int dopage)
Display the contents of a file.
Parameters
 in name file name.
 in option --p page display
Returns
void.
Definition at line 294 of file posix_tests.c.
Referenced by posix_tests().
copy()
MEMSPACE long copy (char * from, char * to)
Copy a file.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Parameters
 in from source file.
 in to destination file.
Returns
bytes written
Definition at line 337 of file posix_tests.c.
Referenced by posix_tests().
ls()
MEMSPACE int ls (char * name, int verbose)
Directory listing.
Parameters
 in path file name or directory
 in option -l for detail
Returns
number of files
Definition at line 553 of file posix_tests.c.
Referenced by posix_tests().
ls_info()
MEMSPACE int ls_info (char * name, int verbose)
list one file
Parameters
 in path file name or directory
 in verbose 1 = detail, 0 = name only
Returns
1 on success 0 on fail
Definition at line 501 of file posix_tests.c.
Referenced by ls().
posix_help()
MEMSPACE void posix_help (int full)
Definition at line 46 of file posix_tests.c.
Referenced by help(), and posix_tests().
posix_tests()
MEMSPACE int posix_tests (int argc, char * argv[])
POSIX tests.
Parameters
 in agc cont of arguments
Returns
1 The ruturn code indicates a command matched.
0 if no rules matched
Definition at line 93 of file posix_tests.c.
Referenced by user_task().
setpage()
MEMSPACE int setpage (int count)
Definition at line 460 of file posix_tests.c.
Referenced by posix_tests().
testpage()
MEMSPACE int testpage (int count)
Used to page output of functions like cat, hexdump, etc.
Parameters
 in *name file to hexdump @retrun -1 = quit, return count or 0 at new page
Definition at line 471 of file posix_tests.c.
Referenced by cat().
Variable Documentation
_pagesize
int _pagesize = 25 [static]
Used to page output of functions like cat, hexdump, etc.
Parameters
 in *name file to hexdump @retrun void
Definition at line 458 of file posix_tests.c.
Referenced by setpage(), and testpage().