fatfs/posix.doxit.c File Reference
#include <hardware/hardware.h>
*
#include <stdio.h>
*
#include <stdint.h>
*
#include <string.h>
*
#include <stdlib.h>
*
#include `ff.h`
*
#include `diskio.h`
*
#include `posix.h`
*
Macros
#define MAX_FILES 16
Functions
FILE * fileno_to_stream (int fileno)
convert fileno to stream, inverse of POSIX fileno()
 Standard: NONE
int stream_to_fileno (FILE *stream)
convert a stream pointer to fileno (index of __iob[])
 man page fileno (3)
 See: POSIX
 Standard: NONE
FIL * fileno_to_fatfs (int fileno)
convert fileno to FatFS handle
 FatFS file handle is pointed to by the avr-libc stream->udata
 Standard: NONE
int fatfs_to_fileno (FIL *fh)
convert FatFS file handle to fileno
 Standard: NONE
int new_file_descriptor (void)
Allocate a file descriptor
 Standard: NONE
int free_file_descriptor (int fileno)
Free fileno FILE descriptor
int isatty (int fileno)
return 1 if fileno is a console (uart avr-libc)
 man page isatty (3)
 Standard: POSIX
void perror (const char *s)
display user message and text errno message
 man page errno (3)
 See: sys_errlist[]
 Standard: POSIX
int fatfs_to_errno (FRESULT Result)
convert FafFs error number into POSIX errno
 man page errno (3)
int posix_fopen_modes_to_open (const char *mode)
convert POSIX fopen mode to POSIX open mode flags
 man page fopen (3), open(2)
 See: POSIX fopen modes
 Example: `r+` implies read/write access
int fatfs_getc (FILE *stream)
avr-libc low level fgetc(FILE * stream) for FatFs
 man page fgetc (3)
 Notes: fgetc does all tests prior to caling us, including ungetc
int fatfs_putc (char c, FILE *stream)
avr-libc low level fputc(char c, FILE * stream)
 man page fputc (3)
int open (const char *pathname, int flags)
 Open a file with integer mode flags
 man page open (2)
 Standard: POSIX
FILE * fopen (const char *path, const char *mode)
 Open a file with path name and ascii file mode string
 man page fopen(3)
 Standard: POSIX
int close (int fileno)
close a file fileno
 Standard: POSIX
int syncfs (int fd)
Sync pending file changes and metadata for specified fileno
 man page syncfs (2)
 Standard: POSIX
void sync (void)
Sync all pending file changes and metadata on ALL files
 man page sync (2)
 Standard: POSIX
int fclose (FILE *stream)
close POSIX stream
 man page flose (3)
 Standard: POSIX
size_t write (int fd, const void *buf, size_t count)
write count bytes from *buf to fileno fd
 man page write (2)
 Standard: POSIX
size_t fwrite (const void *ptr, size_t size, size_t nmemb, FILE *stream)
write nmemb elements from buf, size bytes each, to the stream fd
 man page write (2)
 Standard: POSIX
size_t read (int fd, const void *buf, size_t count)
read count bytes from *buf to fileno fd
 man page read (2)
 Standard: POSIX
size_t fread (void *ptr, size_t size, size_t nmemb, FILE *stream)
read nmemb elements from buf, size bytes each, to the stream fd
 man page fread (3)
 Standard: POSIX
size_t lseek (int fileno, size_t position, int whence)
seek to file position
 man page lseek (2)
 Standard: POSIX
int fseek (FILE *stream, long offset, int whence)
seek to file possition
 man page fseek (3)
 Standard: POSIX
size_t ftell (FILE *stream)
return file position of open stream
 man page fteel (3)
 Standard: POSIX
void rewind (FILE *stream)
rewind file to the beginning
 man page rewind (3)
 Standard: POSIX
int fgetpos (FILE *stream, size_t *pos)
get position of file stream
 man page fgetpos (3)
int fsetpos (FILE *stream, size_t *pos)
set position of file stream
 man page fsetpos (3)
 Standard: POSIX
int unlink (const char *pathname)
delete a file
 man page unlink (2)
 Standard: POSIX
int rmdir (const char *pathname)
delete a directory
 man page rmdir 2
 Standard: POSIX
time_t fat_time_to_unix (uint16_t date, uint16_t time)
convert FatFs file date and time to POSIX epoch seconds
 man page timegm (3)
 See: timegm
int ftruncate (int fd, off_t length)
truncate open file to length
 man page ftruncate (3)
 Standard: POSIX
int truncate (const char *path, off_t length)
truncate file to length
 man page truncate (2)
 Standard: POSIX
int stat (char *name, struct stat *buf)
POSIX stat - file status
 man page (2)
 Standard: POSIX
char * mctime (time_t timev)
display ascii formatted time of timev seconds
 man page ctime (3)
 Reference: result POSIX ctime
 Standard: NONE
void dump_stat (struct stat *sp)
Display struct stat, from stat(0 or fstat(), in ASCII
int rename (const char *oldpath, const char *newpath)
rename a file
 man page (2)
 Standard: NONE
int dirname (char *str)
return the index of the last '/' character
 man page (3)
 Standard: NONE
char * basename (char *str)
basename of string
 man page (3)
 Standard: POSIX
char * baseext (char *str)
file extention of string
 Standard: NONE
Variables
int errno
Note: AVR fdevopen assigns a stdin,stdout,stderr
FILE * __iob [MAX_FILES]
const char * sys_errlist []
POSIX error messages for each errno value
 man page errno (3)
 See: POSIX errno
Macro Definition Documentation
#define MAX_FILES 16
Definition at line 16 of file posix.doxit.c.
Referenced by fatfs_to_fileno(), fileno_to_stream(), free_file_descriptor(), new_file_descriptor(), stream_to_fileno(), and sync().
Function Documentation
char* baseext (char * str)
file extention of string
 Standard: NONE
Parameters
str string to find extension in
Returns
char * pointer to basename extension
Definition at line 1283 of file posix.doxit.c.
char* basename (char * str)
basename of string
 man page (3)
 Standard: POSIX
Parameters
str string to find basename in
Returns
char * pointer to basename of string
Definition at line 1265 of file posix.doxit.c.
int close (int fileno)
close a file fileno
 Standard: POSIX
Parameters
fileno fileno of file
Returns
int 0 on sucess, -1 on error with errno set
Definition at line 644 of file posix.doxit.c.
Referenced by fclose().
int dirname (char * str)
return the index of the last '/' character
 man page (3)
 Standard: NONE
Parameters
str string to examine
Returns
int 0 no directory part, or index of last '/'
Definition at line 1241 of file posix.doxit.c.
void dump_stat (struct stat * sp)
Display struct stat, from stat(0 or fstat(), in ASCII
Parameters
sp struct stat pointer Standard: NONE
Returns
void
Definition at line 1190 of file posix.doxit.c.
time_t fat_time_to_unix (uint16_t date, uint16_t time)
convert FatFs file date and time to POSIX epoch seconds
 man page timegm (3)
 See: timegm
Parameters
date FatFs date
time FatFs time Standard: result is POSIX
Returns
time_t epoch seconds - POSIX
Definition at line 1002 of file posix.doxit.c.
Referenced by stat().
int fatfs_getc (FILE * stream)
avr-libc low level fgetc(FILE * stream) for FatFs
 man page fgetc (3)
 Notes: fgetc does all tests prior to caling us, including ungetc
Parameters
stream POSIX stream pointer
Returns
int character or EOF with errno set
Definition at line 441 of file posix.doxit.c.
Referenced by open().
int fatfs_putc (char c, FILE * stream)
avr-libc low level fputc(char c, FILE * stream)
 man page fputc (3)
Parameters
c character
stream POSIX stream pointer
Returns
int character or EOF on error with errno set
Definition at line 481 of file posix.doxit.c.
Referenced by open().
int fatfs_to_errno (FRESULT Result)
convert FafFs error number into POSIX errno
 man page errno (3)
Parameters
Result FatFs Result code
Returns
int errno or EBADMSG if no conversion possible
Definition at line 298 of file posix.doxit.c.
Referenced by close(), fatfs_getc(), fatfs_putc(), ftruncate(), lseek(), open(), read(), rename(), rmdir(), stat(), syncfs(), truncate(), unlink(), and write().
int fatfs_to_fileno (FIL * fh)
convert FatFS file handle to fileno
 Standard: NONE
Parameters
fh FatFS file pointer
Returns
int fileno, or -1 with errno set to EBADF
Definition at line 109 of file posix.doxit.c.
int fclose (FILE * stream)
close POSIX stream
 man page flose (3)
 Standard: POSIX
Parameters
stream stream pointer
Returns
int 0 on sucess -1 on error witrh errno set
Definition at line 737 of file posix.doxit.c.
int fgetpos (FILE * stream, size_t * pos)
get position of file stream
 man page fgetpos (3)
Parameters
stream POSIX file stream
pos position pointer for return
Returns
int 0 on sucess, -1 on error with errno set Standard: POSIX
Definition at line 936 of file posix.doxit.c.
FIL* fileno_to_fatfs (int fileno)
convert fileno to FatFS handle
 FatFS file handle is pointed to by the avr-libc stream->udata
 Standard: NONE
Parameters
fileno fileno of file
Returns
FIL * FatFS file handle or if fileno is invalid NULL with errno set
Definition at line 80 of file posix.doxit.c.
Referenced by close(), ftell(), ftruncate(), lseek(), open(), read(), sync(), syncfs(), and write().
FILE* fileno_to_stream (int fileno)
convert fileno to stream, inverse of POSIX fileno()
 Standard: NONE
Note: the index of __iob[] is reffered to `fileno`
 br> Reference: libc/avr-libc-1.8.0/libc/stdio
 stdin = __iob[0];
 __iob[1] = stdout
 __iob[2] = stderr
 ========================================
Parameters
fileno fileno is the index of __iob[]
Returns
FILE * or NULL on error with errno set
Definition at line 31 of file posix.doxit.c.
Referenced by close(), fileno_to_fatfs(), fopen(), free_file_descriptor(), and open().
FILE* fopen (const char * path, const char * mode)
 Open a file with path name and ascii file mode string
 man page fopen(3)
 Standard: POSIX
Parameters
pathname filename string
mode POSIX open mode strings
Returns
int stream * or NULL with errno set
Definition at line 628 of file posix.doxit.c.
size_t fread (void * ptr, size_t size, size_t nmemb, FILE * stream)
read nmemb elements from buf, size bytes each, to the stream fd
 man page fread (3)
 Standard: POSIX
Parameters
ptr buffer
nmemb number of items to read
size size of each item in bytes
stream POSIX file stream
Returns
size_t count on sucess or -1 on error with errno set
Definition at line 827 of file posix.doxit.c.
int free_file_descriptor (int fileno)
Free fileno FILE descriptor
Parameters
fileno file number __iob[] index
Returns
int -1 failure, fileno on sucess
Definition at line 178 of file posix.doxit.c.
Referenced by close(), and open().
int fseek (FILE * stream, long offset, int whence)
seek to file possition
 man page fseek (3)
 Standard: POSIX
Parameters
stream POSIX file stream
position offset to seek to
whence SEEK_SET The offset is set to offset bytes.
 SEEK_CUR The offset is set to its current location plus offset bytes.
 SEEK_END The offset is set to the size of the file plus offset bytes.
Returns
int 0 or -1 on error with errno set
Definition at line 883 of file posix.doxit.c.
Referenced by fsetpos(), and rewind().
int fsetpos (FILE * stream, size_t * pos)
set position of file stream
 man page fsetpos (3)
 Standard: POSIX
Parameters
stream POSIX file stream
pos position pointer
Returns
int 0 with *pos set to position or -1 on error with errno set
Definition at line 952 of file posix.doxit.c.
size_t ftell (FILE * stream)
return file position of open stream
 man page fteel (3)
 Standard: POSIX
Parameters
stream POSIX file stream
Returns
size_t file position, or -1 on error with errno set
Definition at line 903 of file posix.doxit.c.
Referenced by fgetpos().
int ftruncate (int fd, off_t length)
truncate open file to length
 man page ftruncate (3)
 Standard: POSIX
Parameters
fd open file number
length length to truncate to
Returns
0 on sucess or -1 n fail
Definition at line 1026 of file posix.doxit.c.
size_t fwrite (const void * ptr, size_t size, size_t nmemb, FILE * stream)
write nmemb elements from buf, size bytes each, to the stream fd
 man page write (2)
 Standard: POSIX
Parameters
ptr buffer
nmemb number of items to write
size size of each item in bytes
stream POSIX file stream
Returns
size_t count written on sucess or -1 on error with errno set
Definition at line 782 of file posix.doxit.c.
int isatty (int fileno)
return 1 if fileno is a console (uart avr-libc)
 man page isatty (3)
 Standard: POSIX
Parameters
fileno fileno of open file
Returns
int 1 if fileno is a console (uart in avr-libc terms)
Todo
Todo Perhaps we should verify console functions have been added ?
Definition at line 218 of file posix.doxit.c.
Referenced by fileno_to_fatfs(), free_file_descriptor(), new_file_descriptor(), sync(), and syncfs().
size_t lseek (int fileno, size_t position, int whence)
seek to file position
 man page lseek (2)
 Standard: POSIX
Parameters
fileno fileno of open file
position offset to seek to
whence SEEK_SET The offset is set to offset bytes.
 SEEK_CUR The offset is set to its current location plus offset bytes.
 SEEK_END The offset is set to the size of the file plus offset bytes.
Returns
size_t file position
Definition at line 845 of file posix.doxit.c.
Referenced by fseek().
char* mctime (time_t timev)
display ascii formatted time of timev seconds
 man page ctime (3)
 Reference: result POSIX ctime
 Standard: NONE
Parameters
timev epoch time in seconds
Returns
char * ascii string pointer
Definition at line 1174 of file posix.doxit.c.
Referenced by dump_stat().
int new_file_descriptor (void)
Allocate a file descriptor
 Standard: NONE
Returns
int fileno or -1 on failure with errno set
Definition at line 139 of file posix.doxit.c.
Referenced by open().
int open (const char * pathname, int flags)
 Open a file with integer mode flags
 man page open (2)
 Standard: POSIX
Parameters
pathname filename string
flags POSIX open modes
Returns
int fileno or -1 on error with errno set
Seek to end of the file
Definition at line 523 of file posix.doxit.c.
Referenced by fopen().
void perror (const char * s)
display user message and text errno message
 man page errno (3)
 See: sys_errlist[]
 Standard: POSIX
Parameters
s User message displayed before the error message
Returns
void
Definition at line 277 of file posix.doxit.c.
Referenced by fatfs_getc(), and fatfs_putc().
int posix_fopen_modes_to_open (const char * mode)
convert POSIX fopen mode to POSIX open mode flags
 man page fopen (3), open(2)
 See: POSIX fopen modes
 Example: `r+` implies read/write access
Parameters
mode POSIX file mode string
Returns
int open mode flags or -1
Definition at line 398 of file posix.doxit.c.
Referenced by fopen().
size_t read (int fd, const void * buf, size_t count)
read count bytes from *buf to fileno fd
 man page read (2)
 Standard: POSIX
Parameters
fd fileno
buf buffer
count number of bytes to write
Returns
size_t count on sucess or -1 on error with errno set
Definition at line 797 of file posix.doxit.c.
Referenced by fread().
int rename (const char * oldpath, const char * newpath)
rename a file
 man page (2)
 Standard: NONE
Parameters
oldpath original name
newpath new name
Returns
int 0 no directory part, or index of last '/'
Definition at line 1220 of file posix.doxit.c.
void rewind (FILE * stream)
rewind file to the beginning
 man page rewind (3)
 Standard: POSIX
Parameters
stream POSIX file stream
Returns
void
Definition at line 924 of file posix.doxit.c.
int rmdir (const char * pathname)
delete a directory
 man page rmdir 2
 Standard: POSIX
Parameters
pathname directory to delete
Returns
int 0 or -1 on error with errno set
Definition at line 981 of file posix.doxit.c.
int stat (char * name, struct stat * buf)
POSIX stat - file status
 man page (2)
 Standard: POSIX
Parameters
name file name
buf struct stat buffer to return results in
Returns
int 0 on success, -1 on error with errno set
Definition at line 1116 of file posix.doxit.c.
int stream_to_fileno (FILE * stream)
convert a stream pointer to fileno (index of __iob[])
 man page fileno (3)
 See: POSIX
 Standard: NONE
Parameters
stream stream pointer
Returns
int fileno, or -1 with errno = EBAFD if stream is NULL or not found
Definition at line 56 of file posix.doxit.c.
Referenced by fclose(), fread(), fseek(), ftell(), and fwrite().
void sync (void)
Sync all pending file changes and metadata on ALL files
 man page sync (2)
 Standard: POSIX
Returns
void
Definition at line 712 of file posix.doxit.c.
int syncfs (int fd)
Sync pending file changes and metadata for specified fileno
 man page syncfs (2)
 Standard: POSIX
Parameters
fd fileno to sync
Returns
int 0 on sucess -1 on error witrh errno set
Definition at line 678 of file posix.doxit.c.
Referenced by sync().
int truncate (const char * path, off_t length)
truncate file to length
 man page truncate (2)
 Standard: POSIX
Parameters
path file name to truncate
length length to truncate to
Returns
0 on sucess or -1 n fail
Definition at line 1058 of file posix.doxit.c.
int unlink (const char * pathname)
delete a file
 man page unlink (2)
 Standard: POSIX
Parameters
pathname filename to delete
Returns
int 0 or -1 on error with errno set
Definition at line 963 of file posix.doxit.c.
size_t write (int fd, const void * buf, size_t count)
write count bytes from *buf to fileno fd
 man page write (2)
 Standard: POSIX
Parameters
fd fileno
buf buffer
count number of bytes to write
Returns
size_t count on sucess or -1 on error with errno set
Definition at line 751 of file posix.doxit.c.
Referenced by fwrite().
Variable Documentation
FILE* __iob[MAX_FILES]
Definition at line 17 of file posix.doxit.c.
Referenced by fatfs_to_fileno(), fileno_to_stream(), free_file_descriptor(), new_file_descriptor(), and stream_to_fileno().
int errno
Note: AVR fdevopen assigns a stdin,stdout,stderr
Definition at line 14 of file posix.doxit.c.
Referenced by close(), fatfs_getc(), fatfs_putc(), fatfs_to_fileno(), fileno_to_fatfs(), fileno_to_stream(), free_file_descriptor(), ftell(), ftruncate(), lseek(), mctime(), new_file_descriptor(), open(), perror(), read(), rename(), rmdir(), stat(), stream_to_fileno(), syncfs(), truncate(), unlink(), and write().
const char* sys_errlist[]
POSIX error messages for each errno value
 man page errno (3)
 See: POSIX errno
Definition at line 230 of file posix.doxit.c.
Referenced by perror().