fatfs/posix_new.c File Reference
#include <hardware/hardware.h>
*
#include <stdio.h>
*
#include <stdint.h>
*
#include <string.h>
*
#include <stdlib.h>
*
#include `ff.h`
*
#include `diskio.h`
*
#include `posix.h`
*
Macros
#define MAX_FILES 16
Functions
< b >< b >< b >< b >< b > FILE * fileno_to_stream (int fileno)
Note: the index of __iob[] is reffered to `fileno`
< b > int stream_to_fileno (FILE *stream)
convert a stream pointer to fileno (index of __iob[])
< b > FIL * fileno_to_fatfs (int fileno)
convert fileno to FatFS handle
int fatfs_to_fileno (FIL *fh)
convert FatFS file handle to fileno
 Standard: NONE<b>
int new_file_descriptor (void)
Allocate a file descriptor
 Standard: NONE<b>
int free_file_descriptor (int fileno)
Free fileno FILE descriptor
< b > int isatty (int fileno)
return 1 if fileno is a console (uart avr-libc)
< b > void perror (const char *s)
display user message and text errno message
< b > int fatfs_to_errno (FRESULT Result)
convert FafFs error number into POSIX errno
< b >< b >< b >< b >< b >< b >
*
< b >< b >< b >< b >< b >< b >
*
< b >< b >< b >< b >< b >< b >
*
< b >< b >< b > int posix_fopen_modes_to_open (const char *mode)
NOTE: ORDER IS IMPORTANT!
< b > int fatfs_getc (FILE *stream)
avr-libc low level fgetc(FILE * stream) for FatFs
< b > int fatfs_putc (char c, FILE *stream)
avr-libc low level fputc(char c, FILE * stream)
< b >< b > int open (const char *pathname, int flags)
< b >< b > FILE * fopen (const char *path, const char *mode)
int close (int fileno)
close a file fileno
 Standard: POSIX<b>
< b > int syncfs (int fd)
Sync pending file changes and metadata for specified fileno
< b > void sync (void)
Sync all pending file changes and metadata on ALL files
< b > int fclose (FILE *stream)
close POSIX stream
< b > size_t write (int fd, const void *buf, size_t count)
write count bytes from *buf to fileno fd
< b > size_t fwrite (const void *ptr, size_t size, size_t nmemb, FILE *stream)
write nmemb elements from buf, size bytes each, to the stream fd
< b > size_t read (int fd, const void *buf, size_t count)
read count bytes from *buf to fileno fd
< b > size_t fread (void *ptr, size_t size, size_t nmemb, FILE *stream)
read nmemb elements from buf, size bytes each, to the stream fd
< b > size_t lseek (int fileno, size_t position, int whence)
seek to file position
< b > int fseek (FILE *stream, long offset, int whence)
seek to file possition
< b > size_t ftell (FILE *stream)
return file position of open stream
< b > void rewind (FILE *stream)
rewind file to the beginning
< b > int fgetpos (FILE *stream, size_t *pos)
get position of file stream
< b > int fsetpos (FILE *stream, size_t *pos)
set position of file stream
< b > int unlink (const char *pathname)
delete a file
< b > int rmdir (const char *pathname)
delete a directory
< b > time_t fat_time_to_unix (uint16_t date, uint16_t time)
convert FatFs file date and time to POSIX epoch seconds
< b > int ftruncate (int fd, off_t length)
truncate open file to length
< b > int truncate (const char *path, off_t length)
truncate file to length
< b > int stat (char *name, struct stat *buf)
POSIX stat - file status
< b > char * mctime (time_t timev)
display ascii formatted time of timev seconds
void dump_stat (struct stat *sp)
Display struct stat, from stat(0 or fstat(), in ASCII
< b > int rename (const char *oldpath, const char *newpath)
rename a file
< b > int dirname (char *str)
return the index of the last '/' character
< b > char * basename (char *str)
basename of string
char * baseext (char *str)
file extention of string
 Standard: NONE<b>
Variables
int errno
Note: AVR fdevopen assigns a stdin,stdout,stderr
FILE * __iob [MAX_FILES]
< b > const char * sys_errlist []
POSIX error messages for each errno value
Macro Definition Documentation
#define MAX_FILES 16
Definition at line 25 of file posix_new.c.
Referenced by fatfs_to_fileno(), fileno_to_stream(), free_file_descriptor(), new_file_descriptor(), stream_to_fileno(), and sync().
Function Documentation
char* baseext (char * str)
file extention of string
 Standard: NONE<b>
file extention of string
 Standard: NONE
Parameters
in <b>str string to find extension in
Returns
char * pointer to basename extension
Definition at line 1292 of file posix_new.c.
<b> char* basename (char * str)
basename of string
basename of string
 man page (3)
 Standard: POSIX
Parameters
in <b>str string to find basename inStandard: POSIX<b>
Returns
char * pointer to basename of string
Definition at line 1274 of file posix_new.c.
int close (int fileno)
close a file fileno
 Standard: POSIX<b>
close a file fileno
 Standard: POSIX
Parameters
in <b>fileno fileno of file
Returns
int 0 on sucess, -1 on error with errno set
Definition at line 653 of file posix_new.c.
Referenced by fclose().
<b> int dirname (char * str)
return the index of the last '/' character
return the index of the last '/' character
 man page (3)
 Standard: NONE
Parameters
in <b>str string to examineStandard: NONE<b>
Returns
int 0 no directory part, or index of last '/'
Definition at line 1250 of file posix_new.c.
void dump_stat (struct stat * sp)
Display struct stat, from stat(0 or fstat(), in ASCII
Display struct stat, from stat(0 or fstat(), in ASCII
Parameters
in <b>sp struct stat pointerStandard: NONE<b>
Returns
void
Definition at line 1199 of file posix_new.c.
<b> time_t fat_time_to_unix (uint16_t date, uint16_t time)
convert FatFs file date and time to POSIX epoch seconds
convert FatFs file date and time to POSIX epoch seconds
 man page timegm (3)
 See: timegm
Parameters
in <b>date FatFs date
in <b>time FatFs timeStandard: result is POSIX<b>
See: timegm<b>
Returns
time_t epoch seconds - POSIX
Definition at line 1011 of file posix_new.c.
Referenced by stat().
<b> int fatfs_getc (FILE * stream)
avr-libc low level fgetc(FILE * stream) for FatFs
avr-libc low level fgetc(FILE * stream) for FatFs
 man page fgetc (3)
 Notes: fgetc does all tests prior to caling us, including ungetc
Parameters
in <b>stream POSIX stream pointerNotes: fgetc does all tests prior to caling us, including ungetc
Returns
int character or EOF with errno set
Definition at line 450 of file posix_new.c.
Referenced by open().
<b> int fatfs_putc (char c, FILE * stream)
avr-libc low level fputc(char c, FILE * stream)
avr-libc low level fputc(char c, FILE * stream)
 man page fputc (3)
Parameters
in <b>c character
in <b>stream POSIX stream pointer
Returns
int character or EOF on error with errno set
Definition at line 490 of file posix_new.c.
Referenced by open().
<b> int fatfs_to_errno (FRESULT Result)
convert FafFs error number into POSIX errno
convert FafFs error number into POSIX errno
 man page errno (3)
Parameters
in <b>Result FatFs Result code
Returns
int errno or EBADMSG if no conversion possible
Definition at line 307 of file posix_new.c.
Referenced by close(), fatfs_getc(), fatfs_putc(), ftruncate(), lseek(), open(), read(), rename(), rmdir(), stat(), syncfs(), truncate(), unlink(), and write().
int fatfs_to_fileno (FIL * fh)
convert FatFS file handle to fileno
 Standard: NONE<b>
convert FatFS file handle to fileno
 Standard: NONE
Parameters
in <b>fh FatFS file pointer
Returns
int fileno, or -1 with errno set to EBADF
Definition at line 118 of file posix_new.c.
<b> int fclose (FILE * stream)
close POSIX stream
close POSIX stream
 man page flose (3)
 Standard: POSIX
Parameters
in <b>stream stream pointerStandard: POSIX<b>
Returns
int 0 on sucess -1 on error witrh errno set
Definition at line 746 of file posix_new.c.
<b> int fgetpos (FILE * stream, size_t * pos)
get position of file stream
get position of file stream
 man page fgetpos (3)
Parameters
in <b>stream POSIX file stream
in <b>pos position pointer for return
Returns
int 0 on sucess, -1 on error with errno set Standard: POSIX<b>
Definition at line 945 of file posix_new.c.
<b> FIL* fileno_to_fatfs (int fileno)
convert fileno to FatFS handle
convert fileno to FatFS handle
 FatFS file handle is pointed to by the avr-libc stream->udata
 Standard: NONE
Parameters
in <b>fileno fileno of fileStandard: NONE<b>
Returns
FIL * FatFS file handle or if fileno is invalid NULL with errno set
Definition at line 89 of file posix_new.c.
Referenced by close(), ftell(), ftruncate(), lseek(), open(), read(), sync(), syncfs(), and write().
<b><b><b><b><b> FILE* fileno_to_stream (int fileno)
Note: the index of __iob[] is reffered to `fileno`
convert fileno to stream, inverse of POSIX fileno()
 Standard: NONE
Reference: libc/avr-libc-1.8.0/libc/stdio
Parameters
in <b>fileno fileno is the index of __iob[]convert fileno to stream, inverse of POSIX fileno()
 Standard: NONE<b>
Returns
FILE * or NULL on error with errno set
Definition at line 40 of file posix_new.c.
Referenced by close(), fileno_to_fatfs(), fopen(), free_file_descriptor(), and open().
<b><b> FILE* fopen (const char * path, const char * mode)
 Open a file with path name and ascii file mode string
 man page fopen(3)
 Standard: POSIX
Parameters
in <b>pathname filename string
in <b>mode POSIX open mode stringsStandard: POSIX<b>
Returns
int stream * or NULL with errno set
Definition at line 637 of file posix_new.c.
<b> size_t fread (void * ptr, size_t size, size_t nmemb, FILE * stream)
read nmemb elements from buf, size bytes each, to the stream fd
read nmemb elements from buf, size bytes each, to the stream fd
 man page fread (3)
 Standard: POSIX
Parameters
in <b>ptr buffer
in <b>nmemb number of items to read
in <b>size size of each item in bytes
in <b>stream POSIX file streamStandard: POSIX<b>
Returns
size_t count on sucess or -1 on error with errno set
Definition at line 836 of file posix_new.c.
int free_file_descriptor (int fileno)
Free fileno FILE descriptor
Free fileno FILE descriptor
Parameters
in <b>fileno file number __iob[] index
Returns
int -1 failure, fileno on sucess
Definition at line 187 of file posix_new.c.
Referenced by close(), and open().
<b> int fseek (FILE * stream, long offset, int whence)
seek to file possition
seek to file possition
 man page fseek (3)
 Standard: POSIX
Parameters
in <b>stream POSIX file stream
in <b>position offset to seek to
in <b>whence:<b> SEEK_SET The offset is set to offset bytes.
 SEEK_CUR The offset is set to its current location plus offset bytes.
 SEEK_END The offset is set to the size of the file plus offset bytes.
Standard: POSIX<b>
Returns
int 0 or -1 on error with errno set
Definition at line 892 of file posix_new.c.
Referenced by fsetpos(), and rewind().
<b> int fsetpos (FILE * stream, size_t * pos)
set position of file stream
set position of file stream
 man page fsetpos (3)
 Standard: POSIX
Parameters
in <b>stream POSIX file stream
in <b>pos position pointerStandard: POSIX<b>
Returns
int 0 with *pos set to position or -1 on error with errno set
Definition at line 961 of file posix_new.c.
<b> size_t ftell (FILE * stream)
return file position of open stream
return file position of open stream
 man page fteel (3)
 Standard: POSIX
Parameters
in <b>stream POSIX file streamStandard: POSIX<b>
Returns
size_t file position, or -1 on error with errno set
Definition at line 912 of file posix_new.c.
Referenced by fgetpos().
<b> int ftruncate (int fd, off_t length)
truncate open file to length
truncate open file to length
 man page ftruncate (3)
 Standard: POSIX
Parameters
in <b>fd open file number
in <b>length length to truncate toStandard: POSIX<b>
Returns
0 on sucess or -1 n fail
Definition at line 1035 of file posix_new.c.
<b> size_t fwrite (const void * ptr, size_t size, size_t nmemb, FILE * stream)
write nmemb elements from buf, size bytes each, to the stream fd
write nmemb elements from buf, size bytes each, to the stream fd
 man page write (2)
 Standard: POSIX
Parameters
in <b>ptr buffer
in <b>nmemb number of items to write
in <b>size size of each item in bytes
in <b>stream POSIX file streamStandard: POSIX<b>
Returns
size_t count written on sucess or -1 on error with errno set
Definition at line 791 of file posix_new.c.
<b> int isatty (int fileno)
return 1 if fileno is a console (uart avr-libc)
return 1 if fileno is a console (uart avr-libc)
 man page isatty (3)
 Standard: POSIX
Parameters
in <b>fileno fileno of open fileStandard: POSIX<b>
Returns
int 1 if fileno is a console (uart in avr-libc terms)
Todo
Todo Perhaps we should verify console functions have been added ?
Definition at line 227 of file posix_new.c.
Referenced by fileno_to_fatfs(), free_file_descriptor(), new_file_descriptor(), sync(), and syncfs().
<b> size_t lseek (int fileno, size_t position, int whence)
seek to file position
seek to file position
 man page lseek (2)
 Standard: POSIX
Parameters
in <b>fileno fileno of open file
in <b>position offset to seek to
in <b>whence:<b> SEEK_SET The offset is set to offset bytes.
 SEEK_CUR The offset is set to its current location plus offset bytes.
 SEEK_END The offset is set to the size of the file plus offset bytes.
Standard: POSIX<b>
Returns
size_t file position
Definition at line 854 of file posix_new.c.
Referenced by fseek().
<b> char* mctime (time_t timev)
display ascii formatted time of timev seconds
display ascii formatted time of timev seconds
 man page ctime (3)
 Reference: result POSIX ctime
 Standard: NONE
Parameters
in <b>timev epoch time in secondsReference: result POSIX ctime
 Standard: NONE<b>
Returns
char * ascii string pointer
Definition at line 1183 of file posix_new.c.
Referenced by dump_stat().
int new_file_descriptor (void)
Allocate a file descriptor
 Standard: NONE<b>
Allocate a file descriptor
 Standard: NONE
Returns
int fileno or -1 on failure with errno set
Definition at line 148 of file posix_new.c.
Referenced by open().
<b><b> int open (const char * pathname, int flags)
 Open a file with integer mode flags
 man page open (2)
 Standard: POSIX
Parameters
in <b>pathname filename string
in <b>flags POSIX open modesStandard: POSIX<b>
Returns
int fileno or -1 on error with errno set
Seek to end of the file<b>
Definition at line 532 of file posix_new.c.
Referenced by fopen().
<b> void perror (const char * s)
display user message and text errno message
display user message and text errno message
 man page errno (3)
 See: sys_errlist[]
 Standard: POSIX
Parameters
in <b>s User message displayed before the error messageSee: sys_errlist[]
 Standard: POSIX<b>
Returns
void
Definition at line 286 of file posix_new.c.
Referenced by fatfs_getc(), and fatfs_putc().
<b><b><b><b><b><b><b><b><b><b><b><b><b><b><b><b><b><b><b><b><b> int posix_fopen_modes_to_open (const char * mode)
NOTE: ORDER IS IMPORTANT!
convert POSIX fopen mode to POSIX open mode flags
 man page fopen (3), open(2)
 See: POSIX fopen modes
 Example: `r+` implies read/write access
Note: The POSIX correct test of O_RDONLY is: (mode & O_ACCMODE) == O_RDONLY
Parameters
in <b>mode POSIX file mode stringconvert POSIX fopen mode to POSIX open mode flags
 See: POSIX fopen modes<b>
Returns
int open mode flags or -1
Definition at line 407 of file posix_new.c.
Referenced by fopen().
<b> size_t read (int fd, const void * buf, size_t count)
read count bytes from *buf to fileno fd
read count bytes from *buf to fileno fd
 man page read (2)
 Standard: POSIX
Parameters
in <b>fd fileno
in <b>buf buffer
in <b>count number of bytes to writeStandard: POSIX<b>
Returns
size_t count on sucess or -1 on error with errno set
Definition at line 806 of file posix_new.c.
Referenced by fread().
<b> int rename (const char * oldpath, const char * newpath)
rename a file
rename a file
 man page (2)
 Standard: NONE
Parameters
in <b>oldpath original name
in <b>newpath new nameStandard: NONE<b>
Returns
int 0 no directory part, or index of last '/'
Definition at line 1229 of file posix_new.c.
<b> void rewind (FILE * stream)
rewind file to the beginning
rewind file to the beginning
 man page rewind (3)
 Standard: POSIX
Parameters
in <b>stream POSIX file streamStandard: POSIX<b>
Returns
void
Definition at line 933 of file posix_new.c.
<b> int rmdir (const char * pathname)
delete a directory
delete a directory
 man page rmdir 2
 Standard: POSIX
Parameters
in <b>pathname directory to deleteStandard: POSIX<b>
Returns
int 0 or -1 on error with errno set
Definition at line 990 of file posix_new.c.
<b> int stat (char * name, struct stat * buf)
POSIX stat - file status
POSIX stat - file status
 man page (2)
 Standard: POSIX
Parameters
in <b>name file name
in <b>buf struct stat buffer to return results inStandard: POSIX<b>
Returns
int 0 on success, -1 on error with errno set
Definition at line 1125 of file posix_new.c.
<b> int stream_to_fileno (FILE * stream)
convert a stream pointer to fileno (index of __iob[])
convert a stream pointer to fileno (index of __iob[])
 man page fileno (3)
 See: POSIX
 Standard: NONE
Parameters
in <b>stream stream pointerSee: POSIX<b>
 Standard: NONE<b>
Returns
int fileno, or -1 with errno = EBAFD if stream is NULL or not found
Definition at line 65 of file posix_new.c.
Referenced by fclose(), fread(), fseek(), ftell(), and fwrite().
<b> void sync (void)
Sync all pending file changes and metadata on ALL files
Sync all pending file changes and metadata on ALL files
 man page sync (2)
 Standard: POSIX
Standard: POSIX<b>
Returns
void
Definition at line 721 of file posix_new.c.
<b> int syncfs (int fd)
Sync pending file changes and metadata for specified fileno
Sync pending file changes and metadata for specified fileno
 man page syncfs (2)
 Standard: POSIX
Parameters
in <b>fd fileno to syncStandard: POSIX<b>
Returns
int 0 on sucess -1 on error witrh errno set
Definition at line 687 of file posix_new.c.
Referenced by sync().
<b> int truncate (const char * path, off_t length)
truncate file to length
truncate file to length
 man page truncate (2)
 Standard: POSIX
Parameters
in <b>path file name to truncate
in <b>length length to truncate toStandard: POSIX<b>
Returns
0 on sucess or -1 n fail
Definition at line 1067 of file posix_new.c.
<b> int unlink (const char * pathname)
delete a file
delete a file
 man page unlink (2)
 Standard: POSIX
Parameters
in <b>pathname filename to deleteStandard: POSIX<b>
Returns
int 0 or -1 on error with errno set
Definition at line 972 of file posix_new.c.
<b> size_t write (int fd, const void * buf, size_t count)
write count bytes from *buf to fileno fd
write count bytes from *buf to fileno fd
 man page write (2)
 Standard: POSIX
Parameters
in <b>fd fileno
in <b>buf buffer
in <b>count number of bytes to writeStandard: POSIX<b>
Returns
size_t count on sucess or -1 on error with errno set
Definition at line 760 of file posix_new.c.
Referenced by fwrite().
Variable Documentation
FILE* __iob[MAX_FILES]
Definition at line 26 of file posix_new.c.
Referenced by fatfs_to_fileno(), fileno_to_stream(), free_file_descriptor(), new_file_descriptor(), and stream_to_fileno().
int errno
Note: AVR fdevopen assigns a stdin,stdout,stderr
Note: AVR fdevopen assigns a stdin,stdout,stderr
Definition at line 23 of file posix_new.c.
Referenced by close(), fatfs_getc(), fatfs_putc(), fatfs_to_fileno(), fileno_to_fatfs(), fileno_to_stream(), free_file_descriptor(), ftell(), ftruncate(), lseek(), mctime(), new_file_descriptor(), open(), perror(), read(), rename(), rmdir(), stat(), stream_to_fileno(), syncfs(), truncate(), unlink(), and write().
<b> const char* sys_errlist[]
POSIX error messages for each errno value
See: POSIX errno<b>
Definition at line 239 of file posix_new.c.
Referenced by perror().