gpib/printer.h File Reference
HPGL printer capture code for HP85 disk emulator project for AVR.
#include <user_config.h>
*
Functions
void printer_open (char *name)
Open a file to receive plot data using POSIX functions.
void printer_init (void)
Initialize plotter structures and state.
void printer_close (void)
Close current plot file and reset states.
int receive_plot_flush (void)
Write Plotter data and flush.
void printer_buffer (uint16_t val)
Buffer Plotter data and flush when buffer is full.
int PRINTER_COMMANDS (uint8_t ch)
GPIB Secondary Command Printer commands.
int controller_send_str (uint8_t from, uint8_t to, uint8_t *str, int len)
Controller Mode send ASCII string Stops sending with EOI.
int controller_read_str (uint8_t from, uint8_t to, uint8_t *str, int len)
Controller Mode read ASCII string Stops reading at EOI.
int controller_read_trace (uint8_t from, uint8_t to)
Controller Mode TRACE read for debugging Stops reading at EOI.
void controller_ifc (void)
void plot_echo (int gpib_address)
Instruct Instrument to send Plot data.
Detailed Description
HPGL printer capture code for HP85 disk emulator project for AVR.
Edit History
[1.0] [Mike Gore] Initial revision of file.
Copyright 2014-2017 Mike Gore, Inc. All rights reserved.
Function Documentation
void controller_ifc (void)
Definition at line 340 of file printer.c.
int controller_read_str (uint8_t from, uint8_t to, uint8_t * str, int len)
Controller Mode read ASCII string Stops reading at EOI.
Parameters
in from GPIB talker
in to GPIB listener
in str string to read
in len maximum number of bytes to read
Returns
number of bytes read
Definition at line 284 of file printer.c.
Referenced by plot_echo().
int controller_read_trace (uint8_t from, uint8_t to)
Controller Mode TRACE read for debugging Stops reading at EOI.
Parameters
in from GPIB talker
in to GPIB listener
Returns
number of bytes read
Definition at line 312 of file printer.c.
Referenced by plot_echo().
int controller_send_str (uint8_t from, uint8_t to, uint8_t * str, int len)
Controller Mode send ASCII string Stops sending with EOI.
Parameters
in from GPIB talker
in to GPIB listener
in str string to send
in len number of bytes to send (if 0 then length of string)
Returns
number of bytes sent
debugging
Definition at line 256 of file printer.c.
Referenced by plot_echo().
void plot_echo (int gpib_address)
Instruct Instrument to send Plot data.
Not finished or working yet - barely started work in progress,
Returns
void
Definition at line 355 of file printer.c.
Referenced by gpib_tests().
void printer_buffer (uint16_t val)
Buffer Plotter data and flush when buffer is full.
Uses POSIX FatFs wrappers.
See also
posix.c
posix.h
Returns
void
Definition at line 183 of file printer.c.
Referenced by gpib_task().
void printer_close (void)
Close current plot file and reset states.
Verify that polt file is open before attempting close.
Uses POSIX FatFs wrappers.
See also
posix.c
posix.h
Returns
void FYI: for the HP54645D plots end with: pd;pu;pu;sp0; This gets called
Definition at line 115 of file printer.c.
Referenced by GPIB(), gpib_init_devices(), listen_cleanup(), plot_echo(), and printer_open().
int PRINTER_COMMANDS (uint8_t ch)
GPIB Secondary Command Printer commands.
Todo
Todo Fully emulated plotter response.
Returns
0
Definition at line 224 of file printer.c.
Referenced by GPIB_COMMANDS().
void printer_init (void)
Initialize plotter structures and state.
Only called once after power on by main().
Returns
void
Definition at line 95 of file printer.c.
Referenced by main(), and printer_close().
void printer_open (char * name)
Open a file to receive plot data using POSIX functions.
Uses POSIX FatFs wrappers.
See also
posix.c
posix.h
Returns
void
Definition at line 40 of file printer.c.
Referenced by GPIB_LISTEN(), and GPIB_TALK().
int receive_plot_flush (void)
Write Plotter data and flush.
Uses POSIX FatFs wrappers.
See also
posix.c
posix.h
printer_buffer()
Returns
file handle
sync filesystem after every write
Definition at line 148 of file printer.c.
Referenced by printer_buffer(), and printer_close().