printf/printf.c File Reference
Small printf, and verious conversion code with floating point support.
#include <stdint.h>
#include <stdarg.h>
#include <string.h>
#include <math.h>
#include `mathio.h`
Functions
MEMSPACE size_t WEAK_ATR strlen (const char *str)
String Length.
MEMSPACE int WEAK_ATR isdigit (int c)
test if a character is a digit
MEMSPACE void WEAK_ATR reverse (char *str)
Reverse a string in place Example: abcdef -> fedcba.
MEMSPACE void WEAK_ATR strupper (char *str)
UPPERCASE a string.
MEMSPACE int bin2num (uint8_t *str, int strmax, int nummin, int base, uint8_t *nump, int numsize, int sign_ch)
Convert an unsigned number (numsize bytes in size) to ASCII in specified base Notes: No limit except available memory on number size.
MEMSPACE void pch_init (p_ch_t *p, char *str, int max)
Initialize character buffer with limits.
MEMSPACE int pch (p_ch_t *p, char ch)
Put character in buffer with limits.
MEMSPACE int pch_ind (p_ch_t *p)
Return current index of character buffer with limits.
MEMSPACE int pch_max_ind (p_ch_t *p)
Return maximum valid index for character buffer.
MEMSPACE void print_flags (f_t f)
print flags set in t_t structure
MEMSPACE int p_ntoa (uint8_t *nump, int numsize, char *str, int strmax, int radix, int width, int prec, f_t f)
Convert number an base 2 .. 16 to ASCII with optional sign Notes: 1) Numbers can be any number of digits long - limited only by memory available To print negative numbers convert to positive before calling this function and set f.b.neg 2) Warning: as with printf width and prec are only minimum sizes - results can be bigger We assume all numbers are positive:
MEMSPACE void _puts_pad (printf_t *fn, char *s, int width, int count, int left)
put string, via user function, count bytes long, padded up to width, left or right aligned
MEMSPACE void _printf_fn (printf_t *fn, __memx const char *fmt, va_list va)
vsnprintf function
MEMSPACE void _putc_buffer_fn (struct _printf_t *p, char ch)
_putc_buffer_fn - character output to a string buffer Used by snprintf and vsnprintf You can make _printf_fn call this helper for each character
MEMSPACE int vsnprintf (char *str, size_t size, const char *format, va_list va)
vsnprintf function
MEMSPACE int snprintf (char *str, size_t size, const char *format,...)
snprintf function
Detailed Description
Small printf, and verious conversion code with floating point support.
Copyright 2014-2020 Mike Gore, All rights reserved. GPL License
See also
 http://github.com/magore/hp85disk
 http://github.com/magore/hp85disk/COPYRIGHT.md for specific Copyright details
You are free to use this code under the terms of GPL
please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Function Documentation
_printf_fn()
MEMSPACE void _printf_fn (printf_t * fn, __memx const char * fmt, va_list va)
vsnprintf function
Parameters
 out fn output character function pointer
 in fmt printf forat string
 in va va_list arguments
Returns
size of string
Calling Variadic Functions
excerpt from https://www.gnu.org/software/libc/manual/html_node/Calling-Variadics.html Since the prototype doesnât specify types for optional arguments, in a call to a variadic function the default argument promotions are performed on the optional argument values. This means the objects of type char or short int (whether signed or not) are promoted to either int or unsigned int, as appropriate; and that objects of type float are promoted to type double. So, if the caller passes a char as an optional argument, it is promoted to an int, and the function can access it with va_arg (ap, int).
Definition at line 806 of file printf.c.
Referenced by fprintf(), and vsnprintf().
_putc_buffer_fn()
MEMSPACE void _putc_buffer_fn (struct _printf_t * p, char ch)
_putc_buffer_fn - character output to a string buffer Used by snprintf and vsnprintf You can make _printf_fn call this helper for each character
Parameters
 in *p structure with pointers and buffer to be written to
 in ch character to place in buffer
Returns
void
Definition at line 1187 of file printf.c.
Referenced by vsnprintf().
_puts_pad()
MEMSPACE void _puts_pad (printf_t * fn, char * s, int width, int count, int left)
put string, via user function, count bytes long, padded up to width, left or right aligned
Parameters
 out fn output character function pointer
 in s string
 in width of characters to pad up to - if needed
 in count number of characters to copy from buff
 in left string is left aligned
Definition at line 678 of file printf.c.
Referenced by _printf_fn().
bin2num()
MEMSPACE int bin2num (uint8_t * str, int strmax, int nummin, int base, uint8_t * nump, int numsize, int sign_ch)
Convert an unsigned number (numsize bytes in size) to ASCII in specified base Notes: No limit except available memory on number size.
Does not use divide or of multiply instructions - great on 8bit CPU's How it works: Say you have a table of powers of 2 in a given base base
To get the result add each table entry, in the base, that corresponds to each 1 bit in the binary number.
Now instead of a table we can start with 1 and multiple by 2 contraining each digit into the base we want - this is the same as using the table except we build it on the fly
Parameters
 out str ASCII number string result
 in strmax maximum size of str in bytes
 in nummin minimum number of digits to display
 in *nump Pointer to binary number
 in numsize size of binary number in bytes
 in sign_ch sign of binary number return converted number string numsize in bytes
Definition at line 143 of file printf.c.
Referenced by p_ntoa().
isdigit()
MEMSPACE int WEAK_ATR isdigit (int c)
test if a character is a digit
undo any existing macros
Parameters
 in c character
Returns
true or false
Definition at line 71 of file printf.c.
Referenced by _printf_fn().
p_ntoa()
MEMSPACE int p_ntoa (uint8_t * nump, int numsize, char * str, int strmax, int radix, int width, int prec, f_t f)
Convert number an base 2 .. 16 to ASCII with optional sign Notes: 1) Numbers can be any number of digits long - limited only by memory available To print negative numbers convert to positive before calling this function and set f.b.neg 2) Warning: as with printf width and prec are only minimum sizes - results can be bigger We assume all numbers are positive:
Parameters
 in nump number pointer
 in numsize number size in bytes
 out *str string result
 in strmax strmaximum length of string result
 in radix Radix may be 2 .. 16
 in width Width of result padded if needed
 in prec minumum number of digits, zero padded if needed
 in f flags f.b.left justify left f.b.plus display + for positive number, - for negative numbers f.b.space display ' ' for positive, - for negative f.b.zero pad with zeros if needed f.b.alt Alternate display form - work in progress f.b.width Width of result - pad if required f.b.prec Zero padd to prec if sepcified f.b.neg Sign of number is negative
Definition at line 314 of file printf.c.
Referenced by _printf_fn().
pch()
MEMSPACE int pch (p_ch_t * p, char ch)
Put character in buffer with limits.
Parameters
 in str string
 in max maximum number of characters plus EOS @See init_p_ch
Returns
void
Definition at line 233 of file printf.c.
pch_ind()
MEMSPACE int pch_ind (p_ch_t * p)
Return current index of character buffer with limits.
Returns
Buffer index
Definition at line 247 of file printf.c.
pch_init()
MEMSPACE void pch_init (p_ch_t * p, char * str, int max)
Initialize character buffer with limits.
Parameters
 in str string
 in max maximum number of characters plus EOS
Returns
void
base of string to write to
current string index
maximum string size including EOS
Definition at line 218 of file printf.c.
pch_max_ind()
MEMSPACE int pch_max_ind (p_ch_t * p)
Return maximum valid index for character buffer.
Returns
Buffer index
Definition at line 256 of file printf.c.
print_flags()
MEMSPACE void print_flags (f_t f)
print flags set in t_t structure
Parameters
 in f f_t flags structure
Returns
void
Definition at line 269 of file printf.c.
reverse()
MEMSPACE void WEAK_ATR reverse (char * str)
Reverse a string in place Example: abcdef -> fedcba.
Parameters
 in str string
Returns
string length
Definition at line 90 of file printf.c.
Referenced by bin2num().
snprintf()
MEMSPACE int snprintf (char * str, size_t size, const char * format, ...)
snprintf function
Parameters
 out str string buffer for result
 in size maximum length of converted string
 in format printf forat string
 in ... list of arguments
Returns
string size
Definition at line 1250 of file printf.c.
strlen()
MEMSPACE size_t WEAK_ATR strlen (const char * str)
String Length.
Parameters
 in str string
Returns
string length
Definition at line 53 of file printf.c.
Referenced by _printf_fn(), reverse(), and vsnprintf().
strupper()
MEMSPACE void WEAK_ATR strupper (char * str)
UPPERCASE a string.
Parameters
 in str string
Returns
void
Definition at line 112 of file printf.c.
Referenced by _printf_fn().
vsnprintf()
MEMSPACE int vsnprintf (char * str, size_t size, const char * format, va_list va)
vsnprintf function
Parameters
 out str string buffer for result
 in size maximum length of converted string
 in format printf forat string
 in va va_list list of arguments
Returns
string size
Definition at line 1220 of file printf.c.
Referenced by snprintf().