gpib/printer.c File Reference
GPIB Controller Mode code HP85 disk emulator project for AVR.
#include `user_config.h`
#include `defines.h`
#include `drives.h`
#include `gpib_hal.h`
#include `gpib.h`
#include `gpib_task.h`
#include `printer.h`
#include `posix.h`
#include `delay.h`
#include `controller.h`
Functions
void printer_open (char *name)
Open a file to receive plot data using POSIX functions.
void printer_init ()
Initialize plotter structures and state.
void printer_close ()
Close current plot file and reset states.
int receive_plot_flush ()
Write Plotter data and flush.
void printer_buffer (uint16_t val)
Buffer Plotter data and flush when buffer is full.
int PRINTER_COMMANDS (uint8_t ch)
GPIB Secondary Command Printer commands.
void plot_echo (int gpib_address)
Instruct Instrument to send Plot data.
Variables
PRINTERStateType plot = { 0 }
Plotter file data structure used for saving plot data.
uint8_t plot_str [] = { 0x3f, 0x5f, 0x47, 0x21 }
Plotter GPIB test vector.
Detailed Description
GPIB Controller Mode code HP85 disk emulator project for AVR.
HPGL printer capture code for HP85 disk emulator project for AVR.
Edit History
[1.0] [Mike Gore] Initial revision of file.
Copyright 2014-2020 Mike Gore, All rights reserved. GPL
Copyright 2014-2020 Mike Gore, All rights reserved. GPL
See also
http://github.com/magore/hp85disk
http://github.com/magore/hp85disk/COPYRIGHT.md for Copyright details
http://github.com/magore/hp85disk
http://github.com/magore/hp85disk/COPYRIGHT.md for Copyright details
Edit History
[1.0] [Mike Gore] Initial revision of file.
Copyright 2014-2020 Mike Gore, All rights reserved. GPL
See also
http://github.com/magore/hp85disk
http://github.com/magore/hp85disk/COPYRIGHT.md for Copyright details
Function Documentation
plot_echo()
void plot_echo (int gpib_address)
Instruct Instrument to send Plot data.
Not finished or working yet - barely started work in progress,
Returns
void
Definition at line 255 of file printer.c.
Referenced by gpib_tests().
printer_buffer()
void printer_buffer (uint16_t val)
Buffer Plotter data and flush when buffer is full.
Uses POSIX FatFs wrappers.
See also
posix.c
posix.h
Returns
void
Definition at line 186 of file printer.c.
Referenced by gpib_task().
printer_close()
void printer_close (void)
Close current plot file and reset states.
Verify that polt file is open before attempting close.
Uses POSIX FatFs wrappers.
See also
posix.c
posix.h
Returns
void FYI: for the HP54645D plots end with: pd;pu;pu;sp0; This gets called
Definition at line 118 of file printer.c.
Referenced by GPIB(), gpib_init_devices(), listen_cleanup(), plot_echo(), and printer_open().
PRINTER_COMMANDS()
int PRINTER_COMMANDS (uint8_t ch)
GPIB Secondary Command Printer commands.
Todo
Todo Fully emulated plotter response.
Returns
0
Definition at line 227 of file printer.c.
Referenced by GPIB_COMMANDS().
printer_init()
void printer_init (void)
Initialize plotter structures and state.
Only called once after power on by main().
Returns
void
Definition at line 98 of file printer.c.
Referenced by main(), and printer_close().
printer_open()
void printer_open (char * name)
Open a file to receive plot data using POSIX functions.
Uses POSIX FatFs wrappers.
See also
posix.c
posix.h
Returns
void
Definition at line 43 of file printer.c.
Referenced by GPIB_LISTEN(), and GPIB_TALK().
receive_plot_flush()
int receive_plot_flush (void)
Write Plotter data and flush.
Uses POSIX FatFs wrappers.
See also
posix.c
posix.h
printer_buffer()
Returns
file handle
sync filesystem after every write
Definition at line 151 of file printer.c.
Referenced by printer_buffer(), and printer_close().
Variable Documentation
plot
PRINTERStateType plot = { 0 }
Plotter file data structure used for saving plot data.
Definition at line 30 of file printer.c.
plot_str
uint8_t plot_str[] = { 0x3f, 0x5f, 0x47, 0x21 }
Plotter GPIB test vector.
Definition at line 33 of file printer.c.