hardware/ram.h File Reference
Memory Utilities and safe free for AVR.
Functions
size_t heaptop (void)
calloc may be aliased to safecalloc
size_t freeRam (void)
Return AVR Free memory for Malloc.
void PrintFree (void)
Display AVR free memory of each type>
void * safecalloc (int size, int elements)
Safe Alloc - Display Error message if Calloc fails.
void * safemalloc (size_t size)
Safe Malloc - Display Error message if Malloc fails.
void safefree (void *p)
Safe free - Only free a pointer if it is in malloc memory range.
Variables
char * __brkval
char * __malloc_heap_start
char * __malloc_heap_end
size_t __malloc_margin
void * __stack
Detailed Description
Memory Utilities and safe free for AVR.
Edit History
[1.0] [Mike Gore] Initial revision of file.
Copyright 2014-2020 Mike Gore, Inc. All rights reserved.
Function Documentation
freeRam()
size_t freeRam ()
Return AVR Free memory for Malloc.
avr-libc dependent code.
Returns
free memory in bytes.
See also
malloc().
Definition at line 50 of file ram.c.
Referenced by PrintFree().
heaptop()
size_t heaptop ()
calloc may be aliased to safecalloc
free may be aliased to safefree
malloc may be aliased to safecalloc
Return top of heap
avr-libc dependent code.
Returns
top of heap
See also
malloc().
Definition at line 27 of file ram.c.
Referenced by freeRam(), PrintFree(), and safefree().
PrintFree()
void PrintFree ()
Display AVR free memory of each type>
avr-libc dependent code.
Stack, BSS, Data, Heap, Malloc.
Returns
void
Definition at line 69 of file ram.c.
Referenced by main(), safefree(), and user_task().
safecalloc()
void* safecalloc (int size, int elements)
Safe Alloc - Display Error message if Calloc fails.
We check if the pointer was in the heap.
Otherwise it may have been statically defined - display error.
Returns
void.
Definition at line 122 of file ram.c.
Referenced by alloc_device(), copy(), fdevopen(), i2c_task_op_add(), lif_calloc(), MatAlloc(), new_file_descriptor(), queue_new(), set_Config_Defaults(), stralloc(), and strnalloc().
safefree()
void safefree (void * p)
Safe free - Only free a pointer if it is in malloc memory range.
We check if the pointer was in the heap.
Otherwise it may have been statically defined - display error.
Parameters
 in p pointer to free.
Returns
void.
Definition at line 158 of file ram.c.
Referenced by copy(), fatfs_tests(), ff_memfree(), free_device(), free_file_descriptor(), i2c_task_free_ops(), lif_free(), MatFree(), mkfs(), new_file_descriptor(), printer_close(), queue_del(), and queue_new().
safemalloc()
void* safemalloc (size_t size)
Safe Malloc - Display Error message if Malloc fails.
We check if the pointer was in the heap.
Otherwise it may have been statically defined - display error.
Parameters
 in size size
Returns
void.
Definition at line 139 of file ram.c.
Referenced by fatfs_tests(), ff_memalloc(), and mkfs().
Variable Documentation
__brkval
char* __brkval
Referenced by heaptop().
__malloc_heap_end
char* __malloc_heap_end
Referenced by heaptop().
__malloc_heap_start
char* __malloc_heap_start
Referenced by PrintFree(), and safefree().
__malloc_margin
size_t __malloc_margin
Referenced by heaptop().
__stack
void* __stack
Referenced by PrintFree().