reg.c File Reference
Functions
int matchhere (char *, char *)
int matchstar (int, char *, char *)
int match (char *re, char *text)
Function Documentation
int match (char * re, char * text)
Definition at line 7 of file reg.c.
int matchhere (char * re, char * text)
Definition at line 19 of file reg.c.
Referenced by match(), and matchstar().
int matchstar (int c, char * re, char * text)
Definition at line 33 of file reg.c.
Referenced by matchhere().