hardware/rs232.h File Reference
RS232 Driver AVR8.
#include `user_config.h`
Data Structures
struct _uart
Macros
#define RX_BUF_SIZE 80
#define RX_FLOW_WINDOW 20
#define RX_OVERFLOW 1
#define XON_CHAR 0x11
#define XOFF_CHAR 0x13
#define XOFF_ENABLE 4
#define XOFF_PUT 2
#define XOFF_GET 1
#define UARTS 1
#define kbhit(uart) uart_rx_count(uart)
#define uart_putc(a, c) uart0_putchar(c,NULL)
Functions
void uart_rx_flush (uint8_t uart)
Flush receive ring buffer for specified uart.
int uart0_getchar (void *f)
UART receive character function using avr-libc.
int uart0_putchar (int c, void *f)
UART transmit character function using avr-libc.
uint16_t uart_ubr (uint32_t baud, int *u2x, uint32_t *actual)
UART baud rate caluculation We compute the best values of baud rate register and prescale.
uint32_t uart_init (uint8_t uart, uint32_t baud)
UART initialization function that works with avr-libc functions.
void uart_rx_interrupt (uint8_t uart, uint8_t data)
UART Receive Interrupt task.
int uart_peek_tail (uint8_t uart)
Return character waiting in ring buffer without removing it.
int uart_get_tail (uint8_t uart)
Return next character from ring buffer.
int uart_rx_count (uint8_t uart)
return count of character count waiting in UART ring buffer.
int uart_rx_byte (uint8_t uart)
Recive character character from uart.
int uart_getchar (uint8_t uart)
Receive character from uart with option CR/LF conversion.
int uart_tx_byte (int c, uint8_t uart)
Transmit 1 byte on uart.
int uart_putchar (int c, int uart)
Transmit 1 byte on uart.
int uart_keyhit (uint8_t uart)
Do we have receive characters waiting ?.
int uart_put (int c)
Transmit a character on UART 0.
int uart_get (void)
Receive a character from UART 0.
int get_line (char *buff, int len)
Get a line from UART 0 up to a maximum of len bytes.
Detailed Description
RS232 Driver AVR8.
Edit History
[1.0] [Mike Gore] Initial revision of file.
Copyright 2014-2020 Mike Gore, Inc. All rights reserved.
Macro Definition Documentation
kbhit
#define kbhit(uart) uart_rx_count(uart)
Definition at line 45 of file rs232.h.
Referenced by task(), and testpage().
RX_BUF_SIZE
#define RX_BUF_SIZE 80
Definition at line 18 of file rs232.h.
Referenced by uart_get_tail(), and uart_rx_interrupt().
RX_FLOW_WINDOW
#define RX_FLOW_WINDOW 20
Definition at line 19 of file rs232.h.
RX_OVERFLOW
#define RX_OVERFLOW 1
Definition at line 21 of file rs232.h.
Referenced by uart_rx_interrupt().
uart_putc
#define uart_putc(a, c) uart0_putchar(c,NULL)
Definition at line 47 of file rs232.h.
Referenced by fatfs_ls().
UARTS
#define UARTS 1
Definition at line 44 of file rs232.h.
Referenced by uart_get_tail(), uart_getchar(), uart_init(), uart_peek_tail(), uart_rx_count(), and uart_rx_flush().
XOFF_CHAR
#define XOFF_CHAR 0x13
Definition at line 24 of file rs232.h.
XOFF_ENABLE
#define XOFF_ENABLE 4
Definition at line 26 of file rs232.h.
XOFF_GET
#define XOFF_GET 1
Definition at line 28 of file rs232.h.
XOFF_PUT
#define XOFF_PUT 2
Definition at line 27 of file rs232.h.
XON_CHAR
#define XON_CHAR 0x11
Definition at line 23 of file rs232.h.
Function Documentation
get_line()
int get_line (char * buff, int len)
Get a line from UART 0 up to a maximum of len bytes.
Parameters
in buff line input buffer
in len line length maximum
Returns
void
Definition at line 418 of file rs232.c.
uart0_getchar()
int uart0_getchar (void * f)
UART receive character function using avr-libc.
Parameters
in f unused FILE *stream pointer.
Returns
uart_getchar(0);.
See also
fdevopen() from avr-libc.
Definition at line 45 of file rs232.c.
Referenced by uart_get(), and uart_init().
uart0_putchar()
int uart0_putchar (int c, void * f)
UART transmit character function using avr-libc.
Parameters
in c character to send.
in f unused FILE *stream pointer.
Returns
uart_putchar(c, 0);.
See also
fdevopen() from avr-libc.
Definition at line 57 of file rs232.c.
Referenced by uart_init(), and uart_put().
uart_get()
int uart_get (void)
Receive a character from UART 0.
Returns
character
Definition at line 408 of file rs232.c.
Referenced by get_line().
uart_get_tail()
int uart_get_tail (uint8_t uart)
Return next character from ring buffer.
Wait for at least one character.
Update index pointers and character count.
Parameters
in uart uart number to read.
Returns
character.
0 on error.
See also
uart_rx_count().
Definition at line 247 of file rs232.c.
Referenced by uart_rx_byte().
uart_getchar()
int uart_getchar (uint8_t uart)
Receive character from uart with option CR/LF conversion.
CR/LF processing is disabled at the moment.
Parameters
in uart uart number.
Returns
Character.
Definition at line 310 of file rs232.c.
Referenced by uart0_getchar().
uart_init()
uint32_t uart_init (uint8_t uart, uint32_t baud)
UART initialization function that works with avr-libc functions.
Parameters
in uart UART number.
in baud Baud Rate in HZ.
Returns
actual baud rate, closest we could get with register settings
See also
fdevopen() avr-libc function that attaches uart functions to getchar and putchar POSIX functions.
actual baud rate
Definition at line 115 of file rs232.c.
Referenced by main().
uart_keyhit()
int uart_keyhit (uint8_t uart)
Do we have receive characters waiting ?.
Returns non zero if there are any caracters.
Parameters
in uart uart number.
Returns
Character count in receive buffer.
Definition at line 392 of file rs232.c.
Referenced by controller_read_trace(), gpib_detect_PP(), gpib_error_test(), gpib_read_byte(), gpib_trace_task(), gpib_write_byte(), and plot_echo().
uart_peek_tail()
int uart_peek_tail (uint8_t uart)
Return character waiting in ring buffer without removing it.
Returns
character.
0 on error.
Definition at line 225 of file rs232.c.
uart_put()
int uart_put (int c)
Transmit a character on UART 0.
Parameters
in c character to write
Returns
void
Definition at line 401 of file rs232.c.
Referenced by get_line().
uart_putchar()
int uart_putchar (int c, int uart)
Transmit 1 byte on uart.
CR/LF Output translation.
Parameters
in c transmit character.
in uart uart number.
Returns
void.
Definition at line 374 of file rs232.c.
Referenced by uart0_putchar().
uart_rx_byte()
int uart_rx_byte (uint8_t uart)
Recive character character from uart.
Parameters
in uart uart number.
Returns
Character.
Definition at line 297 of file rs232.c.
Referenced by plot_echo(), and uart_getchar().
uart_rx_count()
int uart_rx_count (uint8_t uart)
return count of character count waiting in UART ring buffer.
Parameters
in uart uart number to check count for.
Returns
Character count in ring buffer.
Definition at line 275 of file rs232.c.
Referenced by uart_get_tail(), and uart_keyhit().
uart_rx_flush()
void uart_rx_flush (uint8_t uart)
Flush receive ring buffer for specified uart.
Returns
void
Definition at line 22 of file rs232.c.
Referenced by uart_init().
uart_rx_interrupt()
void uart_rx_interrupt (uint8_t uart, uint8_t data)
UART Receive Interrupt task.
Add characters to ring receive buffer.
Parameters
in uart uart number.
in data register data.
Returns
void.
Definition at line 206 of file rs232.c.
Referenced by ISR().
uart_tx_byte()
int uart_tx_byte (int c, uint8_t uart)
Transmit 1 byte on uart.
Parameters
in c transmit character.
in uart uart number.
Returns
void.
Definition at line 345 of file rs232.c.
Referenced by uart_getchar(), and uart_putchar().
uart_ubr()
uint16_t uart_ubr (uint32_t baud, int * u2x, uint32_t * actual)
UART baud rate caluculation We compute the best values of baud rate register and prescale.
Parameters
in uart desired baud rate in HZ
in *u2x computed prescale 1 = divide by 8, 0 = divide by 16
in *actual Actual computed baud rate, closest we could get with register settings
Returns
baud rate register value
See also
fdevopen() avr-libc function that attaches uart functions to getchar and putchar POSIX functions.
Use 8 prescale as a default
Use 16 prescale f we have a low baud rate
Definition at line 72 of file rs232.c.
Referenced by uart_init().