hardware/rtc.h File Reference
DS1307 RTC Driver AVR8.
#include `user_config.h`
Macros
#define DS1307 0x68
#define DS1307_REG_SIZE 8
Functions
uint8_t BINtoBCD (uint8_t data)
RTC BCD conversion functions.
uint8_t BCDtoBIN (uint8_t data)
Convert two `digit` BCD number to binary.
int8_t i2c_rtc_write (uint8_t address, uint8_t ind, uint8_t *buf, uint8_t len)
RTC HAL.
int8_t i2c_rtc_read (uint8_t address, uint8_t ind, uint8_t *buf, uint8_t len)
RTC I2C READ function.
void i2c_rtc_init (void)
RTC I2C initialization code.
uint8_t rtc_write (tm_t *t)
RTC functions.
uint8_t rtc_read (tm_t *t)
Read DS1307 RTC into POSIX struct tm * structure.
int rtc_run (int run)
Set DS1307 run state.
int8_t rtc_run_test (void)
DS1307 run test.
uint8_t rtc_init (int force, time_t seconds)
Initialize DS1307 rtc if not initialied - or if forced.
Variables
int rtc_ok
Detailed Description
DS1307 RTC Driver AVR8.
Edit History
[1.0] [Mike Gore] Initial revision of file.
Copyright 2014-2020 Mike Gore, Inc. All rights reserved.
Macro Definition Documentation
DS1307
#define DS1307 0x68
Definition at line 20 of file rtc.h.
DS1307_REG_SIZE
#define DS1307_REG_SIZE 8
Definition at line 21 of file rtc.h.
Function Documentation
BCDtoBIN()
uint8_t BCDtoBIN (uint8_t data)
Convert two `digit` BCD number to binary.
Parameters
 in data BCD number.
number >= 0 and <= 99 to BCD
Returns
Binary value.
Definition at line 38 of file rtc.c.
Referenced by rtc_read().
BINtoBCD()
uint8_t BINtoBCD (uint8_t data)
RTC BCD conversion functions.
================================================================================
Convert number >= 0 and <= 99 to BCD.
BCD format has each hex nibble has a digit 0 .. 9
Parameters
 in data number to convert.
Returns
BCD value
Warning
we assume the number is in range.
Definition at line 27 of file rtc.c.
Referenced by rtc_write().
i2c_rtc_init()
void i2c_rtc_init ()
RTC I2C initialization code.
Returns
void
Definition at line 123 of file rtc.c.
Referenced by rtc_init().
i2c_rtc_read()
int8_t i2c_rtc_read (uint8_t address, uint8_t index, uint8_t * buf, uint8_t len)
RTC I2C READ function.
Parameters
 in address DS1307 I2C address
 in index DS1307 internal address index pointer
 out buf read buffer
 in len buffer length
Returns
1 = OK, 0 = ERROR
Definition at line 90 of file rtc.c.
Referenced by rtc_read(), and rtc_run().
i2c_rtc_write()
int8_t i2c_rtc_write (uint8_t address, uint8_t index, uint8_t * buf, uint8_t len)
RTC HAL.
================================================================================
RTC I2C WRITE function
Parameters
 in address DS1307 I2C address
 in index DS1307 internal address index pointer
 out buf write buffer
 in len buffer length
Returns
1 = OK, 0 = ERROR
DS1307 internal Address Pointer
Definition at line 55 of file rtc.c.
Referenced by rtc_run(), and rtc_write().
rtc_init()
uint8_t rtc_init (int force, time_t seconds)
Initialize DS1307 rtc if not initialied - or if forced.
Parameters
 in force force initialiation flag.
If 1 then alwasy force initialiation.
 in seconds POSIX EPOCH time in seconds.
Returns
run state 0 = STOP, 1 = RUN
-1 = ERROR
Definition at line 285 of file rtc.c.
Referenced by initialize_clock(), and setdate_r().
rtc_read()
uint8_t rtc_read (tm_t * t)
Read DS1307 RTC into POSIX struct tm * structure.
Parameters
 out t struct tm * POSIX time returned.
Returns
1 on sucess.
0 on fail.
Definition at line 189 of file rtc.c.
Referenced by display_clock(), and initialize_clock().
rtc_run()
int rtc_run (int run)
Set DS1307 run state.
Parameters
 in run state.
1 = run.
0 = stop.
-1 = check run state.
Returns
run state 0/1 on success.
-1 on error.
Definition at line 240 of file rtc.c.
Referenced by rtc_init(), and rtc_run_test().
rtc_run_test()
int8_t rtc_run_test ()
DS1307 run test.
display error if read error occurs.
Returns
1 if running.
0 if not running.
-1 ERROR
Definition at line 271 of file rtc.c.
rtc_write()
uint8_t rtc_write (tm_t * t)
RTC functions.
================================================================================
Set DS1307 RTC from POSIX struct tm * structure.
Parameters
 in t POSIX struct tm * time to set.
Returns
1 on sucess.
0 on fail.
Definition at line 138 of file rtc.c.
Referenced by rtc_init().
Variable Documentation
rtc_ok
int rtc_ok
Definition at line 18 of file rtc.h.
Referenced by rtc_init().