hardware/rtc.c File Reference
DS1307 RTC Driver AVR8.
#include `user_config.h`
#include `lib/time.h`
Functions
uint8_t BINtoBCD (uint8_t data)
Convert number >= 0 and <= 99 to BCD.
uint8_t BCDtoBIN (uint8_t data)
Convert two `digit` BCD number to binary.
int8_t rtc_run_test ()
Check if the DS1307 device is running.
int rtc_run (int run)
Set DS1307 run state.
uint8_t rtc_init (int force, time_t seconds)
Initialize DS1307 rtc if not initialied - or if forced.
uint8_t rtc_write (tm_t *t)
Set DS1307 RTC from POSIX struct tm * structure.
uint8_t rtc_read (tm_t *t)
Read DS1307 RTC into POSIX struct tm * structure.
Detailed Description
DS1307 RTC Driver AVR8.
Edit History
[1.0] [Mike Gore] Initial revision of file.
Copyright 2014-2020 Mike Gore, Inc. All rights reserved.
Function Documentation
BCDtoBIN()
uint8_t BCDtoBIN (uint8_t data)
Convert two `digit` BCD number to binary.
Parameters
in data BCD number.
number >= 0 and <= 99 to BCD
Returns
Binary value.
Definition at line 34 of file rtc.c.
Referenced by rtc_read().
BINtoBCD()
uint8_t BINtoBCD (uint8_t data)
Convert number >= 0 and <= 99 to BCD.
BCD format has each hex nibble has a digit 0 .. 9
Parameters
in data number to convert.
Returns
BCD value
Warning
we assume the number is in range.
Definition at line 23 of file rtc.c.
Referenced by rtc_write().
rtc_init()
uint8_t rtc_init (int force, time_t seconds)
Initialize DS1307 rtc if not initialied - or if forced.
Parameters
in force force initialiation flag.
If 1 then alwasy force initialiation.
in seconds POSIX EPOCH time in seconds.
Returns
1 on success.
0 on fail.
Definition at line 111 of file rtc.c.
Referenced by initialize_clock(), and setdate_r().
rtc_read()
uint8_t rtc_read (tm_t * t)
Read DS1307 RTC into POSIX struct tm * structure.
Parameters
out t struct tm * POSIX time returned.
Returns
1 on sucess.
0 on fail.
Definition at line 231 of file rtc.c.
Referenced by display_clock(), initialize_clock(), and rtc_read().
rtc_run()
int rtc_run (int run)
Set DS1307 run state.
Parameters
in run state.
1 = run.
0 = stop.
-1 = check run state.
Returns
run state 0/1 on success.
-1 on error.
Definition at line 73 of file rtc.c.
Referenced by rtc_init().
rtc_run_test()
int8_t rtc_run_test ()
Check if the DS1307 device is running.
display error if read error occurs.
Returns
1 if running.
0 if not running.
Definition at line 47 of file rtc.c.
rtc_write()
uint8_t rtc_write (tm_t * t)
Set DS1307 RTC from POSIX struct tm * structure.
Parameters
in t POSIX struct tm * time to set.
Returns
1 on sucess.
0 on fail.
Definition at line 179 of file rtc.c.
Referenced by rtc_init().