hardware/spi.c File Reference
SPI Driver AVR8.
#include `user_config.h`
#include <stdlib.h>
#include `spi.h`
Functions
void SPI0_Speed (uint32_t speed)
Set AVR SPI bus rate in HZ.
uint32_t SPI0_Get_Speed (void)
Return previously saved SPI BUS rate in HZ.
void SPI0_Mode (int mode)
Set SPI clock mode.
int SPI0_Get_Mode (void)
Return saved SPI mode as set by SPI0_Mode().
void SPI0_Init (uint32_t speed)
Initialize SPI0 device. See Atmel App Note AVR151 Set default speed, IO pins and mode.
uint8_t SPI0_TXRX_Byte (uint8_t Data)
SPI read/Write byte.
void SPI0_TX (uint8_t *data, int count)
SPI buffered write functions.
void SPI0_TXRX (uint8_t *data, int count)
HSPI write and read using FIFO.
void SPI0_RX (uint8_t *data, int count)
HSPI read using FIFO.
Variables
static uint32_t SPI0_Speed_value = 0
Saved SPI bus speed.
static int SPI0_Mode_value = 0
Saved SPI Mode.
static int SPI0_Init_state = 0
SPI0 initialization flag.
Detailed Description
SPI Driver AVR8.
Edit History
[1.0] [Mike Gore] Initial revision of file.
Copyright
Copyright 2014-2020 Mike Gore, Inc. All rights reserved.
GNU Public License.
Author
Mike Gore
Function Documentation
SPI0_Get_Mode()
int SPI0_Get_Mode (void)
Return saved SPI mode as set by SPI0_Mode().
Returns
saved mode.
Definition at line 176 of file spi.c.
SPI0_Get_Speed()
uint32_t SPI0_Get_Speed (void)
Return previously saved SPI BUS rate in HZ.
Returns
SPI clock rate in HZ.
Definition at line 124 of file spi.c.
SPI0_Init()
void SPI0_Init (uint32_t speed)
Initialize SPI0 device. See Atmel App Note AVR151 Set default speed, IO pins and mode.
Set SPI clock mode 0 SPI Mode CPOL CPHA Sample 0 0 0 Leading (Rising) Edge
Definition at line 188 of file spi.c.
Referenced by spi_init().
SPI0_Mode()
void SPI0_Mode (int mode)
Set SPI clock mode.
Parameters
in mode valid mades:
*   SPI Mode     CPOL    CPHA            Sample
*   0    0       0       Leading (Rising)   Edge
*   1    0       1       Trailing (Falling) Edge
*   2    1       0       Leading (Falling)  Edge
*   3    1       1       Trailing (Rising)  Edge
* 
Returns
void
Definition at line 146 of file spi.c.
Referenced by SPI0_Init(), and spi_init().
SPI0_RX()
void SPI0_RX (uint8_t * data, int count)
HSPI read using FIFO.
Parameters
in *data receive buffer
in count number of bytes to read
Returns
void
Definition at line 293 of file spi.c.
Referenced by spi_RX(), and spi_RX_buffer().
SPI0_Speed()
void SPI0_Speed (uint32_t speed)
Set AVR SPI bus rate in HZ.
Compute precsale rate from desired frequency in HZ.
Slowest rate: F_CPU/128.
Fastest rate: F_CPU/2.
Precsale value is truncated not rounded.
Valid precsle values are 2,4,8,16,32,64,128.
/// SPI2X   SPR1    SPR0     SCK Frequency
/// 1       0       0        fosc/2
/// 0       0       0        fosc/4
/// 1       0       1        fosc/8
/// 0       0       1        fosc/16
/// 1       1       0        fosc/32
/// 0       1       0        fosc/64
/// 1       1       1        fosc/64
/// 0       1       1        fosc/128
/// 
@param[in] speed: SPI clock rate in HZ.

@return  void  
Save speed value
Definition at line 46 of file spi.c.
Referenced by SPI0_Init().
SPI0_TX()
void SPI0_TX (uint8_t * data, int count)
SPI buffered write functions.
HSPI write using FIFO
Parameters
in *data transmit buffer
in count number of bytes to write
Returns
void
Definition at line 260 of file spi.c.
Referenced by spi_TX(), and spi_TX_buffer().
SPI0_TXRX()
void SPI0_TXRX (uint8_t * data, int count)
HSPI write and read using FIFO.
Parameters
in *data transmit / receive buffer
in count number of bytes to write / read
Returns
void
Definition at line 277 of file spi.c.
Referenced by spi_TXRX(), and spi_TXRX_buffer().
SPI0_TXRX_Byte()
uint8_t SPI0_TXRX_Byte (uint8_t Data)
SPI read/Write byte.
We Write and read at the same time.
If we want to read only set Data to 0xff.
Parameters
in Data Data to send.
Returns
Data received.
Definition at line 241 of file spi.c.
Referenced by ppr_set(), SPI0_Init(), SPI0_RX(), SPI0_TX(), and SPI0_TXRX().
Variable Documentation
SPI0_Init_state
int SPI0_Init_state = 0 [static]
SPI0 initialization flag.
Definition at line 183 of file spi.c.
Referenced by SPI0_Init().
SPI0_Mode_value
int SPI0_Mode_value = 0 [static]
Saved SPI Mode.
See also
SPI0_Mode().
Definition at line 132 of file spi.c.
Referenced by SPI0_Get_Mode(), and SPI0_Mode().
SPI0_Speed_value
uint32_t SPI0_Speed_value = 0 [static]
Saved SPI bus speed.
Definition at line 22 of file spi.c.
Referenced by SPI0_Get_Speed(), and SPI0_Speed().