gpib/ss80.h File Reference
SS80 disk emulator for HP85 disk emulator project for AVR8.
#include `gpib/defines.h`
*
Functions
void SS80_Test (void)
SS80 GPIB function.
void SS80_V2B (uint8_t *B, int index, int size, uint32_t val)
Initialize SS80 state and bus.
uint8_t * SS80ControllerPack (int *size)
uint8_t * SS80UnitPack (int *size)
uint8_t * SS80VolumePack (int *size)
void SS80_init (void)
int SS80_Execute_State (void)
SS80 Execute state process.
uint32_t SS80_Blocks_to_Bytes (uint32_t block)
SS80 Return current address in bytes.
uint32_t SS80_Bytes_to_Blocks (uint32_t bytes)
SS80 Return current block addresss from bytes.
int SS80_locate_and_read (void)
SS80 Locate and Read COmmend.
int SS80_locate_and_write (void)
SS80 Locate and Write Commend.
int SS80_test_extended_status (uint8_t *p, int bit)
SS80 test extendend status bits and display them.
void SS80_display_extended_status (uint8_t *p, char *message)
SS80 Display extended 8 byte status messages for debuging.
int SS80_send_status (void)
SS80 send detailed status.
int SS80_describe (void)
Send Controler,Unit and Volume description.
int SS80_Command_State (void)
Process OP Codes following 0x65 Command State.
int SS80_Transparent_State (void)
(0x70 or 0x72) OP Code processing.
int SS80_cmd_seek (void)
Limit tests for disk seek.
int SS80_Report (void)
send QSTAT
void Clear_Common (int u)
Uiniversal and Decvice clear code.
int SS80_Channel_Independent_Clear (int u)
Channel Independent Clear.
int SS80_Universal_Device_Clear (void)
Universal Device CLear.
int SS80_Selected_Device_Clear (int u)
Selected Device Clear.
int SS80_Amigo_Clear (void)
Amigo Clear.
int SS80_Cancel (int u)
Cancel transaction.
int SS80_increment (void)
Increment position Addressy by one block.
int SS80_error_return (void)
Common SS80 Error Return function. Send qstat = 1.
int SS80_COMMANDS (uint8_t ch)
SS80 COMMANDS States.
Detailed Description
SS80 disk emulator for HP85 disk emulator project for AVR8.
Edit History
[1.0] [Mike Gore] Initial revision of file.
Copyright 2014 Mike Gore, Inc. All rights reserved.
Based on work by Anders Gustafsson.
Copyright 2014 Anders Gustafsson All rights reserved..
Function Documentation
void Clear_Common (int u)
Uiniversal and Decvice clear code.
Clear Settings to poweron values.
Clear Unit, Address, Length, Error Status, qstat
See also
: SS80_Selected_Device_Clear()
: SS80_Universal_Device_Clear()
: SS80_Amigo_Clear()
-References:
SS80 ps 4-2 - *** listed as NOT supported for SS80 ***
CS80 pg 4-49, 3-2, 3-4
CS80 Page B-12
SS80 4-11
CS80 4-26, 3-2,3-5
Notes: All Clears are the same
Except: Universal Device Clear to Unit other then 15.
If the unit is NOT 15 then then Unit will remain set
They ALL set Power on Values - Except diagnostic report
The clear command will cause the device to abort the transaction in process as soon as possible without losing any data.
///  Power ON Values
///  CS80 Page B-12
///  Table B-5. Complementary Command Power-on Values
///  COMPLEMENTARY POWER-ON       COMPLEMENTARY               POWER-ON
///  COMMAND       VALUE COMMAND  COMMAND                     VALUE
///  Set Unit     0               Set Retry Time              device specific
///  Set Volume   0               Set Status Mask             disabled
///  Set Address  0,0,0           No Op                       Not Applicable
///  Set Length  -1 (full volume) Set Release                 T = O Z = O
///  Set Burst   disable          Set Options                 device specific
///  Set RPS     disabled         Set Return Addressing Mode  single vector
/// 
///  CS80 3-2
///  Clears the following:
///  - clearable hardware functions
///  - internal buffers
///  - channel interface buffers
///  - Complementary values
///  - status report, unless the Diagnostic Result status bit is set
///  - other programmable functions (device dependent)
/// 
///  CS80 3-3 has more detail
///  1. Abort the current operation at the earliest opportunity such
///     that no data corruption can take place.
///  2. Clear all clearable device or interface conditions currently asserted.
///  3. Reset all Complementary parameters to their power-on values.
///  4. Reset status report, unless the Diagnostic Result status bit is
///     set. This includes resetting power-on status.
///     Note- After the device has reported a diagnostic failure on one unit,
///     the Clear command will clear the status of other units attempting to
///     report the same failure. It is unnecessary for the same failure to
///     be reported more than once.
///  5. Set QSTAT value to indicate whether or not status should be
///     requested. Note: QSTAT will indicate any diagnostic results
///     in addition to the occurrence of an internal release request.
///  6. Enter the reporting state.
/// 
Todo
Todo We do not have RPS or Burst settings yet so we do not clear them/
We do not have a diagnostic mode so bits ALWAYS get cleared.
Parameters
in u unit
Returns
void TODO We do not support multiple units yet TODO We do not support multiple Volumes yet
Todo
Todo FIXME Normally the poweron value is -1 (Full volume) However; Any read will try to read the whole volume. (This is Only used in disk copy functions) A setting of 0 will offer the best chance of the error being spotted by the Controller in Charge However; Typically systems will always set this value BEFORE a transfer.
Todo
Todo FIXME If we have a Diagnostic Report bit then we do not clear the Status/Error bits SS80 4-12
Definition at line 1661 of file ss80.c.
Referenced by SS80_Amigo_Clear(), SS80_Channel_Independent_Clear(), SS80_init(), SS80_Selected_Device_Clear(), and SS80_Universal_Device_Clear().
int SS80_Amigo_Clear (void)
Amigo Clear.
Reference: SS80 4-5
Returns
0 on send
GPIB flags on send error.
See also
gpib.h _FLAGS defines for a full list.
Todo
Todo do something with Parity Check Bit ?
Definition at line 1758 of file ss80.c.
Referenced by SS80_COMMANDS().
uint32_t SS80_Blocks_to_Bytes (uint32_t block)
SS80 Return current address in bytes.
Returns
Byte Address
Definition at line 327 of file ss80.c.
Referenced by SS80_cmd_seek(), SS80_Command_State(), SS80_increment(), SS80_locate_and_read(), and SS80_locate_and_write().
uint32_t SS80_Bytes_to_Blocks (uint32_t bytes)
SS80 Return current block addresss from bytes.
Returns
Block Address
Definition at line 334 of file ss80.c.
Referenced by SS80_cmd_seek(), SS80_locate_and_read(), and SS80_locate_and_write().
int SS80_Cancel (int u)
Cancel transaction.
Reference:
SS80 4-9
CS80 4-26, 3-6
State: TRANSPARENT 0x72
Phases: Command, Report
Todo
Todo
Todo
Todo FIXME
Definition at line 1792 of file ss80.c.
Referenced by SS80_Transparent_State().
int SS80_Channel_Independent_Clear (int u)
Channel Independent Clear.
See also
: Clear_Common()
Reference:
SS80 4-11
CS80 4-26, 3-2,3-5
State: TRANSPARENT 0x72
Phases: Command, Report
Parameters
in u Unit
Returns
0
Definition at line 1702 of file ss80.c.
Referenced by SS80_Transparent_State().
int SS80_cmd_seek (void)
Limit tests for disk seek.
eference SS80 4-39,4-45
We check for read/write past end of disk during the seek
See also
: SS80_locate_and_read()
: SS80_locate_and_write()
Returns
0 on sucess
fatfs error on fail
Fail will set: qstat = 1, Errors |= ERR_SEEK.
Todo
Todo Let f_lseek do bounds checking instead ??? Will we read or write past the end of the disk ??
Definition at line 1520 of file ss80.c.
Referenced by SS80_locate_and_read(), and SS80_locate_and_write().
int SS80_Command_State (void)
Process OP Codes following 0x65 Command State.
References: CS80 pg 4-6.
State: COMMAND STATE.
Returns
0 on sucess.
flags on fail.
See also
gpib.h ERROR_MASK defines for a full list.
///  Notes:
///  We set DPPR on entry and EPPR on exit
///     DPPR = DisablePPR(SS80p->HEADER.PPR);
///     EPPR = EnablePPR(SS80p->HEADER.PPR);
/// 
///  Valid OP Codes for Command State (0x65):
///     Real Time, General Purpose, Complementary, DIagnostic
///     Diagnostic
///     In this Order:
///        (1 to N) Complementary
///        and/or
///        (1) of Real Time, General Purpose, Diagnostic
///        (This later group is always LAST)
///     OP Code Sequence errors: TODO
/// 
///  We Read all of the Data/Opcodes/Parameters at once
///     (while ATN is false).
///     Last byte read should be EOI or an error
///  Why read all at once ?
///     SS80 "Command Messages" are buffered one at a time.
///     A "Command Message" contains all ALL opcodes & their parameters
///     (See SS80 Section 4-12, Page 4-6)
/// 
///  Unknown OP Code processing rules
///     Skip the remaining codes, Wait for Report Phase
/// 
Todo
Todo FIXME
Todo
Todo FIXME
Todo
Todo FIXME, In Execute state calls SS80_locate_and_read();
Todo
Todo FIXME, SS80_locate_and_write();
Todo
Todo FIXME Important SS80 and CS80 differences regarding Complementary Commands! CS80 pg 2-1 1) In CS80 when only complementary commands appear in a message they will set the system defaults: Unit, number, data transfer length, burst size, maximum retry time, and Rotational Position Sensing (RPS) window size and location. 2) If, in the same message, they proceed a Real Time, General Purpose or Diagnostic they are TEMPORARY and just for that single transaction! 3) The exeption to these rules are Set Unit, Set Volume
Todo
Todo Only handles 4-byte Addresses at the moment CS80 pg 4-11, 2-14 SS80 pg 4-67
SS80 pg 4-73
set unit number TODO We do not support multiple units yet
TODO We do not support multiple Volumes yet
Set Return Addressing Type: COMPLEMENTARY Phases: Command, Report SS80 pg 4-81 CS80 4-18,2-24
Todo
Todo TODO Skip Parameters
Todo
Todo not implmented yet SS80 pg 4-43 CS80 pg 4-20, 2-28
Todo
Todo TODO
Todo
Todo FIXME Execute NOW
Todo
Todo FIXME The class GENERAL PURPOSE suggests yes
Todo
Todo FIXME The class GENERAL PURPOSE suggests yes
Validate Key, Set Format Options, Download Type: GENERAL PURPOSE Phases: Command, Report Must be last command in sequence SS80 pg 4-91 CS80 N/A
Todo
Todo TODO Skip Parameters
Initialize Media Type: GENERAL PURPOSE Phases: Command, Report This command must be last and only one SS80 pg 4-33 CS80 4-19,2-26
Todo
Todo TODO
Todo
Todo FIXME
Set Status Mask Type: GENERAL PURPOSE Phases: Command, Report Must be last command in sequence SS80 pg 4-81 CS80 4-15,2-20
Todo
Todo TODO
Todo
Todo TODO
Todo
Todo TODO
Initiate Diagnostic Type: DIAGNOSTIC Phases: Command, Report Must be last command in sequence SS80 pg 4-35 CS80 N/A
Todo
Todo TODO
Definition at line 988 of file ss80.c.
Referenced by SS80_COMMANDS().
int SS80_COMMANDS (uint8_t ch)
SS80 COMMANDS States.
-Reference: SS80 3-2..9
0x6e Execute State
0x65 Command State
0x70 Report State
0x72 Transparent State
Parameters
in ch command.
Returns
0 on send
See also
GPIB error status
gpib.h _FLAGS defines for a full list.
Definition at line 1856 of file ss80.c.
Referenced by GPIB_COMMANDS().
int SS80_describe (void)
Send Controler,Unit and Volume description.
Reference: SS80 4-15.
State: EXEC STATE COMMAND>
Returns
0 on sucess>
flags on fail. @ gpib.h ERROR_MASK defines for a full list of error flags.
Definition at line 903 of file ss80.c.
Referenced by SS80_Execute_State().
void SS80_display_extended_status (uint8_t * p, char * message)
SS80 Display extended 8 byte status messages for debuging.
Parameters
*p extended status vector
*message message header for display
Returns
void
Definition at line 692 of file ss80.c.
Referenced by SS80_Command_State().
int SS80_error_return (void)
Common SS80 Error Return function. Send qstat = 1.
Returns
0 on send
GPIB flags on send error
See also
gpib.h _FLAGS defines for a full list.
Definition at line 1825 of file ss80.c.
Referenced by SS80_locate_and_read().
int SS80_Execute_State (void)
SS80 Execute state process.
Reference SS80 3-1..9
State: EXEC STATE COMMAND
Returns
0 on sucess
GPIB error flags on fail
See also
gpib.h ERROR_MASK defines for a full list of error flags.
Definition at line 289 of file ss80.c.
Referenced by SS80_COMMANDS().
int SS80_increment (void)
Increment position Addressy by one block.
References: SS80 4-39, 4-45.
Returns
0
Definition at line 1807 of file ss80.c.
void SS80_init (void)
Todo
Todo FIXME
Definition at line 258 of file ss80.c.
Referenced by gpib_init_devices(), and gpib_tests().
int SS80_locate_and_read (void)
SS80 Locate and Read COmmend.
Reference: SS80 4-39
Read (SS80s->Length) disk bytes at (Address) offset.
Send this data to the GPIB bus.
State: EXEC STATE COMMAND.
Returns
0 on sucess
GPIB error flags on fail.
See also
gpib.h ERROR_MASK defines for a full list of error flags.
Notes: Any Disk I/O errors will set qstat and Errors.
Limitations:
Currenly we will only process 2 ** 31 bytes Max in one transfer.
If an seek or I/O error happens then we MUST continue to read and discard the GPIB data until we get an EOI or GPIB error...
Todo
Todo FIXME SS80 4-39 For now we will assume the controller will never do this
Returns
Return
Note: this should not happen unless we exit on errors above
Definition at line 354 of file ss80.c.
Referenced by SS80_Execute_State().
int SS80_locate_and_write (void)
SS80 Locate and Write Commend.
Reference: SS80 pg 4-45, CS80 pg 2-8.
Write (SS80s->Length) disk bytes from GPIB at (Address) offset.
State: EXEC STATE COMMAND.
Disk I/O errors will set qstat and Errors.
Limitations.
Currenly we will only process 2 ** 31 bytes Max in one transfer.
If an seek or I/O error happens then we MUST continue to. read and discard the GPIB data until we get an EOI or GPIB error...
Returns
0 on sucess.
GPIB error flags on fail.
See also
gpib.h ERROR_MASK defines for a full list.
Definition at line 485 of file ss80.c.
Referenced by SS80_Execute_State().
int SS80_Report (void)
send QSTAT
Reference: CS80 pg 4-7, Section 4-14.
///    QSTAT, return status byte
///  NORMAL COMPLETION = 0
///     Indicates normal completion of the requested operation.
///  HARD ERROR = 1
///     Indicates that error information is available.
///     The host must issue the Request Status command in order
///     to determine what went wrong.
///  POWER ON = 2
///     Indicates that the device has just returned from a power failure
///     or some form of operator intervention (such as removal of the
///     storage media). Any incomplete transactions were aborted and
///     should be repeated.  The host must reconfigure any programmable
///     operating parameters because they have returned to their
///     power-on values.
/// 
@return  0 on sucess
@see: gpib.h ERROR_MASK defines for a full list.  
Definition at line 1568 of file ss80.c.
Referenced by GPIB(), GPIB_TALK(), and SS80_COMMANDS().
int SS80_Selected_Device_Clear (int u)
Selected Device Clear.
See also
: Clear_Common()
Reference:
SS80 ps 4-2 - *** listed as NOT supported for SS80 ***
CS80 pg 4-49, 3-2, 3-4
CS80 Page B-12
Returns
0
Definition at line 1738 of file ss80.c.
Referenced by GPIB().
int SS80_send_status (void)
SS80 send detailed status.
Reference: SS80 pg 4-59..64.
Send 20 bytes of extended status to host>
State: EXEC STATE COMMAND.
///  SS80 pg 4-59
///  Bits are numbered
///    0 .. 7 (MSB..LSB "backwards")
///  Bytes are numbered
///    1 .. 20 (0..19 in message)
///  Example:
///    Bit 0 represents the MSB of Byte 1
/// 
///  We define ONLY those bits we are using, or might use
///  See: SS80 pg 4-59 for more details
///
///  Indentification Field
///    Byte 1(0)  <VVVVUUUU>
///      VVVV=Volume NUmber
///    Byte 2(1)  <11111111>
///
///  SS80 pg 4-59
///  Reject Errors Field
///       byte 3(2)           byte 4(3)
///  < 0 0 2 0 0 5 6 7 > <8 9 10 0 12 0 0 O>
///  2 = Channel Parity Error
///  5 = Illegal Opcode
///  6 = Module Addressing
///  7 = Address Bounds
///  8 = Parameter Bounds
///  9 = Illegal Parameter
///  10 = Message Sequence
///  12 = Message Length
/// 
///  SS80 pg 4-60
///  Fault Errors Field
///        byte 5(4)               byte 6(5)
///  < 0 17 0 19 0 0 22 0 > < 24 0 0 0 0 0 30 31 >
/// 
///  19 = Controller Fault
///  22 = Unit Fault
///  24 = Diagnostic Result
///  30 = Power Fail
///  31 = Re-transmit
/// 
///
///  SS80 pg 4-60
///  Access Errors Field
///        byte 7(6)                byte 8(7)
///  < 0 33 34 35 36 37 0 0 > < 40 41 0 43 44 0 0 0 >
///  33 = Uninitialized media
///  34 = No Spares Available
///  35 = Not Ready
///  36 = Write Protect
///  37 = No Data Found
///  40 = Unrecoverable Data Overflow
///  41 = Unrecoverable Data
///  43 = End of File
///  44 = End of Volume
/// 
///  SS80 pg 4-62
///  Information Errors Field
///         byte 9(8)             byte 10(9)
///  < 0 0 0 51 52 0 0 55 > < 0 57 0 59 0 0 0 0 >
///  51 = Media Wear
///  52 = Latency induced
///  55 = Auto Sparing Invoked
///  57 = Recoverable Data Overflow
///  59 = Recoverable Data
/// 
/// SS80 4:58
/// The following fault error bits will NEVER be set by an SS/80 device:
/// 26 = Operator request
/// 27 = Diagnostic request
/// 28 = Internal maintenance
/// 32 = Illegal parallel operation
/// 48 = Operator Request
/// 49 = Diagnostic Request
/// 50 = Internal Maintenance
/// 58 = Marginal Data
/// 61 = Maintenance Track Overflow
///
/// SS80 pg 4-64
/// P6 (10 .. 15) is SS80 Specific
///
/// SS80 4:65
/// P1O (16 .. 19)
///
/// @todo  add some of these
///  5 = Illegal Opcode
///  6 = Module Addressing
///  8 = Parameter Bounds
///  9 = Illegal Parameter
///  10 = Message Sequence
///  12 = Message Length
///  19 = Controller Fault
///  24 = Diagnostic Result
///  30 = Power Fail
///  33 = Uninitialized media
///  35 = Not Ready
///  37 = No Data Found
///  41 = Unrecoverable Data
///  43 = End of File
///  44 = End of Volume
/// 
@return 0.
@return GPIB error flags on fail>
@see gpib.h ERROR_MASK defines for a full list.  
Todo
Todo add Diagnostic Result status (MSB of byte 5)
4:63,64
Note: Diagnostic Result bit is NOT set
See also
SET ADDRESS in blocks
Todo
Todo Fixme
Definition at line 831 of file ss80.c.
Referenced by SS80_Execute_State().
void SS80_Test (void)
SS80 GPIB function.
Todo
Todo get this working
Definition at line 121 of file ss80.c.
Referenced by gpib_tests().
int SS80_test_extended_status (uint8_t * p, int bit)
SS80 test extendend status bits and display them.
Reference: SS80 pg 4-58..64.
Look at the 8 status bytes of the extended status message
Debuuging
Parameters
*p extended status vector
bit bit number starting at MSB of first byte as 0
Returns
1 if set
Definition at line 662 of file ss80.c.
Referenced by SS80_display_extended_status().
int SS80_Transparent_State (void)
(0x70 or 0x72) OP Code processing.
References: CS80 pg 4-26, 3-2,3-3,3-4,3-5,3-7,3-9,3-10.
State: Transparent State.
Returns
0 on sucess
flags on fail
See also
gpib.h ERROR_MASK defines for a full list or error flags.
///  Notes:
///     DPPR DisablePPR(SS80p->HEADER.PPR) should already be set at the secondary
///   We do NOT reenable EPPR at any state
/// 
///  Valid OP Codes for Transparent State (0x70 or 0x72):
///     [Unit Complementary] Transparent
/// 
///  Transparent Commands done at HP-IB state, NOT here:
///    Universal Device Clear
///    Selected Device Clear
///    Identify
/// 
///  Read all of the Data/Opcodes/Parameters at once
///     (while ATN is false).
///     Last byte read should be EOI or an error
///  Why read all at once ?
///     SS80 "Command Messages" are buffered one at a time.
///     A "Command Message" contains all ALL opcodes & their parameters
///     (See SS80 Section 4-12, Page 4-6)
/// 
///  Unknown OP Code processing rules
///     Skip the remaining codes, Wait for Report Phase
/// 
Todo
Todo FIXME
work in progress, unit support
Note: Enabling Parallel Poll is up to each function Many transparent Commands require Parallel Poll disabled when done
Todo
Todo FIXME
Todo
Todo TODO Skip Paramter
Todo
Todo FIXME SS80 4-49 CS80 4-27, 3-7
Todo
Todo TODO DO NOT EPPR
Todo
Todo FIXME SS80 4-49 CS80 4-27, 3-7
Todo
Todo TODO DO NOT EPPR
Todo
Todo FIXME SS80 4-11 CS80 4-26, 3-2,3-5
TODO We do not support multiple units yet
Todo
Todo FIXME SS80 4-9 CS80 4-26, 3-6
TODO We do not support multiple units yet
Definition at line 1372 of file ss80.c.
Referenced by SS80_COMMANDS().
int SS80_Universal_Device_Clear (void)
Universal Device CLear.
See also
: Clear_Common()
Reference:
SS80 4-11
CS80 4-26, 3-2,3-3
State: TRANSPARENT, 0x14
Phases: Command, Report
Returns
0
Todo
Todo FIXME
Definition at line 1720 of file ss80.c.
Referenced by GPIB().
void SS80_V2B (uint8_t * B, int index, int size, uint32_t val)
Initialize SS80 state and bus.
///  Reference:
///  CS80 Page B-12
///  Table B-5. Complementary Command Power-on Values
///  COMPLEMENTARY POWER-ON       COMPLEMENTARY               POWER-ON
///  COMMAND       VALUE COMMAND  COMMAND                     VALUE
///  Set Unit     0               Set Retry Time              device specific
///  Set Volume   0               Set Status Mask             disabled
///  Set Address  0,0,0           No Op                       Not Applicable
///  Set Length  -1 (full volume) Set Release                 T = O Z = O
///  Set Burst   disable          Set Options                 device specific
///  Set RPS     disabled         Set Return Addressing Mode  single vector
/// 
Returns
void SS80 Describe helper functions The SS80 docs number describe bytes 1 to N for Controller,Unit and Volume MSB ... LSB
remove 1 bias
Definition at line 157 of file ss80.c.
Referenced by SS80ControllerPack(), SS80UnitPack(), and SS80VolumePack().
uint8_t* SS80ControllerPack (int * size)
Definition at line 163 of file ss80.c.
Referenced by SS80_describe().
uint8_t* SS80UnitPack (int * size)
Definition at line 188 of file ss80.c.
Referenced by SS80_describe().
uint8_t* SS80VolumePack (int * size)
Definition at line 231 of file ss80.c.
Referenced by SS80_describe().