gpib/ss80.c File Reference
SS80 disk emulator for HP85 disk emulator project for AVR8.
#include `user_config.h`
*
#include `defines.h`
*
#include `gpib_hal.h`
*
#include `gpib.h`
*
#include `gpib_task.h`
*
#include `amigo.h`
*
#include `ss80.h`
*
Enumerations
enum ss80exec {
*
EXEC_IDLE,
EXEC_LOCATE_AND_READ,
EXEC_LOCATE_AND_WRITE,
EXEC_SEND_STATUS,
*
EXEC_DESCRIBE
 }
Functions
void SS80_Test (void)
SS80 GPIB function.
DWORD SS80_MaxAddress ()
void SS80_init (void)
int SS80_Execute_State (void)
SS80 Execute state process.
int SS80_locate_and_read (void)
SS80 Locate and Read COmmend.
int SS80_locate_and_write (void)
SS80 Locate and Write Commend.
int SS80_send_status (void)
SS80 send detailed status.
int SS80_describe (void)
Send Controler,Unit and Volume description.
int SS80_Command_State (void)
Process OP Codes following 0x65 Command State.
int SS80_Transparent_State (void)
(0x70 or 0x72) OP Code processing.
int SS80_cmd_seek (void)
Limit tests for disk seek.
int SS80_Report (void)
send QSTAT
void Clear_Common (int u)
Uiniversal and Decvice clear code.
int SS80_Channel_Independent_Clear (int u)
Channel Independent Clear.
int SS80_Universal_Device_Clear (void)
Universal Device CLear.
int SS80_Selected_Device_Clear (int u)
Selected Device Clear.
int SS80_Amigo_Clear (void)
Amigo Clear.
int SS80_Cancel (int u)
Cancel transaction.
int SS80_increment (void)
Increment position Addressy by 256.
int SS80_error_return (void)
Common SS80 Error Return function. Send qstat = 1.
int SS80_COMMANDS (uint8_t ch)
SS80 COMMANDS States.
Variables
uint8_t talking
GPIB BUS states.
uint8_t listening
gpib listen address
uint8_t spoll
gpib serial poll status
int TD []
SS80 GPIB test string.
uint8_t printer_addr = PRINTER_DEFAULT_ADDRESS
Initialize SS80 state and bus.
Detailed Description
SS80 disk emulator for HP85 disk emulator project for AVR8.
Edit History
[1.0] [Mike Gore] Initial revision of file.
Copyright 2014 Mike Gore, Inc. All rights reserved.
Based on work by Anders Gustafsson.
Copyright 2014 Anders Gustafsson All rights reserved..
Enumeration Type Documentation
enum ss80exec
Enumerator
EXEC_IDLE
EXEC_LOCATE_AND_READ
EXEC_LOCATE_AND_WRITE
EXEC_SEND_STATUS
EXEC_DESCRIBE
Definition at line 93 of file ss80.c.
Function Documentation
void Clear_Common (int u)
Uiniversal and Decvice clear code.
Clear Settings to poweron values.
Clear Unit, Address, Length, Error Status, qstat
See also
: SS80_Selected_Device_Clear()
: SS80_Universal_Device_Clear()
: SS80_Amigo_Clear()
-References:
SS80 ps 4-2 - *** listed as NOT supported for SS80 ***
CS80 pg 4-49, 3-2, 3-4
CS80 Page B-12
SS80 4-11
CS80 4-26, 3-2,3-5
Notes: All Clears are the same
Except: Universal Device Clear to Unit other then 15.
If the unit is NOT 15 then then Unit will remain set
They ALL set Power on Values - Except diagnostic report
The clear command will cause the device to abort the transaction in process as soon as possible without losing any data.
///  Power ON Values
///  CS80 Page B-12
///  Table B-5. Complementary Command Power-on Values
///  COMPLEMENTARY POWER-ON       COMPLEMENTARY               POWER-ON
///  COMMAND       VALUE COMMAND  COMMAND                     VALUE
///  Set Unit     0               Set Retry Time              device specific
///  Set Volume   0               Set Status Mask             disabled
///  Set Address  0,0,0           No Op                       Not Applicable
///  Set Length  -1 (full volume) Set Release                 T = O Z = O
///  Set Burst   disable          Set Options                 device specific
///  Set RPS     disabled         Set Return Addressing Mode  single vector
/// 
///  CS80 3-2
///  Clears the following:
///  - clearable hardware functions
///  - internal buffers
///  - channel interface buffers
///  - Complementary values
///  - status report, unless the Diagnostic Result status bit is set
///  - other programmable functions (device dependent)
/// 
///  CS80 3-3 has more detail
///  1. Abort the current operation at the earliest opportunity such
///     that no data corruption can take place.
///  2. Clear all clearable device or interface conditions currently asserted.
///  3. Reset all Complementary parameters to their power-on values.
///  4. Reset status report, unless the Diagnostic Result status bit is
///     set. This includes resetting power-on status.
///     Note- After the device has reported a diagnostic failure on one unit,
///     the Clear command will clear the status of other units attempting to
///     report the same failure. It is unnecessary for the same failure to
///     be reported more than once.
///  5. Set QSTAT value to indicate whether or not status should be
///     requested. Note: QSTAT will indicate any diagnostic results
///     in addition to the occurrence of an internal release request.
///  6. Enter the reporting state.
/// 
Todo
Todo We do not have RPS or Burst settings yet so we do not clear them/
We do not have a diagnostic mode so bits ALWAYS get cleared.
Parameters
in u unit
Returns
void
Todo
Todo FIXME Normally the poweron value is -1 (Full volume) However; Any read will try to read the whole volume. (This is Only used in disk copy functions) A setting of 0 will offer the best chance of the error being spotted by the Controller in Charge However; Typically systems will always set this value BEFORE a transfer.
Todo
Todo FIXME If we have a Diagnostic Report bit then we do not clear the Status/Error bits SS80 4-12
Definition at line 1484 of file ss80.c.
Referenced by SS80_Amigo_Clear(), SS80_Channel_Independent_Clear(), SS80_init(), SS80_Selected_Device_Clear(), and SS80_Universal_Device_Clear().
int SS80_Amigo_Clear (void)
Amigo Clear.
Reference: SS80 4-5
Returns
0 on send
GPIB flags on send error.
See also
gpib.h _FLAGS defines for a full list.
Todo
Todo do something with Parity Check Bit ?
Definition at line 1581 of file ss80.c.
Referenced by SS80_COMMANDS().
int SS80_Cancel (int u)
Cancel transaction.
Reference:
SS80 4-9
CS80 4-26, 3-6
State: TRANSPARENT 0x72
Phases: Command, Report
Todo
Todo
Todo
Todo FIXME
Definition at line 1617 of file ss80.c.
Referenced by SS80_Transparent_State().
int SS80_Channel_Independent_Clear (int u)
Channel Independent Clear.
See also
: Clear_Common()
Reference:
SS80 4-11
CS80 4-26, 3-2,3-5
State: TRANSPARENT 0x72
Phases: Command, Report
Parameters
in u Unit
Returns
0
Definition at line 1525 of file ss80.c.
Referenced by SS80_Transparent_State().
int SS80_cmd_seek (void)
Limit tests for disk seek.
eference SS80 4-39,4-45
We check for read/write past end of disk during the seek
See also
: SS80_locate_and_read()
: SS80_locate_and_write()
Returns
0 on sucess
fatfs error on fail
Fail will set: qstat = 1, Errors |= ERR_SEEK.
Todo
Todo Let f_lseek do bounds checking instead ??? Will we read or write past the end of the disk ??
Definition at line 1342 of file ss80.c.
Referenced by SS80_locate_and_read(), and SS80_locate_and_write().
int SS80_Command_State (void)
Process OP Codes following 0x65 Command State.
References: CS80 pg 4-6.
State: COMMAND STATE.
Returns
0 on sucess.
flags on fail.
See also
gpib.h ERROR_MASK defines for a full list.
///  Notes:
///  We set DPPR on entry and EPPR on exit
///     DPPR = DisablePPR(SS80_PPR);
///     EPPR = EnablePPR(SS80_PPR);
/// 
///  Valid OP Codes for Command State (0x65):
///     Real Time, General Purpose, Complementary, DIagnostic
///     Diagnostic
///     In this Order:
///        (1 to N) Complementary
///        and/or
///        (1) of Real Time, General Purpose, Diagnostic
///        (This later group is always LAST)
///     OP Code Sequence errors: TODO
/// 
///  We Read all of the Data/Opcodes/Parameters at once
///     (while ATN is false).
///     Last byte read should be EOI or an error
///  Why read all at once ?
///     SS80 "Command Messages" are buffered one at a time.
///     A "Command Message" contains all ALL opcodes & their parameters
///     (See SS80 Section 4-12, Page 4-6)
/// 
///  Unknown OP Code processing rules
///     Skip the remaining codes, Wait for Report Phase
/// 
Todo
Todo FIXME
Todo
Todo FIXME
Todo
Todo FIXME, In Execute state calls SS80_locate_and_read();
Todo
Todo FIXME, SS80_locate_and_write();
Todo
Todo FIXME Important SS80 and CS80 differences regarding Complementary Commands! CS80 pg 2-1 1) In CS80 when only complementary commands appear in a message they will set the system defaults: Unit, number, data transfer length, burst size, maximum retry time, and Rotational Position Sensing (RPS) window size and location. 2) If, in the same message, they proceed a Real Time, General Purpose or Diagnostic they are TEMPORARY and just for that single transaction! 3) The exeption to these rules are Set Unit, Set Volume
Todo
Todo Only handles 4-byte Addresses at the moment CS80 pg 4-11, 2-14 SS80 pg 4-67
SS80 pg 4-73
set unit number
Set Return Addressing Type: COMPLEMENTARY Phases: Command, Report SS80 pg 4-81 CS80 4-18,2-24
Todo
Todo TODO Skip Parameters
Todo
Todo not implmented yet SS80 pg 4-43 CS80 pg 4-20, 2-28
Todo
Todo TODO
Todo
Todo FIXME Execute NOW
Todo
Todo FIXME The class GENERAL PURPOSE suggests yes
Todo
Todo FIXME The class GENERAL PURPOSE suggests yes
Validate Key, Set Format Options, Download Type: GENERAL PURPOSE Phases: Command, Report Must be last command in sequence SS80 pg 4-91 CS80 N/A
Todo
Todo TODO Skip Parameters
Initialize Media Type: GENERAL PURPOSE Phases: Command, Report This command must be last and only one SS80 pg 4-33 CS80 4-19,2-26
Todo
Todo TODO
Todo
Todo FIXME
Set Status Mask Type: GENERAL PURPOSE Phases: Command, Report Must be last command in sequence SS80 pg 4-81 CS80 4-15,2-20
Todo
Todo TODO
Todo
Todo TODO
Todo
Todo TODO
Initiate Diagnostic Type: DIAGNOSTIC Phases: Command, Report Must be last command in sequence SS80 pg 4-35 CS80 N/A
Todo
Todo TODO
Definition at line 785 of file ss80.c.
Referenced by SS80_COMMANDS().
int SS80_COMMANDS (uint8_t ch)
SS80 COMMANDS States.
-Reference: SS80 3-2..9
0x6e Execute State
0x65 Command State
0x70 Report State
0x72 Transparent State
Parameters
in ch command.
Returns
0 on send
See also
GPIB error status
gpib.h _FLAGS defines for a full list.
Definition at line 1682 of file ss80.c.
Referenced by GPIB_COMMANDS().
int SS80_describe (void)
Send Controler,Unit and Volume description.
Reference: SS80 4-15.
State: EXEC STATE COMMAND>
Returns
0 on sucess>
flags on fail. @ gpib.h ERROR_MASK defines for a full list of error flags.
Definition at line 701 of file ss80.c.
Referenced by SS80_Execute_State().
int SS80_error_return (void)
Common SS80 Error Return function. Send qstat = 1.
Returns
0 on send
GPIB flags on send error
See also
gpib.h _FLAGS defines for a full list.
Definition at line 1649 of file ss80.c.
Referenced by SS80_locate_and_read().
int SS80_Execute_State (void)
SS80 Execute state process.
Reference SS80 3-1..9
State: EXEC STATE COMMAND
Returns
0 on sucess
GPIB error flags on fail
See also
gpib.h ERROR_MASK defines for a full list of error flags.
Definition at line 199 of file ss80.c.
Referenced by SS80_COMMANDS().
int SS80_increment (void)
Increment position Addressy by 256.
References: SS80 4-39, 4-45.
Returns
0
Definition at line 1632 of file ss80.c.
void SS80_init (void)
Todo
Todo FIXME
Definition at line 170 of file ss80.c.
Referenced by gpib_init_devices(), and gpib_tests().
int SS80_locate_and_read (void)
SS80 Locate and Read COmmend.
Reference: SS80 4-39
Read (SS80State.Length.L) disk bytes at (Address) offset.
Send this data to the GPIB bus.
State: EXEC STATE COMMAND.
Returns
0 on sucess
GPIB error flags on fail.
See also
gpib.h ERROR_MASK defines for a full list of error flags.
Notes: Any Disk I/O errors will set qstat and Errors.
Limitations:
Currenly we will only process 2 ** 31 bytes Max in one transfer.
If an seek or I/O error happens then we MUST continue to read and discard the GPIB data until we get an EOI or GPIB error...
Todo
Todo FIXME SS80 4-39 For now we will assume the controller will never do this
Returns
Return
Note: this should not happen unless we exit on errors above
Definition at line 252 of file ss80.c.
Referenced by SS80_Execute_State().
int SS80_locate_and_write (void)
SS80 Locate and Write Commend.
Reference: SS80 pg 4-45, CS80 pg 2-8.
Write (SS80State.Length.L) disk bytes from GPIB at (Address) offset.
State: EXEC STATE COMMAND.
Disk I/O errors will set qstat and Errors.
Limitations.
Currenly we will only process 2 ** 31 bytes Max in one transfer.
If an seek or I/O error happens then we MUST continue to. read and discard the GPIB data until we get an EOI or GPIB error...
Returns
0 on sucess.
GPIB error flags on fail.
See also
gpib.h ERROR_MASK defines for a full list.
Definition at line 385 of file ss80.c.
Referenced by SS80_Execute_State().
DWORD SS80_MaxAddress (void)
Definition at line 161 of file ss80.c.
Referenced by SS80_cmd_seek().
int SS80_Report (void)
send QSTAT
Reference: CS80 pg 4-7, Section 4-14.
///    QSTAT, return status byte
///  NORMAL COMPLETION = 0
///     Indicates normal completion of the requested operation.
///  HARD ERROR = 1
///     Indicates that error information is available.
///     The host must issue the Request Status command in order
///     to determine what went wrong.
///  POWER ON = 2
///     Indicates that the device has just returned from a power failure
///     or some form of operator intervention (such as removal of the
///     storage media). Any incomplete transactions were aborted and
///     should be repeated.  The host must reconfigure any programmable
///     operating parameters because they have returned to their
///     power-on values.
/// 
@return  0 on sucess
@see: gpib.h ERROR_MASK defines for a full list.  
Definition at line 1391 of file ss80.c.
Referenced by GPIB(), GPIB_TALK(), and SS80_COMMANDS().
int SS80_Selected_Device_Clear (int u)
Selected Device Clear.
See also
: Clear_Common()
Reference:
SS80 ps 4-2 - *** listed as NOT supported for SS80 ***
CS80 pg 4-49, 3-2, 3-4
CS80 Page B-12
Returns
0
Definition at line 1561 of file ss80.c.
Referenced by GPIB().
int SS80_send_status (void)
SS80 send detailed status.
Reference: SS80 pg 4-59..64.
Send 20 bytes of extended status to host>
State: EXEC STATE COMMAND.
///  SS80 pg 4-59
///  Bits are numbered
///    0 .. 7 (MSB..LSB "backwards")
///  Bytes are numbered
///    1 .. 20 (0..19 in message)
///  Example:
///    Bit 0 represents the MSB of Byte 1
/// 
///  We define ONLY those bits we are using, or might use
///  See: SS80 pg 4-59 for more details
///
///  Indentification Field
///    Byte 1(0)  <VVVVUUUU>
///      VVVV=Volume NUmber
///    Byte 2(1)  <11111111>
///
///  SS80 pg 4-59
///  Reject Errors Field
///       byte 3(2)           byte 4(3)
///  < 0 0 2 0 0 5 6 7 > <8 9 10 0 12 0 0 O>
///  2 = Channel Parity Error
///  5 = Illegal Opcode
///  6 = Module Addressing
///  7 = Address Bounds
///  8 = Parameter Bounds
///  9 = Illegal Parameter
///  10 = Message Sequence
///  12 = Message Length
/// 
///  SS80 pg 4-60
///  Fault Errors Field
///        byte 5(4)               byte 6(5)
///  < 0 17 0 19 0 0 22 0 > < 24 0 0 0 0 0 30 31 >
/// 
///  19 = Controller Fault
///  22 = Unit Fault
///  24 = Diagnostic Result
///  30 = Power Fail
///  31 = Re-transmit
/// 
///
///  SS80 pg 4-60
///  Access Errors Field
///        byte 7(6)                byte 8(7)
///  < 0 33 34 35 36 37 0 0 > < 40 41 0 43 44 0 0 0 >
///  33 = Uninitialized media
///  34 = No Spares Available
///  35 = Not Ready
///  36 = Write Protect
///  37 = No Data Found
///  40 = Unrecoverable Data Overflow
///  41 = Unrecoverable Data
///  43 = End of File
///  44 = End of Volume
/// 
///  SS80 pg 4-62
///  Information Errors Field
///         byte 9(8)             byte 10(9)
///  < 0 0 0 51 52 0 0 55 > < 0 57 0 59 0 0 0 0 >
///  51 = Media Wear
///  52 = Latency induced
///  55 = Auto Sparing Invoked
///  57 = Recoverable Data Overflow
///  59 = Recoverable Data
/// 
///
/// SS80 pg 4-64
/// P6 (10 .. 15) is SS80 Specific
///
/// SS80 4:65
/// P1O (16 .. 19)
///
/// @todo  add some of these
///  5 = Illegal Opcode
///  6 = Module Addressing
///  8 = Parameter Bounds
///  9 = Illegal Parameter
///  10 = Message Sequence
///  12 = Message Length
///  19 = Controller Fault
///  24 = Diagnostic Result
///  30 = Power Fail
///  33 = Uninitialized media
///  35 = Not Ready
///  37 = No Data Found
///  41 = Unrecoverable Data
///  43 = End of File
///  44 = End of Volume
/// 
@return 0.
@return GPIB error flags on fail>
@see gpib.h ERROR_MASK defines for a full list.  
Todo
Todo add Diagnostic Result status (MSB of byte 5)
4:63,64
Note: Diagnostic Result bit is NOT set
See also
SET ADDRESS
Todo
Todo Fixme
Definition at line 626 of file ss80.c.
Referenced by SS80_Execute_State().
void SS80_Test (void)
SS80 GPIB function.
Todo
Todo get this working
Definition at line 121 of file ss80.c.
Referenced by gpib_tests().
int SS80_Transparent_State (void)
(0x70 or 0x72) OP Code processing.
References: CS80 pg 4-26, 3-2,3-3,3-4,3-5,3-7,3-9,3-10.
State: Transparent State.
Returns
0 on sucess
flags on fail
See also
gpib.h ERROR_MASK defines for a full list or error flags.
///  Notes:
///     DPPR DisablePPR(SS80_PPR) should already be set at the secondary
///   We do NOT reenable EPPR at any state
/// 
///  Valid OP Codes for Transparent State (0x70 or 0x72):
///     [Unit Complementary] Transparent
/// 
///  Transparent Commands done at HP-IB state, NOT here:
///    Universal Device Clear
///    Selected Device Clear
///    Identify
/// 
///  Read all of the Data/Opcodes/Parameters at once
///     (while ATN is false).
///     Last byte read should be EOI or an error
///  Why read all at once ?
///     SS80 "Command Messages" are buffered one at a time.
///     A "Command Message" contains all ALL opcodes & their parameters
///     (See SS80 Section 4-12, Page 4-6)
/// 
///  Unknown OP Code processing rules
///     Skip the remaining codes, Wait for Report Phase
/// 
Todo
Todo FIXME
work in progress, unit support
Note: Enabling Parallel Poll is up to each function Many transparent Commands require Parallel Poll disabled when done
Todo
Todo FIXME
Todo
Todo TODO Skip Paramter
Todo
Todo FIXME SS80 4-49 CS80 4-27, 3-7
Todo
Todo TODO DO NOT EPPR
Todo
Todo FIXME SS80 4-49 CS80 4-27, 3-7
Todo
Todo TODO DO NOT EPPR
Todo
Todo FIXME SS80 4-11 CS80 4-26, 3-2,3-5
Todo
Todo FIXME SS80 4-9 CS80 4-26, 3-6
Definition at line 1183 of file ss80.c.
Referenced by SS80_COMMANDS().
int SS80_Universal_Device_Clear (void)
Universal Device CLear.
See also
: Clear_Common()
Reference:
SS80 4-11
CS80 4-26, 3-2,3-3
State: TRANSPARENT, 0x14
Phases: Command, Report
Returns
0
Todo
Todo FIXME
Definition at line 1543 of file ss80.c.
Referenced by GPIB().
Variable Documentation
uint8_t listening
gpib listen address
Definition at line 92 of file gpib.c.
Referenced by gpib_state_init(), and SS80_COMMANDS().
uint8_t printer_addr = PRINTER_DEFAULT_ADDRESS
Initialize SS80 state and bus.
=================
///  Reference:
///  CS80 Page B-12
///  Table B-5. Complementary Command Power-on Values
///  COMPLEMENTARY POWER-ON       COMPLEMENTARY               POWER-ON
///  COMMAND       VALUE COMMAND  COMMAND                     VALUE
///  Set Unit     0               Set Retry Time              device specific
///  Set Volume   0               Set Status Mask             disabled
///  Set Address  0,0,0           No Op                       Not Applicable
///  Set Length  -1 (full volume) Set Release                 T = O Z = O
///  Set Burst   disable          Set Options                 device specific
///  Set RPS     disabled         Set Return Addressing Mode  single vector
/// 
Returns
void default PRINTER address
Definition at line 157 of file ss80.c.
Referenced by display_settings(), and POSIX_Read_Config().
uint8_t spoll
gpib serial poll status
Definition at line 97 of file gpib.c.
Referenced by GPIB(), gpib_state_init(), and GPIB_TALK().
uint8_t talking
GPIB BUS states.
///  See LIF filesystem Reference
///  Reference from "Subset 80 for Fixed and Flexible Disk Drives"
///  Page: 3-17, Figure 3-8. Secondaries and Opcodes
/// 
///  Address  Secondary  Opcode   # of other   Comment
///  State  (without            Parameter
///            parity)            bytes
///  -------  ---------  ------   ----------   -------
///  L major    65H      2XH      None        Set Unit
///  L major    65H      40-47H   None        Set Volume
///  L major    65H      10H      6 bytes     Set Address
///  L major    65H      18H      4 bytes     Set Length
///  L major    65H      34H      None        No Op
///  L major    65H      39H      2 bytes     Set RFS (No Op)
///  L major    65H      3BH      1 byte      Set Release (No Op)
///  L major    65H      3EH      8 bytes     Set Status Mask
///  L major    65H      48H      1 byte      Set Return Addressing Mode
///                                           (Only single vector allowed)
///  L major    65H      00H      None        Locate and Read
///  L major    65H      02H      None        Locate and Write
///  L major    65H      04H      None        Locate and Verif y
///  L major    65H      06H      1 byte      Spare Block
///  L major    65H      00H        None        Request Status
///  L major    65H      0EH      None        Release (No Op
///  L major    65H      0FH      None        Release Denied (No Op)
///  L major    65H      31H      2 bytes     Validate Key
///  L major    65H      31H      2 bytes     Set Format Options
///  L major    65H      31H      6 bytes     Download
///  L major    65H      33H      3 bytes     Initiate Diagnostic
///  L major    65H      35H      None        Describe
///  L major    65H      37H      2 bytes     Initialize Media
///  L major    65H      4CH      None        Door Unlock
///  L major    65H      4DH      None        Door Lock
///  L major    72H      01H      1 byte      HP-IB Parity Checking
///  L major    72H      02H      4 bytes     Read Loopback
///  L major    72H      03H      4 bytes     Write Loopback
///  L major    72H      08H      None        Channel Independent Clear
///  L major    72H      09H      None        Cancel
///  L major    72H      --        --         Transparent execution (listen)
///                                           Write Loopback execution
///  L major    6EH      --        --         Normal execution (listen)
///                                           Write execution phase
///                                           Download execution phase
///  L major    70H      --       1 byte      Amigo Clear (1 parameter byte + SOC)
///  T major    70H      --       1 byte      Reporting phase (Stand alone QSTAT)
///  T major    6EH      --        --         Normal execution (talk)
///                                           Read execution phase
///                                           Describe execution phase
///                                           Request Status execution
///  T major    72H      --        --         Transparen texecution (talk)
///                                           Read Loopback execution
///  T minor    ADDRS    --        --         Identify
///  DEC        --       --        --         Universal Device Clear
/// 
///  Figure 3- 8. Secondaries and Opcodes
/// 
GPIB BUS states.
/// SS80 References: ("SS80" is the short form used in the project)
///  "Subset 80 from Fixed and flexible disc drives"
///   Printed November, 1985
///   HP Part# 5958-4129
///
/// CS80 References: ("CS80" is the short form used in the project)
///   "CS/80 Instruction Set Programming Manual"
///   Printed: APR 1983
///   HP Part# 5955-3442
///
/// Amigo References: ("Amigo" is the short form used in the project)
///   "Appendix A of 9895A Flexible Disc Memory Service Manual"
///   HP Part# 09895-90030
/// 
///  Reference: Amigo Command Set Reference used in this document
///  Short Form         Title
///  SS80       "Subset 80 from Fixed and flexible disc drives" 5958-4129
///  HP9123         9123 disc drive manual addendum 5957-6584
///  A          Appendix A "HP 9895A Disc Memory Commends Set"
///             See Receive Status A16
///  L    Buffered Read             0x05    2       A33     Y
///  L    Request Physical Address  0x14    2       A21     Y 0x68
///             See Send Address A20
/// 
///  0x6B Command Op Codes          OP      bytes
///  L    Buffered Read Verify      0x05    2       A37     Y
///  L    ID Triggered Read         0x06    2       A41     Y
/// 
///  0x6C Command Op Codes          OP      bytes
///  L    Unbuffered Read Verify    0x05    2       A38     Y
///  L    Request Physical Address  0x14    2       A21     Y 0x68
///  L    Format Request            0x18    2       A50     N
///  L    Door Lock                 0x19    2       A30     N
///  L    Door Unlock               0x1A    2       A31     N
/// 
///  0x6F Command Op Codes          OP      bytes
///  L    Download Controller       ---     1..256  A26     N
/// 
///  0x70 Command Op Codes          OP      bytes
///  L    HP-300 Clear              ---     1       A23     N
///  T    DSJ                       ---     1       A11     N
/// 
///  0x77 Command Op Codes          OP      bytes
///  T/L  HP-IB CRC                 ---     ---     A30     N
/// 
///  0x7E Command Op Codes          OP      bytes
///  L    Write Loopback Record     ---     1..256  A25     N
///  T    Read Loopback Record      ---     1..256  A14     N
/// 
///  0x7F Command Op Codes          OP      bytes
///  T    Read Self Test Results    ---     2       A13     N
///  L    Initiat Self Test         ---     2       A24     N
/// 
/// Secondary_Commands and OP Code processing
///
/// 0x60 Command Op Codes           OP      bytes
/// L    Receive Data               ---     ---
///         Execute of most receive data requests
///         All Disk Write
/// T    Send Data                  ---     ---
///         Execute of most send data requests
///         All Disk Read
///
/// 0x68 Command Op Codes           OP      bytes   Ref     Execute Phase
/// L    Cold Load Read             0x00    2       A40     Y
/// L    Seek                       0x02    6       A27     N
/// L    Request Status buffered        0x03    2       A15     Y 0x68
/// L    Unbuffered Read            0x05    2       A35     Y
/// L    Verify                     0x07    4       A36     N
/// L    Unbuffered Write Request   0x08    2       A45     Y
/// L    Initialize                 0x0B    2       A46     Y
/// L    Initialize DBIT                0x2B    2       A46     Y
/// L    Request Logical Address    0x14    2       A20     Y 0x68
/// L   End                         0x15    2       A29     N
/// T    Send Status or Address         ----    4       A20     N
///         Execute of all Address and Status Requests 
///         (Y 0x68)
///
/// 0x69 Command Op Codes           OP      bytes
/// L    Buffered Write Request     0x08    2       A43     Y
///
/// 0x6A Command Op Codes           OP      bytes
/// L    Request Status Unbuffered   0x03    2      A15     Y 0x68
///         See Receive Status A16
/// L    Buffered Read              0x05    2       A33     Y
/// L    Request Physical Address   0x14    2       A21     Y 0x68
///         See Send Address A20
///
/// 0x6B Command Op Codes           OP      bytes
/// L    Buffered Read Verify       0x05    2       A37     Y
/// L    ID Triggered Read          0x06    2       A41     Y
///
/// 0x6C Command Op Codes           OP      bytes
/// L    Unbuffered Read Verify     0x05    2       A38     Y
/// L    Request Physical Address   0x14    2       A21     Y 0x68
/// L    Format Request                 0x18    2       A50     N
/// L    Door Lock                  0x19    2       A30     N
/// L    Door Unlock                0x1A    2       A31     N
///
/// 0x6F Command Op Codes           OP      bytes
/// L    Download Controller        ---     1..256  A26     N
///
/// 0x70 Command Op Codes           OP      bytes
/// L    HP-300 Clear               ---     1       A23     N
/// T    DSJ                        ---     1       A11     N
///
/// 0x77 Command Op Codes           OP      bytes
/// T/L  HP-IB CRC                  ---     ---     A30     N
///
/// 0x7E Command Op Codes           OP      bytes
/// L    Write Loopback Record      ---     1..256  A25     N
/// T    Read Loopback Record       ---     1..256  A14     N
///
/// 0x7F Command Op Codes           OP      bytes
/// T    Read Self Test Results         ---     2       A13     N
/// L    Initiat Self Test          ---     2       A24     N
/// 
Definition at line 87 of file gpib.c.
Referenced by gpib_state_init(), and SS80_COMMANDS().
int TD[]
Initial value:
=
{
    0x3F,
    0x5f | ATN_FLAG,
    0x20 | ATN_FLAG,
    0x65 | ATN_FLAG,
    0x20,
    0x40,
    0x34,
    0x37,
    0x00,
    0x0a,
    -1
}
SS80 GPIB test string.
Todo
Todo get this working
Definition at line 104 of file ss80.c.