lib/stringsup.c File Reference
#include `user_config.h`
#include <string.h>
#include `lib/stringsup.h`
Functions
MEMSPACE void sep ()
print seperator
MEMSPACE int WEAK_ATR isdigit (int c)
test if a character is a digit
MEMSPACE int WEAK_ATR isupper (int c)
Is a character upper case.
MEMSPACE int WEAK_ATR islower (int c)
MEMSPACE int WEAK_ATR tolower (int c)
Convert character to lower case, only if it is upper case.
MEMSPACE int WEAK_ATR toupper (int c)
Convert character to upper case, only if it is lower case.
MEMSPACE void * memchr (const void *str, int c, size_t size)
find a character in a string of maximum size
MEMSPACE size_t WEAK_ATR strlen (const char *str)
String Length.
MEMSPACE WEAK_ATR char * strcpy (char *dest, const char *src)
copy a string
MEMSPACE WEAK_ATR char * strncpy (char *dest, const char *src, size_t size)
copy a string of at most N characters
MEMSPACE WEAK_ATR char * strcat (char *dest, const char *src)
Append string.
MEMSPACE WEAK_ATR char * strncat (char *dest, const char *src, size_t max)
Append string of at most N bytes from src.
MEMSPACE void WEAK_ATR reverse (char *str)
Reverse a string in place Example: abcdef -> fedcba.
MEMSPACE void WEAK_ATR strupper (char *str)
UPPERCASE a string.
MEMSPACE void trim_tail (char *str)
Trim White space and control characters from end of string.
MEMSPACE char * skipspaces (char *ptr)
Skip white space in a string - tabs and spaces.
MEMSPACE char * nextspace (char *ptr)
Skip to first white space in a string - tabs and spaces.
MEMSPACE char * skipchars (char *str, char *pat)
Skip characters defined in user string.
MEMSPACE int WEAK_ATR strcmp (const char *str, const char *pat)
Compare two strings.
MEMSPACE int WEAK_ATR strncmp (const char *str, const char *pat, size_t len)
Compare two strings maximum len bytes in size.
MEMSPACE int WEAK_ATR strcasecmp (const char *str, const char *pat)
Compare two strings without case.
MEMSPACE int WEAK_ATR strncasecmp (const char *str, const char *pat, size_t len)
Compare two strings without case maximum len bytes in size.
MEMSPACE int MATCH (char *str, char *pat)
Compare two strings.
MEMSPACE int MATCHARGS (char *str, char *pat, int min, int argc)
Match two strings and compare argument index Display message if the number of arguments is too few.
MEMSPACE int MATCHI (char *str, char *pat)
Compare two strings without case.
MEMSPACE int MATCH_LEN (char *str, char *pat)
Compare two strings limted to length of pattern.
MEMSPACE int MATCHI_LEN (char *str, char *pat)
Compare two strings without case limted to length of pattern.
MEMSPACE int split_args (char *str, char *argv[], int max)
Split string into arguments stored in argv[] We split source string into arguments Warning: source string is modified! To save memory each gap in the source string is terminated with an EOS This becomes the end of string for each argument returned Warning: Do NOT modify the source string or argument contents while using them You can reassign new pointers to the arguments if you like.
MEMSPACE char * get_token (char *str, char *token, int max)
return next token
MEMSPACE int token (char *str, char *pat)
Search for token in a string matching user pattern.
MEMSPACE int32_t get_value (char *str)
get a number
MEMSPACE char * strnalloc (char *str, int len)
Allocate space for string with maximum size.
MEMSPACE char * stralloc (char *str)
Allocate space for string.
Function Documentation
get_token()
MEMSPACE char* get_token (char * str, char * token, int max)
return next token
Skips all non printable ASCII characters before token
Token returns only printable ASCII
Parameters
in str string to search.
out token token to return
in max maximum token size
Returns
pointer past token on success .
NULL if no token found
Definition at line 628 of file stringsup.c.
Referenced by get_token().
get_value()
MEMSPACE int32_t get_value (char * str)
get a number
Used only for debugging
Parameters
in str string to examine
Returns
value
Definition at line 761 of file stringsup.c.
Referenced by assign_value(), and gpib_tests().
isdigit()
MEMSPACE int WEAK_ATR isdigit (int c)
test if a character is a digit
Parameters
in c character
Returns
true or false
Definition at line 48 of file stringsup.c.
Referenced by atol().
islower()
MEMSPACE int WEAK_ATR islower (int c)
Parameters
in c character.
Returns
1 of lower case, else 0
Definition at line 80 of file stringsup.c.
Referenced by toupper().
isupper()
MEMSPACE int WEAK_ATR isupper (int c)
Is a character upper case.
Parameters
in c character.
Returns
1 of upper case, else 0
Definition at line 64 of file stringsup.c.
Referenced by tolower().
MATCH()
MEMSPACE int MATCH (char * str, char * pat)
Compare two strings.
Parameters
in str string to match.
in pat pattern to compare.
Returns
string lenth on match.
0 on no match.
Definition at line 455 of file stringsup.c.
Referenced by fatfs_tests(), gpib_tests(), lif_tests(), ls(), MATCHARGS(), mkfs(), posix_tests(), td02lif(), and td0_open().
MATCH_LEN()
MEMSPACE int MATCH_LEN (char * str, char * pat)
Compare two strings limted to length of pattern.
Parameters
in str string to match.
in pat pattern to compare.
Returns
string lenth on match.
0 on no match.
Warning
Matches sub strings so be caeful.
Definition at line 511 of file stringsup.c.
MATCHARGS()
MEMSPACE int MATCHARGS (char * str, char * pat, int min, int argc)
Match two strings and compare argument index Display message if the number of arguments is too few.
Parameters
str string to test
pat pattern to match
min minumum number or arguments
argc actual number of arguments
Returns
1 on match, 0 on no match or too few arguments
Definition at line 471 of file stringsup.c.
Referenced by fatfs_tests(), gpib_tests(), lif_tests(), posix_tests(), and task().
MATCHI()
MEMSPACE int MATCHI (char * str, char * pat)
Compare two strings without case.
Parameters
in str string to match.
in pat pattern to compare.
Returns
string lenth on match.
0 on no match.
Definition at line 493 of file stringsup.c.
Referenced by gpib_tests().
MATCHI_LEN()
MEMSPACE int MATCHI_LEN (char * str, char * pat)
Compare two strings without case limted to length of pattern.
Parameters
in str string to match.
in pat pattern to compare.
Returns
string lenth on match.
0 on no match.
Warning
Matches sub strings so be caeful.
Definition at line 537 of file stringsup.c.
Referenced by get_value().
memchr()
MEMSPACE void* memchr (const void * str, int c, size_t size)
find a character in a string of maximum size
Parameters
in str string
in c character
in size string length to search
Returns
string length
Definition at line 125 of file stringsup.c.
nextspace()
MEMSPACE char* nextspace (char * ptr)
Skip to first white space in a string - tabs and spaces.
Parameters
in ptr input string
Returns
pointer to first white space character
Definition at line 306 of file stringsup.c.
reverse()
MEMSPACE void WEAK_ATR reverse (char * str)
Reverse a string in place Example: abcdef -> fedcba.
Parameters
in str string
Returns
string length
Definition at line 231 of file stringsup.c.
sep()
MEMSPACE void sep (void)
print seperator
undo any existing macros
Definition at line 32 of file stringsup.c.
Referenced by main(), and SS80_Test().
skipchars()
MEMSPACE char* skipchars (char * str, char * pat)
Skip characters defined in user string.
Parameters
in str string
in pat pattern string
Returns
pointer to string after skipped characters.
Definition at line 328 of file stringsup.c.
skipspaces()
MEMSPACE char* skipspaces (char * ptr)
Skip white space in a string - tabs and spaces.
Parameters
in ptr input string
Returns
pointer to first non white space character
Definition at line 289 of file stringsup.c.
Referenced by assign_value(), get_token(), get_value(), gpib_trace_task(), POSIX_Read_Config(), split_args(), timetests(), and token().
split_args()
MEMSPACE int split_args (char * str, char * argv[], int max)
Split string into arguments stored in argv[] We split source string into arguments Warning: source string is modified! To save memory each gap in the source string is terminated with an EOS This becomes the end of string for each argument returned Warning: Do NOT modify the source string or argument contents while using them You can reassign new pointers to the arguments if you like.
Parameters
Definition at line 566 of file stringsup.c.
Referenced by task().
stralloc()
MEMSPACE char* stralloc (char * str)
Allocate space for string.
Copies tring into allocated space.
Parameters
in str user string.
Returns
pointer to alocated string.
NULL on out of memory.
Definition at line 829 of file stringsup.c.
strcasecmp()
MEMSPACE int WEAK_ATR strcasecmp (const char * str, const char * pat)
Compare two strings without case.
Parameters
in str string to match.
in pat pattern to compare.
Returns
0 on match, < 0 implies str sorts before pat, > 0 implies str sorts after pat
Definition at line 410 of file stringsup.c.
Referenced by lif_find_file(), MATCHI(), and td02lif().
strcat()
MEMSPACE WEAK_ATR char* strcat (char * dest, const char * src)
Append string.
Parameters
in dest string
in src string
Returns
string length
Definition at line 199 of file stringsup.c.
Referenced by gpib_trace_display(), lif_add_ascii_file_as_e010_wrapper(), ls(), and upload().
strcmp()
MEMSPACE int WEAK_ATR strcmp (const char * str, const char * pat)
Compare two strings.
Parameters
in str string to match.
in pat pattern to compare.
Returns
0 on match, < 0 implies str sorts before pat, > 0 implies str sorts after pat
Definition at line 362 of file stringsup.c.
Referenced by MATCH(), and stat().
strcpy()
MEMSPACE WEAK_ATR char * strcpy (char * dest, const char * src)
copy a string
Parameters
in dest destination string
in src source string
Returns
destination string
Definition at line 161 of file stringsup.c.
Referenced by fatfs_ls(), fatfs_scan_files(), lif_lifbcd2timestr(), lif_stralloc(), ls(), stralloc(), and strcat().
strlen()
MEMSPACE size_t WEAK_ATR strlen (const char * str)
String Length.
Parameters
in str string
Returns
string length
Definition at line 146 of file stringsup.c.
Referenced by cat(), controller_send_str(), fatfs_ls(), fatfs_scan_files(), get_line(), gpib_trace_display(), LCD_puts(), lif_ascii_string_to_e010(), lif_find_file(), lif_fixname(), lif_stralloc(), logfile(), ls(), MATCH(), MATCH_LEN(), MATCHI(), MATCHI_LEN(), mctime(), POSIX_Read_Config(), readdir(), reverse(), stralloc(), td02lif(), token(), trim_tail(), and upload().
strnalloc()
MEMSPACE char* strnalloc (char * str, int len)
Allocate space for string with maximum size.
Copies tring into allocated space limited to maximum size.
Parameters
in str user string.
in len maximum string length.
Returns
pointer to alocated string.
Definition at line 805 of file stringsup.c.
strncasecmp()
MEMSPACE int WEAK_ATR strncasecmp (const char * str, const char * pat, size_t len)
Compare two strings without case maximum len bytes in size.
Parameters
in str string to match.
in pat pattern to compare.
in len maximum string length for compare
Returns
0 on match, < 0 implies str sorts before pat, > 0 implies str sorts after pat
Definition at line 432 of file stringsup.c.
Referenced by MATCHI_LEN().
strncat()
MEMSPACE WEAK_ATR char* strncat (char * dest, const char * src, size_t max)
Append string of at most N bytes from src.
Parameters
in dest string
in src string
Returns
string length
Definition at line 214 of file stringsup.c.
strncmp()
MEMSPACE int WEAK_ATR strncmp (const char * str, const char * pat, size_t len)
Compare two strings maximum len bytes in size.
Parameters
in str string to match.
in pat pattern to compare.
in len maximum string length for compare
Returns
0 on match, < 0 implies str sorts before pat, > 0 implies str sorts after pat
Definition at line 386 of file stringsup.c.
Referenced by MATCH_LEN(), and token().
strncpy()
MEMSPACE WEAK_ATR char* strncpy (char * dest, const char * src, size_t size)
copy a string of at most N characters
Parameters
in dest destination string
in src source string
in size maximum destination size
Returns
destination string
Definition at line 179 of file stringsup.c.
Referenced by POSIX_Read_Config(), readdir(), SS80_Initial_Defaults(), strerror_r(), strnalloc(), and strncat().
strupper()
MEMSPACE void WEAK_ATR strupper (char * str)
UPPERCASE a string.
Parameters
in str string
Returns
void
Definition at line 253 of file stringsup.c.
token()
MEMSPACE int token (char * str, char * pat)
Search for token in a string matching user pattern.
Skips all non printable ASCII characters before trying match.
Parameters
in str string to search.
in pat pattern to search for.
Returns
string lenth on match.
0 on no match.
Definition at line 726 of file stringsup.c.
Referenced by get_token(), POSIX_Read_Config(), and rcvr_datablock().
tolower()
MEMSPACE int WEAK_ATR tolower (int c)
Convert character to lower case, only if it is upper case.
Parameters
in c character.
Returns
character or lowercase value or character
Definition at line 96 of file stringsup.c.
Referenced by mkfs().
toupper()
MEMSPACE int WEAK_ATR toupper (int c)
Convert character to upper case, only if it is lower case.
Parameters
in c character.
Returns
character or upper case value or character
Definition at line 112 of file stringsup.c.
Referenced by strcasecmp(), strncasecmp(), and strupper().
trim_tail()
MEMSPACE void trim_tail (char * str)
Trim White space and control characters from end of string.
Parameters
in str string
Returns
void
Warning
Overwrites White space and control characters with EOS.
Definition at line 271 of file stringsup.c.
Referenced by cat(), get_token(), lif_add_ascii_file_as_e010_wrapper(), lif_B2S(), lif_ctime_gmt(), and POSIX_Read_Config().