lif/td02lif.h File Reference
Data Structures
struct td_header_t
TeleDisk Image Header.
struct td_comment_t
Comment header Only used when bit 7 of TrackDensity in TeleDisk Header is set.
struct td_track_t
Track Header Contains the Physical Sectors, Cylinder, Side number From the original physical disk used to make the TeleDIsk image.
struct td_sector_t
Sector Header Contents of the Sector ID fields which preceeded the sector data From the original physical disk used to make the TeleDIsk image.
struct sector_t
Sector information and Sector `ID`.
struct track_t
struct disk_t
struct liftel_t
Master TeleDisk Format Analisis structure We look for the specifications of LIF image stored inside the TeleDisk image We Examine the first 30 tracks (just some number less then 35)
Macros
#define TD_HEADER_SIZE 12
Size of TeleDisk image header.
#define TD_COMMENT_SIZE 10
Size of TeleDisk comment header.
#define TD_TRACK_SIZE 4
Size of TeleDisk track header size.
#define TD_SECTOR_SIZE 6
Size of TeleDisk sector header size.
#define MAXSECTORS 255
Maximum number of sectors per track Used for sector data and sorting tables.
#define MAXSIDES 2
Maximum number of sides per cyinder TeleDisk only trargetted floppies with 2 sides max!
#define MAXCYL 255
Maximum number of tracks per disk.
#define MAXTRACKS (MAXCYL * MAXSIDES)
Typedefs
typedef struct tm tm_t
Enumerations
enum { IBMFORMAT_SD,
IBMFORMAT_DD
 }
Encoding format td_track.PSide & 0x80 values.
enum {
TD0_INIT,
TD0_START,
TD0_WAIT_DIRECTORY,
TD0_DIRECTORY,
TD0_WAIT_FILE,
TD0_FILE,
TD0_DONE
 }
TD0 to LIF state machine states.
Functions
void td0_B2S (uint8_t *B, int index, uint8_t *name, int size)
Create a string from data that has no EOS but known size.
uint16_t td0_crc16 (uint8_t *B, uint16_t crc, uint16_t poly, int size)
Compute CRC16 of 8bit data.
void td0_hexdump (uint8_t *data, int size)
hex listing of data
int td0_unpack_disk_header (uint8_t *B, td_header_t *p)
Extract TeleDisk image header data in architecture nutral way.
int td0_unpack_comment_header (uint8_t *B, td_comment_t *p)
Extract TeleDisk comment header data in architecture nutral way.
int td0_unpack_track_header (uint8_t *B, td_track_t *p)
Extract TeleDisk track header data in architecture nutral way.
int td0_unpack_sector_header (uint8_t *B, td_sector_t *p)
Extract TeleDisk sector header data in architecture nutral way.
void td0_compressed (int flag)
Enable TeleDisk image compression mode.
int td0_read (void *p, int osize, int size, FILE *fp)
Read TeleDisk image data block Optionally decompress the data if decompression is enabled.
int td0_rle (uint8_t *dst, uint8_t *src, int max)
Expand a Run Length encoded TeleDisk sector Notes: the source length is encoded in the source data Credits based on work (C) 2006-2014 Jean-François DEL NERO Part of the HxCFloppyEmulator library GNU GPL version 2 or later Rewitten for clarity,to enforce size limits, provide error reporting and to avoid word order dependent assumptions,.
void td0_trackinfo (disk_t *disk, int trackind, int index)
Display TeleDisk track sector values.
void td0_sectorinfo (td_sector_t *P)
Display TeleDisk sector data.
long td0_density2bitrate (uint8_t density)
Convert Denisity to bitrate don't care about the density except as a possible filter.
int td0_open (disk_t *disk, char *name)
Opne TeleDisk image file process header and optional comment block.
int td0_read_disk (disk_t *disk)
Read TeleDisk image file and save all sector data.
int td0_analize_format (disk_t *disk)
Analize TeleDisk disk sector data Problem: We may have a disk that was reformatted multiple times Each format may have used differing sector sizes, number of tracks, sides For example: First format 80 track disk, two sided, and 9 512 byte sectors per track Second format 35 tracks, single sided, 16 sectors 256 bytes size per track Clearly we only want the 35 tracks on the first side.
int td0_save_lif (disk_t *disk, lif_t *LIF)
save remaining sectors as LIF data
int td0_save_lif_sector (disk_t *disk, uint8_t *data, int size, lif_t *LIF)
Process all sectors on a track from TeleDisk image.
void td0_help (int full)
void td0_init_liftel (void)
TeleDisk image Analisis structure Find attributes of LIF image stored in TeleDisk image.
void td0_init_sectors (disk_t *disk)
Initialize track sector information Optionally decompress the data if decompression is enabled.
int td02lif (int argc, char *argv [])
Convert a Teledisk LIF formatted disk image into a pure LIF image.
Variables
int debuglevel
Debug flag - used to log GPIB and emulator messages.
liftel_t liftel
Teledisk liftel analysis and user overrides.
Macro Definition Documentation
MAXCYL
#define MAXCYL 255
Maximum number of tracks per disk.
Definition at line 64 of file td02lif.h.
Referenced by td0_read_disk().
MAXSECTORS
#define MAXSECTORS 255
Maximum number of sectors per track Used for sector data and sorting tables.
Definition at line 57 of file td02lif.h.
Referenced by td0_analize_format(), td0_init_sectors(), and td0_read_disk().
MAXSIDES
#define MAXSIDES 2
Maximum number of sides per cyinder TeleDisk only trargetted floppies with 2 sides max!
Definition at line 61 of file td02lif.h.
Referenced by td0_read_disk().
MAXTRACKS
#define MAXTRACKS (MAXCYL * MAXSIDES)
Definition at line 66 of file td02lif.h.
Referenced by td02lif(), td0_analize_format(), td0_init_sectors(), td0_read_disk(), and td0_save_lif().
TD_COMMENT_SIZE
#define TD_COMMENT_SIZE 10
Size of TeleDisk comment header.
Definition at line 49 of file td02lif.h.
Referenced by td0_open().
TD_HEADER_SIZE
#define TD_HEADER_SIZE 12
Size of TeleDisk image header.
Definition at line 47 of file td02lif.h.
Referenced by td0_open(), and td0_unpack_disk_header().
TD_SECTOR_SIZE
#define TD_SECTOR_SIZE 6
Size of TeleDisk sector header size.
Definition at line 53 of file td02lif.h.
Referenced by td0_read_disk().
TD_TRACK_SIZE
#define TD_TRACK_SIZE 4
Size of TeleDisk track header size.
Definition at line 51 of file td02lif.h.
Referenced by td0_read_disk().
Typedef Documentation
tm_t
typedef struct tm tm_t
Definition at line 69 of file td02lif.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Encoding format td_track.PSide & 0x80 values.
Enumerator
IBMFORMAT_SD
IBMFORMAT_DD
Definition at line 73 of file td02lif.h.
anonymous enum
anonymous enum
TD0 to LIF state machine states.
Enumerator
TD0_INIT
TD0_START
TD0_WAIT_DIRECTORY
TD0_DIRECTORY
TD0_WAIT_FILE
TD0_FILE
TD0_DONE
Definition at line 80 of file td02lif.h.
Function Documentation
td02lif()
int td02lif (int argc, char * argv[])
Convert a Teledisk LIF formatted disk image into a pure LIF image.
Parameters
in telediskname TELEDISK image name
in lifname LIF file name to write
Returns
1 on success, 0 on error
Write LIF file
LIF summary
Close LIF file
Definition at line 1658 of file td02lif.c.
Referenced by lif_tests().
td0_analize_format()
int td0_analize_format (disk_t * disk)
Analize TeleDisk disk sector data Problem: We may have a disk that was reformatted multiple times Each format may have used differing sector sizes, number of tracks, sides For example: First format 80 track disk, two sided, and 9 512 byte sectors per track Second format 35 tracks, single sided, 16 sectors 256 bytes size per track Clearly we only want the 35 tracks on the first side.
What we do is examine the first 30 tracks (note: 30 is just a safe number less then 35) On side 1, on 30 tracks Find first sector and save its size Reject sectors that do not match size Find Last sector matching size Count sectors matching size On side 2, on 30 tracks Reject sectors that do not match size Find first sector and save its size Find Last sector matching size Count sectors matching size
If the disk had two sides recorded in the header Reject second side if side sector counts do NOT match Reject second side if NO remaining sectors Reject second side if sector ranges do not match or continue in range
Parameters
in dist TD0 image data 1 if OK, 0 on error
Definition at line 894 of file td02lif.c.
Referenced by td02lif().
td0_B2S()
void td0_B2S (uint8_t * B, int index, uint8_t * name, int size)
Create a string from data that has no EOS but known size.
Parameters
in *B source
in index index offset into source data
out *name target string
in size size of string to write - not including EOS
Returns
void
Definition at line 68 of file td02lif.c.
Referenced by td0_unpack_disk_header().
td0_compressed()
void td0_compressed (int flag)
Enable TeleDisk image compression mode.
Parameters
in flag compression anable/disable
Returns
void
Definition at line 248 of file td02lif.c.
Referenced by td0_open().
td0_crc16()
uint16_t td0_crc16 (uint8_t * B, uint16_t crc, uint16_t poly, int size)
Compute CRC16 of 8bit data.
See also
https://en.wikipedia.org/wiki/Cyclic_redundancy_check FYI normal CRC16 typically use 0x1021 for ploy Note: You can do a CRC16 of data in blocks by passing the result as the crc initial value for the next call
Parameters
in *B 8 bit binary data
in crc initial crc value
out poly ploynomial
in size number of bytes
Returns
crc16 of result
Definition at line 88 of file td02lif.c.
Referenced by td0_open(), td0_read_disk(), td0_unpack_comment_header(), td0_unpack_disk_header(), and td0_unpack_track_header().
td0_density2bitrate()
long td0_density2bitrate (uint8_t density)
Convert Denisity to bitrate don't care about the density except as a possible filter.
Parameters
in Density
Returns
bitrate
Definition at line 464 of file td02lif.c.
td0_help()
void td0_help (int full)
Definition at line 1564 of file td02lif.c.
Referenced by lif_tests(), and td02lif().
td0_hexdump()
void td0_hexdump (uint8_t * data, int size)
hex listing of data
Parameters
in *data date to dump
in size size of data to dump void
Definition at line 111 of file td02lif.c.
Referenced by td0_save_lif_sector().
td0_init_liftel()
void td0_init_liftel (void)
TeleDisk image Analisis structure Find attributes of LIF image stored in TeleDisk image.
Definition at line 1584 of file td02lif.c.
Referenced by td02lif().
td0_init_sectors()
void td0_init_sectors (disk_t * disk)
Initialize track sector information Optionally decompress the data if decompression is enabled.
Parameters
out p data buffer for read
out osize size of object
out size number of objects to read
Returns
size of dataactually read
Definition at line 1620 of file td02lif.c.
Referenced by td02lif().
td0_open()
int td0_open (disk_t * disk, char * name)
Opne TeleDisk image file process header and optional comment block.
Parameters
in *disk TeleDisk information structure
in *name image file name
Returns
1 on success 0 on error Note: on success disk->fi has the file handle disk->td0_name has the file name disk->compresssed if image is compressed disk->td_header has teledisk header disk->td_comment has optional teledisk comment header or zeroed If disk.td_comment.Size > 0 disk->comment has optional comment string or empty string If disk.td_comment.Size > 0
TeleDisk disk image header
we expect `TD` (uncompressed) or `td` (compressed) format
We only accept TeleDisk versions >= 10 && version <= 21
Time to Unix format
Definition at line 497 of file td02lif.c.
Referenced by td02lif().
td0_read()
int td0_read (void * p, int osize, int size, FILE * fp)
Read TeleDisk image data block Optionally decompress the data if decompression is enabled.
Parameters
out p data buffer for read
out osize size of object
out size number of objects to read
Returns
1 on success all bytes read, 0 on failure not all bytes read
Definition at line 261 of file td02lif.c.
Referenced by td0_open(), and td0_read_disk().
td0_read_disk()
int td0_read_disk (disk_t * disk)
Read TeleDisk image file and save all sector data.
Parameters
in dist TD0 image data
Returns
1 on success 0 on error
Process all image Data
EOF? TeleDisk specification says EOF is 255 sectors
Process all track sectors
Sector Header
first test verifies sector < 2K in size second test verifies no data or address mark errors
Compute how much data to read
td0_rle does not use len internal data in the buffer does this We limit the expansion to sector size
Definition at line 636 of file td02lif.c.
Referenced by td02lif().
td0_rle()
int td0_rle (uint8_t * dst, uint8_t * src, int max)
Expand a Run Length encoded TeleDisk sector Notes: the source length is encoded in the source data Credits based on work (C) 2006-2014 Jean-François DEL NERO Part of the HxCFloppyEmulator library GNU GPL version 2 or later Rewitten for clarity,to enforce size limits, provide error reporting and to avoid word order dependent assumptions,.
Parameters
out dst destination expanded data
in src source data
in max maximum size of destination data
Returns
size of expanded data, negative if size > max
length
block size
repeat count
Definition at line 303 of file td02lif.c.
Referenced by td0_read_disk().
td0_save_lif()
int td0_save_lif (disk_t * disk, lif_t * LIF)
save remaining sectors as LIF data
Parameters
in data sector data
in LIF LIF structure 1 if OK, 0 on error
Definition at line 1307 of file td02lif.c.
Referenced by td02lif().
td0_save_lif_sector()
int td0_save_lif_sector (disk_t * disk, uint8_t * data, int size, lif_t * LIF)
Process all sectors on a track from TeleDisk image.
Parameters
in data sector data
in size sector size
in LIF LIF structure 1 if OK, 0 on error
==================================================== Write sectors from Teledisk track to LIF file
We continue until the last last file sector
Definition at line 1371 of file td02lif.c.
Referenced by td0_save_lif().
td0_sectorinfo()
void td0_sectorinfo (td_sector_t * P)
Display TeleDisk sector data.
Parameters
in P td_sector pointer
Returns
void
Definition at line 451 of file td02lif.c.
Referenced by td0_read_disk().
td0_trackinfo()
void td0_trackinfo (disk_t * disk, int trackind, int index)
Display TeleDisk track sector values.
Parameters
in sector track sector structure
in index sector index (not sector number)
Returns
void
Definition at line 438 of file td02lif.c.
Referenced by td0_analize_format(), and td0_read_disk().
td0_unpack_comment_header()
int td0_unpack_comment_header (uint8_t * B, td_comment_t * p)
Extract TeleDisk comment header data in architecture nutral way.
Parameters
in B source data
out p TeleDisk comment header structure
Returns
TeleDisk comment header size (not structure size)
Definition at line 179 of file td02lif.c.
Referenced by td0_open().
td0_unpack_disk_header()
int td0_unpack_disk_header (uint8_t * B, td_header_t * p)
Extract TeleDisk image header data in architecture nutral way.
Parameters
in B source data
out p TeleDisk image header structure
Returns
TeleDisk image header size (not structure size)
Definition at line 153 of file td02lif.c.
Referenced by td0_open().
td0_unpack_sector_header()
int td0_unpack_sector_header (uint8_t * B, td_sector_t * p)
Extract TeleDisk sector header data in architecture nutral way.
Parameters
in B source data
out p TeleDisk sector header structure
Returns
TeleDisk sector header size (not structure size)
Definition at line 231 of file td02lif.c.
Referenced by td0_read_disk().
td0_unpack_track_header()
int td0_unpack_track_header (uint8_t * B, td_track_t * p)
Extract TeleDisk track header data in architecture nutral way.
Parameters
in B source data
out p TeleDisk track header structure
Returns
TeleDisk track header size (not structure size)
Definition at line 201 of file td02lif.c.
Referenced by td0_read_disk().
Variable Documentation
debuglevel
int debuglevel
Debug flag - used to log GPIB and emulator messages.
Definition at line 35 of file gpib_task.c.
Referenced by GPIB(), gpib_error_test(), gpib_file_init(), GPIB_LISTEN(), GPIB_SECONDARY_ADDRESS(), GPIB_TALK(), gpib_task(), listen_cleanup(), and Send_Identify().
liftel
liftel_t liftel
Teledisk liftel analysis and user overrides.
Definition at line 60 of file td02lif.c.