lib/timer.c File Reference
timer functions
#include `user_config.h`
#include `mathio.h`
#include `time.h`
#include `timer.h`
Functions
MEMSPACE int set_timers (void(*handler)(void), int timer __attribute__((unused)))
Install a user timer task.
MEMSPACE int kill_timer (int timer)
Delete `Kill` one user timer task.
MEMSPACE void delete_all_timers ()
Clear ALL user timer tasks.
MEMSPACE void subtract_timespec (ts_t *a, ts_t *b)
subtract a-= b timespec * structures.
MEMSPACE char * ts_to_str (ts_t *val)
MEMSPACE void display_ts (ts_t *val)
timespec structure in seconds.nanoseconds.
MEMSPACE void clock_elapsed_begin ()
Store current struct timespec in __clock_elapsed.
MEMSPACE void clock_elapsed_end (char *msg)
Subtract and display time difference from clock_elapesed_begin().
MEMSPACE void clock_clear ()
clear time and timezone to 0.
MEMSPACE void disable_timers ()
Disable all timer tasks.
MEMSPACE void enable_timers ()
Enable timer tasks.
void execute_timers ()
Execute all user timers at SYSTEM_HZ rate. Called by system task.
void clock_task (void)
1000HZ timer task
MEMSPACE void init_timers ()
Setup all timers tasksi and enable interrupts.
MEMSPACE int clock_getres (clockid_t clk_id __attribute__((unused)), struct timespec *res)
Read clock time resolution into struct timepec *ts - POSIX function.
MEMSPACE int clock_settime (clockid_t clk_id __attribute__((unused)), const struct timespec *ts)
Set system clock using seconds and nonoseconds - POSIX function.
MEMSPACE int clock_gettime (clockid_t clk_id __attribute__((unused)), struct timespec *ts)
Generic clock_gettime() function WITHOUT high resolution.
Variables
volatile ts_t __clock
System Clock Time.
tz_t __tzone
System Time Zone.
static int timers_enabled = 0
static int timers_configured = 0
TIMERS timer_irq [MAX_TIMER_CNT]
array or user timers
static char _ts_to_str [32]
timespec structure in seconds.nanoseconds in string.
static ts_t __clock_elapsed
Used for elapsed time calculations.
Detailed Description
timer functions
Copyright 2015 Mike Gore, GPL License
You are free to use this code under the terms of GPL
please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Function Documentation
clock_clear()
MEMSPACE void clock_clear ()
clear time and timezone to 0.
See also
clock_settime().
settimezone().
Returns
void.
Definition at line 222 of file timer.c.
Referenced by init_timers(), and main().
clock_elapsed_begin()
MEMSPACE void clock_elapsed_begin ()
Store current struct timespec in __clock_elapsed.
See also
clock_gettime() POSIX function.
Returns
void
Definition at line 184 of file timer.c.
Referenced by gpib_timer_elapsed_begin().
clock_elapsed_end()
MEMSPACE void clock_elapsed_end (char * msg)
Subtract and display time difference from clock_elapesed_begin().
Notes: Accuracy is a function of timer resolution, CPU overhead and background tasks.
Parameters
 in msg User message to proceed Time display.
Returns
void
See also
clock_gettime().
clock_elapesed_begin().
Definition at line 200 of file timer.c.
Referenced by gpib_timer_elapsed_end().
clock_getres()
MEMSPACE int clock_getres (clockid_t clk_id __attribute__(unused), struct timespec * res)
Read clock time resolution into struct timepec *ts - POSIX function.
Note: We ignore clk_id
Parameters
 in clk_id unused hardware clock index.
 out res timespec resolution result.
Returns
0 on success.
-1 on error.
Definition at line 335 of file timer.c.
Referenced by main().
clock_gettime()
MEMSPACE int clock_gettime (clockid_t clk_id __attribute__(unused), struct timespec * ts)
Generic clock_gettime() function WITHOUT high resolution.
Read clock time into struct timepec *ts - POSIX function.
Note: We ignore clk_id, and include low level counter offsets when available.
Parameters
 in clk_id unused hardware clock index.
 out ts timespec result.
Returns
0 on success.
-1 on error.
Definition at line 386 of file timer.c.
Referenced by clock_elapsed_begin(), clock_elapsed_end(), display_clock(), gettimeofday(), printer_open(), and time().
clock_settime()
MEMSPACE int clock_settime (clockid_t clk_id __attribute__(unused), const struct timespec * ts)
Set system clock using seconds and nonoseconds - POSIX function.
Parameters
 in clk_id Hardware timer index used when there are more then one.
Note: We ignore clk_id for now.
 in ts struct timespec input.
Returns
0.
Definition at line 353 of file timer.c.
Referenced by clock_clear(), clock_set(), initialize_clock(), setdate_r(), and settimeofday().
clock_task()
void clock_task (void)
1000HZ timer task
Returns
void
Definition at line 281 of file timer.c.
Referenced by init_timers().
delete_all_timers()
MEMSPACE void delete_all_timers ()
Clear ALL user timer tasks.
Returns
void
Definition at line 116 of file timer.c.
Referenced by init_timers().
disable_timers()
MEMSPACE void disable_timers ()
Disable all timer tasks.
Returns
void
Definition at line 237 of file timer.c.
display_ts()
MEMSPACE void display_ts (ts_t * val)
timespec structure in seconds.nanoseconds.
Parameters
 in val timespec struct we want to display.
Returns
void.
Definition at line 167 of file timer.c.
enable_timers()
MEMSPACE void enable_timers ()
Enable timer tasks.
Returns
void
Definition at line 251 of file timer.c.
Referenced by init_timers().
execute_timers()
void execute_timers ()
Execute all user timers at SYSTEM_HZ rate. Called by system task.
Returns
void
Definition at line 265 of file timer.c.
init_timers()
MEMSPACE void init_timers ()
Setup all timers tasksi and enable interrupts.
See also
clock_task()
: timer_hal.c for hardware dependent interface
Returns
void
See time.c
Definition at line 299 of file timer.c.
Referenced by main().
kill_timer()
MEMSPACE int kill_timer (int timer)
Delete `Kill` one user timer task.
`kill` is a common Linux term for ending a process.
Parameters
 in timer user timer task index.
Returns
timer on success.
-1 on error.
Definition at line 99 of file timer.c.
set_timers()
MEMSPACE int set_timers (void(*)(void) handler, int timer __attribute__(unused))
Install a user timer task.
timer argument is unsused, reserved for timer source.
Parameters
 in handler) function pointer to user task.
 in timer reserved for systems with additional low level hardware timers.
Returns
timer on success.
-1 on error.
Definition at line 59 of file timer.c.
Referenced by gpib_timer_init(), i2c_init(), init_timers(), and mmc_install_timer().
subtract_timespec()
MEMSPACE void subtract_timespec (ts_t * a, ts_t * b)
subtract a-= b timespec * structures.
Parameters
 in a timespec struct.
 in b timespec struct.
Returns
void.
Definition at line 134 of file timer.c.
Referenced by clock_elapsed_end().
ts_to_str()
MEMSPACE char* ts_to_str (ts_t * val)
Definition at line 154 of file timer.c.
Referenced by clock_elapsed_end(), and display_ts().
Variable Documentation
__clock
volatile ts_t __clock
System Clock Time.
Definition at line 38 of file timer.c.
Referenced by clock_gettime(), clock_settime(), and clock_task().
__clock_elapsed
ts_t __clock_elapsed [static]
Used for elapsed time calculations.
See also
clock_elapsed_begin().
clock_elapsed_end().
Definition at line 176 of file timer.c.
Referenced by clock_elapsed_begin(), and clock_elapsed_end().
__tzone
tz_t __tzone
System Time Zone.
Definition at line 41 of file timer.c.
Referenced by clock_clear().
_ts_to_str
char _ts_to_str[32] [static]
timespec structure in seconds.nanoseconds in string.
Parameters
 in timespec struct we wish to display.
 in output string.
Returns
void.
Definition at line 152 of file timer.c.
Referenced by ts_to_str().
timer_irq
TIMERS timer_irq[MAX_TIMER_CNT]
array or user timers
Definition at line 47 of file timer.c.
Referenced by delete_all_timers(), execute_timers(), kill_timer(), and set_timers().
timers_configured
int timers_configured = 0 [static]
Definition at line 44 of file timer.c.
Referenced by disable_timers(), enable_timers(), and init_timers().
timers_enabled
int timers_enabled = 0 [static]
Definition at line 43 of file timer.c.
Referenced by disable_timers(), enable_timers(), and init_timers().