lib/timer_hal.c File Reference
High resolution timer library and user tasks hardware specific code for AVR8.
#include <hardware/cpu.h>
*
#include <lib/timer.h>
*
#include <lib/time.h>
*
Macros
#define TIMER1_PRESCALE 1L
AVR prescale divider.
#define TIMER1_COUNTS_PER_TIC (F_CPU/TIMER1_PRESCALE/SYSTEM_TASK_HZ)
Computer AVR counts per interrupt.
#define TIMER1_COUNTER_RES (SYSTEM_TASK_TIC_NS/TIMER1_COUNTS_PER_TIC)
Computer AVR count time in Nanoseconds per counter increment.
#define TIMER1_PRE_1 (1 << CS10)						/*< 1 Prescale */
#define TIMER1_PRE_8 (1 << CS11)						/*< 8 Prescale */
#define TIMER1_PRE_64 ((1 << CS11) | (1 << CS10))		/*< 64 Prescale */
#define TIMER1_PRE_256 (1 << CS12)						/*< 256 Prescale */
#define TIMER1_PRE_1024 ((1 << CS12) | (1 << CS10))	/*< 1024 Prescape */
Functions
ISR (TIMER1_COMPA_vect)
AVR Timer Interrupt Vector.
void setup_timers_isr ()
Setup main timers ISR - this ISR calls execute_timers() task.
int clock_gettime (clockid_t clk_id, struct timespec *ts)
Read clock time into struct timepec *ts - POSIX function.
int clock_getres (clockid_t clk_id, struct timespec *res)
Read clock time resolution into struct timepec *ts - POSIX function.
Variables
volatile ts_t __clock
System Clock Time.
Detailed Description
High resolution timer library and user tasks hardware specific code for AVR8.
Edit History
[1.0] [Mike Gore] Initial revision of file.
Copyright 2014 Mike Gore, Inc. All rights reserved.
Definition in file timer_hal.c.
Macro Definition Documentation
#define TIMER1_COUNTER_RES (SYSTEM_TASK_TIC_NS/TIMER1_COUNTS_PER_TIC)
Computer AVR count time in Nanoseconds per counter increment.
Definition at line 29 of file timer_hal.c.
Referenced by clock_getres(), and clock_gettime().
#define TIMER1_COUNTS_PER_TIC (F_CPU/TIMER1_PRESCALE/SYSTEM_TASK_HZ)
Computer AVR counts per interrupt.
Definition at line 26 of file timer_hal.c.
Referenced by clock_gettime(), and setup_timers_isr().
#define TIMER1_PRE_1 (1 << CS10)						/*< 1 Prescale */
Definition at line 35 of file timer_hal.c.
Referenced by setup_timers_isr().
#define TIMER1_PRE_1024 ((1 << CS12) | (1 << CS10))	/*< 1024 Prescape */
Definition at line 39 of file timer_hal.c.
#define TIMER1_PRE_256 (1 << CS12)						/*< 256 Prescale */
Definition at line 38 of file timer_hal.c.
#define TIMER1_PRE_64 ((1 << CS11) | (1 << CS10))		/*< 64 Prescale */
Definition at line 37 of file timer_hal.c.
#define TIMER1_PRE_8 (1 << CS11)						/*< 8 Prescale */
Definition at line 36 of file timer_hal.c.
#define TIMER1_PRESCALE 1L
AVR prescale divider.
Definition at line 22 of file timer_hal.c.
Function Documentation
int clock_getres (clockid_t clk_id, struct timespec * res)
Read clock time resolution into struct timepec *ts - POSIX function.
Note: We ignore clk_id, and include low level counter offsets when available.
Parameters
in clk_id unused hardware clock index.
out res timespec resolution result.
Returns
0 on success.
-1 on error.
Definition at line 141 of file timer_hal.c.
Referenced by main().
int clock_gettime (clockid_t clk_id, struct timespec * ts)
Read clock time into struct timepec *ts - POSIX function.
Note: We ignore clk_id, and include low level counter offsets when available.
Parameters
in clk_id unused hardware clock index.
out ts timespec result.
Returns
0 on success.
-1 on error.
note: counter2 < count1 implies ISR flag must be set
Definition at line 82 of file timer_hal.c.
Referenced by clock_elapsed_begin(), clock_elapsed_end(), display_time(), gettimeofday(), printer_open(), and time().
ISR (TIMER1_COMPA_vect)
AVR Timer Interrupt Vector.
calls execute_timers() - we call this the System task.
Definition at line 45 of file timer_hal.c.
void setup_timers_isr (void)
Setup main timers ISR - this ISR calls execute_timers() task.
Notes:
We attempt to use the largest reload count for a given SYSTEM_HZ interrupt rate. This permits using hardware counter offset to increase resolution to the best possible amount.
Assumptions:
We can divide the CPU frequency EXACTLY with timer/counter having no fractional remander.
See Also
ISR().
Returns
void.
Definition at line 60 of file timer_hal.c.
Referenced by init_timers().
Variable Documentation
volatile ts_t __clock
System Clock Time.
Definition at line 24 of file time.c.