lib/time.c File Reference
POSIX time libraries for AVR8.
#include <hardware/cpu.h>
*
#include <stdio.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include <lib/timer_hal.h>
*
#include <lib/time.h>
*
Macros
#define HAVE_HIRES_TIMER /*< We can read a high resolution hardware timer */
Functions
void clock_task ()
Clock task with nanonsecond resolution.
void clock_clear ()
clear time and timezone to 0.
char * tm_wday_to_ascii (int i)
Get string Short name of day from day number.
char * tm_mon_to_ascii (int i)
Get string Short name of Month from month number.
static int IS_Leap (int year)
Check if a year is a leap year.
static int Leap_Days_Since_1900 (int year)
Number of leap days since 1900 to the BEGINNING of the year.
static int Days_Per_Year (int year)
Find number of days in a given year.
int time_to_tm (time_t epoch, int32_t offset, tm_t *t)
Converts epoch (seconds from 1 Jan EPOCH_YEAR UTC), offset seconds, to UNIX tm *t.
time_t timegm (tm_t *t)
Convert tm_t structure as GMT time into seconds since 1900.
char * asctime_r (tm_t *t, char *buf)
Convert tm_t *t structure into POSIX asctime() ASCII string *buf.
char * asctime (tm_t *t)
Convert tm_t *t structure into POSIX asctime() ASCII string.
char * ctime_r (time_t *t, char *buf)
Convert local time_t *t epoch time into POSIX asctime() ASCII string *buf.
char * ctime (time_t *tp)
Convert local time_t *t epoch time into POSIX asctime() string __ctime_buf[].
char * ctime_gm (time_t *tp)
GMT version of POSIX ctime().
tm_t * gmtime_r (time_t *tp, tm_t *result)
Convert epoch GMT time_t *tp into POSIX tm_t *result.
tm_t * gmtime (time_t *tp)
Convert epoch GMT time_t *tp into POSIX static tm_t *t.
tm_t * localtime_r (time_t *t, tm_t *result)
Convert POSIX epoch time_t *tp into POSIX tm_t *result.
tm_t * localtime (time_t *tp)
Convert POSIX epoch time_t *tp into POSIX tm_t *result.
time_t mktime (tm_t *t)
Convert POSIX tm_t *t struct into POSIX epoch time in seconds with UTC offset adjustment.
int clock_settime (clockid_t clk_id, const struct timespec *tp)
Set system clock using seconds and nonoseconds - POSIX function.
int gettimezone (tz_t *tz)
Get current timezone in struct timezone *tz - POSIX function.
int settimezone (tz_t *tz)
Set current timezone with struct timezone *tz - POSIX function.
int gettimeofday (tv_t *tv, tz_t *tz)
Get current time struct timeval *tv and struct timezone *tz - POSIX function.
time_t time (time_t *t)
Return second from epoch - POSIX function.
int settimeofday (tv_t *tv, tz_t *tz)
Set current time struct timeval *tv and struct timezone *tz - POSIX function.
void clock_set (uint32_t seconds, uint32_t us)
Set system clock with seconds and microseconds.
int setdate (void)
Set date and time by prompting user.
int setdate_r (char *buf)
Set date and time from string in this format `YYYY MM DD HH:MM:SS`.
Variables
volatile ts_t __clock
System Clock Time.
tz_t __tzone
System Time Zone.
static const uint16_t __days_sum []
accumulated days to the start of a month in a year.
static const uint16_t __days []
days in each month.
const char * __WDay [] = { `Sun`,`Mon`,`Tue`,`Wed`,`Thu`,`Fri`,`Sat`,`BAD`}
Short Name of each Day in a week.
const char * __Month []
Short Name or each Month in a year.
static char __ctime_buf [32]
String storage for asctime().
Detailed Description
POSIX time libraries for AVR8.
Edit History
[1.0] [Mike Gore] Initial revision of file.
Copyright 2014 Mike Gore, Inc. All rights reserved.
Definition in file time.c.
Macro Definition Documentation
#define HAVE_HIRES_TIMER /*< We can read a high resolution hardware timer */
Definition at line 18 of file time.c.
Function Documentation
char* asctime (tm_t * t)
Convert tm_t *t structure into POSIX asctime() ASCII string.
Parameters
in t struct tm * time input.
Returns
__ctime_buf[] string pointer in POSIX asctime() format.
Example output: `Thu Dec 8 21:45:05 EST 2011`.
Warning
result is overwritten on each call.
Definition at line 431 of file time.c.
Referenced by display_time().
char* asctime_r (tm_t * t, char * buf)
Convert tm_t *t structure into POSIX asctime() ASCII string *buf.
Todo
Todo implement strftime() and strptime()
Parameters
in t tm_t structure pointer.
out buf user buffer for POSIX asctime() string result.
Example output: `Thu Dec 8 21:45:05 EST 2011`.
Returns
buf string pointer.
Definition at line 406 of file time.c.
Referenced by asctime(), ctime(), ctime_gm(), and ctime_r().
void clock_clear (void)
clear time and timezone to 0.
See Also
clock_settime().
settimezone().
Returns
void.
Definition at line 93 of file time.c.
Referenced by init_timers(), and main().
void clock_set (uint32_t seconds, uint32_t us)
Set system clock with seconds and microseconds.
Note: Alternate clock functions.
Returns
void.
See Also
clock_settime().
Definition at line 672 of file time.c.
int clock_settime (clockid_t clk_id, const struct timespec * tp)
Set system clock using seconds and nonoseconds - POSIX function.
Parameters
in clk_id Hardware timer index used when there are more then one.
Note: We ignore clk_id for now.
in tp struct timespec input.
Returns
0.
Definition at line 571 of file time.c.
Referenced by clock_set(), setdate_r(), settimeofday(), and setup_clock().
void clock_task (void)
Clock task with nanonsecond resolution.
Notes: CLOCK_TIC_NS computed from SYSTEM_HZ.
Returns
void.
See Also
execute_timers().
Definition at line 34 of file time.c.
Referenced by init_timers().
char* ctime (time_t * tp)
Convert local time_t *t epoch time into POSIX asctime() string __ctime_buf[].
Parameters
in tp time_t * time input.
Returns
__ctime_buf[].
Example: `Thu Dec 8 21:45:05 EST 2011`.
Definition at line 456 of file time.c.
char* ctime_gm (time_t * tp)
GMT version of POSIX ctime().
Parameters
in tp time_t * time input.
Returns
__ctime_buf[].
Example: `Thu Dec 8 21:45:05 EST 2011`.
See Also
ctime()
Warning
result is overwritten on each call.
Definition at line 470 of file time.c.
Referenced by mctime().
char* ctime_r (time_t * t, char * buf)
Convert local time_t *t epoch time into POSIX asctime() ASCII string *buf.
Parameters
in t time_t * time input.
out buf string output.
Example output: `Thu Dec 8 21:45:05 EST 2011`
Returns
buf string pointer.
Definition at line 444 of file time.c.
static int Days_Per_Year (int year) [static]
Find number of days in a given year.
Parameters
in year valid over 1900..2199.
Warning
No limit checking
Returns
days in a given year.
See Also
time_to_tm()
ctime_gm()
gmtime_r()
localtime_r()
Definition at line 239 of file time.c.
Referenced by time_to_tm().
int gettimeofday (tv_t * tv, tz_t * tz)
Get current time struct timeval *tv and struct timezone *tz - POSIX function.
Parameters
in tv time.
in tz timezone.
Returns
0
Definition at line 615 of file time.c.
int gettimezone (tz_t * tz)
Get current timezone in struct timezone *tz - POSIX function.
Parameters
out tz timezone result.
Returns
0
Definition at line 588 of file time.c.
Referenced by gettimeofday(), localtime_r(), and mktime().
tm_t* gmtime (time_t * tp)
Convert epoch GMT time_t *tp into POSIX static tm_t *t.
Parameters
in tp time_t * time input.
Returns
tm_t t.
Warning
result is overwritten on each call.
Definition at line 500 of file time.c.
Referenced by display_time(), printer_open(), and rtc_init().
tm_t* gmtime_r (time_t * tp, tm_t * result)
Convert epoch GMT time_t *tp into POSIX tm_t *result.
Parameters
in tp time_t * time input.
out result tm_t *result.
Returns
tm_t *result.
Definition at line 485 of file time.c.
Referenced by gmtime().
static int IS_Leap (int year) [static]
Check if a year is a leap year.
Parameters
in year valid over 1900..2199.
Warning
: No limit checking.
Returns
1 (leap year), 0 (not a leap year(
See Also
time_to_tm()
ctime_gm()
gmtime_r()
localtime_r()
Returns
return
Definition at line 182 of file time.c.
Referenced by Days_Per_Year(), time_to_tm(), and timegm().
static int Leap_Days_Since_1900 (int year) [static]
Number of leap days since 1900 to the BEGINNING of the year.
Parameters
in year valid over 1900..2199.
Warning
No limit checking
Returns
days.
See Also
time_to_tm()
ctime_gm()
gmtime_r()
localtime_r()
Definition at line 208 of file time.c.
Referenced by timegm().
tm_t* localtime (time_t * tp)
Convert POSIX epoch time_t *tp into POSIX tm_t *result.
Parameters
in tp time_t * epoch time input.
Returns
struct tm result.
Warning
result is overwritten on each call.
Definition at line 535 of file time.c.
Referenced by ctime(), and ctime_r().
tm_t* localtime_r (time_t * t, tm_t * result)
Convert POSIX epoch time_t *tp into POSIX tm_t *result.
Parameters
in t time_t * epoch time input.
out result tm_t *result.
Returns
result.
Definition at line 514 of file time.c.
Referenced by localtime().
time_t mktime (tm_t * t)
Convert POSIX tm_t *t struct into POSIX epoch time in seconds with UTC offset adjustment.
Parameters
in t time_t * epoch time input.
Definition at line 547 of file time.c.
int setdate (void)
Set date and time by prompting user.
Prompt use for Date Time input with `YYYY MM DD HH:MM:SS>`
Input format is: `YYYY MM DD HH:MM:SS`
Returns
0 on success.
-1 on error>
Definition at line 690 of file time.c.
Referenced by task().
int setdate_r (char * buf)
Set date and time from string in this format `YYYY MM DD HH:MM:SS`.
Parameters
in buf Date string in this format `YYYY MM DD HH:MM:SS`.
Returns
0 on success.
(-1) on error.
Definition at line 708 of file time.c.
Referenced by setdate().
int settimeofday (tv_t * tv, tz_t * tz)
Set current time struct timeval *tv and struct timezone *tz - POSIX function.
Parameters
in tv time.
in tz timezone.
Returns
0
Definition at line 652 of file time.c.
int settimezone (tz_t * tz)
Set current timezone with struct timezone *tz - POSIX function.
Parameters
in tz timezone result.
Returns
0.
Definition at line 601 of file time.c.
Referenced by settimeofday(), and setup_clock().
time_t time (time_t * t)
Return second from epoch - POSIX function.
Parameters
in,out t pointer to store time in.
Notes: If t is non-NULL, store the return value there also.
Returns
time_t seconds from epoch.
See Also
clock_gettime().
Definition at line 636 of file time.c.
Referenced by gpib_timeout_set().
int time_to_tm (time_t epoch, int32_t offset, tm_t * t)
Converts epoch (seconds from 1 Jan EPOCH_YEAR UTC), offset seconds, to UNIX tm *t.
Parameters
in epoch Seconds elapsed since January 1, EPOCH_YEAR.
unsigned long, range limited to: 0 .. 0xFFFD5D00>
The range 0xFFFEAE80 .. 0xFFFFFFFF is reserverd for Dec 31, 1969.
The range 0xFFFD5D00 .. 0xFFFEAE7F is reserverd of offset overflow.
in offset Offset in seconds to localtime.
long int, range limited to +/- 86400.
(Number of seconds that we add to UTC to get local time).
out t Unix tm struct pointer output.
Returns
0: *t has result.
-1: error.
See Also
ctime_gm()
gmtime_r()
localtime_r()
Definition at line 262 of file time.c.
Referenced by ctime_gm(), gmtime_r(), and localtime_r().
time_t timegm (tm_t * t)
Convert tm_t structure as GMT time into seconds since 1900.
Standards: GNU and BSD.
Limits: year(1900..2199).
Assume: epoch size is uint32_t time_t;
See Also
mktime() POSIX function.
timegm() POSIX function.
Returns
Seconds since EPOCH_YEAR Jan 1st.
-1 on error.
Note: To simplify we caculate Leap Day contributions in stages
Definition at line 344 of file time.c.
Referenced by display_time(), fat_time_to_unix(), mktime(), setdate_r(), and setup_clock().
char* tm_mon_to_ascii (int i)
Get string Short name of Month from month number.
Parameters
in i Month 0 .. 11 to string.
Returns
string pointer to month.
`BAD` on error.
See Also
asctime_r()
Definition at line 162 of file time.c.
Referenced by printer_open().
char* tm_wday_to_ascii (int i)
Get string Short name of day from day number.
Parameters
in i Day 0 .. 6.
Returns
string pointer to day.
`BAD` on error.
Definition at line 136 of file time.c.
Variable Documentation
volatile ts_t __clock
System Clock Time.
Definition at line 24 of file time.c.
char __ctime_buf[32] [static]
String storage for asctime().
Definition at line 422 of file time.c.
const uint16_t __days[] [static]
Initial value:
=
{
    31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31
}
days in each month.
without leap days.
Index: Month 00 .. 11.
See Also
timegm().
Definition at line 118 of file time.c.
const uint16_t __days_sum[] [static]
Initial value:
=
{
    0, 31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334, 365
}
accumulated days to the start of a month in a year.
without Leap days.
Index: Month 00 .. 11 (12 is a year).
See Also
timegm().
Definition at line 109 of file time.c.
const char* __Month[]
Initial value:
=
{
    "Jan","Feb","Mar","Apr","May","Jun","Jul",
        "Aug","Sep","Oct","Nov","Dec","BAD"
}
Short Name or each Month in a year.
Month 0 .. 11 to string.
Definition at line 149 of file time.c.
tz_t __tzone
System Time Zone.
Definition at line 27 of file time.c.
const char* __WDay[] = { `Sun`,`Mon`,`Tue`,`Wed`,`Thu`,`Fri`,`Sat`,`BAD`}
Short Name of each Day in a week.
Day 0 .. 6 to string.
See Also
asctime_r()
Definition at line 128 of file time.c.