lib/timer_hal.h File Reference
timer hardware abstartion layer functions
#include <hardware/hardware.h>
*
#include `timer.h`
*
#include `time.h`
*
Macros
#define HAVE_HIRES_TIMER /*< We can read a high resolution hardware timer */
#define TIMER1_PRESCALE 1L
AVR prescale divider.
#define TIMER1_COUNTS_PER_TIC (F_CPU/TIMER1_PRESCALE/SYSTEM_TASK_HZ)
Computer AVR counts per interrupt.
#define TIMER1_COUNTER_RES (SYSTEM_TASK_TIC_NS/TIMER1_COUNTS_PER_TIC)
Computer AVR count time in Nanoseconds per counter increment.
#define TIMER1_PRE_1 (1 << CS10) /*< 1 Prescale */
#define TIMER1_PRE_8 (1 << CS11) /*< 8 Prescale */
#define TIMER1_PRE_64 ((1 << CS11) | (1 << CS10)) /*< 64 Prescale */
#define TIMER1_PRE_256 (1 << CS12) /*< 256 Prescale */
#define TIMER1_PRE_1024 ((1 << CS12) | (1 << CS10)) /*< 1024 Prescape */
Functions
MEMSPACE void clock_clear (void)
clear time and timezone to 0.
MEMSPACE void disable_timers (void)
Disable all timer tasks.
MEMSPACE void enable_timers (void)
Enable timer tasks.
void execute_timers (void)
Execute all user timers at SYSTEM_HZ rate.
MEMSPACE void clock_init (void)
Initialize clock task.
void clock_task (void)
1000HZ timer task
MEMSPACE void init_timers (void)
Setup all timers tasksi and enable interrupts.
MEMSPACE int clock_getres (clockid_t clk_id, struct timespec *res)
Read clock time resolution into struct timepec *ts - POSIX function.
MEMSPACE int clock_settime (clockid_t clk_id, const struct timespec *ts)
Set system clock using seconds and nonoseconds - POSIX function.
MEMSPACE void setup_timers_isr (void)
Setup main timers ISR - this ISR calls execute_timers() task.
MEMSPACE int clock_gettime (clockid_t clk_id, struct timespec *ts)
Generic clock_gettime() function WITHOUT high resolution.
Detailed Description
timer hardware abstartion layer functions
Copyright 2015 Mike Gore, GPL License
You are free to use this code under the terms of GPL
please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition in file timer_hal.h.
Macro Definition Documentation
#define HAVE_HIRES_TIMER /*< We can read a high resolution hardware timer */
Definition at line 33 of file timer_hal.h.
#define TIMER1_COUNTER_RES (SYSTEM_TASK_TIC_NS/TIMER1_COUNTS_PER_TIC)
Computer AVR count time in Nanoseconds per counter increment.
Definition at line 43 of file timer_hal.h.
#define TIMER1_COUNTS_PER_TIC (F_CPU/TIMER1_PRESCALE/SYSTEM_TASK_HZ)
Computer AVR counts per interrupt.
Definition at line 40 of file timer_hal.h.
Referenced by setup_timers_isr().
#define TIMER1_PRE_1 (1 << CS10) /*< 1 Prescale */
Definition at line 49 of file timer_hal.h.
Referenced by setup_timers_isr().
#define TIMER1_PRE_1024 ((1 << CS12) | (1 << CS10)) /*< 1024 Prescape */
Definition at line 53 of file timer_hal.h.
#define TIMER1_PRE_256 (1 << CS12) /*< 256 Prescale */
Definition at line 52 of file timer_hal.h.
#define TIMER1_PRE_64 ((1 << CS11) | (1 << CS10)) /*< 64 Prescale */
Definition at line 51 of file timer_hal.h.
#define TIMER1_PRE_8 (1 << CS11) /*< 8 Prescale */
Definition at line 50 of file timer_hal.h.
#define TIMER1_PRESCALE 1L
AVR prescale divider.
Definition at line 36 of file timer_hal.h.
Function Documentation
MEMSPACE void clock_clear (void)
clear time and timezone to 0.
See Also
clock_settime().
settimezone().
Returns
void.
Definition at line 50 of file timer_hal.c.
Referenced by clock_init(), and main().
MEMSPACE int clock_getres (clockid_t clk_id, struct timespec * res)
Read clock time resolution into struct timepec *ts - POSIX function.
Note: We ignore clk_id
Parameters
in clk_id unused hardware clock index.
out res timespec resolution result.
Returns
0 on success.
-1 on error.
Definition at line 172 of file timer_hal.c.
Referenced by main().
MEMSPACE int clock_gettime (clockid_t clk_id, struct timespec * ts)
Generic clock_gettime() function WITHOUT high resolution.
Read clock time into struct timepec *ts - POSIX function.
Note: We ignore clk_id, and include low level counter offsets when available.
Parameters
in clk_id unused hardware clock index.
out ts timespec result.
Returns
0 on success.
-1 on error.
Definition at line 313 of file timer_hal.c.
Referenced by clock_elapsed_begin(), clock_elapsed_end(), display_time(), gettimeofday(), printer_open(), and time().
MEMSPACE void clock_init (void)
Initialize clock task.
Returns
void.
See time.c
Definition at line 103 of file timer_hal.c.
Referenced by init_timers().
MEMSPACE int clock_settime (clockid_t clk_id, const struct timespec * ts)
Set system clock using seconds and nonoseconds - POSIX function.
Parameters
in clk_id Hardware timer index used when there are more then one.
Note: We ignore clk_id for now.
in tp struct timespec input.
Returns
0.
Definition at line 188 of file timer_hal.c.
Referenced by clock_clear().
void clock_task (void)
1000HZ timer task
Parameters
in *arg ignored
Returns
void
Definition at line 116 of file timer_hal.c.
Referenced by clock_init(), and init_timers().
MEMSPACE void disable_timers (void)
Disable all timer tasks.
Returns
void
Definition at line 64 of file timer_hal.c.
MEMSPACE void enable_timers (void)
Enable timer tasks.
Returns
void
Definition at line 77 of file timer_hal.c.
Referenced by init_timers().
void execute_timers (void)
Execute all user timers at SYSTEM_HZ rate.
Returns
void
Definition at line 88 of file timer_hal.c.
Referenced by ISR().
MEMSPACE void init_timers (void)
Setup all timers tasksi and enable interrupts.
See Also
clock_task()
: timer_hal.c for hardware dependent interface
Returns
void
See time.c
See time.c
Definition at line 133 of file timer_hal.c.
Referenced by main().
MEMSPACE void setup_timers_isr (void)
Setup main timers ISR - this ISR calls execute_timers() task.
Notes:
We attempt to use the largest reload count for a given SYSTEM_HZ interrupt rate. This permits using hardware counter offset to increase resolution to the best possible amount.
Assumptions:
We can divide the CPU frequency EXACTLY with timer/counter having no fractional remander.
See Also
ISR().
Returns
void.
Definition at line 228 of file timer_hal.c.
Referenced by init_timers().