lib/time.h File Reference
Common Linux/POSIX time functions.
Data Structures
struct tm
POSIX struct tm.
struct timeval
POSIX timeval.
struct timezone
POSIX timezone.
struct timespec
POSIX timespec.
struct dst_t
DST structure.
Macros
#define EPOCH_YEAR 1970 /*< Thursday Jan 1 1970 */
#define EPOCH_DAY 4 /*< Sunday = 0 ... Saturday = 6 */
#define EPOCH 0 /*< Zero seconds */
#define EPOCH_2000 946684800 /*< Sat, 01 Jan 2000 00:00:00 GMT */
Typedefs
typedef uint32_t time_t
type of EPOCH result.
typedef uint16_t clockid_t
type of clockid_t.
typedef struct tm tm_t
POSIX struct tm typedef.
typedef struct timeval tv_t
POSIX timeval typedef.
typedef struct timezone tz_t
POSIX timezone typedef.
typedef struct timespec ts_t
POSIX timespec typedef.
Functions
MEMSPACE char * tm_wday_to_ascii (int i)
Get string Short name of day from day number.
MEMSPACE char * tm_mon_to_ascii (int i)
Get string Short name of Month from month number.
MEMSPACE int finddayofweek (int year, int month, int day)
return day of week for givenn day, month, year
MEMSPACE int Days_Per_Month (int month, int year)
days in a month
MEMSPACE time_t time_to_tm (time_t epoch, int32_t offset, tm_t *t)
Converts epoch (seconds from 1 Jan EPOCH_YEAR UTC), offset seconds, to UNIX tm *t.
MEMSPACE time_t timegm (tm_t *t)
Convert tm_t structure as GMT time into GMT seconds since 1900. All calculactions are in GMT regardless of timezoe settings.
MEMSPACE char * asctime_r (tm_t *t, char *buf)
Convert tm_t *t structure into POSIX asctime() ASCII string *buf.
MEMSPACE char * asctime (tm_t *t)
Convert tm_t *t structure into POSIX asctime() ASCII string.
MEMSPACE char * ctime_r (time_t *t, char *buf)
Convert local time_t *t epoch time into POSIX asctime() ASCII string *buf.
MEMSPACE char * ctime (time_t *tp)
Convert local time_t *t epoch time into POSIX asctime() string buf[].
MEMSPACE char * ctime_gm (time_t *tp)
GMT version of POSIX ctime().
MEMSPACE tm_t * gmtime_r (time_t *t, tm_t *result)
Convert epoch GMT time_t *tp into POSIX tm_t *result.
MEMSPACE tm_t * gmtime (time_t *tp)
Convert epoch GMT time_t *tp into POSIX static tm_t *t.
MEMSPACE tm_t * localtime_r (time_t *t, tm_t *result)
Convert POSIX epoch time_t *tp into POSIX tm_t *result expressed as local time using timezone and DST corrections.
MEMSPACE tm_t * localtime (time_t *tp)
Convert POSIX epoch time_t *tp into POSIX tm_t *result.
MEMSPACE time_t mktime (tm_t *t)
convert tm_t structure to time_t local time epoch
MEMSPACE time_t normalize (tm_t *t, int normalize_to_timezone)
Normalize POSIX tm_t *t struct and convert to epoch time Note: does not deal with DST - by design.
MEMSPACE int gettimezone (tz_t *tz)
Get current timezone in struct timezone *tz - POSIX function.
MEMSPACE int settimezone (tz_t *tz)
Set current timezone with struct timezone *tz - POSIX function.
MEMSPACE int gettimeofday (tv_t *tv, tz_t *tz)
Get current time struct timeval *tv and struct timezone *tz - POSIX function. We assume a GMT hardware clock.
MEMSPACE time_t time (time_t *t)
Return second from epoch - POSIX function.
MEMSPACE int settimeofday (tv_t *tv, tz_t *tz)
Set current time struct timeval *tv and struct timezone *tz - POSIX function. We assume a GMT hardware clock.
MEMSPACE void clock_set (uint32_t seconds, uint32_t us)
Set system clock with seconds and microseconds.
MEMSPACE int setdate (void)
Set date and time by prompting user.
MEMSPACE int setdate_r (char *buf)
Set date and time from string in this format `YYYY MM DD HH:MM:SS`.
MEMSPACE time_t find_dst (int dst, time_t epoch, int year, int month, int weekno, int dayno, int hour)
Calculate GMT seconds of DST transition given LOCAL time start / end time and DST flag.
MEMSPACE void set_dst (time_t epoch)
Set DST start and end time for the given epoch year.
MEMSPACE int is_dst (time_t epoch)
Test GMT epoch time to see if DST applies in a local timezone.
MEMSPACE void print_dst (void)
print start/stop for DST as localtime for this year
MEMSPACE void print_dst_gmt (void)
print start/stop for DST as GMT for this year
MEMSPACE void initialize_clock (int minwest)
initialize system time - if we have an RTC use it
MEMSPACE void display_clock (void)
Display system time and optionally RTC time.
Variables
volatile ts_t __clock
System Clock Time.
tz_t __tzone
System Time Zone.
Detailed Description
Common Linux/POSIX time functions.
Copyright 2015 Mike Gore, GPL License
You are free to use this code under the terms of GPL
please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Macro Definition Documentation
EPOCH
#define EPOCH 0 /*< Zero seconds */
Definition at line 30 of file time.h.
EPOCH_2000
#define EPOCH_2000 946684800 /*< Sat, 01 Jan 2000 00:00:00 GMT */
Definition at line 31 of file time.h.
EPOCH_DAY
#define EPOCH_DAY 4 /*< Sunday = 0 ... Saturday = 6 */
Definition at line 29 of file time.h.
Referenced by time_to_tm().
EPOCH_YEAR
#define EPOCH_YEAR 1970 /*< Thursday Jan 1 1970 */
Definition at line 28 of file time.h.
Referenced by time_to_tm(), timetests(), and tm2epoch().
Typedef Documentation
clockid_t
typedef uint16_t clockid_t
type of clockid_t.
Definition at line 37 of file time.h.
time_t
typedef uint32_t time_t
type of EPOCH result.
Definition at line 34 of file time.h.
tm_t
typedef struct tm tm_t
POSIX struct tm typedef.
tm_isdst value notes 1 DST in effect - add an hour 0 DST not in effect -1 DST Unknown status
Definition at line 62 of file time.h.
ts_t
typedef struct timespec ts_t
POSIX timespec typedef.
Definition at line 92 of file time.h.
tv_t
typedef struct timeval tv_t
POSIX timeval typedef.
Definition at line 72 of file time.h.
tz_t
typedef struct timezone tz_t
POSIX timezone typedef.
Definition at line 82 of file time.h.
Function Documentation
asctime()
MEMSPACE char* asctime (tm_t * t)
Convert tm_t *t structure into POSIX asctime() ASCII string.
Parameters
in t struct tm * time input.
Returns
buf[] string pointer in POSIX asctime() format.
Example output: `Thu Dec 8 21:45:05 EST 2011`.
Warning
result is overwritten on each call.
Definition at line 394 of file time.c.
Referenced by display_clock().
asctime_r()
MEMSPACE char* asctime_r (tm_t * t, char * buf)
Convert tm_t *t structure into POSIX asctime() ASCII string *buf.
Todo
Todo implement strftime() and strptime()
Parameters
in t tm_t structure pointer.
out buf user buffer for POSIX asctime() string result.
Example output: `Thu Dec 8 21:45:05 EST 2011`.
Returns
buf string pointer.
Definition at line 368 of file time.c.
Referenced by asctime(), ctime(), ctime_gm(), ctime_r(), lif_ctime_gmt(), td0_open(), and timetests().
clock_set()
MEMSPACE void clock_set (uint32_t seconds, uint32_t us)
Set system clock with seconds and microseconds.
Note: Alternate clock functions.
Returns
void.
See also
clock_settime().
Definition at line 882 of file time.c.
ctime()
MEMSPACE char* ctime (time_t * tp)
Convert local time_t *t epoch time into POSIX asctime() string buf[].
Parameters
in tp time_t * time input.
Returns
buf[].
Example: `Thu Dec 8 21:45:05 EST 2011`.
Definition at line 424 of file time.c.
Referenced by print_dst().
ctime_gm()
MEMSPACE char* ctime_gm (time_t * tp)
GMT version of POSIX ctime().
Parameters
in tp time_t * time input.
Returns
buf[].
Example: `Thu Dec 8 21:45:05 EST 2011`.
See also
ctime()
Warning
result is overwritten on each call.
Definition at line 441 of file time.c.
Referenced by mctime(), and print_dst_gmt().
ctime_r()
MEMSPACE char* ctime_r (time_t * t, char * buf)
Convert local time_t *t epoch time into POSIX asctime() ASCII string *buf.
Parameters
in t time_t * time input.
out buf string output.
Example output: `Thu Dec 8 21:45:05 EST 2011`
Returns
buf string pointer.
Definition at line 410 of file time.c.
Days_Per_Month()
MEMSPACE int Days_Per_Month (int month, int year)
days in a month
Parameters
in month; month of year
in year; year
Returns
days in month including yeapyears
Definition at line 223 of file time.c.
Referenced by normalize(), and tm2epoch().
display_clock()
MEMSPACE void display_clock (void)
Display system time and optionally RTC time.
Returns
void
See also
: rtc_read
: timegm()
: ascitime()
Definition at line 1234 of file time.c.
Referenced by main(), and user_task().
find_dst()
MEMSPACE time_t find_dst (int dst, time_t epoch, int year, int month, int weekno, int dayno, int hour)
Calculate GMT seconds of DST transition given LOCAL time start / end time and DST flag.
Parameters
in dst 0 .. 1 DST needs to be applied to the arguments for DST caluclulations
in epoch 0 | epoch if non-zero - UTC epoch time used to obtain year of DST calculations
in year 0 | year if non-zero - UTC year of DST calcululation, if year and epoch are used - ignore epoch
in month 0 .. 11, local time month DST transition
in weekno 1 .. 4 localtime dayno count in this month
in dayno 0 .. 6, localtime day of DST transition, 0 = Sunday
in hour 0 .. 23 local time hour of DST transition result is in epoch GMT seconds Example: Eastern Time and Daylight Savings time time_t epoch,start,end; tv_t tv; tv_t tz; gettimeofday(&tv, &tz); epoch = tv.tv_sec; // DST start for this year, 2nd Sunday of Mar at 2:00am EST start = find_dst(0, epoch, 0, 3, 2, 0, 2); // DST start on 2016, 2nd Sunday of Mar at 2:00am EST start = find_dst(0, 0, 2016, 3, 2, 0, 2); // DST ends on for this year, 1st Sunday of Nov at 2:00am DST end = find_dst(1, epoch, 0, 11, 1, 0, 2); // DST ends on 2016, 1st Sunday of Nov at 2:00am DST end = find_dst(1, 0, 2016, 11, 1, 0, 2);
Definition at line 1040 of file time.c.
Referenced by set_dst().
finddayofweek()
MEMSPACE int finddayofweek (int year, int month, int day)
return day of week for givenn day, month, year
Parameters
in year year such as 2016
in month month 0 .. 11
in day day 1 .. 28|29|30|31 result is day of week 0 .. 6, 0 = Sunday
Definition at line 180 of file time.c.
gettimeofday()
MEMSPACE int gettimeofday (tv_t * tv, tz_t * tz)
Get current time struct timeval *tv and struct timezone *tz - POSIX function. We assume a GMT hardware clock.
Parameters
in tv time.
in tz timezone.
Returns
0
Definition at line 822 of file time.c.
Referenced by find_dst(), set_dst(), and timetests().
gettimezone()
MEMSPACE int gettimezone (tz_t * tz)
Get current timezone in struct timezone *tz - POSIX function.
Parameters
out tz timezone result.
Returns
0
Definition at line 792 of file time.c.
Referenced by gettimeofday(), localtime_r(), and normalize().
gmtime()
MEMSPACE tm_t* gmtime (time_t * tp)
Convert epoch GMT time_t *tp into POSIX static tm_t *t.
Parameters
in tp time_t * time input.
Returns
tm_t t.
Warning
result is overwritten on each call.
Definition at line 471 of file time.c.
Referenced by display_clock(), printer_open(), rtc_init(), and unix_time_to_fat().
gmtime_r()
MEMSPACE tm_t* gmtime_r (time_t * t, tm_t * result)
Convert epoch GMT time_t *tp into POSIX tm_t *result.
Parameters
in tp time_t * time input.
out result tm_t *result.
Returns
tm_t *result.
Definition at line 456 of file time.c.
Referenced by ctime_gm(), gmtime(), lif_ctime_gmt(), and lif_time2lifbcd().
initialize_clock()
MEMSPACE void initialize_clock (int minwest)
initialize system time - if we have an RTC use it
Parameters
in minwest your time zone as minute west
Returns
void
See also
: clock_settime()
Definition at line 1184 of file time.c.
Referenced by main().
is_dst()
MEMSPACE int is_dst (time_t epoch)
Test GMT epoch time to see if DST applies in a local timezone.
Parameters
in epoch seconds in GMT normalize() return 1 if yes, 0 if not
Definition at line 1150 of file time.c.
Referenced by localtime_r(), and normalize().
localtime()
MEMSPACE tm_t* localtime (time_t * tp)
Convert POSIX epoch time_t *tp into POSIX tm_t *result.
Parameters
in tp time_t * epoch time input.
Returns
struct tm result.
Warning
result is overwritten on each call.
Definition at line 522 of file time.c.
Referenced by ctime(), ctime_r(), and get_fattime().
localtime_r()
MEMSPACE tm_t* localtime_r (time_t * t, tm_t * result)
Convert POSIX epoch time_t *tp into POSIX tm_t *result expressed as local time using timezone and DST corrections.
Parameters
in t time_t * epoch time input.
out result tm_t *result.
Returns
result.
Definition at line 498 of file time.c.
Referenced by localtime(), and timetests().
mktime()
MEMSPACE time_t mktime (tm_t * t)
convert tm_t structure to time_t local time epoch
Parameters
in t tm_t time input.
Returns
local epoch or -1 on failure out of range
Definition at line 535 of file time.c.
Referenced by timetests().
normalize()
MEMSPACE time_t normalize (tm_t * t, int normalize_to_timezone)
Normalize POSIX tm_t *t struct and convert to epoch time Note: does not deal with DST - by design.
Parameters
in t tm_t time input.
in normalize_to_timezone nonzero = adjust to local timezone and DST
Returns
epoch since 1900 on sucess, -1 on failure out of range
Definition at line 655 of file time.c.
Referenced by asctime_r(), mktime(), and timegm().
print_dst()
MEMSPACE void print_dst (void)
print start/stop for DST as localtime for this year
Definition at line 1162 of file time.c.
print_dst_gmt()
MEMSPACE void print_dst_gmt (void)
print start/stop for DST as GMT for this year
Definition at line 1171 of file time.c.
set_dst()
MEMSPACE void set_dst (time_t epoch)
Set DST start and end time for the given epoch year.
Parameters
in 0 - or epoch seconds in GMT used to determin the year to aply DST in If 0 we get local GMT epoch time in seconds
Definition at line 1115 of file time.c.
Referenced by is_dst().
setdate()
MEMSPACE int setdate (void)
Set date and time by prompting user.
Prompt use for Date Time input with `YYYY MM DD HH:MM:SS>`
Input format is: `YYYY MM DD HH:MM:SS`
Returns
0 on success.
-1 on error>
Definition at line 901 of file time.c.
Referenced by user_task().
setdate_r()
MEMSPACE int setdate_r (char * buf)
Set date and time from string in this format `YYYY MM DD HH:MM:SS`.
Parameters
in buf Date string in this format `YYYY MM DD HH:MM:SS`.
Returns
0 on success.
(-1) on error.
Definition at line 920 of file time.c.
Referenced by setdate().
settimeofday()
MEMSPACE int settimeofday (tv_t * tv, tz_t * tz)
Set current time struct timeval *tv and struct timezone *tz - POSIX function. We assume a GMT hardware clock.
Parameters
in tv time.
in tz timezone.
Returns
0
Definition at line 861 of file time.c.
settimezone()
MEMSPACE int settimezone (tz_t * tz)
Set current timezone with struct timezone *tz - POSIX function.
Parameters
in tz timezone result.
Returns
0.
Definition at line 806 of file time.c.
Referenced by initialize_clock(), and settimeofday().
time()
MEMSPACE time_t time (time_t * t)
Return second from epoch - POSIX function.
Parameters
in,out t pointer to store time in.
Notes: If t is non-NULL, store the return value there also.
Returns
time_t seconds from epoch.
See also
clock_gettime().
Definition at line 843 of file time.c.
Referenced by get_fattime(), gpib_timeout_set(), lif_create_volume(), td0_open(), and utime().
time_to_tm()
MEMSPACE time_t time_to_tm (time_t epoch, int32_t offset, tm_t * t)
Converts epoch (seconds from 1 Jan EPOCH_YEAR UTC), offset seconds, to UNIX tm *t.
Parameters
in epoch Seconds elapsed since January 1, EPOCH_YEAR.
unsigned long, range limited to: 0 .. 0xFFFD5D00>
The range 0xFFFEAE80 .. 0xFFFFFFFF is reserverd for Dec 31, 1969.
The range 0xFFFD5D00 .. 0xFFFEAE7F is reserverd of offset overflow.
in offset Offset in seconds to localtime.
long int, range limited to +/- 86400.
(Number of seconds that we add to UTC to get local time).
out t Unix tm struct pointer output.
Returns
epoch: time in seconds, *t has result.
-1: error.
See also
ctime_gm()
gmtime_r()
localtime_r()
Definition at line 263 of file time.c.
Referenced by find_dst(), gmtime_r(), localtime_r(), and normalize().
timegm()
MEMSPACE time_t timegm (tm_t * t)
Convert tm_t structure as GMT time into GMT seconds since 1900. All calculactions are in GMT regardless of timezoe settings.
Standards: GNU and BSD.
Limits: year(1900..2199).
Assume: epoch size is time_t;
See also
mktime() POSIX function.
timegm() POSIX function.
normalize() and tm2epoch non POSIX functions
Returns
Seconds since EPOCH_YEAR Jan 1st.
-1 on error.
Definition at line 348 of file time.c.
Referenced by display_clock(), fat_time_to_unix(), find_dst(), initialize_clock(), lif_lifbcd2time(), setdate_r(), and td0_open().
tm_mon_to_ascii()
MEMSPACE char* tm_mon_to_ascii (int i)
Get string Short name of Month from month number.
Parameters
in i Month 0 .. 11 to string.
Returns
string pointer to month.
`BAD` on error.
See also
asctime_r()
Definition at line 114 of file time.c.
Referenced by printer_open().
tm_wday_to_ascii()
MEMSPACE char* tm_wday_to_ascii (int i)
Get string Short name of day from day number.
Parameters
in i Day 0 .. 6.
Returns
string pointer to day.
`BAD` on error.
Definition at line 87 of file time.c.
Variable Documentation
__clock
volatile ts_t __clock
System Clock Time.
Definition at line 38 of file timer.c.
__tzone
tz_t __tzone
System Time Zone.
Definition at line 49 of file time.c.