hardware/TWI_AVR8.c File Reference
TWI Peripheral Driver (AVR8)
#include `user_config.h`
Functions
void TWI_Init (const uint8_t Prescale, const uint8_t BitLength)
Initialize I2C device.
static void TWI_Disable (void)
Disable I2C.
void TWI_StopTransmission (void)
Sends a TWI STOP onto the TWI bus, terminating communication with the currently addressed device.
uint8_t TWI_StartTransmission (const uint8_t SlaveAddress, const uint8_t TimeoutMS)
Start I2C transmission.
bool TWI_SendByte (const uint8_t Byte)
TWI send byte.
bool TWI_ReceiveByte (uint8_t *const Byte, const bool LastByte)
uint8_t TWI_ReadPacket (const uint8_t SlaveAddress, const uint8_t TimeoutMS, const uint8_t *InternalAddress, uint8_t InternalAddressLen, uint8_t *Buffer, uint8_t Length)
TWI read packet.
uint8_t TWI_WritePacket (const uint8_t SlaveAddress, const uint8_t TimeoutMS, const uint8_t *InternalAddress, uint8_t InternalAddressLen, const uint8_t *Buffer, uint8_t Length)
TWI write packet.
Detailed Description
TWI Peripheral Driver (AVR8)
On-chip TWI driver for the 8-bit AVR microcontrollers.
Note
This file should not be included directly. It is automatically include d as needed by the TWI driver dispatch header located in LUFA/Drivers/Peripheral/TWI.h.
Function Documentation
TWI_Disable()
static void TWI_Disable (void) [inline], [static]
Disable I2C.
Definition at line 66 of file TWI_AVR8.c.
TWI_Init()
void TWI_Init (const uint8_t Prescale, const uint8_t BitLength)
Initialize I2C device.
Parameters
in Prescale prescale value.
in BitLength Number of bits.
Returns
void.
Definition at line 51 of file TWI_AVR8.c.
TWI_StopTransmission()
void TWI_StopTransmission (void) [inline]
Sends a TWI STOP onto the TWI bus, terminating communication with the currently addressed device.
Definition at line 73 of file TWI_AVR8.c.
Referenced by I2C_Stop(), TWI_ReadPacket(), and TWI_WritePacket().