hardware/TWI_AVR8.h File Reference
TWI Peripheral Driver (AVR8)
#include `user_config.h`
Functions
void TWI_Init (const uint8_t Prescale, const uint8_t BitLength)
Initialize I2C device.
void TWI_StopTransmission (void)
Sends a TWI STOP onto the TWI bus, terminating communication with the currently addressed device.
uint8_t TWI_StartTransmission (const uint8_t SlaveAddress, const uint8_t TimeoutMS)
Start I2C transmission.
bool TWI_SendByte (const uint8_t Byte)
TWI send byte.
bool TWI_ReceiveByte (uint8_t *const Byte, const bool LastByte)
uint8_t TWI_ReadPacket (const uint8_t SlaveAddress, const uint8_t TimeoutMS, const uint8_t *InternalAddress, uint8_t InternalAddressLen, uint8_t *Buffer, uint8_t Length)
TWI read packet.
uint8_t TWI_WritePacket (const uint8_t SlaveAddress, const uint8_t TimeoutMS, const uint8_t *InternalAddress, uint8_t InternalAddressLen, const uint8_t *Buffer, uint8_t Length)
TWI write packet.
Detailed Description
TWI Peripheral Driver (AVR8)
On-chip TWI driver for the 8-bit AVR microcontrollers.
Note
This file should not be included directly. It is automatically included as needed by the TWI driver dispatch header located in LUFA/Drivers/Peripheral/TWI.h.
Function Documentation
TWI_Init()
void TWI_Init (const uint8_t Prescale, const uint8_t BitLength)
Initialize I2C device.
Parameters
in Prescale prescale value.
in BitLength Number of bits.
Returns
void.
Definition at line 53 of file TWI_AVR8.c.
Referenced by main(), and rtc_init().
TWI_ReadPacket()
uint8_t TWI_ReadPacket (const uint8_t SlaveAddress, const uint8_t TimeoutMS, const uint8_t * InternalAddress, uint8_t InternalAddressLen, uint8_t * Buffer, uint8_t Length)
TWI read packet.
Parameters
in SlaveAddress TWI sleave address.
in TimeoutMS Timeout in Milliseconds.
in InternalAddress Our Address.
in InternalAddressLen Our Address Length.
out Buffer Buffer to Read Data into.
in Length Length of data to read.
Returns
0 on success.
Error code on fail.
Definition at line 200 of file TWI_AVR8.c.
Referenced by rtc_read(), rtc_run(), and rtc_run_test().
TWI_ReceiveByte()
bool TWI_ReceiveByte (uint8_t *const Byte, const bool LastByte)
Definition at line 168 of file TWI_AVR8.c.
Referenced by TWI_ReadPacket().
TWI_SendByte()
bool TWI_SendByte (const uint8_t Byte)
TWI send byte.
Returns
1 if Acknowledge.
0 on fail.
Definition at line 158 of file TWI_AVR8.c.
Referenced by i2c_Transmit(), LCD_init(), TWI_ReadPacket(), and TWI_WritePacket().
TWI_StartTransmission()
uint8_t TWI_StartTransmission (const uint8_t SlaveAddress, const uint8_t TimeoutMS)
Start I2C transmission.
Parameters
in SlaveAddress I2C Address.
in TimeoutMS Timeout in Milliseconds.
Returns
TWI_ERROR_NoError on success.
TWI error value on fail.
Definition at line 88 of file TWI_AVR8.c.
Referenced by i2c_Start(), LCD_init(), TWI_ReadPacket(), and TWI_WritePacket().
TWI_StopTransmission()
void TWI_StopTransmission (void) [inline]
Sends a TWI STOP onto the TWI bus, terminating communication with the currently addressed device.
Definition at line 75 of file TWI_AVR8.c.
Referenced by i2c_End(), LCD_init(), TWI_ReadPacket(), and TWI_WritePacket().
TWI_WritePacket()
uint8_t TWI_WritePacket (const uint8_t SlaveAddress, const uint8_t TimeoutMS, const uint8_t * InternalAddress, uint8_t InternalAddressLen, const uint8_t * Buffer, uint8_t Length)
TWI write packet.
Parameters
in SlaveAddress TWI sleave address.
in TimeoutMS Timeout in Milliseconds.
in InternalAddress Our Address.
in InternalAddressLen Our Address Length.
in Buffer Buffer to Write.
in Length Length of data to write.
Returns
0 on success.
Error code on fail.
Definition at line 252 of file TWI_AVR8.c.
Referenced by rtc_init(), rtc_run(), and rtc_write().