lib/util.h File Reference
Flash read and bit utilities.
#include <user_config.h>
*
Macros
#define SWAP(a, b) do { a ^= b; b ^= a; a ^= b; } while(0)
#define ABS(x) ((x)<0 ? -(x) : (x))
#define SIGN(x) (((x) == 0) ? 0 : ((x) > 0) ? 1 : -1)
#define MAX(x, y) (((x) > (y)) ? x : y)
#define SPACES ` \t\r`
#define SPACESNL ` \t\n\r`
Functions
MEMSPACE char * skipspaces (char *ptr)
Skip white space in a string - tabs and spaces.
MEMSPACE char * nextspace (char *ptr)
Skip to first white space in a string - tabs and spaces.
MEMSPACE char * skipchars (char *str, char *pat)
Skip characters defined in user string.
MEMSPACE void trim_tail (char *str)
Trim White space and control characters from end of string.
MEMSPACE char * strnalloc (char *str, int len)
Allocate space for string with maximum size.
MEMSPACE char * stralloc (char *str)
Allocate space for string.
MEMSPACE char * get_token (char *str, char *token, int max)
return next token
MEMSPACE int token (char *str, char *pat)
Search for token in a string matching user pattern.
MEMSPACE uint8_t hexd (char c)
Convert Character into HEX digit.
MEMSPACE long atoh (const char *p)
Convert ASCII hex string to long integer.
MEMSPACE int isupper (int c)
Is a character upper case.
MEMSPACE int islower (int c)
Is a character lower case.
MEMSPACE int tolower (int c)
Convert character to lower case, only if it is upper case.
MEMSPACE int toupper (int c)
Convert character to upper case, only if it is lower case.
MEMSPACE int strcasecmp (const char *str, const char *pat)
Compare two strings without case.
MEMSPACE int strncasecmp (const char *str, const char *pat, size_t len)
Compare two strings without case maximum len bytes in size.
MEMSPACE int MATCH (char *str, char *pat)
Compare two strings.
MEMSPACE int MATCHI (char *str, char *pat)
Compare two strings without case.
MEMSPACE int MATCH_LEN (char *str, char *pat)
Compare two strings limted to length of pattern.
MEMSPACE int MATCHI_LEN (char *str, char *pat)
Compare two strings without case limted to length of pattern.
Detailed Description
Flash read and bit utilities.
Copyright 2015 Mike Gore, GPL License
You are free to use this code under the terms of GPL
Please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition in file util.h.
Macro Definition Documentation
#define ABS(x) ((x)<0 ? -(x) : (x))
Definition at line 29 of file util.h.
#define MAX(x, y) (((x) > (y)) ? x : y)
Definition at line 31 of file util.h.
#define SIGN(x) (((x) == 0) ? 0 : ((x) > 0) ? 1 : -1)
Definition at line 30 of file util.h.
#define SPACES ` \t\r`
Definition at line 33 of file util.h.
#define SPACESNL ` \t\n\r`
Definition at line 34 of file util.h.
#define SWAP(a, b) do { a ^= b; b ^= a; a ^= b; } while(0)
Definition at line 28 of file util.h.
Function Documentation
MEMSPACE long atoh (const char * p)
Convert ASCII hex string to long integer.
Parameters
in p String to convert.
Returns
long integer result.
See Also
strtol() for return overflow and underflow results.
Definition at line 275 of file util.c.
Referenced by gpib_tests().
MEMSPACE char* get_token (char * str, char * token, int max)
return next token
Skips all non printable ASCII characters before token
Token returns only printable ASCII
Parameters
in str string to search.
out token token to return
in max maximum token size
Returns
pointer past token on success .
NULL if no token found
Definition at line 177 of file util.c.
MEMSPACE uint8_t hexd (char c)
Convert Character into HEX digit.
Parameters
in c character.
Returns
HEX digit [0..F] on success.
0xff on fail.
Definition at line 256 of file util.c.
MEMSPACE int islower (int c)
Is a character lower case.
Parameters
in c character.
Returns
1 of lower case, else 0
Definition at line 298 of file util.c.
Referenced by toupper().
MEMSPACE int isupper (int c)
Is a character upper case.
Parameters
in c character.
Returns
1 of upper case, else 0
Definition at line 286 of file util.c.
Referenced by tolower().
MEMSPACE int MATCH (char * str, char * pat)
Compare two strings.
Parameters
in str string to match.
in pat pattern to compare.
Returns
string lenth on match.
0 on no match.
Definition at line 437 of file util.c.
MEMSPACE int MATCH_LEN (char * str, char * pat)
Compare two strings limted to length of pattern.
Parameters
in str string to match.
in pat pattern to compare.
Returns
string lenth on match.
0 on no match.
Warning
Matches sub strings so be caeful.
Definition at line 473 of file util.c.
MEMSPACE int MATCHI (char * str, char * pat)
Compare two strings without case.
Parameters
in str string to match.
in pat pattern to compare.
Returns
string lenth on match.
0 on no match.
Definition at line 455 of file util.c.
MEMSPACE int MATCHI_LEN (char * str, char * pat)
Compare two strings without case limted to length of pattern.
Parameters
in str string to match.
in pat pattern to compare.
Returns
string lenth on match.
0 on no match.
Warning
Matches sub strings so be caeful.
Definition at line 499 of file util.c.
MEMSPACE char* nextspace (char * ptr)
Skip to first white space in a string - tabs and spaces.
Parameters
in ptr input string
Returns
pointer to first white space character
Definition at line 51 of file util.c.
Referenced by fatfs_tests().
MEMSPACE char* skipchars (char * str, char * pat)
Skip characters defined in user string.
Parameters
in str string
in pat pattern string
Returns
pointer to string after skipped characters.
Definition at line 73 of file util.c.
MEMSPACE char* skipspaces (char * ptr)
Skip white space in a string - tabs and spaces.
Parameters
in ptr input string
Returns
pointer to first non white space character
Definition at line 34 of file util.c.
Referenced by FatFs_Read_Config(), fatfs_tests(), get_token(), gpib_tests(), gpib_trace_task(), plot_echo(), POSIX_Read_Config(), receive_plot(), and task().
MEMSPACE char* stralloc (char * str)
Allocate space for string.
Copies tring into allocated space.
Parameters
in str user string.
Returns
pointer to alocated string.
NULL on out of memory.
Definition at line 150 of file util.c.
MEMSPACE int strcasecmp (const char * str, const char * pat)
Compare two strings without case.
Parameters
in str string to match.
in pat pattern to compare.
Returns
0 on match, < 0 implies str sorts before pat, > 0 implies str sorts after pat
Definition at line 394 of file util.c.
Referenced by MATCHI().
MEMSPACE char* strnalloc (char * str, int len)
Allocate space for string with maximum size.
Copies tring into allocated space limited to maximum size.
Parameters
in str user string.
in len maximum string length.
Returns
pointer to alocated string.
Definition at line 126 of file util.c.
MEMSPACE int strncasecmp (const char * str, const char * pat, size_t len)
Compare two strings without case maximum len bytes in size.
Parameters
in str string to match.
in pat pattern to compare.
in len maximum string length for compare
Returns
0 on match, < 0 implies str sorts before pat, > 0 implies str sorts after pat
Definition at line 415 of file util.c.
Referenced by MATCHI_LEN().
MEMSPACE int token (char * str, char * pat)
Search for token in a string matching user pattern.
Skips all non printable ASCII characters before trying match.
Parameters
in str string to search.
in pat pattern to search for.
Returns
string lenth on match.
0 on no match.
Definition at line 221 of file util.c.
Referenced by FatFs_Read_Config(), fatfs_tests(), gpib_tests(), plot_echo(), POSIX_Read_Config(), rcvr_datablock(), and task().
MEMSPACE int tolower (int c)
Convert character to lower case, only if it is upper case.
Parameters
in c character.
Returns
character or lowercase value or character
Definition at line 311 of file util.c.
MEMSPACE int toupper (int c)
Convert character to upper case, only if it is lower case.
Parameters
in c character.
Returns
character or upper case value or character
Definition at line 323 of file util.c.
Referenced by strcasecmp(), and strncasecmp().
MEMSPACE void trim_tail (char * str)
Trim White space and control characters from end of string.
Parameters
in str string
Returns
void
Warning
Overwrites White space and control characters with EOS.
Definition at line 103 of file util.c.
Referenced by FatFs_Read_Config(), and POSIX_Read_Config().