gpib/vector.c File Reference
Convert between values and byte arrays.
#include `user_config.h`
#include `vector.h`
Functions
void V2B_MSB (uint8_t *B, int index, int size, uint32_t val)
Convert Value into byte array bytes are MSB ... LSB order.
void V2B_LSB (uint8_t *B, int index, int size, uint32_t val)
Convert Value into byte array bytes are LSB ... MSB order.
uint32_t B2V_MSB (uint8_t *B, int index, int size)
Convert a byte array into a value bytes are MSB ... LSB order.
uint32_t B2V_LSB (uint8_t *B, int index, int size)
Convert a byte array into a value bytes are LSB ... MSB order.
void B2S (uint8_t *B, int index, uint8_t *name, int size)
Create a string from data that has no EOS but known size.
Detailed Description
Convert between values and byte arrays.
Edit History
[1.0] [Mike Gore] Initial revision of file.
Copyright 2014-2020 Mike Gore, All rights reserved. GPL
See also
http://github.com/magore/hp85disk
http://github.com/magore/hp85disk/COPYRIGHT.md for Copyright details
Function Documentation
B2S()
void B2S (uint8_t * B, int index, uint8_t * name, int size)
Create a string from data that has no EOS but known size.
Parameters
in *B source
in index index offset into source data
out *name target string
in size size of string to write - not including EOS
Returns
void
Definition at line 98 of file vector.c.
B2V_LSB()
uint32_t B2V_LSB (uint8_t * B, int index, int size)
Convert a byte array into a value bytes are LSB ... MSB order.
Parameters
B byte array
index offset into byte array
size number of bytes to process
Returns
value
Definition at line 78 of file vector.c.
Referenced by lif_str2dir(), td0_read_disk(), td0_rle(), td0_unpack_comment_header(), td0_unpack_disk_header(), td0_unpack_sector_header(), and td0_unpack_track_header().
B2V_MSB()
uint32_t B2V_MSB (uint8_t * B, int index, int size)
Convert a byte array into a value bytes are MSB ... LSB order.
Parameters
B byte array
index offset into byte array
size number of bytes to process
Returns
value
Definition at line 58 of file vector.c.
Referenced by lif_str2dir(), lif_str2vol(), and SS80_Command_State().
V2B_LSB()
void V2B_LSB (uint8_t * B, int index, int size, uint32_t val)
Convert Value into byte array bytes are LSB ... MSB order.
Parameters
B byte array
index offset into byte array
size number of bytes to process
val Value to convert
Returns
void
Definition at line 41 of file vector.c.
Referenced by lif_dir2str().
V2B_MSB()
void V2B_MSB (uint8_t * B, int index, int size, uint32_t val)
Convert Value into byte array bytes are MSB ... LSB order.
Parameters
B byte array
index offset into byte array
size number of bytes to process
val Value to convert
Returns
void
Definition at line 22 of file vector.c.
Referenced by lif_dir2str(), lif_vol2str(), Send_Identify(), SS80_send_status(), and V2B_MSB_Index1().