10 DISP "THIS IS A TEST OF A BIG FILE"
20 DISP "SO WE HAVE A LOT OF TEST TO"
30 DISP "TEST THE FILE IO FUNCTIONS WITH"
40 DISP "MORE THEN 256 CHARACTERS OF TEXT"
50 DISP "ARE REQUIRED TO DISPLAY THIS"
70 DISP "AMMOUNT OF TEXT FOR THIS TEST"
80 DISP "THIS SHOULD BE ENOUGH TEXT"
90 END
100 DISP "WE ARE DONE..."
